### ISSUE TITLE
Synchronization issue between Portus and Private Registry

### ISSUE THREAD

**Issue by surco1971** [SUSE/Portus#1014]
I have Portus running together with a private registry. It works fine to login, pull and push images. 

But the Synchronization does not work between Registry and Portus. When a pull was made, the notification event reaches Portus, but the following GET against the registry asking for the tag fails. Log file says: "error authorizing context: authorization token required". Portus does not hang as it is described in other synchronization issues. Anyway, it is a kind of strange, because Portus itself is the authorization service.

I checked already that the default user can be logged in with the default password to Portus (environment: development)

The same authorization error happens when the Catalog is requested every 10 minutes to sync portus with registry.

### Logs
Here are some log snippets seen after a pull of an image.

Registry:
```
time="2016-07-28T11:07:11Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.5.3 http.request.host=registry.mydomain http.request.id=0628b6cb-b3b3-493a-a021-929b3fc091b0 http.request.method=GET http.request.remoteaddr="10.11.16.16:39817" http.request.uri="/v2/test/activemq/tags/list?n=100" http.request.useragent=Ruby instance.id=480ae37f-31e7-4df8-989a-56d976681de6 vars.name="test/activemq" version=v2.3.1 
10.11.16.16 - - [28/Jul/2016:11:07:11 +0000] "GET /v2/test/activemq/tags/list?n=100 HTTP/1.0" 401 149 "" "Ruby"
```

portus_web_1:
```
Namespace Load (0.3ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`registry_id` = 1 AND `namespaces`.`name` = 'test' LIMIT 1
Could not fetch the tag for target {"mediaType"=>"application/vnd.docker.distribution.manifest.v2+json", "size"=>1959, "digest"=>"sha256:1abcabcfa150543bc3590c6fc02183bc3b9d67bede97b03fd893b774e6a9b141", "length"=>1959, "repository"=>"test/activemq", "url"=>"https://registry.mydomain:443/v2/test/activemq/manifests/sha256:1abcabcfa150543bc3590c6fc02183bc3b9d67bede97b03fd893b774e6a9b141"}
Reason: execution expired
```

### This is my setup:

Portus: 2.1.0-dev   (deployed with compose-setup.sh)
Registry:  github.com/docker/distribution v2.3.1

Services are running on different VMs, but are behind one nginx 

Configurations are pretty the default ones:

```
Registry config.yml
http:
    addr: :5000
    host: https://registry.mydomain:443
    headers:
        X-Content-Type-Options: [nosniff]
auth:
  token:
    realm: http://registry.mydomain:44304/v2/token
    service: registry.mydomain
    issuer: registry.mydomain
    rootcertbundle: /etc/docker/registry/portus.crt
notifications:
  endpoints:
    - name: portus
      url: http://registry.mydomain:44304/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s
```

Portus/docker-compose.yml
`PORTUS_MACHINE_FQDN_VALUE=registry.mydomain`

Here is some portus:info outputs:

```
docker exec -it portus_crono_1 rake portus:info
[Mailer config] Host:     registry.mydomain
[Mailer config] Protocol: http://

Portus version: master@3b06e03
Portus has evaluated the following configuration:
---
email:
  from: portus@example.com
  name: Portus
  reply_to: no-reply@example.com
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    user_name: username@example.com
    password: "****"
    domain: example.com
gravatar:
  enabled: true
delete:
  enabled: false
ldap:
  enabled: false
  hostname: ldap_hostname
  port: 389
  method: plain
  base: ''
  filter: ''
  uid: uid
  authentication:
    enabled: false
    bind_dn: ''
    password: "****"
  guess_email:
    enabled: false
    attr: ''
first_user_admin:
  enabled: true
signup:
  enabled: true
check_ssl_usage:
  enabled: true
registry:
  jwt_expiration_time:
    value: 5
  catalog_page:
    value: 100
machine_fqdn:
  value: registry.mydomain
display_name:
  enabled: false
user_change_visibility:
  enabled: true



docker exec -it portus_web_1 rake portus:info
[Mailer config] Host:     registry.mydomain
[Mailer config] Protocol: http://

Portus version: master@3b06e03
Portus has evaluated the following configuration:
---
email:
  from: portus@example.com
  name: Portus
  reply_to: no-reply@example.com
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    user_name: username@example.com
    password: "****"
    domain: example.com
gravatar:
  enabled: true
delete:
  enabled: false
ldap:
  enabled: false
  hostname: ldap_hostname
  port: 389
  method: plain
  base: ''
  filter: ''
  uid: uid
  authentication:
    enabled: false
    bind_dn: ''
    password: "****"
  guess_email:
    enabled: false
    attr: ''
first_user_admin:
  enabled: true
signup:
  enabled: true
check_ssl_usage:
  enabled: true
registry:
  jwt_expiration_time:
    value: 5
  catalog_page:
    value: 100
machine_fqdn:
  value: registry.mydomain
display_name:
  enabled: false
user_change_visibility:
  enabled: true

```
