### ISSUE TITLE
Cannot create new team from UI .. need help

### ISSUE THREAD

**Issue by diamondbigdata** [SUSE/Portus#1030]
Dear devloper ,

I clone the Portus from master branch to my local build Ubuntu based ruby image, can startup the portus , but can not create any team.  is there anyone ever met this ?  or is there any advice for how to determine the root cause ?

**Comment by monstermunchkin** [comment]
We will need some more information here. What exactly happens when you try creating a new team? Could you possibly provide some logs?

**Comment by It4lik** [comment]
Hi, 

I got the same problem, here are some more informations. 

I'm on CentOS7, I'm using Apache as reverse proxy (with rewrite rules) and Unicorn as an app server for Portus. 

When I'm trying to create a new team from the UI, I do the following : 
- go to Teams tab
- click on "Create new team" button
- fill some informations
- click on "Add"

Then, nothin happen. When I use the builtin network inspector in my browser, I see that i got a 500 error. 

Here are my unicorn logs about this error : 

```
Started POST "/portus/teams" for _private_ip_ at 2016-08-17 17:06:26 +0200
Cannot render console from _private_ip_! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by TeamsController#create as JS
  Parameters: {"utf8"=>"✓", "team"=>{"name"=>"sesi", "description"=>"sesi"}, "commit"=>"Add"}
  User Load (383.5ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 2  ORDER BY `users`.`id` ASC LIMIT 1
   (28.8ms)  SELECT COUNT(*) FROM `registries`
Completed 500 Internal Server Error in 442ms (ActiveRecord: 412.3ms)

NoMethodError (undefined method `[]' for nil:NilClass):
  lib/portus/config.rb:50:in `block in add_enabled'
  app/policies/team_policy.rb:19:in `create?'
  app/controllers/teams_controller.rb:28:in `create'


  Rendered /home/user/.rvm/gems/ruby-2.1.2@portus/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_source.erb (4.3ms)
  Rendered /home/user/.rvm/gems/ruby-2.1.2@portus/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (0.6ms)
  Rendered /home/user/.rvm/gems/ruby-2.1.2@portus/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb (0.8ms)
  Rendered /home/user/.rvm/gems/ruby-2.1.2@portus/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/diagnostics.text.erb (23.1ms)
```

Thx for reading, 
It4.

**Comment by monstermunchkin** [comment]
@It4lik, thanks for the helpful details. We changed the `user_permission` section not too long ago, so this is likely the problem. Please ensure the aforementioned section in your `config.yml` looks similar to this:

```yaml
...

 user_permission:
  # Allow users to change the visibility or their personal namespace. If this is
  # disabled, only an admin will be able to change this. It defaults to true.
  change_visibility:
    enabled: true

  # Allow users to create/modify teams if they are an owner of it. If this is
  # disabled only an admin will be able to do this. This defaults to true.
  manage_team:
    enabled: true

  # Allow users to create/modify namespaces if they are an owner of it. If this
  # is disabled, only an admin will be able to do this. This defaults to true.
  manage_namespace:
    enabled: true

...
```
