### ISSUE TITLE
Can't delete tags

### ISSUE THREAD

**Issue by It4lik** [SUSE/Portus#1038]
Hi, 

I searched for similar problems in other issues but I didn't find anything..

I'm unable to delete tags from the UI. 
I can successfully delete comments.

When I try to delete some, I got a "Tag could not be removed" error message in the UI.
I also got the following entry in the logs :
```
Started DELETE "/portus/tags/8" for priv_IP at 2016-08-23 15:06:31 +0200
Cannot render console from priv_IP! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by TagsController#destroy as HTML
  Parameters: {"authenticity_token"=>"055JT2yD3uDY9BvSd3R7TdzZGq/txGBbMYfdQODUv3YOBI2Up9wqTOxZC+r/0/zOG812NSblSQKisFYBlbRmsQ==", "id"=>"8"}
  User Load (138.6ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 2  ORDER BY `users`.`id` ASC LIMIT 1
   (3.4ms)  SELECT COUNT(*) FROM `registries`
  Tag Load (3.1ms)  SELECT  `tags`.* FROM `tags` WHERE `tags`.`id` = 8 LIMIT 1
  Repository Load (5.1ms)  SELECT  `repositories`.* FROM `repositories` WHERE `repositories`.`id` = 4 LIMIT 1
  SQL (25.0ms)  UPDATE `tags` SET `tags`.`marked` = 1 WHERE `tags`.`digest` = 'sha256:ebfa84fca81c3173346128246ac7edd4d5aef67fd67e17478e9c056b6b369108'
  Registry Load (1.1ms)  SELECT  `registries`.* FROM `registries`  ORDER BY `registries`.`id` ASC LIMIT 1
  Namespace Load (5.0ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`id` = 5 LIMIT 1

Started GET "/portus/v2/token?account=portus&scope=repository%3Amyrepo%2Fmysql%3A%2A&service=priv.domain%3A5000" for priv_IP at 2016-08-23 15:06:33 +0200
Cannot render console from priv_IP! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by Api::V2::TokensController#show as JSON
  Parameters: {"account"=>"portus", "scope"=>"repository:myrepo/mysql:*", "service"=>"priv.domain:5000"}
  User Load (0.4ms)  SELECT  `users`.* FROM `users` WHERE `users`.`username` = 'portus' LIMIT 1
  ApplicationToken Load (0.2ms)  SELECT `application_tokens`.* FROM `application_tokens` WHERE `application_tokens`.`user_id` = 1
  User Load (0.2ms)  SELECT  `users`.* FROM `users` WHERE `users`.`username` = 'portus'  ORDER BY `users`.`id` ASC LIMIT 1
   (0.1ms)  BEGIN
  SQL (8.6ms)  UPDATE `users` SET `failed_attempts` = 8, `updated_at` = '2016-08-23 13:06:33' WHERE `users`.`id` = 1
   (0.1ms)  COMMIT
Completed 401 Unauthorized in 88ms (ActiveRecord: 9.5ms)
Could not delete tag on the registry: Cannot obtain authorization token: #<Net::HTTPUnauthorized:0x00000008f2e740>
Redirected to https://priv.domain/portus/repositories/4
Completed 302 Found in 1051ms (ActiveRecord: 181.2ms)
```

My Portus installation is as follows : 
- Registry as a docker container
- Portus is launched by Unicorn app server
- I got an Apache2 reverse proxy for encryption and a few other things

ps : I enabled the tag/image deletion in the config.yml file

Thanks for reading !

**Comment by monstermunchkin** [comment]
Which version of Portus are you running? Are you sure `priv.domain` is reachable by Portus?

**Comment by It4lik** [comment]
I replace my own ip with `priv.domain` for security reasons (public IP of a machine at work). So yes, this IP is reachable, I'm using it to get to Portus' UI :)

And I git cloned this repo 5 days ago, so I got the latest version (since the most recent commit was 8 days ago).

**Comment by tboerger** [comment]
Have you also enabled image delete within the registry?
For reference: https://github.com/docker/distribution/blob/master/docs/configuration.md#delete

**Comment by It4lik** [comment]
Yes I did :) Here is my registry config.yml 

```
version: 0.1
loglevel: info
storage:
  filesystem:
    rootdirectory: /var/lib/docker-registry
  delete:
    enabled: true
http:
  addr: 0.0.0.0:5000
  host: my.priv.domain

auth:
  token:
    realm: https://my.priv.domain/portus/v2/token
    service: my.priv.domain:5000
    issuer: my.priv.domain
    rootcertbundle: /ssl/my.priv.domain.pem

notifications:
  endpoints:
    - name: portus
      url: https://my.priv.domain/portus/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s
```

Thanks for your answer anyway :)
