### ISSUE TITLE
auth/cover.js precompiled asset?

### ISSUE THREAD

**Issue by schancel** [SUSE/Portus#1153]
I'm not a rails developer, so I'm not entirely sure what the problem is.  But following on-screen instructions, I modified the following line to `config/initializers/assets.rb`

```ruby
Rails.application.config.assets.precompile += %w(*.woff2 auth/cover.js)
```

I'm using a compose development environment with `pg` added as a dependency in the Gemfile and based off this PR: https://github.com/SUSE/Portus/pull/1093

My compose file is as follows:

```yaml
version: '2'
services:
  web:
    build: .
    command: puma -b tcp://0.0.0.0:3000 -w 3
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=XXXXX
      - PORTUS_DB_HOST=portus_db_1
      - PORTUS_DB_PORT=5432
      - PORTUS_DB_USERNAME=postgres
      - PORTUS_DB_PASSWORD=portus
      - PORTUS_DB_ADAPTER=postgresql
    volumes:
      - .:/portus
    depends_on:
      - db
    ports:
      - 3000:3000
  
  crono:
    image: portus_web
    entrypoint: bin/crono
    environment:
      - PORTUS_MACHINE_FQDN=XXXXX
      - PORTUS_DB_HOST=portus_db_1
      - PORTUS_DB_PORT=5432
      - PORTUS_DB_USERNAME=postgres
      - PORTUS_DB_PASSWORD=portus
      - PORTUS_DB_ADAPTER=postgresql
    volumes:
      - .:/portus
    depends_on:
      - db
  
  db:
    image: library/postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: portus
  
  registry:
    image: library/registry:2.3.1
    volumes:
      - /registry_data
      - ./compose/registry/portus.crt:/etc/docker/registry/portus.crt:ro
      - ./compose/registry/config.yml:/etc/docker/registry/config.yml:ro
    ports:
      - 5000:5000
      - 5001:5001 # required to access debug service
    links:
      - web
```
