### ISSUE TITLE
Failed to get token during webhook

### ISSUE THREAD

**Issue by tturbs** [SUSE/Portus#1317]
Dear all,

My portus configuration failed to get authorizing during webhook's handle_push_event. When I push a image into registry,

1. `Handling 'push' event` is ok. I tracked down to call get_page() on registry_client.rb .
2. As a result of the above, registry's `authorization token required` request token to portus. But portus returns any response.
3. Every of portus is hung. Also whole web is not working nest 2 mins.

  ```
  portus_1    | Could not fetch manifest for 'yongkkim/busybox' with digest 'sha256:be3c11fdba7cfe299214e46edc642e09514dbb9bbefcd0d3836c05a1e0cd0642': Net::ReadTimeout
  portus_1    | Completed 202 Accepted in 120266ms (ActiveRecord: 113.6ms)
  ```

Does anyone have same problem with me?
My server's details:
```
$ uname -a
Linux css0262 4.4.76-nx #150 SMP Thu Jul 6 09:09:33 KST 2017 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/redhat-release
CentOS release 6.3 (Final)
```

docker-compose.yml .

```
version: "2"

services:
  portus:
    image: opensuse/portus:head
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}
      - PORTUS_CHECK_SSL_USAGE_ENABLED=false

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_PRODUCTION_HOST=db
      - PORTUS_PRODUCTION_PASSWORD=portus
      - PORTUS_PRODUCTION_DATABASE=portus_production

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=b494a25faa8d22e430e843e220e424e10ac84d2ce0e64231f5b636d21251eb6d267adb042ad5884cbff0f3891bcf911bdf8abb3ce719849ccda9a4889249e5c2
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=12341234

      # NGinx is serving the assets instead of Puma. If you want to change this,
      # uncomment this line.
      - RAILS_SERVE_STATIC_FILES=true
    ports:
      - 3000:3000
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro

  crono:
    image: opensuse/portus:head
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_PRODUCTION_HOST=db
      - PORTUS_PRODUCTION_DATABASE=portus_production
      - PORTUS_PRODUCTION_PASSWORD=portus

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=b494a25faa8d22e430e843e220e424e10ac84d2ce0e64231f5b636d21251eb6d267adb042ad5884cbff0f3891bcf911bdf8abb3ce719849ccda9a4889249e5c2
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=12341234

      # We want to execute crono, not portus
      - PORTUS_INIT_COMMAND=bin/crono
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro

  db:
    image: library/mariadb:10.0.23
    environment:
      MYSQL_DATABASE: portus_production

      # Again, the password shouldn't be handled like this.
      MYSQL_ROOT_PASSWORD: portus
    volumes:
      - ./volume/mariadb:/var/lib/mysql

  registry:
    image: library/registry:2.6
    environment:
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: http://${MACHINE_FQDN}/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /secrets/portus.crt

      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: http://${MACHINE_FQDN}/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
      - ./volume/registry:/registry_data
      - ./secrets:/secrets:ro
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
    ports:
      - 5000:5000
      - 5001:5001 # required to access debug service
    links:
      - portus:portus

  nginx:
    image: library/nginx
    volumes:
      - ./nginx/nginx-cocofarm.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    links:
      - registry:registry
      - portus:portus

```
