### ISSUE TITLE
pushing microsoft image fail (in plain registry without authentication it works)

### ISSUE THREAD

**Issue by pjottr** [SUSE/Portus#1387]
Hi,

I`ve setup a portus environment last days and I find an issue while trying to push an image to the registry.
I've used a registry <-> portus setup described in examples/compose/docker-compose.yml.
Pushing a linux image work fine:
```
root@WL-DockerReg-02:/home/docker/portus/examples/compose# docker push WL-DockerReg-02:1200/ubuntu
The push refers to a repository [WL-DockerReg-02:1200/ubuntu]
a09947e71dc0: Pushed
9c42c2077cde: Pushed
625c7a2a783b: Pushed
25e0901a71b8: Pushed
8aa4fcad5eeb: Pushed
latest: digest: sha256:634a341aa83f32b48949ef428db8fefcd897dbacfdac26f044b60c14d1b5e972 size: 1357
```
But pushing a microsoft image fail:
```
root@WL-DockerReg-02:/home/docker/portus/examples/compose# docker push WL-DockerReg-02:1200/microsoft/mssql-server-linux
The push refers to a repository [WL-DockerReg-02:1200/microsoft/mssql-server-linux]
79580630673f: Preparing
88366be3b5a9: Preparing
cc31aa8aca7d: Preparing
668724d35c59: Preparing
d7c22be21371: Preparing
c1bd37d01c89: Waiting
943edb549a83: Waiting
bf6751561805: Waiting
f934e33a54a6: Waiting
e7ebc6e16708: Waiting
denied: requested access to the resource is denied
root@WL-DockerReg-02:/home/docker/portus/examples/compose#
```
After changing the registry configuration from:
```
  registry:
    image: library/registry:2.6
    command: ["/bin/sh", "/etc/docker/registry/init"]
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"

      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: https://${MACHINE_FQDN}/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: ${MACHINE_FQDN}:${REGISTRY_PORT}
      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /secrets/portus.crt

      # SSL
      REGISTRY_HTTP_TLS_CERTIFICATE: /secrets/portus.crt
      REGISTRY_HTTP_TLS_KEY: /secrets/portus.key

      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://${MACHINE_FQDN}/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
      - /var/lib/portus/registry:/var/lib/registry
      - ./secrets:/secrets:ro
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
      - ./registry/init:/etc/docker/registry/init:ro
    ports:
      - ${REGISTRY_PORT}:5000
      - 5001:5001 # required to access debug service
    links:
      - portus:portus
```
to a plain registry without authentication:
```
  registry:
    image: library/registry:2.6
    command: ["/bin/sh", "/etc/docker/registry/init"]
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"

      # SSL
      REGISTRY_HTTP_TLS_CERTIFICATE: /secrets/portus.crt
      REGISTRY_HTTP_TLS_KEY: /secrets/portus.key

    volumes:
      - /var/lib/portus/registry:/var/lib/registry
      - ./secrets:/secrets:ro
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
      - ./registry/init:/etc/docker/registry/init:ro
    ports:
      - ${REGISTRY_PORT}:5000
      - 5001:5001 # required to access debug service
    links:
      - portus:portus

```
pushing works (--allow-nondistributable-artifacts is configured on client side):
```
root@WL-DockerReg-02:/home/docker/portus/examples/compose# docker push WL-DockerReg-02:1200/microsoft/mssql-server-linux
The push refers to a repository [WL-DockerReg-02:1200/microsoft/mssql-server-linux]
79580630673f: Pushing [=============>                                     ]  63.63MB/238MB
88366be3b5a9: Pushing [======>                                            ]  120.2MB/905.7MB
cc31aa8aca7d: Pushed
668724d35c59: Pushing [=================================>                 ]  77.69MB/115.6MB
d7c22be21371: Pushed
c1bd37d01c89: Pushed
943edb549a83: Pushed
bf6751561805: Pushed
f934e33a54a6: Pushed
e7ebc6e16708: Pushing [=========>                                         ]  24.39MB/128.1MB
```

I've searched inside the documentation, but I found only pushing examples with linux based images.
Do you have an idea why pushing of microsoft images fail?

Best regards,
Peter

PS: Configuration:
Docker client, daemon, registy, portus, ... run all on the same maschine.
docker info:
```
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 19
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 132
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-83-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.64GiB
Name: WL-DockerReg-02
ID: 3VTP:SCPU:IYR6:ZMON:QEUL:BG46:BFWS:BBXW:RWUG:5T6W:7DRB:76TE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 WL-DockerReg-02:1200
 wl-dockerreg-01:1200
 127.0.0.0/8
Registry Mirrors:
 https://wl-dockerreg-01:1201/
Live Restore Enabled: false

WARNING: No swap limit support
```
docker version:
```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
dockerd parameter:
`/usr/bin/dockerd -H fd:// --insecure-registry=WL-DockerReg-02:1200 --insecure-registry=wl-dockerreg-01:1200 --registry-mirror=https://wl-dockerreg-01:1201 --allow-nondistributable-artifacts WL-DockerReg-02:1200
`
