### ISSUE TITLE
Images not listed anymore after upgrade to latest head version

### ISSUE THREAD

**Issue by phasenohr** [SUSE/Portus#1408]
Hello,

I had a running combination of docker registry (distribution/registry:latest from July, 7th), portus and portus-crono (opensuse/portus:head retrieved beginning of July) until I updated to opensuse/portus:head on Tuesday 5 September.
Now the registry structure is still correctly displayed, user authentication/authorisation in Portus UI and for the registry are correctly working but no images are displayed anymore.
In the screenshots below, I just pushed an image test-paul:head under the jeodpp-services namespace. It is listed under jeodpp-services but when trying to get more details about it, I get this message: "Unable to fetch tags data." instead of listing the tag "head" and allowing me e.g. to delete it.

Could someone give me a hint on what went wrong during this change of opensuse/portus image?

Thanks in advance.
Best regards,
Paul
![image](https://user-images.githubusercontent.com/2728008/30116647-69b43d14-931e-11e7-9665-abcecd9244b4.png)
![image](https://user-images.githubusercontent.com/2728008/30116679-8003c058-931e-11e7-9b6e-a131c6167b80.png)

**Comment by phasenohr** [comment]
In the registry logs, I find the following entries which make me think of some kind of authentication issue but as I did not change any of the configuration options used when running a portus and portus-crono containers out of the opensuse/portus:head image, I am wondering what happened there:

`172.17.0.1 - - [06/Sep/2017:15:01:01 +0000] "GET /v2/jeodpp-services/test-paul/manifests/head HTTP/1.1" 200 949 "" "Ruby"
time="2017-09-06T15:02:58Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.7.5 http.request.host="jeoreg.cidsn.jrc.it:5000" http.request.id=08e4148b-9493-42c5-b578-1ca27eb9fb07 http.request.method=GET http.request.remoteaddr="172.17.0.1:34024" http.request.uri="/v2/jeodpp-services/test-paul/tags/list?n=100" http.request.useragent=Ruby instance.id=1cc8e160-05e2-49e6-8f2a-eb73c4347c76 vars.name="jeodpp-services/test-paul" version=42ea75c`

`172.17.0.1 - - [06/Sep/2017:15:02:58 +0000] "GET /v2/jeodpp-services/test-paul/tags/list?n=100 HTTP/1.1" 401 168 "" "Ruby"
time="2017-09-06T15:02:59Z" level=info msg="response completed" go.version=go1.7.5 http.request.host="jeoreg.cidsn.jrc.it:5000" http.request.id=ed5e2afe-8116-4b53-9bc0-c6199b8390af http.request.method=GET http.request.remoteaddr="172.17.0.1:34032" http.request.uri="/v2/jeodpp-services/test-paul/tags/list?n=100" http.request.useragent=Ruby http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.657542ms http.response.status=200 http.response.written=53 instance.id=1cc8e160-05e2-49e6-8f2a-eb73c4347c76 version=42ea75c `

`172.17.0.1 - - [06/Sep/2017:15:02:59 +0000] "GET /v2/jeodpp-services/test-paul/tags/list?n=100 HTTP/1.1" 200 53 "" "Ruby"
time="2017-09-06T15:03:01Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.7.5 http.request.host="jeoreg.cidsn.jrc.it:5000" http.request.id=950a82af-cd47-4b5d-acbd-5d2782b7c8b8 http.request.method=GET http.request.remoteaddr="172.17.0.1:34384" http.request.uri="/v2/jeodpp-services/test-paul/manifests/head" http.request.useragent=Ruby instance.id=1cc8e160-05e2-49e6-8f2a-eb73c4347c76 vars.name="jeodpp-services/test-paul" vars.reference=head version=42ea75c `

`172.17.0.1 - - [06/Sep/2017:15:03:01 +0000] "GET /v2/jeodpp-services/test-paul/manifests/head HTTP/1.1" 401 168 "" "Ruby"
time="2017-09-06T15:03:01Z" level=info msg="response completed" go.version=go1.7.5 http.request.host="jeoreg.cidsn.jrc.it:5000" http.request.id=1bfffbec-b17c-49f3-8dcc-31009eb429a7 http.request.method=GET http.request.remoteaddr="172.17.0.1:34396" http.request.uri="/v2/jeodpp-services/test-paul/manifests/head" http.request.useragent=Ruby http.response.contenttype="application/vnd.docker.distribution.manifest.v2+json" http.response.duration=3.491853ms http.response.status=200 http.response.written=949 instance.id=1cc8e160-05e2-49e6-8f2a-eb73c4347c76 version=42ea75c `

**Comment by phasenohr** [comment]
And an extract of portus logs:

```
Started POST "/apps/portus/v2/webhooks/events" for 172.17.0.1 at 2017-09-06 15:55:01 +0000
Processing by Api::V2::EventsController#create as JSON
Completed 202 Accepted in 0ms (ActiveRecord: 0.0ms)
Started GET "/apps/portus/v2/token?account=portus&scope=repository%3Ajeodpp-services%2Ftest-paul%3Apull&service=jeoreg.cidsn.jrc.it%3A5000" for 172.17.0.1 at 2017-09-06 15:55:01 +0000
Processing by Api::V2::TokensController#show as JSON
  Parameters: {"account"=>"portus", "scope"=>"repository:jeodpp-services/test-paul:pull", "service"=>"jeoreg.cidsn.jrc.it:5000"}
Started POST "/apps/portus/v2/webhooks/events" for 172.17.0.1 at 2017-09-06 15:55:01 +0000
Processing by Api::V2::EventsController#create as JSON
Completed 202 Accepted in 0ms (ActiveRecord: 0.0ms)
```

Also, in case it helps, the output of portusctl rake portus:info ran in the portus container:
```
bash-4.3# portusctl rake portus:info
[Mailer config] Host:     jeodpp-portus.cidsn.jrc.it
[Mailer config] Protocol: https://
Users to be updated:
None. Doing nothing...

Portus version: 2.3.0-dev
Portus has evaluated the following configuration:
---
email:
  from: REMOVED@jrc.ec.europa.eu
  name: JRC JEODPP
  reply_to: REMOVED@jrc.ec.europa.eu
  smtp:
    enabled: true
    address: cidsn.jrc.it
    port: 25
    user_name: username@example.com
    password: "****"
    domain: cidsn.jrc.it
gravatar:
  enabled: false
delete:
  enabled: true
ldap:
  enabled: true
  hostname: REMOVED.cidsn.jrc.it
  port: 636
  method: simple_tls
  base: REMOVED
  filter: REMOVED
  uid: uid
  authentication:
    enabled: true
    bind_dn: REMOVED
    password: "****"
  guess_email:
    enabled: true
    attr: mail
first_user_admin:
  enabled: true
signup:
  enabled: true
check_ssl_usage:
  enabled: true
registry:
  jwt_expiration_time:
    value: 5
  catalog_page:
    value: 100
machine_fqdn:
  value: jeodpp-portus.cidsn.jrc.it
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: true
  create_team:
    enabled: false
  manage_team:
    enabled: true
  create_namespace:
    enabled: false
  manage_namespace:
    enabled: true
security:
  clair:
    server: ''
  zypper:
    server: ''
  dummy:
    server: ''
```

**Comment by Vad1mo** [comment]
what is the registry config?

**Comment by Vad1mo** [comment]
can you also send the registry setting of portus?
you can find them in the DB `SELECT * FROM registries;`

e.g.
```
id	name	hostname	created_at	updated_at	use_ssl	external_hostname
1	Registry	registry:5000	2017-09-04 19:47:32	2017-09-04 19:47:32	0	
```

**Comment by phasenohr** [comment]
Thanks for the fast answer. Registry config file:
```
[root@s-jrciprjeop162p build_registry]# more config.yml 
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
auth:
  token:
    realm: https://jeodpp-portus.cidsn.jrc.it:30000/apps/portus/v2/token
    service: jeoreg.cidsn.jrc.it:5000
    issuer: jeodpp-portus.cidsn.jrc.it
    rootcertbundle: /cert/jeoreg.cert.pem
http:
  addr: :5000
  secret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  host: https://jeoreg.cidsn.jrc.it:5000
  tls:
    certificate: /cert/jeoreg_bundle.crt
    key: /cert/jeoreg.key
#    clientcas: 
#     - /cert/cid_cacert.crt
  headers:
    X-Content-Type-Options: [nosniff]
notifications:
  endpoints:
  - name: portus
    disabled: false
    url: https://jeodpp-portus.cidsn.jrc.it:30000/apps/portus/v2/webhooks/events
    timeout: 500ms
    threshod: 5
    backoff: 1000ms
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```

Output of `SELECT * FROM registries;`
```
MariaDB [portus_db]> select * from registries;
+----+-----------------+--------------------------+---------------------+---------------------+---------+-------------------+
| id | name            | hostname                 | created_at          | updated_at          | use_ssl | external_hostname |
+----+-----------------+--------------------------+---------------------+---------------------+---------+-------------------+
|  1 | JEODPP Registry | jeoreg.cidsn.jrc.it:5000 | 2017-06-21 13:34:51 | 2017-06-21 13:34:51 |       1 |                   |
+----+-----------------+--------------------------+---------------------+---------------------+---------+-------------------+
1 row in set (0.00 sec)
```
