### ISSUE TITLE
Clair security scan: the parent layer is unknown

### ISSUE THREAD

**Issue by Amiiya** [SUSE/Portus#1453]
I finally got Portus to run. But using the vulnerability scanner isn't working like it supposed to be.
I definied Clair via `PORTUS_SECURITY_CLAIR_SERVER: http://${MACHINE_FQDN}:6060` and it seems to work without a problem.
Pushing it works fine but in the UI it says that there are 	0 vulnerabilities found.
If I analyze my images locally it works fine..

```
$ analyze-local-images 5ab4352f7a87
2017/10/16 15:29:52 Saving 5ab4352f7a87 to local disk (this may take some time)
2017/10/16 15:29:53 Retrieving image history
2017/10/16 15:29:53 Analyzing 23 layers... 
2017/10/16 15:29:53 Analyzing 
...
2017/10/16 15:29:53 Retrieving image's vulnerabilities
Clair report for image 5ab4352f7a87 (2017-10-16 13:29:53.713056388 +0000 UTC)
CVE-2014-9114 (High)
	Blkid in util-linux before 2.26rc-1 allows local users to execute arbitrary
	code.

	Package:       util-linux @ 2.20.1-5.3
	Link:          https://security-tracker.debian.org/tracker/CVE-2014-9114
	Layer:         25dcfa7e0ce1da60e3dc6dcf31cf7bb0169eb26b8a2d63368b2ccb57fd685e06
...
```

While accessing the UI, Clair is throwing a lot of logs. But I can't figure out what the issue is. Clair is able to scan but not in combination with Portus.

```
clair_1     | {"Event":"the parent layer is unknown. it must be processed first","Level":"warning","Location":"worker.go:93","Time":"2017-10-16 13:42:54.589262","layer":"sha256:7446aa686419efb8d7fdbf8c59a7686f9cc464298b710752fb081265b9af679b","parent layer":"sha256:525c7803da870ae15f31af116fe0fda8ab6eae87f426682c35fc5d82cd1b9e16"}
clair_1     | {"Event":"Handled HTTP request","Level":"info","Location":"router.go:57","Time":"2017-10-16 13:42:54.589461","elapsed time":1093429,"method":"POST","remote addr":"172.21.0.1:55534","request uri":"/v1/layers","status":"400"}
clair_1     | {"Event":"the parent layer is unknown. it must be processed first","Level":"warning","Location":"worker.go:93","Time":"2017-10-16 13:42:54.593350","layer":"sha256:6e645d888cf7bb06cd3b5e70d26b2037a8501b5e806418f79fb0159e1de900db","parent layer":"sha256:7446aa686419efb8d7fdbf8c59a7686f9cc464298b710752fb081265b9af679b"}
clair_1     | {"Event":"Handled HTTP request","Level":"info","Location":"router.go:57","Time":"2017-10-16 13:42:54.593572","elapsed time":1232946,"method":"POST","remote addr":"172.21.0.1:55538","request uri":"/v1/layers","status":"400"}
```
**Portus log**
I don't understand why a SSL error `<Puma::MiniSSL::SSLError: System error: Success - 0>` appears. I can push and pull without any problems..
```
portus_1    | Started GET "/v2/token?account=portus&scope=repository%3Aadmin%2Fcve-heartbleed%3Apull&service=portus.test.lan" for 172.22.0.6 at 2017-10-19 12:12:53 +0000
portus_1    | Processing by Api::V2::TokensController#show as JSON
portus_1    |   Parameters: {"account"=>"portus", "scope"=>"repository:admin/cve-heartbleed:pull", "service"=>"portus.test.lan"}
portus_1    | Completed 200 OK in 76ms (Views: 0.2ms | ActiveRecord: 5.7ms)
nginx_1     | 172.22.0.1 - portus [19/Oct/2017:12:12:53 +0000] "GET /v2/token?account=portus&scope=repository%3Aadmin%2Fcve-heartbleed%3Apull&service=portus.test.lan HTTP/1.1" 200 883 "-" "Ruby"
registry_1  | time="2017-10-19T12:12:53Z" level=info msg="response completed" go.version=go1.7.6 http.request.host=portus.test.lan http.request.id=819bb6e2-3b60-43e1-9232-a1bedcfa21a0 http.request.method=GET http.request.remoteaddr=172.22.0.1 http.request.uri="/v2/admin/cve-heartbleed/manifests/latest" http.request.useragent=Ruby http.response.contenttype="application/vnd.docker.distribution.manifest.v2+json" http.response.duration=2.833762ms http.response.status=200 http.response.written=5094 instance.id=6fee1333-64b7-4cc7-a3bd-02b332e17063 version=v2.6.2 
registry_1  | 172.22.0.6 - - [19/Oct/2017:12:12:53 +0000] "GET /v2/admin/cve-heartbleed/manifests/latest HTTP/1.0" 200 5094 "" "Ruby"
nginx_1     | 172.22.0.1 - - [19/Oct/2017:12:12:53 +0000] "GET /v2/admin/cve-heartbleed/manifests/latest HTTP/1.1" 200 5094 "-" "Ruby"
portus_1    | Started POST "/v2/webhooks/events" for 172.22.0.6 at 2017-10-19 12:12:53 +0000
portus_1    | Processing by Api::V2::EventsController#create as JSON
portus_1    | Completed 202 Accepted in 0ms (ActiveRecord: 0.0ms)
portus_1    | 2017-10-19 12:12:53 +0000: SSL error, peer: 172.22.0.6, peer cert: , #<Puma::MiniSSL::SSLError: System error: Success - 0>
nginx_1     | 172.22.0.1 - - [19/Oct/2017:12:12:53 +0000] "POST /v2/webhooks/events HTTP/2.0" 202 0 "-" "Go-http-client/2.0"
portus_1    | Completed 200 OK in 224ms (Views: 207.9ms | ActiveRecord: 3.4ms)
nginx_1     | 172.22.0.1 - - [19/Oct/2017:12:12:53 +0000] "GET /repositories/2.json HTTP/2.0" 304 0 "https://portus.test.lan/repositories/2" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36"
portus_1    | Started GET "/repositories/2.json" for 172.22.0.6 at 2017-10-19 12:13:03 +0000
portus_1    | Processing by RepositoriesController#show as JSON
portus_1    |   Parameters: {"id"=>"2"}
registry_1  | time="2017-10-19T12:13:03Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.7.6 http.request.host=portus.test.lan http.request.id=fcf53bae-538b-4bc6-b5d6-c8882ff7c278 http.request.method=GET http.request.remoteaddr=172.22.0.1 http.request.uri="/v2/admin/cve-heartbleed/manifests/latest" http.request.useragent=Ruby instance.id=6fee1333-64b7-4cc7-a3bd-02b332e17063 vars.name="admin/cve-heartbleed" vars.reference=latest version=v2.6.2 
nginx_1     | 172.22.0.1 - - [19/Oct/2017:12:13:03 +0000] "GET /v2/admin/cve-heartbleed/manifests/latest HTTP/1.1" 401 163 "-" "Ruby"
registry_1  | 172.22.0.6 - - [19/Oct/2017:12:13:03 +0000] "GET /v2/admin/cve-heartbleed/manifests/latest HTTP/1.0" 401 163 "" "Ruby"
portus_1    | Started GET "/v2/token?account=portus&scope=repository%3Aadmin%2Fcve-heartbleed%3Apull&service=portus.test.lan" for 172.22.0.6 at 2017-10-19 12:13:03 +0000
portus_1    | Processing by Api::V2::TokensController#show as JSON
portus_1    |   Parameters: {"account"=>"portus", "scope"=>"repository:admin/cve-heartbleed:pull", "service"=>"portus.test.lan"}
portus_1    | Completed 200 OK in 78ms (Views: 0.2ms | ActiveRecord: 5.6ms)
nginx_1     | 172.22.0.1 - portus [19/Oct/2017:12:13:03 +0000] "GET /v2/token?account=portus&scope=repository%3Aadmin%2Fcve-heartbleed%3Apull&service=portus.test.lan HTTP/1.1" 200 883 "-" "Ruby"
registry_1  | time="2017-10-19T12:13:03Z" level=info msg="response completed" go.version=go1.7.6 http.request.host=portus.test.lan http.request.id=e607730e-072d-411a-b223-b18b0e21ca72 http.request.method=GET http.request.remoteaddr=172.22.0.1 http.request.uri="/v2/admin/cve-heartbleed/manifests/latest" http.request.useragent=Ruby http.response.contenttype="application/vnd.docker.distribution.manifest.v2+json" http.response.duration=1.785797ms http.response.status=200 http.response.written=5094 instance.id=6fee1333-64b7-4cc7-a3bd-02b332e17063 version=v2.6.2 
registry_1  | 172.22.0.6 - - [19/Oct/2017:12:13:03 +0000] "GET /v2/admin/cve-heartbleed/manifests/latest HTTP/1.0" 200 5094 "" "Ruby"
nginx_1     | 172.22.0.1 - - [19/Oct/2017:12:13:03 +0000] "GET /v2/admin/cve-heartbleed/manifests/latest HTTP/1.1" 200 5094 "-" "Ruby"
portus_1    | Started POST "/v2/webhooks/events" for 172.22.0.6 at 2017-10-19 12:13:03 +0000
portus_1    | Processing by Api::V2::EventsController#create as JSON
portus_1    | Completed 202 Accepted in 0ms (ActiveRecord: 0.0ms)
portus_1    | 2017-10-19 12:13:03 +0000: SSL error, peer: 172.22.0.6, peer cert: , #<Puma::MiniSSL::SSLError: System error: Success - 0>
nginx_1     | 172.22.0.1 - - [19/Oct/2017:12:13:03 +0000] "POST /v2/webhooks/events HTTP/2.0" 202 0 "-" "Go-http-client/2.0"
portus_1    | Completed 200 OK in 225ms (Views: 211.9ms | ActiveRecord: 2.7ms)
nginx_1     | 172.22.0.1 - - [19/Oct/2017:12:13:03 +0000] "GET /repositories/2.json HTTP/2.0" 200 439 "https://portus.test.lan/repositories/2" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36"
```
This is my **dockerfile**
```
version: "2"

services:
  portus:
    image: mssola/portus:susecon
    environment:
      PORTUS_MACHINE_FQDN_VALUE: ${MACHINE_FQDN}
      PORTUS_SECURITY_CLAIR_SERVER: http://${MACHINE_FQDN}:6060      

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      PORTUS_PRODUCTION_HOST: db
      PORTUS_PRODUCTION_DATABASE: portus_production
      PORTUS_PRODUCTION_PASSWORD: ${DATABASE_PASSWORD}

      # Secrets. It can possibly be handled better with Swarm's secrets.
      PORTUS_SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      PORTUS_KEY_PATH: /certificates/portus.key
      PORTUS_PASSWORD: ${PORTUS_PASSWORD}

      # SSL
      PORTUS_PUMA_TLS_KEY: /certificates/portus.key
      PORTUS_PUMA_TLS_CERT: /certificates/portus.crt

      # NGinx is serving the assets instead of Puma. If you want to change this,
      # uncomment this line.
      #RAILS_SERVE_STATIC_FILES: 'true'
    ports:
      - 3000:3000
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro
      - static:/srv/Portus/public
    extra_hosts:
      - "${MACHINE_FQDN}:172.17.0.1"

  crono:
    image: mssola/portus:susecon
    environment:
      PORTUS_MACHINE_FQDN_VALUE: ${MACHINE_FQDN}

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      PORTUS_PRODUCTION_HOST: db
      PORTUS_PRODUCTION_DATABASE: portus_production
      PORTUS_PRODUCTION_PASSWORD: ${DATABASE_PASSWORD}

      # Secrets. It can possibly be handled better with Swarm's secrets.
      PORTUS_SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      PORTUS_KEY_PATH: /certificates/portus.key
      PORTUS_PASSWORD: ${PORTUS_PASSWORD}

      # We want to execute crono, not portus
      PORTUS_INIT_COMMAND: bin/crono
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro

  db:
    image: library/mariadb:10.0.23
    environment:
      MYSQL_DATABASE: portus_production

      # Again, the password shouldn't be handled like this.
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - /var/lib/portus/mariadb:/var/lib/mysql

  registry:
    image: library/registry:2.6
    command: ["/bin/sh", "/etc/docker/registry/init"]
    environment:
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: https://${MACHINE_FQDN}/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /secrets/portus.crt

      # SSL
      REGISTRY_HTTP_TLS_CERTIFICATE: /secrets/portus.crt
      REGISTRY_HTTP_TLS_KEY: /secrets/portus.key

      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://${MACHINE_FQDN}/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
      - /var/lib/portus/registry:/var/lib/registry
      - ./secrets:/secrets:ro
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
      - ./registry/init:/etc/docker/registry/init:ro
    ports:
      - 5000:5000
      - 5001:5001 # required to access debug service
    links:
      - portus:portus
    extra_hosts:
      - "${MACHINE_FQDN}:172.17.0.1"

  nginx:
    image: library/nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./secrets:/secrets:ro
      - static:/srv/Portus/public:ro
    ports:
      - 80:80
      - 443:443
    links:
      - registry:registry
      - portus:portus

volumes:
  static:
    driver: local
```
I hope someone can help me!
Thanks :)
