### ISSUE TITLE
Registry reachability tests are failing

### ISSUE THREAD

**Issue by Vad1mo** [SUSE/Portus#1486]
On latest master the registry reachability test is always indicating that the registry is not reachable even though login/push/pull is working just fine.  Of what does the Reachable test consists?

The tooltip error is: something went wrong check your configuration

Logs:

```
Registry not reachable: #<NoMethodError: undefined method `[]' for nil:NilClass>
 Write fragment views/registry1_status/6400318743a2031dc52df318c76c5c13 (4.8ms)
 Rendered admin/registries/index.html.slim within layouts/application (80.0ms)
```

**Comment by Vad1mo** [comment]
One more thing, when the registry is indicated as broken it doesn't safe any changes.

There is a **Skip remote checks** message but no checkbox.
`Error: something went wrong. Check your configuration. You can skip this check by clicking on the "Skip remote checks" checkbox.`

**Comment by vitoravelino** [comment]
Are you sure? Because Travis [shows green](https://travis-ci.org/SUSE/Portus/builds/293162202).

**Comment by Vad1mo** [comment]
I a pretty sure I tried two different scenarios in prod and localy

for local development I don't run portus in a container so I have portus on :3000 and registry on :5000

```
➜  Portus git:(develop) ✗ curl -I 127.0.0.1:5000
HTTP/1.1 200 OK
Cache-Control: no-cache
Date: Mon, 30 Oct 2017 11:33:44 GMT
Content-Type: text/plain; charset=utf-8
```


```
Started GET "//api/v1/registries/validate?name=myReg&hostname=127.0.0.1%3A5000&external_hostname=&use_ssl=false&force=false&only%5B%5D=name" for ::1 at 2017-10-30 12:32:45 +0100
  User Load (0.6ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 2  ORDER BY `users`.`id` ASC LIMIT 1
  Registry Exists (0.7ms)  SELECT  1 AS one FROM `registries` WHERE `registries`.`name` = BINARY 'myReg' LIMIT 1
  Registry Exists (0.4ms)  SELECT  1 AS one FROM `registries` WHERE `registries`.`hostname` = BINARY '127.0.0.1:5000' LIMIT 1
```

In prod setup, the behaviour is the same.

**Comment by vitoravelino** [comment]
What's the response for the `validate` endpoint?

**Comment by Vad1mo** [comment]
```sh
curl http://localhost:3000/api/v1/registries/validate\?name\=myReg\&hostname\=127.0.0.1%3A5000\&external_hostname\=\&use_ssl\=false\&force\=false\&only%5B%5D\=name%22
{"error":"Authentication fails."}% 
```

In browser:
```
{"messages":{},"valid":true}
```

**Comment by vitoravelino** [comment]
So, it's valid. That's the expected behaviour since `127.0.0.1:5000` is reachable. The button should be fine and not message appear. I didn't get your point. 😕

**Comment by Vad1mo** [comment]
Thats the point, From the api point of view all is fine, however the UI is displaying this:


![bildschirmfoto 2017-10-30 um 12 48 46](https://user-images.githubusercontent.com/1492007/32169437-bd5287ec-bd70-11e7-96c4-bafd90c0204a.png)


also when I skip the checks, it stays forever like this:

![image](https://user-images.githubusercontent.com/1492007/32169486-f74dec70-bd70-11e7-98bd-bc9572f85139.png)

**Comment by vitoravelino** [comment]
`Registry does not implement v2 of the API.` That's why you are getting the error. Not because it isn't reachable.

**Comment by Vad1mo** [comment]
The check doesn't know if it is V2 or not.  see: `registry.rb`
```ruby 
      r = client.reachable?

      # At this point, !r is only possible if the returned code is 404, which
      # according to the documentation we have to assume that the registry is
      # not implementing the v2 of the API.
      return "Error: registry does not implement v2 of the API." unless r
```

```
fd4db5d4fa7        registry:2          "/entrypoint.sh /e..."   7 weeks ago         Up 4 days           0.0.0.0:5000->5000/tcp   registry
```

**Comment by vitoravelino** [comment]
@Vad1mo, gotcha. Could you print what `r` is? 

@mssola, maybe this code is deprecated now and we need to update it?

**Comment by Vad1mo** [comment]
r == `false`

**Comment by Vad1mo** [comment]
I also get this error, this when I try to change the existing registry.
```
http://localhost:3000/api/v1/registries/validate?name=MyReg&hostname=127.0.0.1%3A5000&external_hostname=&use_ssl=false&force=false&only%5B%5D=hostname
```

```

{"messages":{"hostname":["has already been taken","Error: registry does not implement v2 of the API."]},"valid":false}
```

**Comment by vitoravelino** [comment]
> r == false

My bad on this, what needs to be checked is the `res` value  in the `registry_client.rb#reachable?`.

**Comment by Vad1mo** [comment]
Content of *res*

```yaml
--- !ruby/object:Net::HTTPOK
http_version: '1.1'
code: '200'
message: OK
header:
  content-length:
  - '2'
  content-type:
  - application/json; charset=utf-8
  docker-distribution-api-version:
  - registry/2.0
  x-content-type-options:
  - nosniff
  date:
  - Mon, 30 Oct 2017 12:49:43 GMT
body: "{}"
read: true
uri: !ruby/object:URI::HTTP
  scheme: http
  user: 
  password: 
  host: 127.0.0.1
  port: 5000
  path: "/v2/"
  query: 
  opaque: 
  fragment: 
  parser: !ruby/object:URI::RFC3986_Parser
    regexp:
      :SCHEME: !ruby/regexp /\A[A-Za-z][A-Za-z0-9+\-.]*\z/
      :USERINFO: !ruby/regexp /\A(?:%\h\h|[!$&-.0-;=A-Z_a-z~])*\z/
      :HOST: !ruby/regexp /\A(?:(?<IP-literal>\[(?:(?<IPv6address>(?:\h{1,4}:){6}(?<ls32>\h{1,4}:\h{1,4}|(?<IPv4address>(?<dec-octet>[1-9]\d|1\d{2}|2[0-4]\d|25[0-5]|\d)\.\g<dec-octet>\.\g<dec-octet>\.\g<dec-octet>))|::(?:\h{1,4}:){5}\g<ls32>|\h{,4}::(?:\h{1,4}:){4}\g<ls32>|(?:(?:\h{1,4}:)?\h{1,4})?::(?:\h{1,4}:){3}\g<ls32>|(?:(?:\h{1,4}:){,2}\h{1,4})?::(?:\h{1,4}:){2}\g<ls32>|(?:(?:\h{1,4}:){,3}\h{1,4})?::\h{1,4}:\g<ls32>|(?:(?:\h{1,4}:){,4}\h{1,4})?::\g<ls32>|(?:(?:\h{1,4}:){,5}\h{1,4})?::\h{1,4}|(?:(?:\h{1,4}:){,6}\h{1,4})?::)|(?<IPvFuture>v\h+\.[!$&-.0-;=A-Z_a-z~]+))\])|\g<IPv4address>|(?<reg-name>(?:%\h\h|[!$&-.0-9;=A-Z_a-z~])*))\z/
      :ABS_PATH: !ruby/regexp /\A\/(?:%\h\h|[!$&-.0-;=@-Z_a-z~])*(?:\/(?:%\h\h|[!$&-.0-;=@-Z_a-z~])*)*\z/
      :REL_PATH: !ruby/regexp /\A(?:%\h\h|[!$&-.0-;=@-Z_a-z~])+(?:\/(?:%\h\h|[!$&-.0-;=@-Z_a-z~])*)*\z/
      :QUERY: !ruby/regexp /\A(?:%\h\h|[!$&-.0-;=@-Z_a-z~\/?])*\z/
      :FRAGMENT: !ruby/regexp /\A(?:%\h\h|[!$&-.0-;=@-Z_a-z~\/?])*\z/
      :OPAQUE: !ruby/regexp /\A(?:[^\/].*)?\z/
      :PORT: !ruby/regexp /\A[\x09\x0a\x0c\x0d ]*\d*[\x09\x0a\x0c\x0d ]*\z/
decode_content: true
socket: 
body_exist: true

```
