### ISSUE TITLE
Why `push` events are getting ignore?

### ISSUE THREAD

**Issue by zot24** [SUSE/Portus#1502]
According to this lines https://github.com/SUSE/Portus/blob/master/lib/portus/registry_notification.rb#L6 `push` and `delete` should be supported as events being sent by the Docker registry but why I'm seeing the error message `Event discarded because it's not relevant`?

It's a little bit confuse as I can see the 202 accepted at the end of the message however the new image doesn't appear in Portus after being pushed, as well as I got that weird SSL error at the button.

```
11/3/2017 3:05:50 PMStarted POST "/v2/webhooks/events" for 52.174.111.167 at 2017-11-03 15:05:50 +0000
11/3/2017 3:05:50 PMProcessing by Api::V2::EventsController#create as JSON
11/3/2017 3:05:50 PMIncoming event:
11/3/2017 3:05:50 PM{
11/3/2017 3:05:50 PM  "id": "d3dd78dd-90c9-42a2-b912-5b13ca54e604",
11/3/2017 3:05:50 PM  "timestamp": "2017-11-03T15:05:33.018845371Z",
11/3/2017 3:05:50 PM  "action": "push",
11/3/2017 3:05:50 PM  "target": {
11/3/2017 3:05:50 PM    "mediaType": "application/octet-stream",
11/3/2017 3:05:50 PM    "size": 628,
11/3/2017 3:05:50 PM    "digest": "sha256:368c8989db4102e165d5d973e211fd8d24aa21ccb8dc96e717a2f3ec943bf19f",
11/3/2017 3:05:50 PM    "length": 628,
11/3/2017 3:05:50 PM    "repository": "zot24/website",
11/3/2017 3:05:50 PM    "url": "https://test.molt.in/v2/zot24/website/blobs/sha256:368c8989db4102e165d5d973e211fd8d24aa21ccb8dc96e717a2f3ec943bf19f"
11/3/2017 3:05:50 PM  },
11/3/2017 3:05:50 PM  "request": {
11/3/2017 3:05:50 PM    "id": "d9310931-eea7-4806-a9dd-b1e012679fd9",
11/3/2017 3:05:50 PM    "addr": "31.22.3.66",
11/3/2017 3:05:50 PM    "host": "test.zot24.com",
11/3/2017 3:05:50 PM    "method": "PUT",
11/3/2017 3:05:50 PM    "useragent": "docker/17.06.0-ce go/go1.8.3 git-commit/02c1d87 kernel/4.9.36-moby os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.0-ce \\(darwin\\))"
11/3/2017 3:05:50 PM  },
11/3/2017 3:05:50 PM  "actor": {
11/3/2017 3:05:50 PM    "name": "zot24"
11/3/2017 3:05:50 PM  },
11/3/2017 3:05:50 PM  "source": {
11/3/2017 3:05:50 PM    "addr": "402842deaa0e:5000",
11/3/2017 3:05:50 PM    "instanceID": "cab702bd-a774-4870-9ff9-6331d41827a2"
11/3/2017 3:05:50 PM  }
11/3/2017 3:05:50 PM}
11/3/2017 3:05:50 PMUnsupported mediaType 'application/octet-stream'
11/3/2017 3:05:50 PMEvent discarded because it's not relevant
11/3/2017 3:05:50 PMCompleted 202 Accepted in 1ms (ActiveRecord: 0.0ms)
11/3/2017 3:05:50 PM2017-11-03 15:05:50 +0000: SSL error, peer: 10.42.225.250, peer cert: , #<Puma::MiniSSL::SSLError: System error: Success - 0>
```
I'm using `mssola/portus:susecon` image as `opensuse/portus:head` doesn't work atm (doesn't seems to be loading any specific configuration)

> NOTE: I can provide my `docker-compose.yml` if needed, my configuration is based on https://github.com/SUSE/Portus/blob/master/examples/compose/docker-compose.yml

**Comment by zot24** [comment]
This is how my setup looks like atm:

```
version: "2"
services:
  portus:
    image: mssola/portus:susecon
    environment:
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/production/certs/registry/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      - PORTUS_PUMA_TLS_KEY=/certificates/production/certs/registry/portus.key
      - PORTUS_PUMA_TLS_CERT=/certificates/production/certs/registry/portus.crt

      - PORTUS_LOG_LEVEL=debug

      - PORTUS_PRODUCTION_HOST=mariadb
      - PORTUS_PRODUCTION_DATABASE=portus
      - PORTUS_PRODUCTION_PASSWORD=${DATABASE_PASSWORD}

      - PORTUS_DB_POOL=5

      - PORTUS_GRAVATAR_ENABLED=true
      - PORTUS_DELETE_ENABLED=true
      - PORTUS_LDAP_ENABLED=false
      - PORTUS_FIRST_USER_ADMIN_ENABLED=true
      - PORTUS_SIGNUP_ENABLED=true
      - PORTUS_CHECK_SSL_USAGE_ENABLED=true

      - PORTUS_REGISTRY_JWT_EXPIRATION_TIME_VALUE=30
      - PORTUS_REGISTRY_CATALOG_PAGE_VALUE=100

      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}

      - PORTUS_SECURITY_CLAIR_SERVER=http://clair:6060
      - PORTUS_SECURITY_CLAIR_SERVER_HEALTH_PORT=6061
      - PORTUS_SECURITY_CLAIR_SERVER_ZYPPER_SERVER=
      - PORTUS_SECURITY_CLAIR_SERVER_DUMMY_SERVER=

      - PORTUS_ANONYMOUS_BROWSING_ENABLED=false
      - PORTUS_DISPLAY_NAME_ENABLED=true

      - PORTUS_USER_PERMISSION_CHANGE_VISIBILITY_ENABLED=false
      - PORTUS_USER_PERMISSION_MANAGE_TEAM_ENABLED=false
      - PORTUS_USER_PERMISSION_MANAGE_NAMESPACE_ENABLED=false
    depends_on:
      - mariadb
    links:
      - mariadb
      - registry:registry
    ports:
      - 3000:3000
    volumes:
      - static:/srv/Portus/public
      - certificates:/certificates:ro

  mariadb:
    image: library/mariadb:10.0.23
    environment:
      - MYSQL_DATABASE=portus
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    # volumes:
    #   - /var/lib/portus/mariadb:/var/lib/mysql

  crono:
    image: mssola/portus:susecon
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}

      - PORTUS_PRODUCTION_HOST=mariadb
      - PORTUS_PRODUCTION_DATABASE=portus
      - PORTUS_PRODUCTION_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/production/certs/registry/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      - PORTUS_INIT_COMMAND=bin/crono
    depends_on:
      - mariadb
    links:
      - mariadb
    volumes:
      - certificates:/certificates:ro

  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: password

  clair:
    image: quay.io/coreos/clair:v2.0.1
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - clair:/config:ro
    command: [-config, /config/config.yaml]

  registry:
    image: library/registry:2.5
    environment:
      REGISTRY_LOG_LEVEL: debug
      REGISTRY_HTTP_SECRET: secret

      REGISTRY_AUTH: token
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: https://${MACHINE_FQDN}/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certificates/production/certs/registry/portus.crt
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
      # SSL
      REGISTRY_HTTP_HOST: https://${MACHINE_FQDN}
      REGISTRY_HTTP_HEADERS_X-CONTENT-TYPE-OPTIONS: '[nosniff]'
      REGISTRY_LOG_FIELDS_SERVICE: registry

      REGISTRY_HTTP_TLS_CERTIFICATE: /certificates/production/certs/registry/portus.crt
      REGISTRY_HTTP_TLS_KEY: /certificates/production/certs/registry/portus.key
      REGISTRY_NOTIFICATIONS_ENDPOINTS: |
         - name: portus
           url: https://${MACHINE_FQDN}/v2/webhooks/events
           timeout: 2000ms
           threshold: 5
           backoff: 1s
    links:
      - portus:portus
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      # - /var/lib/portus/registry:/var/lib/registry
      - certificates:/certificates:ro
      - registry:/etc/docker/registry:ro

  nginx:
    image: nginx:latest
    volumes:
      - nginx:/etc/nginx/conf.d
      - certificates:/certificates:ro
      - static:/srv/Portus/public:ro
    depends_on:
      - portus
      - registry
    links:
      - portus:portus
      - registry:registry
    ports:
      - 80:80
      - 443:443

  data:
    image: registry.zot24.com/zot24/registry-data:latest
    volumes:
      - clair:/clair
      - nginx:/nginx
      - portus:/portus
      - registry:/registry
      - certificates:/certificates
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.pull_image: always

volumes:
  static:
    driver: local
  nginx:
    driver: local
  registry:
    driver: local
  portus:
    driver: local
  clair:
    driver: local
```
