### ISSUE TITLE
Can not push images to registry

### ISSUE THREAD

**Issue by wrfly** [SUSE/Portus#1515]
docker version:
host: 17.06.1-ce
client: 17.06.1-ce

docker-compose file:

```
version: "2"

services:
  portus:
    image: opensuse/portus:head
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_PRODUCTION_HOST=db
      - PORTUS_PRODUCTION_DATABASE=portus_production
      - PORTUS_PRODUCTION_PASSWORD=${DATABASE_PASSWORD}


      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      # SSL
      - PORTUS_PUMA_TLS_KEY=/certificates/portus.key
      - PORTUS_PUMA_TLS_CERT=/certificates/portus.crt

      # NGinx is serving the assets instead of Puma. If you want to change this,
      # uncomment this line.
      #- RAILS_SERVE_STATIC_FILES='true'
    ports:
      - 3000:3000
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro
      - static:/srv/Portus/public
      - ./config.yml:/srv/Portus/config/config.yml
    extra_hosts:
      - "registry.nxgvm.net:10.6.19.55"

  crono:
    image: opensuse/portus:head
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_PRODUCTION_HOST=db
      - PORTUS_PRODUCTION_DATABASE=portus_production
      - PORTUS_PRODUCTION_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      # We want to execute crono, not portus
      - PORTUS_INIT_COMMAND=bin/crono
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro

  db:
    image: library/mariadb:10.0.23
    environment:
      - MYSQL_DATABASE=portus_production

      # Again, the password shouldn't be handled like this.
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./mariadb:/var/lib/mysql

  registry:
    image: library/registry:2.6
    command: ["/bin/sh", "/etc/docker/registry/init"]
    environment:
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: https://${MACHINE_FQDN}/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /secrets/portus.crt
      REGISTRY_LOGLEVEL: debug

      # SSL
      REGISTRY_HTTP_TLS_CERTIFICATE: /secrets/portus.crt
      REGISTRY_HTTP_TLS_KEY: /secrets/portus.key

      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://${MACHINE_FQDN}/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
      - ./registry_data:/var/lib/registry
      - ./secrets:/secrets:ro
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
      - ./registry/init:/etc/docker/registry/init:ro
    ports:
      - 5000:5000
      - 5001:5001 # required to access debug service
    links:
      - portus:portus
    hostname: registry
    extra_hosts:
      - "registry.nxgvm.net:10.6.19.55"

  nginx:
    image: library/nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./secrets:/secrets:ro
      - static:/srv/Portus/public:ro
    ports:
      - 8080:80
      - 443:443
    links:
      - registry:registry
      - portus:portus
    extra_hosts:
      - "registry.nxgvm.net:10.6.19.55"

volumes:
  static:
    driver: local
```

.env:
```
MACHINE_FQDN=registry.nxgvm.net

SECRET_KEY_BASE=b494a25faa8d22e430e843e220e424e10ac84d2ce0e64231f5b636d21251eb6d267adb042ad5884cbff0f3891bcf911bdf8abb3ce719849ccda9a4889249e5c2
PORTUS_PASSWORD=12341234
DATABASE_PASSWORD=portus
```

push log:
```
docker push registry.nxgvm.net/admin/platform-index
The push refers to a repository [registry.nxgvm.net/admin/platform-index]
694b6127a718: Preparing
2566184aad73: Preparing
ac7521f796fe: Preparing
536c1a4e0d46: Preparing
929456210ad5: Preparing
5f8cd39d275c: Waiting
959ea408ed69: Waiting
ec01751c27a4: Waiting
3fb66f713c9f: Waiting
denied: requested access to the resource is denied
```

registry log:

```
Attaching to compose_registry_1
registry_1  | time="2017-11-14T11:17:26Z" level=debug msg="authorizing request" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=1b91d25e-7ceb-4575-b03c-eb7ee4d2e297 http.request.method=GET http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f version=v2.6.2
registry_1  | time="2017-11-14T11:17:26Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=1b91d25e-7ceb-4575-b03c-eb7ee4d2e297 http.request.method=GET http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f version=v2.6.2
registry_1  | 172.22.0.6 - - [14/Nov/2017:11:17:26 +0000] "GET /v2/ HTTP/1.0" 401 87 "" "docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))"
registry_1  | time="2017-11-14T11:17:27Z" level=debug msg="authorizing request" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=9ad91c62-7478-4b11-83ea-f473dd6425e0 http.request.method=POST http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/admin/platform-index/blobs/uploads/" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f vars.name="admin/platform-index" version=v2.6.2
registry_1  | time="2017-11-14T11:17:27Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=9ad91c62-7478-4b11-83ea-f473dd6425e0 http.request.method=POST http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/admin/platform-index/blobs/uploads/" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f vars.name="admin/platform-index" version=v2.6.2
registry_1  | 172.22.0.6 - - [14/Nov/2017:11:17:27 +0000] "POST /v2/admin/platform-index/blobs/uploads/ HTTP/1.0" 401 242 "" "docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))"
registry_1  | time="2017-11-14T11:17:27Z" level=debug msg="authorizing request" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=508cfee4-576f-4377-82d2-ecd31c371cb7 http.request.method=POST http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/admin/platform-index/blobs/uploads/" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f vars.name="admin/platform-index" version=v2.6.2
registry_1  | time="2017-11-14T11:17:27Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=508cfee4-576f-4377-82d2-ecd31c371cb7 http.request.method=POST http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/admin/platform-index/blobs/uploads/" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f vars.name="admin/platform-index" version=v2.6.2
registry_1  | 172.22.0.6 - - [14/Nov/2017:11:17:27 +0000] "POST /v2/admin/platform-index/blobs/uploads/ HTTP/1.0" 401 242 "" "docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))"
registry_1  | time="2017-11-14T11:17:27Z" level=debug msg="authorizing request" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=cfdbb24a-f856-4efa-864b-f4aee227cc24 http.request.method=POST http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/admin/platform-index/blobs/uploads/" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f vars.name="admin/platform-index" version=v2.6.2
registry_1  | time="2017-11-14T11:17:27Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=cfdbb24a-f856-4efa-864b-f4aee227cc24 http.request.method=POST http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/admin/platform-index/blobs/uploads/" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f vars.name="admin/platform-index" version=v2.6.2
registry_1  | 172.22.0.6 - - [14/Nov/2017:11:17:27 +0000] "POST /v2/admin/platform-index/blobs/uploads/ HTTP/1.0" 401 242 "" "docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))"
registry_1  | time="2017-11-14T11:17:27Z" level=debug msg="authorizing request" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=3f5a54b5-88d6-41fd-abd6-f7a79e07962a http.request.method=POST http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/admin/platform-index/blobs/uploads/" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f vars.name="admin/platform-index" version=v2.6.2
registry_1  | time="2017-11-14T11:17:27Z" level=debug msg="authorizing request" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=12b6364e-4b84-40c0-b1f9-b099ec9f5354 http.request.method=POST http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/admin/platform-index/blobs/uploads/" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f vars.name="admin/platform-index" version=v2.6.2
registry_1  | time="2017-11-14T11:17:27Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=3f5a54b5-88d6-41fd-abd6-f7a79e07962a http.request.method=POST http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/admin/platform-index/blobs/uploads/" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f vars.name="admin/platform-index" version=v2.6.2
registry_1  | 172.22.0.6 - - [14/Nov/2017:11:17:27 +0000] "POST /v2/admin/platform-index/blobs/uploads/ HTTP/1.0" 401 242 "" "docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))"
registry_1  | time="2017-11-14T11:17:27Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=12b6364e-4b84-40c0-b1f9-b099ec9f5354 http.request.method=POST http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/admin/platform-index/blobs/uploads/" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f vars.name="admin/platform-index" version=v2.6.2
registry_1  | 172.22.0.6 - - [14/Nov/2017:11:17:27 +0000] "POST /v2/admin/platform-index/blobs/uploads/ HTTP/1.0" 401 242 "" "docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))"
registry_1  | time="2017-11-14T11:17:27Z" level=debug msg="authorizing request" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=c863b891-dde0-4db6-83df-420c7cdde55c http.request.method=HEAD http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/admin/platform-index/blobs/sha256:282faf0ba1610c0c4a084b389ac75ef67200c730795fc7d691165d37900a4b47" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f vars.digest="sha256:282faf0ba1610c0c4a084b389ac75ef67200c730795fc7d691165d37900a4b47" vars.name="admin/platform-index" version=v2.6.2
registry_1  | time="2017-11-14T11:17:27Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=c863b891-dde0-4db6-83df-420c7cdde55c http.request.method=HEAD http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/admin/platform-index/blobs/sha256:282faf0ba1610c0c4a084b389ac75ef67200c730795fc7d691165d37900a4b47" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f vars.digest="sha256:282faf0ba1610c0c4a084b389ac75ef67200c730795fc7d691165d37900a4b47" vars.name="admin/platform-index" version=v2.6.2
registry_1  | 172.22.0.6 - - [14/Nov/2017:11:17:27 +0000] "HEAD /v2/admin/platform-index/blobs/sha256:282faf0ba1610c0c4a084b389ac75ef67200c730795fc7d691165d37900a4b47 HTTP/1.0" 401 163 "" "docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))"
registry_1  | time="2017-11-14T11:17:27Z" level=debug msg="authorizing request" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=3d98546f-52a3-49a9-b9ec-6d8ea17bf017 http.request.method=HEAD http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/admin/platform-index/blobs/sha256:2aecc7e1714b6fad58d13aedb0639011b37b86f743ba7b6a52d82bd03014b78e" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f vars.digest="sha256:2aecc7e1714b6fad58d13aedb0639011b37b86f743ba7b6a52d82bd03014b78e" vars.name="admin/platform-index" version=v2.6.2
registry_1  | time="2017-11-14T11:17:27Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=3d98546f-52a3-49a9-b9ec-6d8ea17bf017 http.request.method=HEAD http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/admin/platform-index/blobs/sha256:2aecc7e1714b6fad58d13aedb0639011b37b86f743ba7b6a52d82bd03014b78e" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f vars.digest="sha256:2aecc7e1714b6fad58d13aedb0639011b37b86f743ba7b6a52d82bd03014b78e" vars.name="admin/platform-index" version=v2.6.2
registry_1  | 172.22.0.6 - - [14/Nov/2017:11:17:27 +0000] "HEAD /v2/admin/platform-index/blobs/sha256:2aecc7e1714b6fad58d13aedb0639011b37b86f743ba7b6a52d82bd03014b78e HTTP/1.0" 401 163 "" "docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))"
registry_1  | time="2017-11-14T11:17:27Z" level=debug msg="authorizing request" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=b33db40b-c7de-40bc-ba55-204b1cc2adde http.request.method=HEAD http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/admin/platform-index/blobs/sha256:031d57e4298b7a7c584115aae6e13bcc06a56d65e3842e38494b68e560afb379" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f vars.digest="sha256:031d57e4298b7a7c584115aae6e13bcc06a56d65e3842e38494b68e560afb379" vars.name="admin/platform-index" version=v2.6.2
registry_1  | time="2017-11-14T11:17:27Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=b33db40b-c7de-40bc-ba55-204b1cc2adde http.request.method=HEAD http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/admin/platform-index/blobs/sha256:031d57e4298b7a7c584115aae6e13bcc06a56d65e3842e38494b68e560afb379" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f vars.digest="sha256:031d57e4298b7a7c584115aae6e13bcc06a56d65e3842e38494b68e560afb379" vars.name="admin/platform-index" version=v2.6.2
registry_1  | 172.22.0.6 - - [14/Nov/2017:11:17:27 +0000] "HEAD /v2/admin/platform-index/blobs/sha256:031d57e4298b7a7c584115aae6e13bcc06a56d65e3842e38494b68e560afb379 HTTP/1.0" 401 163 "" "docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))"
registry_1  | time="2017-11-14T11:17:27Z" level=debug msg="authorizing request" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=68c65f20-921d-4fd7-835e-0b1541f69441 http.request.method=HEAD http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/admin/platform-index/blobs/sha256:023f0885c8f650d666f3d6a2871532bdb20c4c59e7348f3c0618ae276469ef19" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f vars.digest="sha256:023f0885c8f650d666f3d6a2871532bdb20c4c59e7348f3c0618ae276469ef19" vars.name="admin/platform-index" version=v2.6.2
registry_1  | time="2017-11-14T11:17:27Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=68c65f20-921d-4fd7-835e-0b1541f69441 http.request.method=HEAD http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/admin/platform-index/blobs/sha256:023f0885c8f650d666f3d6a2871532bdb20c4c59e7348f3c0618ae276469ef19" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f vars.digest="sha256:023f0885c8f650d666f3d6a2871532bdb20c4c59e7348f3c0618ae276469ef19" vars.name="admin/platform-index" version=v2.6.2
registry_1  | 172.22.0.6 - - [14/Nov/2017:11:17:27 +0000] "HEAD /v2/admin/platform-index/blobs/sha256:023f0885c8f650d666f3d6a2871532bdb20c4c59e7348f3c0618ae276469ef19 HTTP/1.0" 401 163 "" "docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))"
registry_1  | time="2017-11-14T11:17:27Z" level=debug msg="authorizing request" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=f1b92d5e-e8ed-41f5-b932-d308bea0b0a5 http.request.method=POST http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/admin/platform-index/blobs/uploads/" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f vars.name="admin/platform-index" version=v2.6.2
registry_1  | time="2017-11-14T11:17:27Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=f1b92d5e-e8ed-41f5-b932-d308bea0b0a5 http.request.method=POST http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/admin/platform-index/blobs/uploads/" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f vars.name="admin/platform-index" version=v2.6.2
registry_1  | 172.22.0.6 - - [14/Nov/2017:11:17:27 +0000] "POST /v2/admin/platform-index/blobs/uploads/ HTTP/1.0" 401 242 "" "docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))"
registry_1  | time="2017-11-14T11:17:27Z" level=debug msg="authorizing request" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=ee68269b-d8b5-43c1-92c6-c22efa2b44ce http.request.method=POST http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/admin/platform-index/blobs/uploads/" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f vars.name="admin/platform-index" version=v2.6.2
registry_1  | time="2017-11-14T11:17:27Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=ee68269b-d8b5-43c1-92c6-c22efa2b44ce http.request.method=POST http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/admin/platform-index/blobs/uploads/" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f vars.name="admin/platform-index" version=v2.6.2
registry_1  | 172.22.0.6 - - [14/Nov/2017:11:17:27 +0000] "POST /v2/admin/platform-index/blobs/uploads/ HTTP/1.0" 401 242 "" "docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))"
registry_1  | time="2017-11-14T11:17:27Z" level=debug msg="authorizing request" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=aebd4d15-f3e0-4250-afe6-ccc6328a2d55 http.request.method=POST http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/admin/platform-index/blobs/uploads/" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f vars.name="admin/platform-index" version=v2.6.2
registry_1  | time="2017-11-14T11:17:27Z" level=debug msg="authorizing request" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=72ae3504-6393-4ee3-bfef-8f753ffc3777 http.request.method=POST http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/admin/platform-index/blobs/uploads/" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f vars.name="admin/platform-index" version=v2.6.2
registry_1  | time="2017-11-14T11:17:27Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=aebd4d15-f3e0-4250-afe6-ccc6328a2d55 http.request.method=POST http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/admin/platform-index/blobs/uploads/" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f vars.name="admin/platform-index" version=v2.6.2
registry_1  | 172.22.0.6 - - [14/Nov/2017:11:17:27 +0000] "POST /v2/admin/platform-index/blobs/uploads/ HTTP/1.0" 401 242 "" "docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))"
registry_1  | time="2017-11-14T11:17:27Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.7.6 http.request.host=registry.nxgvm.net http.request.id=72ae3504-6393-4ee3-bfef-8f753ffc3777 http.request.method=POST http.request.remoteaddr=10.6.19.55 http.request.uri="/v2/admin/platform-index/blobs/uploads/" http.request.useragent="docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))" instance.id=678cdd8b-3fc8-4374-a5e3-77237d0cf81f vars.name="admin/platform-index" version=v2.6.2
registry_1  | 172.22.0.6 - - [14/Nov/2017:11:17:27 +0000] "POST /v2/admin/platform-index/blobs/uploads/ HTTP/1.0" 401 242 "" "docker/17.06.1-ce go/go1.8.3 git-commit/874a737 kernel/4.4.0-31-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.06.1-ce \\(linux\\))"
```

I can login to this registry, but I cannot push or pull anything. I once succeed pushed an image, but when I remove the data and `down & up` the containers, I never saw it again.

Struggling a whole day, please help...
