### ISSUE TITLE
Connecting to database timeout

### ISSUE THREAD

**Issue by ironhouzi** [SUSE/Portus#1674]
I'm using the following `docker-compose.yml`:

```
version: "2"

services:
  portus:
    image: opensuse/portus:2.3
    environment:
      - PORTUS_MACHINE_FQDN_VALUE={{ portus_fqdn }}

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD={{ portus_db_password }}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE={{ portus_secret_key_base }}
      # - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_KEY_PATH=/certificates/live/{{ portus_fqdn }}/privkey.pem
      - PORTUS_PASSWORD={{ portus_password }}

      # SSL
      # - PORTUS_PUMA_TLS_KEY=/certificates/portus.key
      - PORTUS_PUMA_TLS_KEY=/certificates/live/{{ portus_fqdn }}/privkey.pem
      # - PORTUS_PUMA_TLS_CERT=/certificates/portus.crt
      - PORTUS_PUMA_TLS_CERT=/certificates/live/{{ portus_fqdn }}/fullchain.pem
      # NGinx is serving the assets instead of Puma. If you want to change this,
      # uncomment this line.
      #- RAILS_SERVE_STATIC_FILES='true'
    ports:
      - 3000:3000
    links:
      - db
    volumes:
      - secrets:/certificates:ro
      - static:/srv/Portus/public

  background:
    image: opensuse/portus:2.3
    depends_on:
      - portus
      - db
    environment:
      # Theoretically not needed, but cconfig's been buggy on this...
      - CCONFIG_PREFIX=PORTUS
      - PORTUS_MACHINE_FQDN_VALUE={{ portus_fqdn }}

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD={{ portus_db_password }}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE={{ portus_secret_key_base }}
      # - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_KEY_PATH=/certificates/live/{{ portus_fqdn }}/privkey.pem
      - PORTUS_PASSWORD={{ portus_password }}

      - PORTUS_BACKGROUND=true
    links:
      - db
    volumes:
      - secrets:/certificates:ro

  db:
    image: library/mariadb:10.0.23
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      - MYSQL_DATABASE=portus_production

      # Again, the password shouldn't be handled like this.
      - MYSQL_ROOT_PASSWORD={{ portus_db_password }}
    volumes:
      - /var/lib/portus/mariadb:/var/lib/mysql

  registry:
    image: library/registry:2.6
    command: ["/bin/sh", "/etc/docker/registry/init"]
    environment:
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: https://{{ portus_fqdn }}/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: {{ portus_fqdn }}
      REGISTRY_AUTH_TOKEN_ISSUER: {{ portus_fqdn }}
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /secrets/live/{{ portus_fqdn }}/fullchain.pem

      # SSL
      REGISTRY_HTTP_TLS_CERTIFICATE: /secrets/live/{{ portus_fqdn }}/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: /secrets/live/{{ portus_fqdn }}/privkey.pem

      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://{{ portus_fqdn }}/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
      - /var/lib/portus/registry:/var/lib/registry
      - secrets:/secrets:ro
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
      - ./registry/init:/etc/docker/registry/init:ro
    ports:
      - 5000:5000
      - 5001:5001 # required to access debug service
    links:
      - portus:portus

  nginx:
    image: library/nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - secrets:/secrets:ro
      - static:/srv/Portus/public:ro
    ports:
      - 80:80
      - 443:443
    links:
      - registry:registry
      - portus:portus

volumes:
  static:
    driver: local
  secrets:
    external: true
```

My log:

```
portus_1      | Waiting for mariadb to be ready in 5 seconds
background_1  | [Mailer config] Host:     docker.mycorp.no
background_1  | [Mailer config] Protocol: https://
background_1  | [Database] Not ready yet. Waiting...
registry_1    | + registry serve /etc/docker/registry/config.yml
registry_1    | time="2018-02-08T14:42:37Z" level=info msg="debug server listening 0.0.0.0:5001"
registry_1    | time="2018-02-08T14:42:37Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.7.6 instance.id=3e7fc735-38f8-4e43-a7e8-dac6a064be3d version=v2.6.2
registry_1    | time="2018-02-08T14:42:37Z" level=info msg="configuring endpoint portus (https://docker.mycorp.no/v2/webhooks/events), timeout=2s, headers=map[]" go.version=go1.7.6 instance.id=3e7fc735-38f8-4e43-a7e8-dac6a064be3d version=v2.6.2
registry_1    | time="2018-02-08T14:42:37Z" level=info msg="redis not configured" go.version=go1.7.6 instance.id=3e7fc735-38f8-4e43-a7e8-dac6a064be3d version=v2.6.2
registry_1    | time="2018-02-08T14:42:37Z" level=info msg="Starting upload purge in 4m0s" go.version=go1.7.6 instance.id=3e7fc735-38f8-4e43-a7e8-dac6a064be3d version=v2.6.2
registry_1    | time="2018-02-08T14:42:37Z" level=info msg="listening on [::]:5000, tls" go.version=go1.7.6 instance.id=3e7fc735-38f8-4e43-a7e8-dac6a064be3d version=v2.6.2
db_1          | 180208 14:42:32 [Note] mysqld (mysqld 10.0.23-MariaDB-1~jessie) starting as process 1 ...
db_1          | 180208 14:42:32 [Note] InnoDB: Using mutexes to ref count buffer pool pages
db_1          | 180208 14:42:32 [Note] InnoDB: The InnoDB memory heap is disabled
db_1          | 180208 14:42:32 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1          | 180208 14:42:32 [Note] InnoDB: Memory barrier is not used
db_1          | 180208 14:42:32 [Note] InnoDB: Compressed tables use zlib 1.2.8
db_1          | 180208 14:42:32 [Note] InnoDB: Using Linux native AIO
db_1          | 180208 14:42:32 [Note] InnoDB: Not using CPU crc32 instructions
db_1          | 180208 14:42:32 [Note] InnoDB: Initializing buffer pool, size = 256.0M
db_1          | 180208 14:42:32 [Note] InnoDB: Completed initialization of buffer pool
db_1          | 180208 14:42:33 [Note] InnoDB: Highest supported file format is Barracuda.
db_1          | 180208 14:42:33 [Note] InnoDB: 128 rollback segment(s) are active.
db_1          | 180208 14:42:33 [Note] InnoDB: Waiting for purge to start
db_1          | 180208 14:42:33 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.26-76.0 started; log sequence number 1617073
db_1          | 180208 14:42:33 [Note] Plugin 'FEEDBACK' is disabled.
db_1          | 180208 14:42:33 [Note] Server socket created on IP: '::'.
db_1          | 180208 14:42:33 [Warning] 'proxies_priv' entry '@% root@d7f46df262b7' ignored in --skip-name-resolve mode.
db_1          | 180208 14:42:33 [Note] mysqld: ready for connections.
db_1          | Version: '10.0.23-MariaDB-1~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
background_1  | [Database] Not ready yet. Waiting...
portus_1      | Waiting for mariadb to be ready in 5 seconds
background_1  | [Database] Not ready yet. Waiting...
background_1  | [Database] Not ready yet. Waiting...
portus_1      | Waiting for mariadb to be ready in 5 seconds
background_1  | [Database] Not ready yet. Waiting...
portus_1      | Waiting for mariadb to be ready in 5 seconds
background_1  | [Database] Not ready yet. Waiting...
background_1  | [Database] Not ready yet. Waiting...
portus_1      | Waiting for mariadb to be ready in 5 seconds
background_1  | [Database] Not ready yet. Waiting...
background_1  | [Database] Not ready yet. Waiting...
```

.. which continues until `background` and `portus` containers timeout and I get this error:

```
background_1  | [Database] Timeout reached, exiting with error. Check the logs...
background_1  | bundler: failed to load command: packaging/suse/portusctl/bin/portusctl (packaging/suse/portusctl/bin/portusctl)
background_1  | /srv/Portus/lib/portus/db.rb:40:in `wait_until': Timeout reached for 'ready' status (Portus::DB::TimeoutReachedError)
background_1  |         from /srv/Portus/bin/background.rb:8:in `<top (required)>'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `load'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `<top (required)>'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:90:in `runner'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
background_1  |         from bin/rails:12:in `require'
background_1  |         from bin/rails:12:in `<main>'
background_1  | RuntimeError: Something went wrong while invoking: /srv/Portus/vendor/bundle/ruby/2.5.0/bin/bundler.ruby2.5 exec rails r /srv/Portus/bin/background.rb
background_1  |   /srv/Portus/packaging/suse/portusctl/lib/runner.rb:12:in `exec'
background_1  |   /srv/Portus/packaging/suse/portusctl/lib/runner.rb:34:in `block in bundler_exec'
background_1  |   /srv/Portus/packaging/suse/portusctl/lib/runner.rb:30:in `chdir'
background_1  |   /srv/Portus/packaging/suse/portusctl/lib/runner.rb:30:in `bundler_exec'
background_1  |   /srv/Portus/packaging/suse/portusctl/lib/cli.rb:258:in `exec'
background_1  |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
background_1  |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
background_1  |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
background_1  |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
background_1  |   packaging/suse/portusctl/bin/portusctl:6:in `<top (required)>'
```

I have tried the following:

- Create host directory `/var/lib/portus/mariadb`.
- Verified that the `docker-compose.yml` `jinja` template variables are expanded correctly.
- Verified that the two containers in question can reach the database host with `ping`.
- Change the container tag version to `head` and `2.2`. 

What I'd like to troubleshoot, but haven't managed:

- Manually log into the database. I've tried `docker exec`'ing into the `db` container and run `mysql --password=$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE`.
- Check what credentials the ruby app is trying to connect with in the `check_db.rb` script.

I've seen similar errors in other issues, but they seem to be unresolved. Still, I was hoping to get some help with the troubleshooting.
