### ISSUE TITLE
Failed to create bus connection | uninitialized constant Portus::DB::Mysql2

### ISSUE THREAD

**Issue by soosap** [SUSE/Portus#1697]
### Description

This is day 3 in which I try to run a portus deployment through Kubernetes and Helm. Since I am only familiar with postgresql I am trying to use that particular `PORTUS_DB_ADAPTER`. I am receiving a series of errors and I am not sure how to resolve them.

### Steps to reproduce

1. First I did this...
Deploy portus through my helm chart (see attached the k8s workloads)
2. Then that...
`$ kubectl get po`
`$ kubectl logs registry-portus-d49564454-txtfz -c portus`
3. And this happened!
* `Failed to create bus connection: No such file or directory`
* `uninitialized constant Portus::DB::Mysql2`
Seems like `PORTUS_DB_ADAPTER` **postgresql** is being ignored. It still tries to connect w/ Mysql2 for some reason. Please help :)

- **Expected behavior**: I expected this to happen!
No errors.

- **Actual behavior**: But this happened...
```
Failed to create bus connection: No such file or directory
/srv/Portus/lib/portus/db.rb:19:in `rescue in ping': uninitialized constant Portus::DB::Mysql2 (NameError)
	from /srv/Portus/lib/portus/db.rb:15:in `ping'
	from /srv/Portus/bin/check_db.rb:17:in `<top (required)>'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `load'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `<top (required)>'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:90:in `runner'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:12:in `require'
	from bin/rails:12:in `<main>'
RuntimeError: Something went wrong while invoking: /srv/Portus/vendor/bundle/ruby/2.5.0/bin/bundler.ruby2.5 exec rails r /srv/Portus/bin/check_db.rb
  /srv/Portus/packaging/suse/portusctl/lib/runner.rb:12:in `exec'
  /srv/Portus/packaging/suse/portusctl/lib/runner.rb:34:in `block in bundler_exec'
  /srv/Portus/packaging/suse/portusctl/lib/runner.rb:30:in `chdir'
  /srv/Portus/packaging/suse/portusctl/lib/runner.rb:30:in `bundler_exec'
  /srv/Portus/packaging/suse/portusctl/lib/cli.rb:258:in `exec'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  packaging/suse/portusctl/bin/portusctl:6:in `<top (required)>'

```

### Deployment information

**Deployment method**:
Custom helm chart heavily inspired by `https://github.com/kubic-project/caasp-services/blob/master/contrib/helm-charts/portus/` with some customisation.

**Configuration**:
`portusctl bundle exec rake portus:info`
* portus:info
```yml
Failed to create bus connection: No such file or directory
[Mailer config] Host:     registry-portus
[Mailer config] Protocol: https://
Evaluated configuration:
---
email:
  from: portus@company.io
  name: Portus | C O M P A N Y
  reply_to: no-reply@company.io
  smtp:
    enabled: true
    address: smtp.zoho.eu
    port: 465
    user_name: username@example.com
    password: "****"
    domain: company.io
gravatar:
  enabled: true
delete:
  enabled: true
ldap:
  enabled: false
  hostname: ldap_hostname
  port: 389
  method: plain
  base: ''
  filter: ''
  uid: uid
  authentication:
    enabled: false
    bind_dn: ''
    password: "****"
  guess_email:
    enabled: false
    attr: ''
oauth:
  local_login:
    enabled: true
  google_oauth2:
    enabled: false
    id: ''
    secret: ''
    domain: ''
    options:
      hd: ''
  open_id:
    enabled: false
    identifier: ''
    domain: ''
  github:
    enabled: false
    client_id: ''
    client_secret: ''
    organization: ''
    team: ''
    domain: ''
  gitlab:
    enabled: false
    application_id: ''
    secret: ''
    group: ''
    domain: ''
    server: ''
  bitbucket:
    enabled: false
    key: ''
    secret: ''
    domain: ''
    options:
      team: ''
first_user_admin:
  enabled: true
signup:
  enabled: false
check_ssl_usage:
  enabled: true
registry:
  jwt_expiration_time:
    value: 5
  catalog_page:
    value: 100
  timeout:
    value: 2
  read_timeout:
    value: 120
machine_fqdn:
  value: registry-portus
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: true
  create_team:
    enabled: true
  manage_team:
    enabled: true
  create_namespace:
    enabled: true
  manage_namespace:
    enabled: true
security:
  clair:
    server: ''
    health_port: 6061
  zypper:
    server: ''
  dummy:
    server: ''
anonymous_browsing:
  enabled: false

Portus version: 2.4.0-dev@46ae80aeed17075974988de5a88a75fd9d4ebb53
```

* Kubernetes workloads
```yml
NAME:   registry
REVISION: 1
RELEASED: Thu Feb 22 09:58:47 2018
CHART: registry-1.0.0
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
nginx:
  config:
    provided: true
  global: {}
  image:
    pullPolicy: IfNotPresent
    repository: nginx
    tag: 1.13.8-alpine
  replicaCount: 1
  service:
    externalPort: 80
    internalPort: 80
    type: ClusterIP
portus:
  background:
    enabled: true
    resources:
      requests:
        cpu: 300m
        memory: 512Mi
  config:
    anonymous_browsing:
      enabled: false
    check_ssl_usage:
      enabled: true
    delete:
      enabled: true
    display_name:
      enabled: false
    email:
      from: portus@company.io
      name: Portus | C O M P A N Y
      reply_to: no-reply@company.io
      smtp:
        address: smtp.zoho.eu
        domain: company.io
        enabled: true
        port: 465
        username: portus@company.io
    first_user_admin:
      enabled: true
    gravatar:
      enabled: true
    machine_fqdn:
      value: registry.company.io
    signup:
      enabled: false
  environment:
    PORTUS_DB_DATABASE: portus
    PORTUS_DB_PASSWORD: s3cr3t
    PORTUS_DB_PORT: 5432
    PORTUS_DB_USERNAME: portus
    PORTUS_EMAIL_SMTP_PASSWORD: s3cr3t
  global: {}
  image:
    pullPolicy: Always
    repository: portus
    tag: head
  ingress:
    domains:
    - portus.company.io
    enabled: true
  replicaCount: 1
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
  service:
    externalPort: 3000
    internalPort: 3000
    type: ClusterIP
postgres:
  backup:
    bucket: company-backup
    enabled: true
    schedule: nightly
  environment:
    PGDATA: /var/lib/postgresql/data/pgdata
    POSTGRES_DB: portus
    POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    POSTGRES_USER: company
  global: {}
  image:
    namespace: company
    pullPolicy: IfNotPresent
    registry: localhost:30000
    repository: postgres
    tag: 9.6.7-alpine
  replicaCount: 1
  service:
    externalPort: 5432
    internalPort: 5432
    type: ClusterIP
  storage:
    class: aws-ebs-gp2
    size: 2Gi
registry:
  config:
    health:
      storagedriver:
        enabled: false
    http:
      addr: :5000
      debug:
        addr: :5001
      headers:
        Access-Control-Allow-Headers:
        - Authorization
        Access-Control-Allow-Methods:
        - HEAD
        - GET
        - OPTIONS
        - DELETE
        Access-Control-Expose-Headers:
        - Docker-Content-Digest
        X-Content-Type-Options:
        - nosniff
    log:
      level: debug
    storage:
      delete:
        enabled: true
      s3:
        bucket: company-registry
        region: eu-central-1
        rootdirectory: /
    version: 0.1
  environment:
    REGISTRY_AUTH: token
  global: {}
  image:
    pullPolicy: IfNotPresent
    repository: registry
    tag: 2.6.2
  ingress:
    domains:
    - registry.company.io
    enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: 1500m
      memory: 2Gi
    requests:
      cpu: 750m
      memory: 750Mi
  service:
    debug:
      externalPort: 30001
    externalPort: 30000
    type: NodePort
registry-proxy:
  global: {}
  image:
    namespace: google_containers
    pullPolicy: IfNotPresent
    registry: gcr.io
    repository: kube-registry-proxy
    tag: 0.4
  registry:
    port: 5000
  resources:
    limits:
      cpu: 200m
      memory: 100Mi
  tolerations:
  - effect: NoSchedule
    key: kops.k8s.io/instancegroup
    operator: Equal
    value: builders

HOOKS:
MANIFEST:

---
# Source: registry/charts/portus/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-portus-config
  namespace: default
data:
  config-local.yml: |
    anonymous_browsing:
      enabled: false
    check_ssl_usage:
      enabled: true
    delete:
      enabled: true
    display_name:
      enabled: false
    email:
      from: portus@company.io
      name: Portus | C O M P A N Y
      reply_to: no-reply@company.io
      smtp:
        address: smtp.zoho.eu
        domain: company.io
        enabled: true
        port: 465
        username: portus@company.io
    first_user_admin:
      enabled: true
    gravatar:
      enabled: true
    machine_fqdn:
      value: registry.company.io
    signup:
      enabled: false
---
# Source: registry/charts/registry/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-registry-config
  namespace: default
data:
  config.yml: |
    health:
      storagedriver:
        enabled: false
    http:
      addr: :5000
      debug:
        addr: :5001
      headers:
        Access-Control-Allow-Headers:
        - Authorization
        Access-Control-Allow-Methods:
        - HEAD
        - GET
        - OPTIONS
        - DELETE
        Access-Control-Expose-Headers:
        - Docker-Content-Digest
        X-Content-Type-Options:
        - nosniff
    log:
      level: debug
    storage:
      delete:
        enabled: true
      s3:
        bucket: company-registry
        region: eu-central-1
        rootdirectory: /
    version: 0.1
---
# Source: registry/templates/nginx-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-nginx-config
  labels:
    app: registry
    chart: "registry-1.0.0"
    release: registry
    heritage: Tiller
data:
  nginx.conf: |
    # This file is largely based on the one written by @Djelibeybi in:
    #      https://github.com/Djelibeybi/Portus-On-OracleLinux7/
    events {
      worker_connections 1024;
    }
    http {
      default_type  application/octet-stream;
      charset       UTF-8;
      # Some basic config.
      server_tokens off;
      sendfile      on;
      tcp_nopush    on;
      tcp_nodelay   on;
      # On timeouts.
      keepalive_timeout     65;
      client_header_timeout 240;
      client_body_timeout   240;
      fastcgi_read_timeout  249;
      reset_timedout_connection on;
      ## Set a variable to help us decide if we need to add the
      ## 'Docker-Distribution-Api-Version' header.
      ## The registry always sets this header.
      ## In the case of nginx performing auth, the header will be unset
      ## since nginx is auth-ing before proxying.
      map $upstream_http_docker_distribution_api_version $docker_distribution_api_version {
        '' 'registry/2.0';
      }
      upstream registry-portus {
        least_conn;
        server registry-portus:3000 max_fails=3 fail_timeout=15s;
      }
      upstream registry-registry:30000 {
        least_conn;
        server registry-registry:30000 max_fails=3 fail_timeout=15s;
      }
      server {
        server_name registry-nginx
        listen 80 http2;
        ##
        # Docker-specific stuff.
        proxy_set_header Host $http_host;   # required for Docker client sake
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Scheme $scheme;
        # disable any limits to avoid HTTP 413 for large image uploads
        client_max_body_size 0;
        # required to avoid HTTP 411: see Issue #1486
        # (https://github.com/docker/docker/issues/1486)
        chunked_transfer_encoding on;
        ##
        # Custom headers.
        # Adding HSTS[1] (HTTP Strict Transport Security) to avoid SSL stripping[2].
        #
        # [1] https://developer.mozilla.org/en-US/docs/Security/HTTP_Strict_Transport_Security
        # [2] https://en.wikipedia.org/wiki/SSL_stripping#SSL_stripping
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
        # Don't allow the browser to render the page inside a frame or iframe
        # and avoid Clickjacking. More in the following link:
        #
        # https://developer.mozilla.org/en-US/docs/HTTP/X-Frame-Options
        add_header X-Frame-Options DENY;
        # Disable content-type sniffing on some browsers.
        add_header X-Content-Type-Options nosniff;
        # This header enables the Cross-site scripting (XSS) filter built into
        # most recent web browsers. It's usually enabled by default anyway, so the
        # role of this header is to re-enable the filter for this particular
        # website if it was disabled by the user.
        add_header X-XSS-Protection "1; mode=block";
        # Add header for IE in compatibility mode.
        add_header X-UA-Compatible "IE=edge";

        # Redirect (most) requests to /v2/* to the Docker Registry
        location /v2/ {
          # Do not allow connections from docker 1.5 and earlier
          # docker pre-1.6.0 did not properly set the user agent on ping, catch "Go *" user agents
          if ($http_user_agent ~ "^(docker\/1\.(3|4|5(?!\.[0-9]-dev))|Go ).*$" ) {
            return 404;
          }
          ## If $docker_distribution_api_version is empty, the header will not be added.
          ## See the map directive above where this variable is defined.
          add_header 'Docker-Distribution-Api-Version' $docker_distribution_api_version always;
          proxy_pass http://registry-registry:30000;
          proxy_set_header Host $http_host;   # required for docker client's sake
          proxy_set_header X-Real-IP $remote_addr; # pass on real client's IP
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_read_timeout 900;
          proxy_buffering on;
        }

        # Portus needs to handle /v2/token for authentication
        location = /v2/token {
          proxy_pass http://registry-portus;
          proxy_set_header Host $http_host;   # required for docker client's sake
          proxy_set_header X-Real-IP $remote_addr; # pass on real client's IP
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_read_timeout 900;
          proxy_buffering on;
        }

        # Portus needs to handle /v2/webhooks/events for notifications
        location = /v2/webhooks/events {
          proxy_pass http://registry-portus;
          proxy_set_header Host $http_host;   # required for docker client's sake
          proxy_set_header X-Real-IP $remote_addr; # pass on real client's IP
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_read_timeout 900;
          proxy_buffering on;
        }

        # Portus handles everything else for the UI
        location / {
          try_files $uri/index.html $uri.html $uri @registry-portus;
        }

        location @registry-portus {
          proxy_pass http://registry-portus;
          proxy_set_header Host $http_host;   # required for docker client's sake
          proxy_set_header X-Real-IP $remote_addr; # pass on real client's IP
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_read_timeout 900;
          proxy_buffering on;
        }
      }
    }
---
# Source: registry/charts/postgres/templates/volume.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-postgres-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: aws-ebs-gp2
  resources:
    requests:
      storage: 2Gi
---
# Source: registry/charts/nginx/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: registry-nginx
  namespace: default
  labels:
    app: nginx
    chart: nginx-0.1.0
    release: registry
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
  - name: nginx-port
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
    release: registry
---
# Source: registry/charts/portus/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: registry-portus
  namespace: default
  labels:
    app: portus
    chart: portus-0.1.0
    release: registry
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
  - name: portus-port
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: portus
    release: registry
---
# Source: registry/charts/postgres/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: registry-postgres
  namespace: default
  labels:
    app: postgres
    chart: postgres-0.1.0
    release: registry
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
  - name: postgres-port
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres
    release: registry
---
# Source: registry/charts/registry/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: registry-registry
  namespace: default
  labels:
    app: registry
    chart: registry-0.1.0
    release: registry
    heritage: Tiller
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: registry
spec:
  type: NodePort
  ports:
  - name: registry-port
    port: 5000
    nodePort: 30000
    targetPort: registry-port
    protocol: TCP
  - name: debug-port
    port: 5001
    nodePort: 30001
    targetPort: debug-port
    protocol: TCP
  selector:
    app: registry
    release: registry
---
# Source: registry/charts/registry-proxy/templates/daemonset.yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: registry-proxy
  namespace: default
  labels:
    app: registry-proxy
    chart: registry-proxy-0.1.0
    release: registry
    version: v0.4
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      app: registry-proxy
      release: registry
  template:
    metadata:
      labels:
        app: registry-proxy
        release: registry
        version: v0.4
        kubernetes.io/name: registry-proxy
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: registry-proxy
        image: "gcr.io/google_containers/kube-registry-proxy:0.4"
        ports:
        - name: registry-port
          containerPort: 80
          hostPort: 5000
        env:
        - name: REGISTRY_HOST
          value: "registry-registry.default.svc.cluster.local"
        - name: REGISTRY_PORT
          value: "$(REGISTRY_REGISTRY_SERVICE_PORT)"
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
      tolerations:
      - effect: NoSchedule
        key: kops.k8s.io/instancegroup
        operator: Equal
        value: builders
---
# Source: registry/charts/nginx/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry-nginx
  labels:
    app: nginx
    chart: nginx-0.1.0
    release: registry
    heritage: Tiller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        release: registry
    spec:
      containers:
      - name: nginx
        image: "nginx:1.13.8-alpine"
        imagePullPolicy: IfNotPresent
        ports:
        - name: nginx-port
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: "/etc/nginx/nginx.conf"
          subPath: "nginx.conf"
      volumes:
      - name: config
        configMap:
          name: registry-nginx-config
---
# Source: registry/charts/portus/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: registry-portus
  namespace: default
  labels:
    app: portus
    chart: portus-0.1.0
    release: registry
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portus
      release: registry
  template:
    metadata:
      labels:
        app: portus
        release: registry
    spec:
      containers:
      - name: portus
        image: "opensuse/portus:head"
        imagePullPolicy: Always
        ports:
        - name: portus-port
          containerPort: 3000
          protocol: TCP
        env:
        - name: PORTUS_LOG_LEVEL
          value: "debug"
        - name: PORTUS_MACHINE_FQDN_VALUE
          value: "registry-portus"
        - name: CCONFIG_PREFIX
          value: "PORTUS"
        - name: RAILS_SERVE_STATIC_FILES
          value: "true"
        - name: PORTUS_PASSWORD
          value: "s3cr3t"
        - name: PORTUS_SECRET_KEY_BASE
          value: "s3cr3t"
        - name: PORTUS_DB_ADAPTER
          value: "postgresql"
        - name: PORTUS_DB_HOST
          value: "registry-postgres.default.svc.cluster.local"
        - name: PORTUS_KEY_PATH
          value: "/certificates/portus.key"
        - name: PORTUS_PUMA_HOST
          value: "registry-portus.default.svc.cluster.local:$(REGISTRY_PORTUS_SERVICE_PORT)"
        - name: PORTUS_DB_DATABASE
          value: "portus"
        - name: PORTUS_DB_PASSWORD
          value: "s3cr3t"
        - name: PORTUS_DB_PORT
          value: "5432"
        - name: PORTUS_DB_USERNAME
          value: "portus"
        - name: PORTUS_EMAIL_SMTP_PASSWORD
          value: "s3cr3t"
        volumeMounts:
        - name: config
          mountPath: "/srv/Portus/config/config-local.yml"
          subPath: "config-local.yml"
          readOnly: True
        - name: tls
          mountPath: "/certificates/portus.key"
          subPath: "portus.key"
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
      - name: background
        image: "company/portus:head"
        imagePullPolicy: Always
        env:
        - name: PORTUS_LOG_LEVEL
          value: "debug"
        - name: PORTUS_BACKGROUND
          value: "true"
        - name: PORTUS_KEY_PATH
          value: "/certificates/portus.key"
        - name: PORTUS_PASSWORD
          value: "s3cr3t"
        - name: PORTUS_SECRET_KEY_BASE
          value: "s3cr3t"
        - name: PORTUS_DB_ADAPTER
          value: "postgresql"
        - name: PORTUS_DB_HOST
          value: "registry-postgres.default.svc.cluster.local"
        - name: PORTUS_DB_DATABASE
          value: "portus"
        - name: PORTUS_DB_PASSWORD
          value: "s3cr3t"
        - name: PORTUS_DB_PORT
          value: "5432"
        - name: PORTUS_DB_USERNAME
          value: "portus"
        - name: PORTUS_EMAIL_SMTP_PASSWORD
          value: "s3cr3t"
        volumeMounts:
        - name: tls
          mountPath: "/certificates/portus.key"
          subPath: "portus.key"
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
      volumes:
      - name: config
        configMap:
          name: "registry-portus-config"
      - name: tls
        secret:
          secretName: "tls-registry-portus-cert"
---
# Source: registry/charts/postgres/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry-postgres
  namespace: default
  labels:
    app: postgres
    chart: postgres-0.1.0
    release: registry
    heritage: Tiller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        release: registry
    spec:
      containers:
      - name: postgres
        image: "postgres:9.6.7-alpine"
        imagePullPolicy: IfNotPresent
        ports:
        - name: postgres-port
          containerPort: 5432
          protocol: TCP
        env:
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        - name: POSTGRES_DB
          value: "portus"
        - name: POSTGRES_PASSWORD_FILE
          value: "/run/secrets/postgres-password"
        - name: POSTGRES_USER
          value: "company"
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "$(POSTGRES_USER)", "-d", "$(POSTGRES_DB)"]
        volumeMounts:
        - name: postgres-volume
          mountPath: "/var/lib/postgresql/data"
      volumes:
      - name: postgres-volume
        persistentVolumeClaim:
          claimName: registry-postgres-pvc
---
# Source: registry/charts/registry/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: registry-registry
  namespace: default
  labels:
    app: registry
    chart: registry-0.1.0
    release: registry
    heritage: Tiller
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
      release: registry
  template:
    metadata:
      labels:
        app: registry
        release: registry
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: registry
        image: "registry:2.6.2"
        imagePullPolicy: IfNotPresent
        ports:
        - name: registry-port
          containerPort: 5000
          protocol: TCP
        - name: debug-port
          containerPort: 5001
          protocol: TCP
        env:
        - name: REGISTRY_AUTH_TOKEN_REALM
          value: "registry-nginx.default.svc.cluster.local:$(REGISTRY_NGINX_SERVICE_PORT)/v2/token"
        - name: REGISTRY_AUTH_TOKEN_SERVICE
          value: "registry-registry.default.svc.cluster.local:$(REGISTRY_REGISTRY_SERVICE_PORT)"
        - name: REGISTRY_AUTH_TOKEN_ISSUER
          value: "registry-portus"
        - name: REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE
          value: "/certificates/portus.crt"
        - name: REGISTRY_NOTIFICATIONS_ENDPOINTS
          value: >
            - name: nginx
              url: "registry-nginx.default.svc.cluster.local:$(REGISTRY_NGINX_SERVICE_PORT)/v2/webhooks/events"
              timeout: 2000ms
              threshold: 5
              backoff: 1s
        - name: REGISTRY_AUTH
          value: "token"
        volumeMounts:
        - name: config
          mountPath: "/etc/docker/registry/config.yml"
          subPath: "config.yml"
        - name: tls
          mountPath: "/certificates/portus.crt"
          subPath: "portus.crt"
        resources:
          limits:
            cpu: 1500m
            memory: 2Gi
          requests:
            cpu: 750m
            memory: 750Mi
      volumes:
      - name: config
        configMap:
          name: registry-registry-config
      - name: tls
        secret:
          secretName: "tls-registry-portus-cert"

```

**Portus version**: 2.4.0-dev@46ae80aeed17075974988de5a88a75fd9d4ebb53
