### ISSUE TITLE
Docker secrets support.

### ISSUE THREAD

**Issue by Nols1000** [SUSE/Portus#1700]
### Description

I recently wanted to update our infrastructure and looked into [Manage sensitive data with Docker secrets](https://docs.docker.com/engine/swarm/secrets/). I couldn't find any documentation on this subject for Portus so I assume it is not supported yet. Then I found this pull-request openSUSE/docker-containers#74 and I dont get why this isn't merged yet. It would be nice if you could help me with information about how to use Docker secrets with Portus or with an explaination why it's not supported yet.

**Comment by Vad1mo** [comment]
You can use  secrets right now with Portus. All You need are a few lines in your compose. 

Example, for config.yml same goes for other files. The PR openSUSE/docker-containers#74 simplifies it a bit.  IMHO its not the right approach.

```
version: "3.1"
services:
  redis:
    image: portus
    secrets:
      - source: config
        target: app/config/config.yml
secrets:
  config:
    file: ./local/location/config.yml
```
