### ISSUE TITLE
How to change the default port of registry?

### ISSUE THREAD

**Issue by kanlidy** [SUSE/Portus#1713]
### Description

443, 5000, 3000 is already taken by our server's another service. So, we need to choose another port to replace the default.

We can login in width ourdoman.com:26005 with username and passwd, but can't push our images to registry with error:

```
root@ubuntu:~# docker login ourdoman.com:26005/
Username: username
Password:
Login Succeeded

root@ubuntu:~# docker push ourdoman.com:26005/username/nginx
The push refers to repository [ourdoman.com:26005/username/nginx]
e89b70d28795: Preparing
832a3ae4ac84: Preparing
014cf8bfcb2d: Preparing
denied: requested access to the resource is denied
```

Check out the `CONTRIBUTING.md` file for some considerations before submitting a
new issue.

### Steps to reproduce

1. Change the default 5000 port of registry in docker-compose.yml
2. Upload my certs into example files.
3. modify docker-compse.yml
4. run docker-compose up -d

### Deployment information

Change the docker-compose.yml file with these places:
```
1. portus: 
    - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}:26443
    ports:
      - 26003:3000
2. background:
    - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}:26443
3. registry:
     REGISTRY_AUTH_TOKEN_REALM: https://${MACHINE_FQDN}:26443/v2/token
     REGISTRY_AUTH_TOKEN_SERVICE: ${MACHINE_FQDN}:26443
     REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}:26443
     
     url: https://${MACHINE_FQDN}:26443/v2/webhooks/events

    ports:
      - 26005:5000
      - 26006:5001 # required to access debug service
4. nginx:
    ports:
      - 26443:443
```

.env file:
```
MACHINE_FQDN=xxx.xxx.com
```

docker-compose.yml
```
version: "2"

services:
  portus:
    image: opensuse/portus:head
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}:26443

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      # SSL
      - PORTUS_PUMA_TLS_KEY=/certificates/portus.key
      - PORTUS_PUMA_TLS_CERT=/certificates/portus.crt

      # NGinx is serving the assets instead of Puma. If you want to change this,
      # uncomment this line.
      #- RAILS_SERVE_STATIC_FILES='true'
    ports:
      - 26003:3000
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro
      - static:/srv/Portus/public

  background:
    image: opensuse/portus:head
    depends_on:
      - portus
      - db
    environment:
      # Theoretically not needed, but cconfig's been buggy on this...
      - CCONFIG_PREFIX=PORTUS
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}:26443

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      - PORTUS_BACKGROUND=true
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro

  db:
    image: library/mariadb:10.0.23
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      - MYSQL_DATABASE=portus_production

      # Again, the password shouldn't be handled like this.
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - /var/lib/portus/mariadb:/var/lib/mysql

  registry:
    image: library/registry:2.6
    command: ["/bin/sh", "/etc/docker/registry/init"]
    environment:
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: https://${MACHINE_FQDN}:26443/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: ${MACHINE_FQDN}:26443
      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}:26443
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /secrets/portus.crt

      # SSL
      REGISTRY_HTTP_TLS_CERTIFICATE: /secrets/portus.crt
      REGISTRY_HTTP_TLS_KEY: /secrets/portus.key

      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://${MACHINE_FQDN}:26443/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
      - /var/lib/portus/registry:/var/lib/registry
      - ./secrets:/secrets:ro
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
      - ./registry/init:/etc/docker/registry/init:ro
    ports:
      - 26005:5000
      - 26006:5001 # required to access debug service
    links:
      - portus:portus

  nginx:
    image: library/nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./secrets:/secrets:ro
      - static:/srv/Portus/public:ro
    ports:
    # - 26008:80
      - 26443:443
    links:
      - registry:registry
      - portus:portus

volumes:
  static:
    driver: local

```

**Portus version**: with commit if possible. You can get this info too with the
above commands.

Thanks!!!
