### ISSUE TITLE
"Security" tag urls do not respect RAILS_RELATIVE_URL_ROOT

### ISSUE THREAD

**Issue by embik** [SUSE/Portus#1718]
### Description

Hey there. Thank you very much for creating Portus.

We're running Portus and a Docker Registry over the same DNS name. Portus is configured in a subdirectory. The vulnerability links for tags do not respect the application's `RAILS_RELATIVE_URL_ROOT`. These links are only present in the repository view afaik.

For example, the url linked for a tag is `https://fqdn/tags/5` although Portus is reachable as `https://fqdn/subdir/`. Therefore, opening `https://fqdn/tags/5` fails (the CVE list is available at `https://fqdn/subdir/tags/5` though). At the moment I'm redirecting those requests at the load balancer to work around this issue.

### Steps to reproduce

1. Deploy portus v2.3 from 2.3 docker tag
2. Configure `RAILS_RELATIVE_URL_ROOT`
3. Configure Clair as security scanner
4. Open a repository overview
5. Click "vulnerabilities"

### Deployment information

Portus is deployed as a Kubernetes Deployment (based on the available [Helm charts](https://github.com/kubic-project/caasp-services/tree/master/contrib/helm-charts/portus)). I'll add relevant configuration below.

**Configuration**:

Deployment:
```yml
[...]
containers:
        - name: portus
          image: opensuse/portus:2.3
[...]
          env:
            - name: RAILS_RELATIVE_URL_ROOT
               value: "/subdir/"
[...]
```

ConfigMap (`config-local.yml`):
```yml
[...]
security:
  clair:
    server: http://clair.fqdn:6060
    health_port: 6061
[...]
```

**Portus version**: `Portus version: 2.3.0@6bf45381824ef4edf2dc572374e9b13080817a9a`
