### ISSUE TITLE
Portus hangs after some time running in Swarm

### ISSUE THREAD

**Issue by dtitov** [SUSE/Portus#1725]
### Description

Hi, I've got an issue with Portus: right after deployment it works like a charm, but in a while (undefined term, sorry) it stops responding, even though for each browser request I get an entry in logs: `
Started GET "/" for 10.255.0.2 at 2018-03-13 09:28:57 +0000`. Not only UI is unaccessible, but also registry (as authentication stops working as well). 

**UPDATE**: right now I noticed that after some minutes (~5) of spinning browser loaded Portus successfully. And now it works fast again. So looks like it drops to some kind of "hibernation" and then needs a while to "wake up".

### Steps to reproduce

1. I just keep the system running for a while.
2. Then I try to access front page.
3. Browser doesn't load it, it has eternal loading spinner and that's it.

- **Expected behavior**: I expect Portus to work regardless of its uptime.
- **Actual behavior**: But Portus works only some few time after restart.

Here are the logs: https://gist.github.com/dtitov/6cdf6fc3a6cafcb362b8d5a413822d4e
The last three lines are attempts to load Portus when it didn't response:
```
Started GET "/" for 10.255.0.2 at 2018-03-13 09:28:57 +0000,
Started GET "/" for 10.255.0.2 at 2018-03-13 09:29:36 +0000,
Started GET "/" for 10.255.0.2 at 2018-03-13 09:31:12 +0000,
```

### Deployment information

**Deployment method**: I deployed it as a Stack to the Swarm cluster.

**Configuration**:
Config file:

```yml
version: '3.3'

services:
  database:
    restart: always
    image: mariadb
    deploy:
      placement:
        constraints:
          - node.labels.database == true
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - db:/var/lib/mysql

  adminer:
    restart: always
    image: adminer
    deploy:
      placement:
        constraints:
          - node.labels.database == true
    depends_on:
      - database
      
  registry:
    restart: always
    image: registry:2
    deploy:
      placement:
        constraints:
          - node.labels.registry == true
    ports:
      - 80:5000
    environment:
      # SSL
      REGISTRY_HTTP_TLS_CERTIFICATE: /run/secrets/cert.crt
      REGISTRY_HTTP_TLS_KEY: /run/secrets/privkey.key
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: https://${MACHINE_FQDN}/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /run/secrets/cert.crt
      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://${MACHINE_FQDN}/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    secrets:
      - cert.crt
      - privkey.key
    volumes:
      - /registry:/var/lib/registry

  portus:
    restart: always
    image: opensuse/portus:2.3
    deploy:
      placement:
        constraints:
          - node.labels.portus == true
    ports:
      - 443:3000
    environment:
      # DB
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}
      - PORTUS_DB_HOST=database
      - PORTUS_DB_DATABASE=${MYSQL_DATABASE}
      - PORTUS_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PORTUS_DB_POOL=5
      # Secrets
      - PORTUS_SECRET_KEY_BASE
      - PORTUS_KEY_PATH=/run/secrets/privkey.key
      - PORTUS_PASSWORD
      # SSL
      - PORTUS_PUMA_TLS_KEY=/run/secrets/privkey.key
      - PORTUS_PUMA_TLS_CERT=/run/secrets/cert.crt
      # Other
      - RAILS_SERVE_STATIC_FILES='true'
    secrets:
      - cert.crt
      - privkey.key
    depends_on:
      - database
      - registry
    
volumes:
  db:
  
secrets:
    cert.crt:
        external: true
    privkey.key:
        external: true
```

**Portus version**: opensuse/portus:2.3 (2.3.0@6bf45381824ef4edf2dc572374e9b13080817a9a).
