### ISSUE TITLE
Cannot obtain authorization token

### ISSUE THREAD

**Issue by lightnet328** [SUSE/Portus#1730]
### Description

portus-background keeps sending the following logs.
```
[Initialization] Running: 'Registry events', 'Registry synchronization'
Exception: Cannot obtain authorization token: #<Net::HTTPBadRequest:0x0000000004c45a78>
Exception: Cannot obtain authorization token: #<Net::HTTPBadRequest:0x0000000004bb9f78>
Exception: Cannot obtain authorization token: #<Net::HTTPBadRequest:0x0000000004b59bf0>
Exception: Cannot obtain authorization token: #<Net::HTTPBadRequest:0x0000000004a9b7b8>
Exception: Cannot obtain authorization token: #<Net::HTTPBadRequest:0x00000000049b7f40>
```

portus-registry logs:
```
time="2018-03-15T10:39:43Z" level=warning msg="error authorizing context: silly authentication challenge: silly.challenge{realm:\"http://registry.example.com:443/v2/token\", service:\"portus-portus-registry:5000\", scope:\"\"}" go.version=go1.6.4 http.request.host=registry.example.com http.request.id=15a90ff2-a8a6-434e-817f-ca78f309d53f http.request.method=GET http.request.remoteaddr=202.13.169.56 http.request.uri="/v2/" http.request.useragent=Ruby instance.id=885493d0-f5b6-4984-914b-282c3b0fda22 version=v2.5.2
10.233.119.45 - - [15/Mar/2018:10:39:43 +0000] "GET /v2/ HTTP/1.0" 401 87 "" "Ruby"
time="2018-03-15T10:39:45Z" level=warning msg="error authorizing context: silly authentication challenge: silly.challenge{realm:\"http://registry.example.com:443/v2/token\", service:\"portus-portus-registry:5000\", scope:\"\"}" go.version=go1.6.4 http.request.host=registry.example.com http.request.id=1087401e-b2f2-4420-b634-ecc085836c88 http.request.method=GET http.request.remoteaddr=202.13.169.56 http.request.uri="/v2/" http.request.useragent=Ruby instance.id=885493d0-f5b6-4984-914b-282c3b0fda22 version=v2.5.2
10.233.119.45 - - [15/Mar/2018:10:39:45 +0000] "GET /v2/ HTTP/1.0" 401 87 "" "Ruby"
time="2018-03-15T10:39:45Z" level=warning msg="error authorizing context: silly authentication challenge: silly.challenge{realm:\"http://registry.example.com:443/v2/token\", service:\"portus-portus-registry:5000\", scope:\"\"}" go.version=go1.6.4 http.request.host=registry.example.com http.request.id=d6d226c6-f765-4178-b2d3-fbdc57b42fc5 http.request.method=GET http.request.remoteaddr=202.13.169.56 http.request.uri="/v2/" http.request.useragent=Ruby instance.id=885493d0-f5b6-4984-914b-282c3b0fda22 version=v2.5.2
10.233.119.45 - - [15/Mar/2018:10:39:45 +0000] "GET /v2/ HTTP/1.0" 401 87 "" "Ruby"
```

### Steps to reproduce

1. I launched Portus with the following commands and settings

`$ helm install -n portus --namespace example -f ./portus.yml .`

```yml
nginx:
  host: registry.example.com
  # Added
  port: "443"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    tls:
      enabled: true
      secretName: example-tls
```

2. Background process cannot obtain authorization token

**Comment by adnoh** [comment]
the problem is the configuration of your registry (silly authentication vs. token), not from portus. can u share how you're running the registry? whats inside of the portus.yml?

**Comment by lightnet328** [comment]
Thanks for your response.
registry has deployed by helm too.
Then the environment variable had the following values.

```
REGISTRY_AUTH_SILLY_REALM: http://registry.example.com:443/v2/token
REGISTRY_AUTH_SILLY_SERVICE: portus-portus-registry:5000
```

portus does not support the silly authentication?

portus.yml:
```yml
nginx:
  host: registry.example.com
  # Added
  port: "443"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    tls:
      enabled: true
      secretName: example-tls
```
