### ISSUE TITLE
Improve the documentation of assets management

### ISSUE THREAD

**Issue by superstator** [SUSE/Portus#1734]
### Description

When running Portus from a docker image, I get an "Error compiling CSS asset" error.

### Steps to reproduce

1. Added the opensuse/portus:2.3 image to our kubernetes cluster
2. Tried to open https://portus.domain.io
3. Redirected to https://portus.domain.io/users/sign_up as expected
4. Css error appears

Error message comes from a CSS asset:

```
body:before {
            font-weight: bold;
            content: "\000a Sass::SyntaxError: File to import not found or unreadable: font-awesome.\000a Load paths:\000a   \002f srv\002f Portus\002f app\002f assets\002f images\000a   \002f srv\002f Portus\002f app\002f assets\002f javascripts\000a   \002f srv\002f Portus\002f app\002f assets\002f stylesheets\000a   \002f srv\002f Portus\002f vendor\002f bundle\002f ruby\002f 2.5.0\002f gems\002f font-awesome-rails-4.7.0.3\002f app\002f assets\002f fonts\000a   \002f srv\002f Portus\002f vendor\002f bundle\002f ruby\002f 2.5.0\002f gems\002f font-awesome-rails-4.7.0.3\002f app\002f assets\002f stylesheets";
          }

```

In the container logs I see:
```
Database ready
[42] Puma starting in cluster mode...
[42] * Version 3.10.0 (ruby 2.5.0-p0), codename: Russell's Teapot
[42] * Min threads: 1, max threads: 4
[42] * Environment: production
[42] * Process workers: 2
[42] * Preloading application
[Mailer config] Host:     portus.domain.io
[Mailer config] Protocol: https://
[42] * Listening on tcp://0.0.0.0:3000
[42] Use Ctrl-C to stop
[42] - Worker 0 (pid: 45) booted, phase: 0
[42] - Worker 1 (pid: 47) booted, phase: 0
Started GET "/" for 10.244.5.33 at 2018-03-15 20:27:12 +0000
Processing by Auth::SessionsController#new as HTML
Redirected to http://portus:3000/users/sign_up
Completed 302 Found in 42ms (ActiveRecord: 6.3ms)
Started GET "/users/sign_up" for 10.244.5.33 at 2018-03-15 20:27:12 +0000
Processing by Auth::RegistrationsController#new as HTML
  Rendered shared/_notification.html.slim (8.5ms)
  Rendered shared/_notification.html.slim (0.1ms)
  Rendered shared/_notifications.html.slim (16.5ms)
  Rendered devise/registrations/new.html.slim within layouts/authentication (39.5ms)
Completed 200 OK in 140ms (Views: 66.7ms | ActiveRecord: 5.5ms)
Started GET "/assets/application-20f67d7832e7f80743d80b935441f204ab9a5cfdbfbc155027f330d6397aed28.css" for 10.244.5.33 at 2018-03-15 20:27:12 +0000
Started GET "/assets/unmanaged-6cf4a1295ff6946a5e84e7ccee9d29838b7d173552a385e3f59eb5215abfbe73.js" for 10.244.5.33 at 2018-03-15 20:27:12 +0000
Started GET "/assets/webpack/application-76abd0e6b2530af98dd1.js" for 10.244.5.33 at 2018-03-15 20:27:12 +0000

ActionController::RoutingError (No route matches [GET] "/assets/unmanaged-6cf4a1295ff6946a5e84e7ccee9d29838b7d173552a385e3f59eb5215abfbe73.js"):
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:165:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'


Processing by ErrorsController#show as */*
  Parameters: {"status"=>"404"}

ActionController::RoutingError (No route matches [GET] "/assets/webpack/application-76abd0e6b2530af98dd1.js"):
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:165:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'


Processing by ErrorsController#show as */*
  Parameters: {"status"=>"404"}
  Rendered errors/404.html.slim within layouts/errors (2.1ms)
  Rendered errors/404.html.slim within layouts/errors (1.7ms)
  Rendered errors/_status_title.html.slim (2.1ms)
Completed 404 Not Found in 42ms (Views: 32.8ms | ActiveRecord: 0.0ms)
  Rendered errors/_status_title.html.slim (3.5ms)
Completed 404 Not Found in 43ms (Views: 41.4ms | ActiveRecord: 0.0ms)
Started GET "/assets/layout/portus-logo-login-page-c7ac1df0bc28985c89e8bb9f7b555013dd72f2da762c088af26717a170ff46f3.png" for 10.244.5.33 at 2018-03-15 20:27:13 +0000
Started GET "/favicon/favicon-32x32.png" for 10.244.5.33 at 2018-03-15 20:27:13 +0000

ActionController::RoutingError (No route matches [GET] "/favicon/favicon-32x32.png"):
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:165:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'


Processing by ErrorsController#show as HTML
  Parameters: {"status"=>"404"}
  Rendered errors/404.html.slim within layouts/errors (2.6ms)
  Rendered errors/_status_title.html.slim (2.5ms)
Completed 404 Not Found in 8ms (Views: 7.0ms | ActiveRecord: 0.0ms)
Started GET "/favicon/favicon-16x16.png" for 10.244.5.33 at 2018-03-15 20:27:14 +0000

ActionController::RoutingError (No route matches [GET] "/favicon/favicon-16x16.png"):
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:165:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'


Processing by ErrorsController#show as HTML
  Parameters: {"status"=>"404"}
  Rendered errors/404.html.slim within layouts/errors (13.3ms)
  Rendered errors/_status_title.html.slim (2.5ms)
Completed 404 Not Found in 37ms (Views: 36.4ms | ActiveRecord: 0.0ms)
Started GET "/favicon/favicon-96x96.png" for 10.244.5.33 at 2018-03-15 20:27:14 +0000

ActionController::RoutingError (No route matches [GET] "/favicon/favicon-96x96.png"):
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:165:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'


Processing by ErrorsController#show as HTML
  Parameters: {"status"=>"404"}
  Rendered errors/404.html.slim within layouts/errors (0.0ms)
  Rendered errors/_status_title.html.slim (0.0ms)
Completed 404 Not Found in 2ms (Views: 1.2ms | ActiveRecord: 0.0ms)
Started GET "/favicon/android-chrome-192x192.png" for 10.244.5.33 at 2018-03-15 20:27:14 +0000

ActionController::RoutingError (No route matches [GET] "/favicon/android-chrome-192x192.png"):
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:165:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'


Processing by ErrorsController#show as HTML
  Parameters: {"status"=>"404"}
  Rendered errors/404.html.slim within layouts/errors (0.0ms)
  Rendered errors/_status_title.html.slim (0.0ms)
Completed 404 Not Found in 2ms (Views: 1.2ms | ActiveRecord: 0.0ms)
Started GET "/favicon/favicon.ico" for 10.244.5.33 at 2018-03-15 20:27:14 +0000

ActionController::RoutingError (No route matches [GET] "/favicon/favicon.ico"):
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:165:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'


Processing by ErrorsController#show as HTML
  Parameters: {"status"=>"404"}
  Rendered errors/404.html.slim within layouts/errors (0.0ms)
  Rendered errors/_status_title.html.slim (0.0ms)
Completed 404 Not Found in 1ms (Views: 1.0ms | ActiveRecord: 0.0ms)
Started GET "/favicon.ico" for 10.244.5.33 at 2018-03-15 20:27:20 +0000

ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:165:in `call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'
  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'


Processing by ErrorsController#show as HTML
  Parameters: {"status"=>"404"}
  Rendered errors/404.html.slim within layouts/errors (0.0ms)
  Rendered errors/_status_title.html.slim (0.1ms)
Completed 404 Not Found in 3ms (Views: 1.6ms | ActiveRecord: 0.0ms)
Started GET "/assets/application-20f67d7832e7f80743d80b935441f204ab9a5cfdbfbc155027f330d6397aed28.css" for 10.244.5.33 at 2018-03-15 20:27:30 +0000
```

### Deployment information

**Configuration**:

k8s yaml:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: portus-config
data:
  config.yml: |
    email:
      from: "noreply@domain.com"
      name: "Portus"
      reply_to: "noreply@domain"
    delete:
      enabled: true
    first_user_admin:
      enabled: true
    machine_fqdn:
      value: "portus.domain.io"
    signup:
      enabled: true
    check_ssl_usage:
      enabled: false
    display_name:
      enabled: false
    user_permission:
      change_visibility:
        enabled: true
      create_team:
        enabled: true
      manage_team:
        enabled: true
      create_namespace:
        enabled: true
      manage_namespace:
        enabled: true
      push_images:
        enabled: true
    background:
      registry:
        enabled: true
      sync:
        enabled: true
        strategy: initial

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: portus
  labels:
    app: portus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portus
  template:
    metadata:
      labels:
        app: portus
    spec:
      containers:
      - name: portus
        image: opensuse/portus:2.3
        ports:
        - containerPort: 80
        - containerPort: 3000
        env:
        - name: PORTUS_LOCAL_CONFIG_PATH
          value: /etc/docker/portus/config.yml
        - name: PORTUS_SECRET_KEY_BASE
          value: <secret>
        - name: PORTUS_KEY_PATH
          value: /etc/ssl/key
        - name: PORTUS_PASSWORD
          value: <password>
        - name: PORTUS_DB_HOST
          value: mariadb
        - name: PORTUS_DB_USERNAME
          value: root
        - name: PORTUS_DB_PASSWORD
          value: <password>
        - name: PORTUS_DB_DATABASE
          value: portus
        volumeMounts:
        - name: portus-config
          mountPath: /etc/docker/portus/config.yml
          subPath: config.yml
        - name: ssl
          mountPath: /etc/ssl
          readOnly: true
      volumes:
        - name: portus-config
          configMap:
            name: portus-config
        - name: ssl
          secret:
            secretName: 2018.domain.io.cert            
```

portusctl info:

```
bash-4.3# portusctl exec rake portus:info
You have not changed the FQDN configuration. Are you sure about this?
[Mailer config] Host:     portus.test.lan
[Mailer config] Protocol: https://
Evaluated configuration:
---
email:
  from: noreply@domain.com
  name: Portus
  reply_to: noreply@domain
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    user_name: username@example.com
    password: "****"
    domain: example.com
gravatar:
  enabled: true
delete:
  enabled: true
ldap:
  enabled: false
  hostname: ldap_hostname
  port: 389
  method: plain
  base: ''
  filter: ''
  uid: uid
  authentication:
    enabled: false
    bind_dn: ''
    password: "****"
  guess_email:
    enabled: false
    attr: ''
oauth:
  google_oauth2:
    enabled: false
    id: ''
    secret: ''
    domain: ''
    options:
      hd: ''
  open_id:
    enabled: false
    identifier: ''
    domain: ''
  github:
    enabled: false
    client_id: ''
    client_secret: ''
    organization: ''
    team: ''
    domain: ''
  gitlab:
    enabled: false
    application_id: ''
    secret: ''
    group: ''
    domain: ''
    server: ''
  bitbucket:
    enabled: false
    key: ''
    secret: ''
    domain: ''
    options:
      team: ''
first_user_admin:
  enabled: true
signup:
  enabled: true
check_ssl_usage:
  enabled: false
registry:
  jwt_expiration_time:
    value: 5
  catalog_page:
    value: 100
  timeout:
    value: 2
  read_timeout:
    value: 120
machine_fqdn:
  value: portus.domain.io
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: true
  create_team:
    enabled: true
  manage_team:
    enabled: true
  create_namespace:
    enabled: true
  manage_namespace:
    enabled: true
security:
  clair:
    server: ''
    health_port: 6061
  zypper:
    server: ''
  dummy:
    server: ''
anonymous_browsing:
  enabled: true
background:
  registry:
    enabled: true
  sync:
    enabled: true
    strategy: initial

Portus version: 2.3.0@6bf45381824ef4edf2dc572374e9b13080817a9a
```
