### ISSUE TITLE
Docker push rejected because of "insufficient scope"

### ISSUE THREAD

**Issue by apophis90** [SUSE/Portus#1736]
### Description

When deploying Portus in secure mode with Docker Compose, I'm unable to push images to my private Docker Registry due to a permissions error. 

### Steps to reproduce

1. First, I deployed Portus using your `examples/docker-compose.yml` file as a basis. The only thing I changed is that I added the Clair and Postgres services. My `docker-compose.yml` looks as follows:

1. Deploy Portus and peripherals with docker-compose.yml and configurations posted below.
2. Make sure you can connect to your LDAP server.
3. Log in to Portus and add the Docker Registry with SSL enabled.
4. From CLI: `docker login localhost:5000` with your LDAP credentials (should succeed).
5. Try to push an image tagged something like _localhost:5000/hello_. This should fail:

```
$ docker login localhost:5000     
Username: Patrick.Kleindienst    
Password:*******
Login Succeeded

$ docker push localhost:5000/hello                            
The push refers to repository [localhost:5000/hello]
f999ae22f308: Preparing 
denied: requested access to the resource is denied
```

```
$ docker-compose logs registry

registry_1    | time="2018-03-20T11:08:18Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.7.6 http.request.host="localhost:5000" http.request.id=96dc5e14-e987-4fa1-ac4a-9d511dcc382f http.request.method=POST http.request.remoteaddr="172.21.0.1:37770" http.request.uri="/v2/hello/blobs/uploads/" http.request.useragent="docker/17.12.1-ce go/go1.9.4 git-commit/7390fc6 kernel/4.13.0-37-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.12.1-ce \\(linux\\))" instance.id=25591423-ec9c-428a-8c6d-588d0f0357f0 vars.name=hello version=v2.6.2 
registry_1    | 172.21.0.1 - - [20/Mar/2018:11:08:18 +0000] "POST /v2/hello/blobs/uploads/ HTTP/1.1" 401 212 "" "docker/17.12.1-ce go/go1.9.4 git-commit/7390fc6 kernel/4.13.0-37-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.12.1-ce \\(linux\\))"
registry_1    | time="2018-03-20T11:08:23Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.7.6 http.request.host="registry:5000" http.request.id=a7312300-d5f4-45c9-b86f-dc1dacda5689 http.request.method=GET http.request.remoteaddr="172.21.0.6:60494" http.request.uri="/v2/_catalog?n=100" http.request.useragent=Ruby instance.id=25591423-ec9c-428a-8c6d-588d0f0357f0 version=v2.6.2 
registry_1    | 172.21.0.6 - - [20/Mar/2018:11:08:23 +0000] "GET /v2/_catalog?n=100 HTTP/1.1" 401 145 "" "Ruby
```

Portus produces the following logs:

```
$ docker-compose logs portus

Started GET "/v2/token?account=Patrick.Kleindienst&client_id=docker&offline_token=true&service=172.21.0.1%3A5000" for 172.21.0.8 at 2018-03-20 10:36:21 +0000
portus_1      | Processing by Api::V2::TokensController#show as JSON
portus_1      |   Parameters: {"account"=>"Patrick.Kleindienst", "client_id"=>"docker", "offline_token"=>"true", "service"=>"172.21.0.1:5000"}
portus_1      | Completed 200 OK in 507ms (Views: 0.2ms | ActiveRecord: 8.9ms)
portus_1      | Started GET "/v2/token?account=Patrick.Kleindienst&scope=repository%3Apatrick.kleindienst%2Fhello%3Apush%2Cpull&service=172.21.0.1%3A5000" for 172.21.0.8 at 2018-03-20 10:36:26 +0000
portus_1      | Processing by Api::V2::TokensController#show as JSON
portus_1      |   Parameters: {"account"=>"Patrick.Kleindienst", "scope"=>"repository:patrick.kleindienst/hello:push,pull", "service"=>"172.21.0.1:5000"}
portus_1      | Completed 200 OK in 493ms (Views: 0.1ms | ActiveRecord: 1.7ms)
```

- **Expected behavior**: 
I'd expect the Docker push operation to work.

- **Actual behavior**: 
Docker push operation fails, the registry produces the logs you can see above. Seems like Portus does not set the _scope_ parameter to what the Registry expects it to be.

### Deployment information

**Deployment method**: 

I deployed Portus via Docker Compose, basically using the docker-compose file from `examples/docker-compose.yml`. I only added the Clair and Postgres services according to `examples/docker-compose.clair.yml` (along with config files you provide).

**Configuration**:

__docker-compose.yml:__

```yml
version: "2"

services:
  portus:
    image: opensuse/portus:2.3
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}

      # DB
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      # SSL
      - PORTUS_PUMA_TLS_KEY=/certificates/portus.key
      - PORTUS_PUMA_TLS_CERT=/certificates/portus.crt 

      # Clair
      - PORTUS_SECURITY_CLAIR_SERVER=http://clair:6060
    ports:
      - 3000:3000
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro
      - ./portus-config/config-local.yml:/srv/Portus/config/config-local.yml
      - static:/srv/Portus/public

  background:
    image:opensuse/portus:2.3
    depends_on:
      - portus
      - db
    environment:
      - CCONFIG_PREFIX=PORTUS
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}

      # DB
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      # Clair
      - PORTUS_SECURITY_CLAIR_SERVER=http://clair:6060

      - PORTUS_BACKGROUND=true
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro
      - ./portus-config/config-local.yml:/srv/Portus/config/config-local.yml

  db:
    image: library/mariadb:10.0.23
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      - MYSQL_DATABASE=portus_production
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./mariadb:/var/lib/mysql

  registry:
    image: library/registry:2.6
    environment:
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: https://${MACHINE_FQDN}/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /secrets/portus.crt

      # SSL
      REGISTRY_HTTP_TLS_CERTIFICATE: /secrets/portus.crt
      REGISTRY_HTTP_TLS_KEY: /secrets/portus.key

      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://${MACHINE_FQDN}/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
      - ./registry:/var/lib/registry
      - ./secrets:/secrets:ro
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
      - ./registry/init:/etc/docker/registry/init:ro
    links: 
      - portus:portus
    ports:
      - 5000:5000
      - 5001:5001 # required to access debug service
    command: ["/bin/sh", "/etc/docker/registry/init"]

  nginx:
    image: library/nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./secrets:/secrets:ro
      - static:/srv/Portus/public:ro
    links:
      - registry:registry
      - portus:portus
    ports:
      - 80:80
      - 443:443

  clair: 
    # We use a custom image derived from the original Clair image to import our certificates on startup.
    image: privateRegistry/clair
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "6060-6061:6060-6061"
    links:
      - postgres
    volumes:
      - ./clair/tmp/:/tmp
      - ./clair/clair.yml:/clair.yml
      - ./secrets:/secrets:ro
    command: ["-config", "/clair.yml"]    

  postgres:
    image: library/postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: portus
  
volumes:
  static:
    driver: local
```

__portus-config/config-local.yml:__

```yml
ldap:
  enabled: true
  hostname: "our-ldap.com"
  port: 389
  method: "plain"
  base: "o=we.com"
  filter: "ou=people"
  uid: "mail"

  authentication:
    enabled: true
    bind_dn: ""
    password: ""
```

Checking if Portus applied the config as expected:

```
$ docker-compose exec portus sh
sh-4.3# portusctl exec rake portus:info
[Mailer config] Host:     portus.test.lan
[Mailer config] Protocol: https://
Evaluated configuration:
---
email:
  from: portus@example.com
  name: Portus
  reply_to: no-reply@example.com
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    user_name: username@example.com
    password: "****"
    domain: example.com
gravatar:
  enabled: true
delete:
  enabled: false
ldap:
  enabled: true
  hostname: our-ldap.com
  port: 389
  method: plain
  base: o=ibm.com
  filter: ou=we.com
  uid: mail
  authentication:
    enabled: true
    bind_dn: ''
    password: "****"
  guess_email:
    enabled: false
    attr: ''
oauth:
  google_oauth2:
    enabled: false
    id: ''
    secret: ''
    domain: ''
    options:
      hd: ''
  open_id:
    enabled: false
    identifier: ''
    domain: ''
  github:
    enabled: false
    client_id: ''
    client_secret: ''
    organization: ''
    team: ''
    domain: ''
  gitlab:
    enabled: false
    application_id: ''
    secret: ''
    group: ''
    domain: ''
    server: ''
  bitbucket:
    enabled: false
    key: ''
    secret: ''
    domain: ''
    options:
      team: ''
first_user_admin:
  enabled: false
signup:
  enabled: true
check_ssl_usage:
  enabled: true
registry:
  jwt_expiration_time:
    value: 5
  catalog_page:
    value: 100
  timeout:
    value: 2
  read_timeout:
    value: 120
machine_fqdn:
  value: 172.21.0.1
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: true
  create_team:
    enabled: true
  manage_team:
    enabled: true
  create_namespace:
    enabled: true
  manage_namespace:
    enabled: true
security:
  clair:
    server: http://clair:6060
    health_port: 6061
  zypper:
    server: ''
  dummy:
    server: ''
anonymous_browsing:
  enabled: true
background:
  registry:
    enabled: true
  sync:
    enabled: true
    strategy: initial
Portus version: 2.3.0@6bf45381824ef4edf2dc572374e9b13080817a9a
```

__registry/config.yml:__

```yml
version: 0.1
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: 0.0.0.0:5000
  debug:
    addr: 0.0.0.0:5001
```

I skip the Clair and Nginx config here since I guess this should not be related to the problem and besides does not differ from what you provide in the `examples` folder.

Cheers,
Patrick

**Comment by adnoh** [comment]
the registry name (or the external hostname) configured inside of portus must match your REGISTRY_AUTH_TOKEN_SERVICE value

**Comment by apophis90** [comment]
Yep, that works. Thx!

**Comment by Jean-Baptiste-Lasselle** [comment]
> the registry name (or the external hostname) configured inside of portus webinterface must match your REGISTRY_AUTH_TOKEN_SERVICE value

Thank yyou so much ! (see https://github.com/SUSE/Portus/issues/2264#issuecomment-565750459 )

**Comment by ravensorb** [comment]
It seems like I am hitting the same issue and I am pretty much 100% sure things match :)  Is there something else that needs to match too?

Screenshot of my web interface 
![image](https://user-images.githubusercontent.com/2222472/105104299-fb655280-5a7f-11eb-994d-b6d1466a52fb.png)

env variables for portus
```
PORTUS_ANONYMOUS_BROWSING_ENABLED=true
PORTUS_BACKGROUND_SYNC_ENABLED=false
PORTUS_BACKGROUND_SYNC_STRATEGY=update-delete
PORTUS_CHECK_SSL_USAGE_ENABLED=false
PORTUS_DB_ADAPTER=mysql2
PORTUS_DB_DATABASE=portusdb
PORTUS_DB_HOST=portusdb
PORTUS_DB_PASSWORD=xxxxxxxx
PORTUS_DB_USERNAME=portusdb
PORTUS_DELETE_CONTRIBUTORS=true
PORTUS_DELETE_ENABLED=true
PORTUS_DELETE_GARBAGE_COLLECTOR_ENABLED=true
PORTUS_DELETE_GARBAGE_COLLECTOR_KEEP_LATEST=5
PORTUS_DELETE_GARBAGE_COLLECTOR_OLDER_THAN=30
PORTUS_DELETE_GARBAGE_COLLECTOR_TAG=
PORTUS_DISPLAY_NAME_ENABLED=true
PORTUS_EMAIL_FROM=portus@home.local
PORTUS_EMAIL_NAME=
PORTUS_EMAIL_REPLY_TO=
PORTUS_GRAVATAR_ENABLED=true
PORTUS_HOST_EXTERNAL=portus.home.local
PORTUS_HOST_INTERNAL=portus
PORTUS_KEY_PATH=/certs/key/portus.key
PORTUS_MACHINE_FQDN_VALUE=portus-registry.home.local
PORTUS_PASSWORD=xxxxxxxx
PORTUS_SECRET_KEY_BASE=xxxxxxxx
PORTUS_SMTP_ADDRESS=smtp.home.local
PORTUS_SMTP_AUTHENTICATION=login
PORTUS_SMTP_DOMAIN=home.local
PORTUS_SMTP_ENABLED=false
PORTUS_SMTP_PASSWORD=
PORTUS_SMTP_PORT=25
PORTUS_SMTP_USER_NAME=
RAILS_SERVE_STATIC_FILES=true
```

env variables for registry
```
REGISTRY_AUTH_TOKEN_ISSUER=portus-registry.home.local
REGISTRY_LOG_LEVEL=debug
REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/crt/portus.crt
REGISTRY_AUTH_TOKEN_REALM=http://portus.home.local/v2/token
REGISTRY_NOTIFICATIONS_ENDPOINTS_URL=http://portus:3000/v2/webhooks/events
REGISTRY_LOG_ACCESSLOG_DISABLED=false
REGISTRY_AUTH_TOKEN_SERVICE=portus-registry.home.local
REGISTRY_STORAGE_DELETE_ENABLED=true
REGISTRY_HTTP_SECRET=xxxxxx
REGISTRY_NOTIFICATIONS_ENDPOINTS_NAME=portus
REGISTRY_NOTIFICATIONS_ENDPOINTS_DISABLED=false
```

and here is the config for portus
```
sh-4.4# portusctl exec rake portus:info
[schema] Selected the schema for mysql
[Mailer config] Host:     portus.test.lan
[Mailer config] Protocol: https://
Evaluated configuration:
---
email:
  from: portus@home.local
  name: ''
  reply_to: ''
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    domain: example.com
    ssl_tls: ''
    enable_starttls_auto: false
    openssl_verify_mode: none
    ca_path: ''
    ca_file: ''
    user_name: ''
    password: "****"
    authentication: login
gravatar:
  enabled: true
delete:
  enabled: true
  contributors: true
  garbage_collector:
    enabled: true
    older_than: 30
    keep_latest: 5
    tag: ''
ldap:
  enabled: false
  hostname: ldap_hostname
  port: 389
  timeout: 5
  encryption:
    method: ''
    options:
      ca_file: ''
      ssl_version: TLSv1_2
  base: ''
  admin_base: ''
  group_base: ''
  filter: ''
  uid: uid
  authentication:
    enabled: false
    bind_dn: ''
    password: "****"
  group_sync:
    enabled: true
    default_role: viewer
  guess_email:
    enabled: false
    attr: ''
oauth:
  local_login:
    enabled: true
  google_oauth2:
    enabled: false
    id: ''
    secret: ''
    domain: ''
    options:
      hd: ''
  open_id:
    enabled: false
    identifier: ''
    domain: ''
  openid_connect:
    enabled: false
    issuer: ''
    identifier: ''
    secret: ''
  github:
    enabled: false
    client_id: ''
    client_secret: ''
    organization: ''
    team: ''
    domain: ''
  gitlab:
    enabled: false
    application_id: ''
    secret: ''
    group: ''
    domain: ''
    server: ''
  bitbucket:
    enabled: false
    key: ''
    secret: ''
    domain: ''
    options:
      team: ''
first_user_admin:
  enabled: true
signup:
  enabled: true
check_ssl_usage:
  enabled: false
registry:
  jwt_expiration_time:
    value: 15
  catalog_page:
    value: 100
  timeout:
    value: 2
  read_timeout:
    value: 120
machine_fqdn:
  value: portus-registry.home.local
display_name:
  enabled: true
user_permission:
  change_visibility:
    enabled: true
  create_team:
    enabled: true
  manage_team:
    enabled: true
  create_namespace:
    enabled: true
  manage_namespace:
    enabled: true
  create_webhook:
    enabled: true
  manage_webhook:
    enabled: true
  push_images:
    policy: allow-teams
security:
  clair:
    server: ''
    health_port: 6061
    timeout: 900
  zypper:
    server: ''
  dummy:
    server: ''
anonymous_browsing:
  enabled: true
background:
  registry:
    enabled: true
  sync:
    enabled: false
    strategy: update-delete
pagination:
  per_page: 10
  before_after: 2
```

and here is the log entry
```
portus-registry        | time="2021-01-19T22:53:12.85319284Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.11.2 http.request.host=portus-registry.home.local http.request.id=16e22790-55ee-4adf-b516-2b1a36941ac0 http.request.method=POST http.request.remoteaddr=172.21.0.1 http.request.uri="/v2/testuser/containerimage"/blobs/uploads/" http.request.useragent="docker/20.10.2 go/go1.13.15 git-commit/8891c58 kernel/5.4.0-1036-azure os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.2 \(linux\))" vars.name="testuser/containerimage" 
```
