### ISSUE TITLE
Waiting for mariadb to be ready in 5 seconds

### ISSUE THREAD

**Issue by amou1012** [SUSE/Portus#1788]
I want to setup Portus in my local NB, and I follow the docker-compose file in the github and customize it.
All the containers run well at first , but soon I got some error logs:
   `portus_1      | Waiting for mariadb to be ready in 5 seconds`
   `background_1  | [Database] Not ready yet. Waiting...`

I have no idea where is wrong...
Can anyone help me ?
Thanks a lot !

Here is my docker-compose:
```yml
version: "2"

services:
  portus:
    image: opensuse/portus:head
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=portus.test.com
      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_USERNAME=portus
      - PORTUS_DB_PASSWORD=portus
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=3e42d49459846d68792fb44d1bc5c8d80954fad8228256333779b42345d21811dc23532bb3e370f0067efc99b2c648cbcf19cfb52a4080cfe41b3c88dfa85a88
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=portus

      # SSL
      - PORTUS_CHECK_SSL_USAGE_ENABLED=false
      #- PORTUS_PUMA_TLS_KEY=/certificates/portus.key
      #- PORTUS_PUMA_TLS_CERT=/certificates/portus.crt

      # NGinx is serving the assets instead of Puma. If you want to change this,
      # uncomment this line.
      #- RAILS_SERVE_STATIC_FILES='true'
    ports:
      - 3000:3000
    links:
      - db
    volumes:
      - ../certs:/certificates:ro
      #- static:/srv/Portus/public

  background:
    image: opensuse/portus:head
    depends_on:
      - portus
      - db
    environment:
      # Theoretically not needed, but cconfig's been buggy on this...
      - CCONFIG_PREFIX=PORTUS
      - PORTUS_MACHINE_FQDN_VALUE=portus.test.com

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_USERNAME=portus
      - PORTUS_DB_PASSWORD=portus
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=3e42d49459846d68792fb44d1bc5c8d80954fad8228256333779b42345d21811dc23532bb3e370f0067efc99b2c648cbcf19cfb52a4080cfe41b3c88dfa85a88
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=portus

      - PORTUS_BACKGROUND=true
    links:
      - db
    volumes:
      - ../certs:/certificates:ro

  db:
    image: library/mariadb:10.0.23
    environment:
      - MYSQL_DATABASE=portus_production
      - MYSQL_ROOT_PASSWORD=portus
    volumes:
      - /var/lib/portus/mariadb:/var/lib/mysql

  registry:
    image: registry
    restart: always
    environment:
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: https://portus.test.com/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: portus.test.com
      REGISTRY_AUTH_TOKEN_ISSUER: portus.test.com
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certificates/portus.crt

      # SSL
      REGISTRY_HTTP_TLS_CERTIFICATE: /certificates/portus.crt
      REGISTRY_HTTP_TLS_KEY: /certificates/portus.key

    volumes:
      - ./registry:/var/lib/registry
      #- ./config.yml:/etc/docker/registry/config.yml:ro
      - ../certs:/certificates:ro
    ports:
      - 5000:5000
    links:
      - portus:portus
```
