### ISSUE TITLE
Tags are not listed after upgrade from 2.3.0-dev (tag:head)  to the 2.3.2(tag:latest) 

### ISSUE THREAD

**Issue by str1k3r** [SUSE/Portus#1819]
### Description

After upgrade from 2.3.0-dev (tag: head) to the 2.3.2(tag:latest) my Portus installation isn't showing tags information:

![image](https://user-images.githubusercontent.com/19888/39961646-c415cc6e-5632-11e8-9677-1f0c8fd7033e.png)

I can pull image using tag name without any problems. Portus works behind standalone NGINX.
Any ideas?

### Configuration:
```yml
[Mailer config] Host:     portus.test.lan
[Mailer config] Protocol: https://
Evaluated configuration:
---
email:
  from: portus@example.com
  name: Portus
  reply_to: no-reply@example.com
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    user_name: username@example.com
    password: "****"
    domain: example.com
gravatar:
  enabled: true
delete:
  enabled: false
ldap:
  enabled: false
  hostname: ldap_hostname
  port: 389
  method: plain
  base: ''
  filter: ''
  uid: uid
  authentication:
    enabled: false
    bind_dn: ''
    password: "****"
  guess_email:
    enabled: false
    attr: ''
oauth:
  google_oauth2:
    enabled: false
    id: ''
    secret: ''
    domain: ''
    options:
      hd: ''
  open_id:
    enabled: false
    identifier: ''
    domain: ''
  github:
    enabled: false
    client_id: ''
    client_secret: ''
    organization: ''
    team: ''
    domain: ''
  gitlab:
    enabled: false
    application_id: ''
    secret: ''
    group: ''
    domain: ''
    server: ''
  bitbucket:
    enabled: false
    key: ''
    secret: ''
    domain: ''
    options:
      team: ''
first_user_admin:
  enabled: true
signup:
  enabled: true
check_ssl_usage:
  enabled: true
registry:
  jwt_expiration_time:
    value: 5
  catalog_page:
    value: 100
  timeout:
    value: 2
  read_timeout:
    value: 120
machine_fqdn:
  value: docker-registry.str1k3r.local
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: true
  create_team:
    enabled: true
  manage_team:
    enabled: true
  create_namespace:
    enabled: true
  manage_namespace:
    enabled: true
security:
  clair:
    server: ''
    health_port: 6061
    timeout: 900
  zypper:
    server: ''
  dummy:
    server: ''
anonymous_browsing:
  enabled: true
background:
  registry:
    enabled: true
  sync:
    enabled: true
    strategy: initial


```
### Portus ENV's
```code

PORTUS_PASSWORD | password
PORTUS_DB_HOST | db
PORTUS_SECRET_KEY_BASE | secret_key
PORTUS_KEY_PATH | /certificates/portus.key
PORTUS_PUMA_TLS_KEY | /certificates/portus.key
PORTUS_DB_DATABASE | portus_production
PORTUS_MACHINE_FQDN_VALUE | docker-registry.str1k3r.local
PORTUS_DB_POOL | 5
PORTUS_PUMA_TLS_CERT | /certificates/portus.crt
PORTUS_DB_PASSWORD | db_pass
RAILS_SERVE_STATIC_FILES | 'true'
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin


```

**Deployment method**:docker (compose)
**Portus version**: 2.3.2@ae07ec4ca2cd263e846e33516f7f11c45783ba05

### Different Logs:

***Registry***
```log

WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping


+ registry serve /etc/docker/registry/config.yml


time="2018-05-12T21:15:59Z" level=info msg="debug server listening 0.0.0.0:5001" 


time="2018-05-12T21:15:59Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.7.6 instance.id=e8d1dbb8-3008-4c04-a109-fd096d432430 version=v2.6.2 


time="2018-05-12T21:15:59Z" level=info msg="configuring endpoint portus (https://docker-registry.str1k3r.local/v2/webhooks/events), timeout=2s, headers=map[]" go.version=go1.7.6 instance.id=e8d1dbb8-3008-4c04-a109-fd096d432430 version=v2.6.2 


time="2018-05-12T21:15:59Z" level=info msg="Starting upload purge in 34m0s" go.version=go1.7.6 instance.id=e8d1dbb8-3008-4c04-a109-fd096d432430 version=v2.6.2 


time="2018-05-12T21:15:59Z" level=info msg="redis not configured" go.version=go1.7.6 instance.id=e8d1dbb8-3008-4c04-a109-fd096d432430 version=v2.6.2 


time="2018-05-12T21:15:59Z" level=info msg="listening on [::]:5000, tls" go.version=go1.7.6 instance.id=e8d1dbb8-3008-4c04-a109-fd096d432430 version=v2.6.2 
```
**Background**
```log
[Mailer config] Host:     docker-registry.str1k3r.local


[Mailer config] Protocol: https://


`Registry synchronization` was disabled because strategy is set to 'initial' and the database is not empty


[Initialization] Running: 'Registry events'


[Mailer config] Host:     docker-registry.str1k3r.local


[Mailer config] Protocol: https://


[Database] Not ready yet. Waiting...


`Registry synchronization` was disabled because strategy is set to 'initial' and the database is not empty


[Initialization] Running: 'Registry events'
```
***Portus***

```log

Processing by ErrorsController#show as JSON


  Parameters: {"status"=>"404"}


  Rendered errors/404.html.slim within layouts/errors (0.0ms)


  Rendered errors/_status_title.html.slim (0.0ms)


Completed 404 Not Found in 1ms (Views: 1.2ms | ActiveRecord: 0.0ms)


Started GET "/repositories/api/v1/repositories/10/tags/grouped" for 83.216.83.215 at 2018-05-12 21:24:54 +0000




ActionController::RoutingError (No route matches [GET] "/repositories/api/v1/repositories/10/tags/grouped"):


  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'


  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'


  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:38:in `call_app'


  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `block in call'


  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `block in tagged'


  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:26:in `tagged'


  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `tagged'


  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `call'


  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/request_id.rb:21:in `call'


  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'


  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'


  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'


  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/static.rb:120:in `call'


  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'


  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:518:in `call'


  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:165:in `call'


  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'


  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'


  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'


  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'


  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'


  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'


  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'


  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'






Processing by ErrorsController#show as JSON


  Parameters: {"status"=>"404"}


  Rendered errors/404.html.slim within layouts/errors (0.0ms)


  Rendered errors/_status_title.html.slim (0.0ms)


Completed 404 Not Found in 1ms (Views: 1.1ms | ActiveRecord: 0.0ms)


Started GET "/repositories/api/v1/repositories/10/tags/grouped" for 83.216.83.215 at 2018-05-12 21:25:06 +0000




ActionController::RoutingError (No route matches [GET] "/repositories/api/v1/repositories/10/tags/grouped"):


  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'


  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'


  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:38:in `call_app'


  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `block in call'


  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `block in tagged'


  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:26:in `tagged'


  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/tagged_logging.rb:68:in `tagged'


  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/rack/logger.rb:20:in `call'


  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/request_id.rb:21:in `call'


  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'


  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'


  vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'


  vendor/bundle/ruby/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/static.rb:120:in `call'


  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'


  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:518:in `call'


  vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:165:in `call'


  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'


  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'


  vendor/bundle/ruby/2.5.0/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'


  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'


  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'


  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'


  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'


  vendor/bundle/ruby/2.5.0/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'






Processing by ErrorsController#show as JSON


  Parameters: {"status"=>"404"}


  Rendered errors/404.html.slim within layouts/errors (0.0ms)


  Rendered errors/_status_title.html.slim (0.0ms)


Completed 404 Not Found in 1ms (Views: 1.1ms | ActiveRecord: 0.0ms)
```
