### ISSUE TITLE
Portus missing some repositories when syncing

### ISSUE THREAD

**Issue by ignuki** [SUSE/Portus#1823]
### Description

I am deploying Portus in Kubernetes with a preexisting Docker registry . Portus is apparently able to sync with the registry but the web interface only shows some of the repositories.

### Steps to reproduce

1. Create Docker registry, have a catalog similar to this:
```
$ curl http://registry.example.com:5000/v2/_catalog
{"repositories":["busybox/busybox","clair","httpd","myapp/myapp","vulnerables/cve-2016-10033"]}
```

2. Deploy Portus, point it to the private Docker registry
3. In the Docker registry namespace, only these repositories are shown:
![repos](https://user-images.githubusercontent.com/11045073/40102272-5a3ca1c2-58ea-11e8-91b4-dcb73d6eb0d2.png)

- **Expected behavior**: The web interface shows all repositories
- **Actual behavior**: The web interface does not show repos returned as `<library>/<repository>`

### Deployment information

**Deployment method**: I am testing Portus in Kubernetes with a configuration, based on https://github.com/mssola/Portus/tree/c0bdfa54687e0ad7117a65cb244cdf9cf186d4aa/examples/kubernetes

**Configuration**:

```yml
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
  namespace: portus-ns
type: Opaque
data:
  root: <pass>
  password: <pass>
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb-storage
  namespace: portus-ns
  labels:
    app: mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: portus-ns
  labels:
    app: mariadb
    tier: backend
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mariadb
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb
  namespace: portus-ns
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
        tier: backend
    spec:
      containers:
      - name: master
        image: library/mariadb
        env:
        - name: MYSQL_USER
          value: portus
        - name: MYSQL_DATABASE
          value: portus_production
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: root
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: password
        args:
          - "--character-set-server=utf8"
          - "--collation-server=utf8_unicode_ci"
          - "--init-connect='SET NAMES UTF8;'"
          - "--innodb-flush-log-at-trx-commit=0"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: mariadb-storage
---
# NOTE: this file should be hidden somehow, or recreated only from the CLI. This
# has been done this way to illustrate better the example.

apiVersion: v1
kind: Secret
metadata:
  name: portus-secrets
  namespace: portus-ns
type: Opaque
data:
  # openssl rand -hex 64 | base64 -w 0
  keybase: <keybase>
  # openssl rand -hex 64 | base64 -w 0
  password: <pwd>
---
apiVersion: v1
kind: Service
metadata:
  name: portus
  namespace: portus-ns
  labels:
    app: portus
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32119
  selector:
    app: portus
    tier: registry
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: portus
  namespace: portus-ns
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: portus
        tier: registry
    spec:
      containers:
      - name: portus
        image: opensuse/portus:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
        ports:
        - containerPort: 443
        volumeMounts:
        - name: certificates
          mountPath: /certificates
          readOnly: true
        env:
        - name: REGISTRY_TIMEOUT
          value: "2"
        - name: REGISTRY_READ_TIMEOUT
          value: "120"
        - name: REGISTRY_CATALOG_PAGE
          value: "100"
        - name:  PORTUS_MACHINE_FQDN_VALUE
          value: "portus.kubernetes.cluster"
        # DB
        - name:  PORTUS_DB_HOST
          value: "mariadb.portus-ns.svc.cluster.local"
        - name:  PORTUS_DB_DATABASE
          value: "portus_production"
        - name: PORTUS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: password
        # Secrets
        - name: PORTUS_SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: portus-secrets
              key: keybase
        - name: PORTUS_KEY_PATH
          value: "/certificates/portus.key"
        - name: PORTUS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: portus-secrets
              key: password
        # For simplicity we serve assets through Rails.
        - name: RAILS_SERVE_STATIC_FILES
          value: "true"
        - name: PORTUS_PUMA_TLS_KEY
          value: "/certificates/portus.key"
        - name: PORTUS_PUMA_TLS_CERT
          value: "/certificates/portus.crt"
      - name: background
        image: opensuse/portus:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: certificates
          mountPath: /certificates
          readOnly: true
        env:
        - name: REGISTRY_TIMEOUT
          value: "2"
        - name: REGISTRY_READ_TIMEOUT
          value: "120"
        - name: REGISTRY_CATALOG_PAGE
          value: "100"
        - name:  PORTUS_MACHINE_FQDN_VALUE
          value: "portus.kubernetes.cluster"
        # DB
        - name:  PORTUS_DB_HOST
          value: "mariadb.portus-ns.svc.cluster.local"
        - name:  PORTUS_DB_DATABASE
          value: "portus_production"
        - name: CCONFIG_PREFIX
          value: "PORTUS"
        - name: PORTUS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: password
       # Secrets
        - name: PORTUS_SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: portus-secrets
              key: keybase
        - name: PORTUS_KEY_PATH
          value: "/certificates/portus.key"
        - name: PORTUS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: portus-secrets
              key: password
        - name: PORTUS_BACKGROUND
          value: "true"
      volumes:
      - name: secrets
        secret:
          secretName: certificates
      - name: certificates
        secret:
          secretName: certificates
```

**Portus version**: I'm using the official `portus:latest` image.
