### ISSUE TITLE
Portus crashes when guessing LDAP email

### ISSUE THREAD

**Issue by alexanderteves** [SUSE/Portus#1832]
### Description

Portus crashes when guessing LDAP email while working fine without it.

### Steps to reproduce

I set up Portus to use LDAP which works fine without guessing the email. But when enabling guessing with the actual attribute, Portus crashes with:

```
NoMethodError (undefined method `size' for nil:NilClass):
  lib/portus/ldap.rb:235:in `guess_email'
  lib/portus/ldap.rb:213:in `find_or_create_user!'
  lib/portus/ldap.rb:195:in `portus_login!'
  lib/portus/ldap.rb:43:in `authenticate!'
  app/controllers/application_controller.rb:56:in `force_update_profile!'
  app/middleware/catch_json_parse_errors.rb:11:in `call'
```

At least I would expect it to fall back to no email setup and redirecting the user to the profile page to enter it manually as stated in the docs.

### Deployment information

**Deployment method**:

Bare metal with official Docker image v2.3

**Configuration**:

```yml
ldap:
  enabled: true

  hostname: "ldap.example.com"
  port: 389
  method: "start_tls"

  encryption:
    method: "plain"
  
base: "dc=example,dc=com"

  filter: "(&(objectClass=person)(|(employeeType=temporary)(employeeType=permanent)(employeeType=technical)(employeeType=external)))"

  uid: "uid"

  authentication:
    enabled: true
    bind_dn: "cn=readonly,ou=admin,dc=example,dc=com"
    password: "secret123"

  guess_email:
    enabled: true
    attr: "mail"
```

**Portus version**: v2.3
