### ISSUE TITLE
Allow disabling TLS usage for SMTP email

### ISSUE THREAD

**Issue by embik** [SUSE/Portus#1852]
### Description

We are using a local postfix instance to forward emails to our mail servers. Configuring Portus' email/smtp options results in 'STARTTLS' in our postfix logs although we don't want to use TLS in any way here.

I would like to disable TLS usage for smtp either by a flag or by setting the port 25 (unencrypted smtp).

### Steps to reproduce

1. Configure a Postfix plaintext-only instance
2. Configure that instance as SMTP host via port 25
3. Try to reset a password via email

- **Expected behavior**: The email being sent to my forwarder via plaintext SMTP
- **Actual behavior**: SSL error message

```
[Mailer] hostname "<hostname>" does not match the server certificate: could not stablish connection: SSL error
```

### Deployment information

**Deployment method**: On a Kubernetes cluster using self-written deployments which are based on example resources.

**Configuration**:

```yml
---
email:
  from: <email address>
  name: <email name>
  reply_to: <email reply to>
  smtp:
    enabled: true
    address: <forwarder>
    port: 25
    user_name: username@example.com
    password: "****"
    domain: example.com
gravatar:
  enabled: false
delete:
  enabled: true
ldap:
  enabled: false
  hostname: ldap_hostname
  port: 389
  method: plain
  encryption:
    method: ''
    options:
      ca_file: ''
      ssl_version: TLSv1_2
  base: ''
  filter: ''
  uid: uid
  authentication:
    enabled: false
    bind_dn: ''
    password: "****"
  guess_email:
    enabled: false
    attr: ''
oauth:
  google_oauth2:
    enabled: false
    id: ''
    secret: ''
    domain: ''
    options:
      hd: ''
  open_id:
    enabled: false
    identifier: ''
    domain: ''
  github:
    enabled: false
    client_id: ''
    client_secret: ''
    organization: ''
    team: ''
    domain: ''
  gitlab:
    enabled: false
    application_id: ''
    secret: ''
    group: ''
    domain: ''
    server: ''
  bitbucket:
    enabled: false
    key: ''
    secret: ''
    domain: ''
    options:
      team: ''
first_user_admin:
  enabled: true
signup:
  enabled: false
check_ssl_usage:
  enabled: false
registry:
  jwt_expiration_time:
    value: 5
  catalog_page:
    value: 100
  timeout:
    value: 2
  read_timeout:
    value: 120
machine_fqdn:
  value: <FQDN>
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: false
  create_team:
    enabled: false
  manage_team:
    enabled: true
  create_namespace:
    enabled: false
  manage_namespace:
    enabled: true
security:
  clair:
    server: ''
    health_port: 6061
    timeout: 900
  zypper:
    server: ''
  dummy:
    server: ''
anonymous_browsing:
  enabled: false
background:
  registry:
    enabled: true
  sync:
    enabled: true
    strategy: initial
```

**Portus version**: 2.3.3@edd5b8201e4f9e3127053dc5b1231ae4b16a3ba7
