### ISSUE TITLE
Could not fetch manifest, connection timed out

### ISSUE THREAD

**Issue by wesm-outreach** [SUSE/Portus#1863]
### Description

Check out the `CONTRIBUTING.md` file for some considerations before submitting a
new issue.

### Steps to reproduce

I see this repeated over and over in the logs for the background worker.

- **Expected behavior**: no errors are reported
- **Actual behavior**: 

```
[catalog] Could not fetch manifest for 'thing1' with tag '1': Net::OpenTimeout: connection timed out.
Net::OpenTimeout: connection timed out.
[catalog] Could not fetch manifest for 'thing1' with tag '2': Net::OpenTimeout: connection timed out.
OpenSSL::SSL::SSLError: could not stablish connection: SSL error.
[catalog] Could not fetch manifest for 'thing1' with tag '3': OpenSSL::SSL::SSLError: could not stablish connection: SSL error.
Net::OpenTimeout: connection timed out.
```

I tried putting to debug log level, but it doesn't appear to provide any additional information

### Deployment information

**Deployment method**: Kubernetes deployment without nginx. 3 pod deployments - registry, web, background

**Configuration**:

```yml
bash-4.3# portusctl exec rake portus:info
Failed to create bus connection: No such file or directory
[Mailer config] Host:     portus.test.lan
[Mailer config] Protocol: https://
Evaluated configuration:
---
email:
  from: portus@example.com
  name: Portus
  reply_to: no-reply@example.com
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    user_name: username@example.com
    password: "****"
    domain: example.com
gravatar:
  enabled: true
delete:
  enabled: false
ldap:
  enabled: false
  hostname: ldap_hostname
  port: 389
  method: plain
  encryption:
    method: ''
    options:
      ca_file: ''
      ssl_version: TLSv1_2
  base: ''
  filter: ''
  uid: uid
  authentication:
    enabled: false
    bind_dn: ''
    password: "****"
  guess_email:
    enabled: false
    attr: ''
oauth:
  google_oauth2:
    enabled: false
    id: ''
    secret: ''
    domain: ''
    options:
      hd: ''
  open_id:
    enabled: false
    identifier: ''
    domain: ''
  github:
    enabled: false
    client_id: ''
    client_secret: ''
    organization: ''
    team: ''
    domain: ''
  gitlab:
    enabled: false
    application_id: ''
    secret: ''
    group: ''
    domain: ''
    server: ''
  bitbucket:
    enabled: false
    key: ''
    secret: ''
    domain: ''
    options:
      team: ''
first_user_admin:
  enabled: true
signup:
  enabled: true
check_ssl_usage:
  enabled: true
registry:
  jwt_expiration_time:
    value: 5
  catalog_page:
    value: 100
  timeout:
    value: 2
  read_timeout:
    value: 120
machine_fqdn:
  value: registry.<REDACTED>
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: true
  create_team:
    enabled: true
  manage_team:
    enabled: true
  create_namespace:
    enabled: true
  manage_namespace:
    enabled: true
security:
  clair:
    server: ''
    health_port: 6061
    timeout: 900
  zypper:
    server: ''
  dummy:
    server: ''
anonymous_browsing:
  enabled: false
background:
  registry:
    enabled: true
  sync:
    enabled: true
    strategy: update

Portus version: 2.3.3@edd5b8201e4f9e3127053dc5b1231ae4b16a3ba7
```
