### ISSUE TITLE
Search does not work with admin user, but works with other users

### ISSUE THREAD

**Issue by LoLei** [SUSE/Portus#1881]
### Description

The search returns an error when done with a user that has "Admin" enabled, but works if "Admin" is disabled on that user.

### Steps to reproduce

1. Create a user
2. Enable "Admin" for that user
3. Log in as that user
4. Search for anything
5. **Get error (See log below)**
6. Disable "Admin" for that user
7. Log in as that user
8. Search for anything
9. **Get working search results**

- **Expected behavior**: Search results should be displayed for all users, dare I say especially for admin users.
- **Actual behavior**: The search does not work for admin users.

Log: 
```
portus_1      | Started GET "/search?utf8=%E2%9C%93&search=test" for 172.20.0.1 at 2018-07-16 09:32:21 +0000
portus_1      | Processing by SearchController#index as HTML
portus_1      |   Parameters: {"utf8"=>"✓", "search"=>"test"}
portus_1      | Completed 401 Unauthorized in 9ms (ActiveRecord: 0.7ms)
portus_1      | 
portus_1      | NoMethodError (undefined method `search' for #<Array:0x0000000005909430>
portus_1      | Did you mean?  bsearch
portus_1      |                each):
portus_1      |   app/controllers/search_controller.rb:8:in `index'
portus_1      |   app/middleware/catch_json_parse_errors.rb:11:in `call'
portus_1      | 
portus_1      | 
portus_1      | Processing by ErrorsController#show as HTML
portus_1      |   Parameters: {"utf8"=>"✓", "search"=>"test", "status"=>"500"}
portus_1      |   Rendered errors/500.html.erb within layouts/errors (0.0ms)
portus_1      |   Rendered errors/_status_title.html.slim (0.0ms)
portus_1      | Completed 500 Internal Server Error in 1ms (Views: 0.9ms | ActiveRecord: 0.0ms)

```

### Deployment information

**Deployment method**: https://github.com/SUSE/Portus/tree/master/examples/compose#insecure-example  

**Configuration**:
I did not change anything from the example.
```yml
[Mailer config] Host:     portus.test.lan
[Mailer config] Protocol: https://
Evaluated configuration:
---
email:
  from: portus@example.com
  name: Portus
  reply_to: ''
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    user_name: username@example.com
    password: "****"
    domain: example.com
gravatar:
  enabled: true
delete:
  enabled: true
  contributors: false
ldap:
  enabled: false
  hostname: ldap_hostname
  port: 389
  timeout: 5
  encryption:
    method: ''
    options:
      ca_file: ''
      ssl_version: TLSv1_2
  base: ''
  filter: ''
  uid: uid
  authentication:
    enabled: false
    bind_dn: ''
    password: "****"
  guess_email:
    enabled: false
    attr: ''
oauth:
  local_login:
    enabled: true
  google_oauth2:
    enabled: false
    id: ''
    secret: ''
    domain: ''
    options:
      hd: ''
  open_id:
    enabled: false
    identifier: ''
    domain: ''
  github:
    enabled: false
    client_id: ''
    client_secret: ''
    organization: ''
    team: ''
    domain: ''
  gitlab:
    enabled: false
    application_id: ''
    secret: ''
    group: ''
    domain: ''
    server: ''
  bitbucket:
    enabled: false
    key: ''
    secret: ''
    domain: ''
    options:
      team: ''
first_user_admin:
  enabled: true
signup:
  enabled: true
check_ssl_usage:
  enabled: "'false'"
registry:
  jwt_expiration_time:
    value: 5
  catalog_page:
    value: 100
  timeout:
    value: 2
  read_timeout:
    value: 120
machine_fqdn:
  value: 172.17.0.1
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: true
  create_team:
    enabled: true
  manage_team:
    enabled: true
  create_namespace:
    enabled: true
  manage_namespace:
    enabled: true
  create_webhook:
    enabled: true
  manage_webhook:
    enabled: true
  push_images:
    policy: allow-teams
security:
  clair:
    server: ''
    health_port: 6061
    timeout: 900
  zypper:
    server: ''
  dummy:
    server: ''
anonymous_browsing:
  enabled: true
background:
  registry:
    enabled: true
  sync:
    enabled: true
    strategy: initial
pagination:
  limit: 10
  before_after: 2
```

**Portus version**: Version: 2.4.0-dev@d643078bbf8d10a521f02edfcbabd70aac96ebc3
