### ISSUE TITLE
connection reset when connecting to external ldap server

### ISSUE THREAD

**Issue by vaskosdune** [SUSE/Portus#1894]
### Description

Hi,

When using ldap-auth with an external ad-server in our company i get the following from rails: 

` [ldap] Connection reset by peer @ io_fillbuf - fd:16 . `

I verified the connection to the ldap-server using openldaps 'ldapsearch' with the same config as in my compose file both on the vm itself and on a test-container. 

I very new to this, so i hope i have provided all the necessary information. 

### Steps to reproduce

I get the error as soon as i try to log in. 

- **Expected behavior**: portus gets the user from ldap server
- **Actual behavior**: connection gets reset

Here are the docker-compose logs on debug level:
```
Creating portusdeploymentmaster_db_1
Creating portusdeploymentmaster_portus_1
Creating portusdeploymentmaster_registry_1
Creating portusdeploymentmaster_background_1
Creating portusdeploymentmaster_nginx_1
Attaching to portusdeploymentmaster_db_1, portusdeploymentmaster_portus_1, portusdeploymentmaster_background_1, portusdeploymentmaster_registry_1, portusdeploymentmaster_nginx_1
db_1          | 180723  8:44:45 [Note] mysqld (mysqld 10.0.23-MariaDB-1~jessie) starting as process 1 ...
db_1          | 180723  8:44:45 [Note] InnoDB: Using mutexes to ref count buffer pool pages
db_1          | 180723  8:44:45 [Note] InnoDB: The InnoDB memory heap is disabled
db_1          | 180723  8:44:45 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1          | 180723  8:44:45 [Note] InnoDB: Memory barrier is not used
db_1          | 180723  8:44:45 [Note] InnoDB: Compressed tables use zlib 1.2.8
db_1          | 180723  8:44:45 [Note] InnoDB: Using Linux native AIO
db_1          | 180723  8:44:45 [Note] InnoDB: Not using CPU crc32 instructions
db_1          | 180723  8:44:45 [Note] InnoDB: Initializing buffer pool, size = 256.0M
db_1          | 180723  8:44:46 [Note] InnoDB: Completed initialization of buffer pool
db_1          | 180723  8:44:46 [Note] InnoDB: Highest supported file format is Barracuda.
db_1          | 180723  8:44:47 [Note] InnoDB: 128 rollback segment(s) are active.
db_1          | 180723  8:44:47 [Note] InnoDB: Waiting for purge to start
db_1          | 180723  8:44:47 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.26-76.0 started; log sequence number 2213909
db_1          | 180723  8:44:47 [Note] Plugin 'FEEDBACK' is disabled.
db_1          | 180723  8:44:47 [Note] Server socket created on IP: '::'.
db_1          | 180723  8:44:47 [Warning] 'proxies_priv' entry '@% root@fa4f5be158ab' ignored in --skip-name-resolve mode.
db_1          | 180723  8:44:47 [Note] mysqld: ready for connections.
db_1          | Version: '10.0.23-MariaDB-1~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
registry_1    | + cp /secrets/portus.crt /usr/local/share/ca-certificates
registry_1    | cp: can't stat '/secrets/portus.crt': No such file or directory
registry_1    | + update-ca-certificates
registry_1    | WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
registry_1    | + registry serve /etc/docker/registry/config.yml
registry_1    | time="2018-07-23T08:44:48Z" level=info msg="debug server listening 0.0.0.0:5001" 
registry_1    | time="2018-07-23T08:44:48Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.7.6 instance.id=8a18bce9-fb07-4823-95e9-9f3d82a36561 version=v2.6.2 
registry_1    | time="2018-07-23T08:44:48Z" level=info msg="configuring endpoint portus (http://a_hostname:3000/v2/webhooks/events), timeout=2s, headers=map[]" go.version=go1.7.6 instance.id=8a18bce9-fb07-4823-95e9-9f3d82a36561 version=v2.6.2 
registry_1    | time="2018-07-23T08:44:48Z" level=info msg="redis not configured" go.version=go1.7.6 instance.id=8a18bce9-fb07-4823-95e9-9f3d82a36561 version=v2.6.2 
registry_1    | time="2018-07-23T08:44:48Z" level=info msg="Starting upload purge in 3m0s" go.version=go1.7.6 instance.id=8a18bce9-fb07-4823-95e9-9f3d82a36561 version=v2.6.2 
registry_1    | time="2018-07-23T08:44:48Z" level=info msg="listening on [::]:5000, tls" go.version=go1.7.6 instance.id=8a18bce9-fb07-4823-95e9-9f3d82a36561 version=v2.6.2 
nginx_1       | 2018/07/23 08:44:49 [warn] 1#1: the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/nginx.conf:53
nginx_1       | nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/nginx.conf:53
background_1  | [Mailer config] Host:     a_hostname
background_1  | [Mailer config] Protocol: https://
portus_1      | Database ready
background_1  | [Initialization] Running: 'Registry events', 'Registry synchronization'
portus_1      | [43] Puma starting in cluster mode...
portus_1      | [43] * Version 3.10.0 (ruby 2.5.0-p0), codename: Russell's Teapot
portus_1      | [43] * Min threads: 1, max threads: 4
portus_1      | [43] * Environment: production
portus_1      | [43] * Process workers: 2
portus_1      | [43] * Preloading application
portus_1      | [Mailer config] Host:     a_hostname
portus_1      | [Mailer config] Protocol: https://
portus_1      | [43] * Listening on ssl://0.0.0.0:3000?cert=/certificates/portus.cer&key=/certificates/privkey.pem&verify_mode=none
portus_1      | [43] Use Ctrl-C to stop
portus_1      | [43] - Worker 0 (pid: 46) booted, phase: 0
portus_1      | [43] - Worker 1 (pid: 56) booted, phase: 0
portus_1      | Started GET "/" for 172.18.0.6 at 2018-07-23 08:46:14 +0000
portus_1      | Processing by Auth::SessionsController#new as HTML
portus_1      |    (0.9ms)  SELECT COUNT(*) FROM `users` WHERE (`users`.`username` != 'portus')
portus_1      |   Rendered shared/_notification.html.slim (6.7ms)
portus_1      |   Rendered shared/_notifications.html.slim (12.8ms)
portus_1      |   User Load (0.7ms)  SELECT `users`.* FROM `users` WHERE (`users`.`username` != 'portus')
portus_1      |   Rendered devise/sessions/new.html.slim within layouts/authentication (50.1ms)
portus_1      | Completed 200 OK in 155ms (Views: 71.1ms | ActiveRecord: 5.6ms)
nginx_1       | 10.1.0.215 - - [23/Jul/2018:08:46:15 +0000] "GET / HTTP/2.0" 200 1604 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
nginx_1       | 10.1.0.215 - - [23/Jul/2018:08:46:16 +0000] "GET /favicon/favicon-16x16.png HTTP/2.0" 200 1131 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
portus_1      | Started POST "/users/sign_in" for 172.18.0.6 at 2018-07-23 08:46:19 +0000
portus_1      | Processing by Auth::SessionsController#create as HTML
portus_1      |   Parameters: {"utf8"=>"✓", "authenticity_token"=>"Ux8M1Ak7GjXJEBHPi5IXltP6zzSBqUW3yVM8XRQyojU7qpM9yr2X0PC3BCUE9RfR87kvWfGGN3LLCo/8MBIqtw==", "user"=>{"username"=>"a_user", "password"=>"[FILTERED]"}, "button"=>""}
portus_1      | [ldap] Connection reset by peer @ io_fillbuf - fd:16 .
portus_1      | Completed 401 Unauthorized in 4ms (ActiveRecord: 0.0ms)
portus_1      | Processing by Auth::SessionsController#new as HTML
portus_1      |   Parameters: {"utf8"=>"✓", "authenticity_token"=>"Ux8M1Ak7GjXJEBHPi5IXltP6zzSBqUW3yVM8XRQyojU7qpM9yr2X0PC3BCUE9RfR87kvWfGGN3LLCo/8MBIqtw==", "user"=>{"username"=>"a_user", "password"=>"[FILTERED]"}, "button"=>""}
portus_1      |    (0.4ms)  SELECT COUNT(*) FROM `users` WHERE (`users`.`username` != 'portus')
portus_1      |   Rendered shared/_notification.html.slim (0.1ms)
portus_1      |   Rendered shared/_notification.html.slim (0.0ms)
portus_1      |   Rendered shared/_notifications.html.slim (0.5ms)
portus_1      |   User Load (0.3ms)  SELECT `users`.* FROM `users` WHERE (`users`.`username` != 'portus')I replaced sensitive information with comments. 
portus_1      |   Rendered devise/sessions/new.html.slim within layouts/authentication (3.6ms)
portus_1      | Completed 200 OK in 90ms (Views: 4.9ms | ActiveRecord: 0.7ms)
nginx_1       | 10.1.0.215 - - [23/Jul/2018:08:46:20 +0000] "POST /users/sign_in HTTP/2.0" 200 4540 "https://a_hostname" "Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
registry_1    | time="2018-07-23T08:47:48Z" level=info msg="PurgeUploads starting: olderThan=2018-07-16 08:47:48.584753545 +0000 UTC, actuallyDelete=true" 
registry_1    | time="2018-07-23T08:47:48Z" level=info msg="Purge uploads finished.  Num deleted=0, num errors=1" 
registry_1    | time="2018-07-23T08:47:48Z" level=info msg="Starting upload purge in 24h0m0s" go.version=go1.7.6 instance.id=8a18bce9-fb07-4823-95e9-9f3d82a36561 version=v2.6.2
```
### Deployment information

I deployed portus with docker-compose inside a vm, to migrate from a rpm-based Installation. This setup is a mix between the secure example and the ldap example.

**Configuration**:

portus:info: 
```
[Mailer config] Host:     portus.test.lan
[Mailer config] Protocol: https://
Evaluated configuration:
---
email:
  from: portus@example.com
  name: Portus
  reply_to: no-reply@example.com
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    user_name: username@example.com
    password: "****"
    domain: example.com
gravatar:
  enabled: true
delete:
  enabled: false
ldap:
  enabled: true
  hostname: ad_host.domain
  port: 636
  method: plain
  encryption:
    method: start_tls
    options:
      ca_file: "/ldap-certificates/ca.pem"
      ssl_version: TLSv1_2
  base: OU=User,OU=Location00,OU=org,dc=domain,dc=local
  filter: ''
  uid: cn
  authentication:
    enabled: true
    bind_dn: CN=service_user,OU=FunktionsUser,OU=User,OU=Location00,OU=org,DC=domain,DC=local
    password: "****"
  guess_email:
    enabled: false
    attr: ''
oauth:
  google_oauth2:
    enabled: false
    id: ''
    secret: ''
    domain: ''
    options:
      hd: ''
  open_id:
    enabled: false
    identifier: ''
    domain: ''
  github:
    enabled: false
    client_id: ''
    client_secret: ''
    organization: ''
    team: ''
    domain: ''
  gitlab:
    enabled: false
    application_id: ''
    secret: ''
    group: ''
    domain: ''
    server: ''
  bitbucket:
    enabled: false
    key: ''
    secret: ''
    domain: ''
    options:
      team: ''
first_user_admin:
  enabled: true
signup:
  enabled: true
check_ssl_usage:
  enabled: true
registry:
  jwt_expiration_time:
    value: 5
  catalog_page:
    value: 100
  timeout:
    value: 2
  read_timeout:
    value: 120
machine_fqdn:
  value: a_hostname
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: true
  create_team:
    enabled: true
  manage_team:
    enabled: true
  create_namespace:
    enabled: true
  manage_namespace:
    enabled: true
security:
  clair:
    server: ''
    health_port: 6061
    timeout: 900
  zypper:
    server: ''
  dummy:
    server: ''
anonymous_browsing:
  enabled: true
background:
  registry:
    enabled: true
  sync:
    enabled: true
    strategy: initial
```

```yml
version: "2"

services:
  portus:
    # opensuse/portus:head
    image: org/portus:2.3
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}


      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      # SSL
      - PORTUS_PUMA_TLS_KEY=/certificates/privkey.pem
      - PORTUS_PUMA_TLS_CERT=/certificates/a_hostname.cer

      # LDAP
      - PORTUS_LDAP_ENABLED=true
      - PORTUS_LDAP_HOSTNAME=ad_host.domain
      - PORTUS_LDAP_PORT=636
      - PORTUS_LDAP_UID=cn
      - PORTUS_LDAP_BASE=OU=User,OU=Location00,OU=org,dc=domain,dc=local
      - PORTUS_LDAP_AUTHENTICATION_ENABLED=true
      - PORTUS_LDAP_AUTHENTICATION_BIND_DN=CN=service_user,OU=FunktionsUser,OU=User,OU=Location00,OU=org,DC=domain,DC=local
      - PORTUS_LDAP_AUTHENTICATION_PASSWORD=password
      - PORTUS_LDAP_ENCRYPTION_METHOD=start_tls
      - PORTUS_LDAP_ENCRYPTION_OPTIONS_CA_FILE=/ldap-certificates/ca.pem
      #- PORTUS_LDAP_ENCRYPTION_OPTIONS_SSL_VERSION=TLSv2
      # assets
      #- RAILS_SERVE_STATIC_FILES=true
      - PORTUS_LOG_LEVEL=debug
    ports:
      - 3000:3000
    extra_hosts:
      - "ad_host.domain:ip"
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro
      - ./secrets/ldap:/ldap-certificates:ro
      - static:/srv/Portus/public

  background:
    # opensuse/portus
    image: org/portus:2.3
    depends_on:
      - portus
      - db
    environment:
      # Theoretically not needed, but cconfig's been buggy on this...
      - CCONFIG_PREFIX=PORTUS
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      - PORTUS_BACKGROUND=true
    links:
      - db
      - portus
    volumes:
      - ./secrets:/certificates:ro

  db:
    image: org/mariadb:10.0.23
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      - MYSQL_DATABASE=portus_production
      - MYSQL_PASSWORD=portus
      # Again, the password shouldn't be handled like this.
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - /var/lib/mysql:/var/lib/mysql


  registry:
    # registry:2.6
    image: org/registry:2.6 
    command: ["/bin/sh", "/etc/docker/registry/init"]
    environment:
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: http://${MACHINE_FQDN}:3000/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: ${MACHINE_FQDN}:5000
      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /secrets/t-portus.m086.cer

      REGISTRY_HTTP_TLS_CERTIFICATE: /secrets/t-portus.m086.cer
      REGISTRY_HTTP_TLS_KEY: /secrets/privkey.pem

      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: http://${MACHINE_FQDN}:3000/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
      - /var/lib/registry:/var/lib/registry
      - ./secrets:/secrets:ro
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
      - ./registry/init:/etc/docker/registry/init:ro
    ports:
      - 5000:5000
      - 5001:5001 # required to access debug service
    links:
      - portus:portus
    
  nginx:
    # nginx:alpine
    image: org/nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./secrets:/secrets:ro
      - static:/srv/Portus/public:ro
    ports:
      - "80:80"
      - "443:443"
    links:
      - registry:registry
      - portus:portus

volumes:
  static:
    driver: local

```

**Portus version**:  Portus version: 2.3.3@edd5b8201e4f9e3127053dc5b1231ae4b16a3ba7
