### ISSUE TITLE
Background service crashing

### ISSUE THREAD

**Issue by Hugo1380** [SUSE/Portus#1895]
### Description

Service `background` crashing after changing MACHINE_FQDN in `.env`.

### Steps to reproduce

1. Set container_name to `portus-registry` for registry service
2. Set MACHINE_FQDN=portus-registry.dnstest.com

- **Expected behavior**: Background service start
- **Actual behavior**: But background service exit

```
background_1  | bin/rails: undefined method `[]' for nil:NilClass (NoMethodError)
portus_background_1 exited with code 1
```

### Deployment information

Deploy with `docker-compose up`

**Configuration**:

- In a container:
  - Using the development `docker-compose.yml` at the repo root

I have a DNS container [phensley/docker-dns](https://github.com/phensley/docker-dns) that point all my container to a DNS entry according his container name. (So portus-registry = portus-registry.dnstest.com)

```yml
version: '2'

services:
  portus:
    build: .
    image: opensuse/portus:development
    command: bundle exec rails runner /srv/Portus/examples/development/compose/init.rb
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}
      - PORTUS_PUMA_HOST=0.0.0.0:3000
      - PORTUS_CHECK_SSL_USAGE_ENABLED=false
      - PORTUS_SECURITY_CLAIR_SERVER=http://clair:6060

      - CCONFIG_PREFIX=PORTUS

      - PORTUS_DB_HOST=db
      - PORTUS_DB_PASSWORD=XXXXX
      - PORTUS_DB_POOL=5

      - RAILS_SERVE_STATIC_FILES=true
    ports:
      - 3000:3000
    dns: dns_ip_server
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/srv/Portus
    network_mode: bridge

  background:
    image: opensuse/portus:development
    entrypoint: bundle exec rails runner /srv/Portus/bin/background.rb
    depends_on:
      - portus
      - db
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}
      - PORTUS_SECURITY_CLAIR_SERVER=http://clair:6060

      # Theoretically not needed, but cconfig's been buggy on this...
      - CCONFIG_PREFIX=PORTUS

      - PORTUS_DB_HOST=db
      - PORTUS_DB_PASSWORD=XXXX
      - PORTUS_DB_POOL=5
    volumes:
      - .:/srv/Portus
    dns: dns_ip_server
    links:
      - db
    network_mode: bridge

  webpack:
    image: kkarczmarczyk/node-yarn:6.9-slim
    command: bash /srv/Portus/examples/development/compose/bootstrap-webpack
    working_dir: /srv/Portus
    volumes:
      - .:/srv/Portus
    network_mode: bridge

  clair:
    image: quay.io/coreos/clair:v2.0.1
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "6060-6061:6060-6061"
    volumes:
      - /tmp:/tmp
      - ./examples/development/compose/clair.yml:/clair.yml
    command: [-config, /clair.yml]
    network_mode: bridge

  db:
    image: library/mariadb:10.0.23
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_ROOT_PASSWORD: XXXX
    network_mode: bridge

  postgres:
    image: library/postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: XXXXX
    network_mode: bridge

  registry:
    image: library/registry:2.3.1
    container_name: portus-registry
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry_data
      REGISTRY_STORAGE_DELETE_ENABLED: "true"

      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_HTTP_DEBUG_ADDR: 0.0.0.0:5001

      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /etc/docker/registry/portus.crt

      REGISTRY_AUTH_TOKEN_REALM: http://${MACHINE_FQDN}:3000/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: ${MACHINE_FQDN}:${REGISTRY_PORT}
      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}

      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: http://${MACHINE_FQDN}:3000/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
      - /registry_data
      - ./examples/development/compose/portus.crt:/etc/docker/registry/portus.crt:ro
    ports:
      - ${REGISTRY_PORT}:5000
      - 5001:5001
    dns: dns_ip_server
    links:
      - portus
    network_mode: bridge
```

**Portus version**: 2.3.3 commit edd5b82
