### ISSUE TITLE
Add documentation for the garbage collector introduced in 2.4

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#1904]
### Description

The PR #1864 introduced another task for the background job. We should update the page about the background job by explaining this new task.

**Comment by tankbusta** [comment]
It's important to note for those using custom Portus configs, that they add the new items for the Garbage Collector otherwise the background process will crash. I noticed the PR said it's off by default but when I pulled down the new images today, I kept crashing until I added the GC directives.

**Comment by mssola** [comment]
@tankbusta that's certainly a bug :confused: You are talking about the latest `head` image? Could you paste some logs?

**Comment by tankbusta** [comment]
Yes this is with the latest head image

```
background_1  | [Initialization] Running: 'Registry events', 'Security scanning', 'Registry synchronization', 'Garbage collector'
background_1  | /srv/Portus/lib/portus/background/garbage_collector.rb:55:in `older_than': undefined method `[]' for nil:NilClass (NoMethodError)
background_1  | 	from /srv/Portus/lib/portus/background/garbage_collector.rb:47:in `tags_to_be_collected'
background_1  | 	from /srv/Portus/lib/portus/background/garbage_collector.rb:18:in `work?'
background_1  | 	from /srv/Portus/bin/background.rb:58:in `block (2 levels) in <top (required)>'
background_1  | 	from /srv/Portus/bin/background.rb:56:in `each'
background_1  | 	from /srv/Portus/bin/background.rb:56:in `each_with_index'
background_1  | 	from /srv/Portus/bin/background.rb:56:in `block in <top (required)>'
background_1  | 	from /srv/Portus/bin/background.rb:55:in `loop'
background_1  | 	from /srv/Portus/bin/background.rb:55:in `<top (required)>'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `load'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `<top (required)>'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:90:in `runner'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
background_1  | 	from bin/rails:12:in `require'
background_1  | 	from bin/rails:12:in `<main>'
background_1  | exit status 1
```

I solved it by adding the config entries under `delete`

```
  # The garbage collector will run when enabled in the background process, and
  # it will only delete tags matching the given conditions.
  garbage_collector:
    enabled: false

    # Remove images older than a specific value. This value is interpreted as
    # the number of days.
    older_than: 30

    # Provide a string containing a regular expression. If you provide a
    # valid regular expression, garbage collector will only be applied into tags
    # matching a given name.
    #
    # Valid values might be:
    #   - "jenkins": if you anticipate that you will always have a tag with a
    #     specific name, you can simply use that.
    #   - "build-\\d+": your tag follows a format like "build-1234" (note that
    #     we need to specify "\\d" and not just "\d").
    tag: ""
```
