### ISSUE TITLE
Sendgrid smtp error

### ISSUE THREAD

**Issue by hmilkovi** [SUSE/Portus#1922]
### Description

Can't setup sendgrid in smtp

### Steps to reproduce

1. Put sendgrid stuff into ` config.yml `  : 
```
  smtp:
    enabled: true
    address: "smtp.sendgrid.net"
    port: 2525,
    user_name: "<username>"
    password: "<password>"
    domain: "<company email>"
```
2. Restart Portus in docker
3. Error was thrown:
```
portus_1      |   Rendered vendor/bundle/ruby/2.5.0/gems/devise-4.4.0/app/views/devise/mailer/reset_password_instructions.html.erb (0.3ms)
portus_1      |
portus_1      | Sent mail to hmilkovi@gmail.com (244.4ms)
portus_1      | Completed 401 Unauthorized in 255ms (ActiveRecord: 2.4ms)
portus_1      |
portus_1      | Net::SMTPAuthenticationError (535 Authentication failed: Bad username / password
portus_1      | ):
portus_1      |   app/controllers/passwords_controller.rb:14:in `create'
portus_1      |   app/middleware/catch_json_parse_errors.rb:11:in `call'
```

- **Expected behavior**: Email was sent
- **Actual behavior**: Response http 500 with above error

### Deployment information

**Deployment method**: docker compose and other stuff works as expected.

**Portus version**:  2.4.0-dev@34e5d9aed844120373c6f832ccff6d4931633e2a

**Comment by mssola** [comment]
A couple of things:

1. Don't change the `config.yml` directly. As documented [here](http://port.us.org/docs/Configuring-Portus.html), you should use environment variables or the `config-local.yml` file instead.
2. This looks like a configuration issue. I didn't know about sendgrid, but it should be able to act as any other server for SMTP. In particular, from what I can read [here](https://sendgrid.com/docs/Integrate/Frameworks/rubyonrails.html), the port should be the standard 587, and not 2525 as you have. Besides this, check that the credentials you used are the ones being expected on sendgrid.

**Comment by mssola** [comment]
@hmilkovi now it should hopefully be fine (see #1967 and the [new documentation for the mailer](http://port.us.org/docs/Configuring-Portus.html#email-configuration)). I've also tested it with sendgrid, and for me the configuration was something like:

```yaml
email:
 from: "myemail@example.com"
 name: "Miquel"

 smtp:
   enabled: true
   address: "smtp.sendgrid.net"
   port: 587,
   domain: "smtp.sendgrid.net"
   user_name: "user"
   password: "password"
   authentication: "login"
   enable_starttls_auto: true
   openssl_verify_mode:  "none"

```
