### ISSUE TITLE
Net::OpenTimeout: Portus cannot connect to docker registry.

### ISSUE THREAD

**Issue by PawanDalal** [SUSE/Portus#1933]
I am trying to connect to docker registry hosted on my product cloud machine with the portus with the help of the configuration provided [here](https://github.com/SUSE/Portus/blob/master/examples/compose/docker-compose.yml). I did not use the `background` container in my docker-compose.yml configuration. Also I used PORTUS_SECRET_KEY_BASE_FILE instead of PORTUS_SECRET_KEY_BASE variable.

I am not able to connect the portus UI to the registry. 

The logs and configuration is taken from production (So, I'm not allowed to expose some details here)

**LOGS:**

```
portus_1    |   Parameters: {"utf8"=>"&#x2713;", "authenticity_token"=>"5uDez4fkDo4DmXzE7Mvbkk/cVtKaVQ7nDpCPcmmHEkNmrzDl+YvciPbbhkhnM0+D7Ef0yUwwWcZhFLE0US3yAg==", "registry"=>{"name"=>"$$$$$$", "hostname"=>"registry.$$$$$$.com:5000", "use_ssl"=>"1", "external_hostname"=>"registry.$$$$$$.com"}, "commit"=>"Update", "id"=>"1"}
portus_1    | Net::OpenTimeout: connection timed out.
portus_1    | 
portus_1    | Registry not reachable:
portus_1    | #<Registry id: 1, name: "$$$$$$", hostname: "registry.$$$$$$.com:5000", created_at: "2018-07-31 20:47:14", updated_at: "2018-07-31 20:47:14", use_ssl: true, external_hostname: "registry.$$$$$$.com">
portus_1    | Net::OpenTimeout: connection timed out.
portus_1    | 
portus_1    |   Rendered admin/registries/components/_form.html.slim (2.8ms)
portus_1    |   Rendered admin/registries/edit.html.slim within layouts/application (3.4ms)
portus_1    |   Rendered shared/_header.html.slim (1.1ms)
portus_1    |   Rendered shared/_aside.html.slim (0.8ms)
portus_1    |   Rendered shared/_search.html.slim (0.3ms)
portus_1    |   Rendered shared/_notification.html.slim (0.1ms)
portus_1    |   Rendered shared/_notification.html.slim (0.1ms)
portus_1    |   Rendered shared/_notifications.html.slim (0.6ms)
```
**Configuration**:
```
version: "2.0"

services:
  portus:
    image: opensuse/portus:latest
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=portus.$$$$$$.com

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_$$$$$$
      - PORTUS_DB_PASSWORD=$$$$$$$$$$
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE_FILE=/secrets/keybase
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD_FILE=/secrets/passwd

      # SSL
      - PORTUS_PUMA_TLS_KEY=/certificates/portus.key
      - PORTUS_PUMA_TLS_CERT=/certificates/portus.crt

      # NGinx is serving the assets instead of Puma. If you want to change this,
      # uncomment this line.
      - RAILS_SERVE_STATIC_FILES='true'
    ports:
      - 3000:3000
    links:
      - db
    volumes:
      - static:/srv/Portus/public
      - /home/ubuntu/portus/certs:/certificates:ro
      - /home/ubuntu/portus/keys:/secrets

  db:
    image: library/mariadb:10.0.23
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      - MYSQL_DATABASE=portus_$$$$$$$

      # Again, the password shouldn't be handled like this.
      - MYSQL_ROOT_PASSWORD=$$$$$$$
    volumes:
      - /var/lib/portus/mariadb:/var/lib/mysql

  registry:
    image: library/registry:2.6
    command: ["/bin/sh", "/etc/docker/registry/init"]
    environment:
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: https://registry.$$$$$$.com/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: registry.$$$$$$.com
      REGISTRY_AUTH_TOKEN_ISSUER: registry.$$$$$$.com
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certs/server.crt

      # SSL
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/server.crt
      REGISTRY_HTTP_TLS_KEY: /certs/server.key

      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://registry.$$$$$$.com/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
      - /opt/docker-registry/data:/var/lib/registry
      - /opt/docker-registry/certs:/certs:ro 
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
      - ./registry/init:/etc/docker/registry/init:ro
    ports:
      - 5000:5000
      - 5001:5001 # required to access debug service
    links:
      - portus:portus
  
  nginx:
    image: library/nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/ubuntu/portus/certs:/certificates:ro
      - static:/srv/Portus/public:ro
    ports:
      - 80:80
      - 443:443
    links:
      - registry:registry
      - portus:portus
    depends_on:
      - portus
      - registry
volumes:
  static:
    driver: local

```
**Portus Version:** 2.3.3@edd5b8201e4f9e3127053dc5b1231ae4b16a3ba7
