### ISSUE TITLE
Repository view runs into timeout with large amount of repositories

### ISSUE THREAD

**Issue by Bonko** [SUSE/Portus#1940]
### Description

After having synced all repositories from docker registry to portus, calling https://portus.internal-domain/repositories returns after about 10s with a `504 - GATEWAY_TIMEOUT`.

Our registry contains about 650 repositories with up to 3000 tags each.

### Steps to reproduce

1. Set up portus with existing registry
2. Wait until everything is synced
3. Open `/repositories` in browser.

- **Expected behavior**: A list of all repositories
- **Actual behavior**: HTTP 504 `GATEWAY_TIMEOUT`

All other views work.

The same behaviour occurs when opening the URL with `curl`. The timeout happens in less than 10s. The configured ELB in front of the service has an idle timeout of 60s.

### Deployment information

**Deployment method**:

Running the official docker image in Amazon ECS behind an ELB.

**Configuration**:

```yml
Evaluated configuration:
---
email:
  from: portus@example.com
  name: Portus
  reply_to: no-reply@example.com
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    user_name: username@example.com
    password: "****"
    domain: example.com
gravatar:
  enabled: true
delete:
  enabled: true
ldap:
  enabled: false
  hostname: ldap_hostname
  port: 389
  method: plain
  encryption:
    method: ''
    options:
      ca_file: ''
      ssl_version: TLSv1_2
  base: ''
  filter: ''
  uid: uid
  authentication:
    enabled: false
    bind_dn: ''
    password: "****"
  guess_email:
    enabled: false
    attr: ''
oauth:
  google_oauth2:
    enabled: true
    id: XXX
    secret: XXX
    domain: XXX.com
    options:
      hd: XXX.com
  open_id:
    enabled: false
    identifier: ''
    domain: ''
  github:
    enabled: false
    client_id: ''
    client_secret: ''
    organization: ''
    team: ''
    domain: ''
  gitlab:
    enabled: false
    application_id: ''
    secret: ''
    group: ''
    domain: ''
    server: ''
  bitbucket:
    enabled: false
    key: ''
    secret: ''
    domain: ''
    options:
      team: ''
first_user_admin:
  enabled: true
signup:
  enabled: false
check_ssl_usage:
  enabled: false
registry:
  jwt_expiration_time:
    value: 5
  catalog_page:
    value: 100
  timeout:
    value: 2
  read_timeout:
    value: 120
machine_fqdn:
  value: portus.XXX.net
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: true
  create_team:
    enabled: true
  manage_team:
    enabled: true
  create_namespace:
    enabled: true
  manage_namespace:
    enabled: true
security:
  clair:
    server: http://clair:6060
    health_port: 6061
    timeout: 900
  zypper:
    server: ''
  dummy:
    server: ''
anonymous_browsing:
  enabled: false
background:
  registry:
    enabled: true
  sync:
    enabled: true
    strategy: initial
```

**Portus version**: 
2.3.5@d1bc09bf2d27246d04349c6677c9c35e09e0fb7b
