### ISSUE TITLE
Background container got exited after configure docker registry on UI

### ISSUE THREAD

**Issue by DavidTinoco** [SUSE/Portus#1947]
### Description

When i configure the docker registry on UI the background container got exited.

### Steps to reproduce

I just cloned the repository, configure the `MAQUINE_FQDN` on the `.env` file and the `server` variable on `nginx/nginx.conf` and created the self-signed certificates on the `secrets` directory. 

```
openssl req -x509 -newkey rsa:4096 -sha256 -nodes -keyout portus.key -out portus.crt -subj "/CN=portus-lab.test.es" -days 3650
```

Then execute the `docker-compose up -d`, and when all its up, and the Portus web it's accesible, i configure the admin user, and add the registry successfully, but the `compose_background_1` container go to `Exit 1` State

That's the log of the container
```
docker-compose logs background
Attaching to compose_background_1
background_1  | [Mailer config] Host:     portus-lab.test.es
background_1  | [Mailer config] Protocol: https://
background_1  | [Database] Not ready yet. Waiting...
background_1  | [Database] Not ready yet. Waiting...
background_1  | [Database] Not ready yet. Waiting...
background_1  | [Initialization] Running: 'Registry events', 'Registry synchronization', 'Garbage collector'
background_1  | /srv/Portus/lib/portus/registry_client.rb:182:in `get_page': Something went wrong while fetching the catalog Response: [401] - {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Class":"","Name":"catalog","Action":"*"}]}]} (Portus::RegistryClient::RegistryError)
background_1  |         from /srv/Portus/lib/portus/registry_client.rb:160:in `paged_response'
background_1  |         from /srv/Portus/lib/portus/registry_client.rb:107:in `catalog'
background_1  |         from /srv/Portus/lib/portus/background/sync.rb:63:in `block in execute!'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `each'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `block in find_each'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:124:in `find_in_batches'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:50:in `find_each'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/querying.rb:9:in `find_each'
background_1  |         from /srv/Portus/lib/portus/background/sync.rb:62:in `execute!'
background_1  |         from /srv/Portus/bin/background.rb:58:in `block (2 levels) in <top (required)>'
background_1  |         from /srv/Portus/bin/background.rb:56:in `each'
background_1  |         from /srv/Portus/bin/background.rb:56:in `each_with_index'
background_1  |         from /srv/Portus/bin/background.rb:56:in `block in <top (required)>'
background_1  |         from /srv/Portus/bin/background.rb:55:in `loop'
background_1  |         from /srv/Portus/bin/background.rb:55:in `<top (required)>'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `load'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `<top (required)>'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:90:in `runner'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
background_1  |         from bin/rails:12:in `require'
background_1  |         from bin/rails:12:in `<main>'
background_1  | exit status 1
```

**Configuration**:

Here the portus info
```
docker exec -it compose_portus_1 portusctl exec rake portus:info
[Mailer config] Host:     portus.test.lan
[Mailer config] Protocol: https://
Evaluated configuration:
---
email:
  from: portus@example.com
  name: Portus
  reply_to: ''
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    user_name: username@example.com
    password: "****"
    domain: example.com
gravatar:
  enabled: true
delete:
  enabled: true
  contributors: false
  garbage_collector:
    enabled: false
    older_than: 30
    tag: ''
ldap:
  enabled: false
  hostname: ldap_hostname
  port: 389
  timeout: 5
  encryption:
    method: ''
    options:
      ca_file: ''
      ssl_version: TLSv1_2
  base: ''
  filter: ''
  uid: uid
  authentication:
    enabled: false
    bind_dn: ''
    password: "****"
  guess_email:
    enabled: false
    attr: ''
oauth:
  local_login:
    enabled: true
  google_oauth2:
    enabled: false
    id: ''
    secret: ''
    domain: ''
    options:
      hd: ''
  open_id:
    enabled: false
    identifier: ''
    domain: ''
  github:
    enabled: false
    client_id: ''
    client_secret: ''
    organization: ''
    team: ''
    domain: ''
  gitlab:
    enabled: false
    application_id: ''
    secret: ''
    group: ''
    domain: ''
    server: ''
  bitbucket:
    enabled: false
    key: ''
    secret: ''
    domain: ''
    options:
      team: ''
first_user_admin:
  enabled: true
signup:
  enabled: true
check_ssl_usage:
  enabled: true
registry:
  jwt_expiration_time:
    value: 5
  catalog_page:
    value: 100
  timeout:
    value: 2
  read_timeout:
    value: 120
machine_fqdn:
  value: portus-lab.test.es
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: true
  create_team:
    enabled: true
  manage_team:
    enabled: true
  create_namespace:
    enabled: true
  manage_namespace:
    enabled: true
  create_webhook:
    enabled: true
  manage_webhook:
    enabled: true
  push_images:
    policy: allow-teams
security:
  clair:
    server: ''
    health_port: 6061
    timeout: 900
  zypper:
    server: ''
  dummy:
    server: ''
anonymous_browsing:
  enabled: true
background:
  registry:
    enabled: true
  sync:
    enabled: true
    strategy: initial
pagination:
  limit: 10
  before_after: 2

Portus version: 2.4.0-dev@312cde6fda4dcab736ddf99eeae9e4d4991227e9
```

Thanks in advance.
