### ISSUE TITLE
Could not find sprockets-3.7.2 in any of the sources

### ISSUE THREAD

**Issue by Hugo1380** [SUSE/Portus#1960]
### Description

An error occur with the Gem Builder and Sprockets.

### Steps to reproduce

1. Start `docker-compose up`
2. Then portus and background services crash

- **Expected behavior**: All start correctly.
- **Actual behavior**: But portus and background services crashing
```

portus        | /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.16.0/lib/bundler/spec_set.rb:88:in `block in materialize': Could not find sprockets-3.7.2 in any of the sources (Bundler::GemNotFound)
portus        | 	from /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.16.0/lib/bundler/spec_set.rb:82:in `map!'
portus        | 	from /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.16.0/lib/bundler/spec_set.rb:82:in `materialize'
portus        | 	from /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.16.0/lib/bundler/definition.rb:170:in `specs'
portus        | 	from /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.16.0/lib/bundler/definition.rb:237:in `specs_for'
portus        | 	from /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.16.0/lib/bundler/definition.rb:226:in `requested_specs'
portus        | 	from /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:108:in `block in definition_method'
portus        | 	from /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:20:in `setup'
portus        | 	from /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.16.0/lib/bundler.rb:107:in `setup'
portus        | 	from /usr/lib64/ruby/gems/2.5.0/gems/bundler-1.16.0/lib/bundler/setup.rb:20:in `<top (required)>'
portus        | 	from /usr/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
portus        | 	from /usr/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
portus exited with code 1

```

And same reaction with `portus_background`.

### Deployment information

With `docker-compose.yml` at the root of the repo a little bit modified.

```yml
version: '2'

services:
  portus:
    build: .
    image: opensuse/portus:head
    command: bundle exec rails runner /srv/Portus/examples/development/compose/init.rb
    container_name: portus
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}
      - PORTUS_PUMA_HOST=0.0.0.0:3000
      - PORTUS_CHECK_SSL_USAGE_ENABLED=false
      - PORTUS_SECURITY_CLAIR_SERVER=http://clair:6060

      - CCONFIG_PREFIX=PORTUS

      - PORTUS_DB_HOST=db
      - PORTUS_DB_PASSWORD=****
      - PORTUS_DB_POOL=5

      - RAILS_SERVE_STATIC_FILES=true
    ports:
      - 3000:3000
    dns: 172.17.0.3
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/srv/Portus
    network_mode: bridge

  background:
    image: opensuse/portus:head
    entrypoint: bundle exec rails runner /srv/Portus/bin/background.rb
    depends_on:
      - portus
      - db
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}
      - PORTUS_SECURITY_CLAIR_SERVER=http://clair:6060

      # Theoretically not needed, but cconfig's been buggy on this...
      - CCONFIG_PREFIX=PORTUS

      - PORTUS_DB_HOST=db
      - PORTUS_DB_PASSWORD=*****
      - PORTUS_DB_POOL=5
    volumes:
      - .:/srv/Portus
    dns: 172.17.0.3
    links:
      - db
    network_mode: bridge

  webpack:
    image: kkarczmarczyk/node-yarn:6.9-slim
    command: bash /srv/Portus/examples/development/compose/bootstrap-webpack
    working_dir: /srv/Portus
    volumes:
      - .:/srv/Portus
    network_mode: bridge

  clair:
    image: quay.io/coreos/clair:v2.0.1
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "6060-6061:6060-6061"
    volumes:
      - /tmp:/tmp
      - ./examples/development/compose/clair.yml:/clair.yml
    command: [-config, /clair.yml]
    network_mode: bridge

  db:
    image: library/mariadb:10.0.23
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_ROOT_PASSWORD: ****
    network_mode: bridge

  postgres:
    image: library/postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: ****
    network_mode: bridge

  registry:
    image: library/registry:2.3.1
    container_name: portus-registry
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry_data
      REGISTRY_STORAGE_DELETE_ENABLED: "true"

      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_HTTP_DEBUG_ADDR: 0.0.0.0:5001

      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /etc/docker/registry/portus.crt

      REGISTRY_AUTH_TOKEN_REALM: http://${MACHINE_FQDN}:3000/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: ${MACHINE_FQDN}:${REGISTRY_PORT}
      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}

      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: http://${MACHINE_FQDN}:3000/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
      - /registry_data
      - ./examples/development/compose/portus.crt:/etc/docker/registry/portus.crt:ro
    ports:
      - ${REGISTRY_PORT}:5000
      - 5001:5001
    dns: 172.17.0.3
    links:
      - portus
    network_mode: bridge
```

**Portus version**: 2.3.5 (d1bc09b)
