### ISSUE TITLE
Portus example for compose insecure does not work (unable to configure authorization)

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [SUSE/Portus#1980]
### Description

I tried running Portus using the `docker-compose.insecure.yml` because its an isolated network, the registry container exits immediately. After providing a certificate (see below), the container stays up, but connection between portus and registry fails.
What `MACHINE_FQDN` do I have to provide? The FQDN of the docker host does not work (see below)

### Steps to reproduce

1. Clone Portus git repository, go to ./examples/compose
2. execute `docker-compose -f docker-compose.insecure.yml up -d`
3. Check container state `docker-compose ps` , `compose_registry_1` has exited

- **Expected behavior**: The registry should be running
- **Actual behavior**: Check using `docker-compose logs registry`
```
    docker-compose logs registry
    Attaching to compose_registry_1
    registry_1    | time="2018-09-27T17:11:30Z" level=info msg="debug server listening 0.0.0.0:5001"
    registry_1    | time="2018-09-27T17:11:30Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.7.6 instance.id=8ee4a246-f34f-486f-9bb5-cd727facf419 version=v2.6.2
    registry_1    | time="2018-09-27T17:11:30Z" level=info msg="configuring endpoint portus (http://172.17.0.1:3000/v2/webhooks/events), timeout=2s, headers=map[]" go.version=go1.7.6 instance.id=8ee4a246-f34f-486f-9bb5-cd727facf419 version=v2.6.2
    registry_1    | time="2018-09-27T17:11:30Z" level=info msg="redis not configured" go.version=go1.7.6 instance.id=8ee4a246-f34f-486f-9bb5-cd727facf419 version=v2.6.2
    registry_1    | time="2018-09-27T17:11:30Z" level=info msg="Starting upload purge in 39m0s" go.version=go1.7.6 instance.id=8ee4a246-f34f-486f-9bb5-cd727facf419 version=v2.6.2
    registry_1    | panic: unable to configure authorization (token): token auth requires at least one token signing root certificate
    registry_1    |
    registry_1    | goroutine 1 [running]:
    registry_1    | panic(0xb4ccc0, 0xc4203f8060)
    registry_1    |         /usr/local/go/src/runtime/panic.go:500 +0x1a1
    registry_1    | github.com/docker/distribution/registry/handlers.NewApp(0x1066800, 0xc42039db90, 0xc42038aa80, 0x1066800)
    registry_1    |         /go/src/github.com/docker/distribution/registry/handlers/app.go:302 +0x1b6a
    registry_1    | github.com/docker/distribution/registry.NewRegistry(0x7fc6967a1040, 0xc42039db90, 0xc42038aa80, 0xc, 0x0, 0x0)
    registry_1    |         /go/src/github.com/docker/distribution/registry/registry.go:86 +0x213
    registry_1    | github.com/docker/distribution/registry.glob..func1(0x108e180, 0xc42032f930, 0x1, 0x1)
    registry_1    |         /go/src/github.com/docker/distribution/registry/registry.go:55 +0x106
    registry_1    | github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x108e180, 0xc42032f8e0, 0x1, 0x1, 0x108e180, 0xc42032f8e0)
    registry_1    |         /go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x190
    registry_1    | github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x108e320, 0xc4201b7f40, 0xc4200001a0)
    registry_1    |         /go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0x3c3
    registry_1    | main.main()
    registry_1    |         /go/src/github.com/docker/distribution/cmd/registry/main.go:24 +0x2d
    registry_1    | time="2018-09-27T17:20:20Z" level=info msg="debug server listening 0.0.0.0:5001"
    registry_1    | time="2018-09-27T17:20:20Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.7.6 instance.id=9311d6e5-a682-430a-b0eb-70b61bf4a3db version=v2.6.2
    registry_1    | time="2018-09-27T17:20:20Z" level=info msg="configuring endpoint portus (http://172.17.0.1:3000/v2/webhooks/events), timeout=2s, headers=map[]" go.version=go1.7.6 instance.id=9311d6e5-a682-430a-b0eb-70b61bf4a3db version=v2.6.2
    registry_1    | time="2018-09-27T17:20:20Z" level=info msg="Starting upload purge in 26m0s" go.version=go1.7.6 instance.id=9311d6e5-a682-430a-b0eb-70b61bf4a3db version=v2.6.2
    registry_1    | time="2018-09-27T17:20:20Z" level=info msg="redis not configured" go.version=go1.7.6 instance.id=9311d6e5-a682-430a-b0eb-70b61bf4a3db version=v2.6.2
    registry_1    | panic: unable to configure authorization (token): unable to open token auth root certificate bundle file "/secrets/portus.crt": open /secrets/portus.crt: no such file or directory
    registry_1    |
    registry_1    | goroutine 1 [running]:
    registry_1    | panic(0xb4ccc0, 0xc4203f0060)
    registry_1    |         /usr/local/go/src/runtime/panic.go:500 +0x1a1
    registry_1    | github.com/docker/distribution/registry/handlers.NewApp(0x1066800, 0xc4203c0c90, 0xc420386a80, 0x1066800)
    registry_1    |         /go/src/github.com/docker/distribution/registry/handlers/app.go:302 +0x1b6a
    registry_1    | github.com/docker/distribution/registry.NewRegistry(0x7fa04477f040, 0xc4203c0c90, 0xc420386a80, 0xc, 0x0, 0x0)
    registry_1    |         /go/src/github.com/docker/distribution/registry/registry.go:86 +0x213
    registry_1    | github.com/docker/distribution/registry.glob..func1(0x108e180, 0xc42031fdd0, 0x1, 0x1)
    registry_1    |         /go/src/github.com/docker/distribution/registry/registry.go:55 +0x106
    registry_1    | github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x108e180, 0xc42031fd80, 0x1, 0x1, 0x108e180, 0xc42031fd80)
    registry_1    |         /go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x190
    registry_1    | github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x108e320, 0xc4201dbf40, 0xc4200001a0)
    registry_1    |         /go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0x3c3
    registry_1    | main.main()
    registry_1    |         /go/src/github.com/docker/distribution/cmd/registry/main.go:24 +0x2d

```

- Notice: `open /secrets/portus.crt: no such file or directory`
- The compose file has this bind mount: `- ./secrets:/secrets:ro`
- The [./secrets/](https://github.com/SUSE/Portus/tree/master/examples/compose/secrets) directory is empty, except an `.gitignore` containing `portus.*`
- try creating an empty file: `touch ./secrets/portus.crt` and run compose again, error message does not change... ?
- run `docker rm compose_registry_1` , run docker-compose up, check logs again:
```
registry_1    | time="2018-09-27T17:29:29Z" level=info msg="debug server listening 0.0.0.0:5001"
registry_1    | time="2018-09-27T17:29:29Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.7.6 instance.id=66bc9ffa-f529-4922-8e03-b0e5c38f3684 version=v2.6.2
registry_1    | time="2018-09-27T17:29:29Z" level=info msg="configuring endpoint portus (http://172.17.0.1:3000/v2/webhooks/events), timeout=2s, headers=map[]" go.version=go1.7.6 instance.id=66bc9ffa-f529-4922-8e03-b0e5c38f3684 version=v2.6.2
registry_1    | time="2018-09-27T17:29:29Z" level=info msg="redis not configured" go.version=go1.7.6 instance.id=66bc9ffa-f529-4922-8e03-b0e5c38f3684 version=v2.6.2
registry_1    | time="2018-09-27T17:29:29Z" level=info msg="Starting upload purge in 42m0s" go.version=go1.7.6 instance.id=66bc9ffa-f529-4922-8e03-b0e5c38f3684 version=v2.6.2
registry_1    | panic: unable to configure authorization (token): token auth requires at least one token signing root certificate
registry_1    |
registry_1    | goroutine 1 [running]:
registry_1    | panic(0xb4ccc0, 0xc4203c4050)
registry_1    |         /usr/local/go/src/runtime/panic.go:500 +0x1a1
registry_1    | github.com/docker/distribution/registry/handlers.NewApp(0x1066800, 0xc4203ca2d0, 0xc4203b2000, 0x1066800)
registry_1    |         /go/src/github.com/docker/distribution/registry/handlers/app.go:302 +0x1b6a
registry_1    | github.com/docker/distribution/registry.NewRegistry(0x7f65137c6068, 0xc4203ca2d0, 0xc4203b2000, 0xc, 0x0, 0x0)
registry_1    |         /go/src/github.com/docker/distribution/registry/registry.go:86 +0x213
registry_1    | github.com/docker/distribution/registry.glob..func1(0x108e180, 0xc420392ff0, 0x1, 0x1)
registry_1    |         /go/src/github.com/docker/distribution/registry/registry.go:55 +0x106
registry_1    | github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x108e180, 0xc420392fa0, 0x1, 0x1, 0x108e180, 0xc420392fa0)
registry_1    |         /go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x190
registry_1    | github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x108e320, 0xc4201e3f40, 0xc4200001a0)
registry_1    |         /go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0x3c3
registry_1    | main.main()
registry_1    |         /go/src/github.com/docker/distribution/cmd/registry/main.go:24 +0x2d
```

- try to generate some certificate, [like this](https://serverfault.com/questions/224122/what-is-crt-and-key-files-and-how-to-generate-them), putting it to `./secrets/portus.crt`
- **the registry container now stays up, why is this necessary for the "insecure" environment?**

Actually, for the following part, I could open another issue if you'd like:

- Create admin user in Portus -> OK
- Configuring the registry in Portus fails, no matter what ip or hostname I use (with Port :5000)
**`Errno::ECONNREFUSED: connection refused`**
(tried FQDN, short hostname, ipv4, 0.0.0.0
- `http://<docker-host>:5000/` is accessible in browser, so registry is running

**Do I have to set `MACHINE_FQDN` in `.env` ? This is not clear**
-> Tried using the docker host fqdn, short hostname, ip-adresses, does not make a difference

### Deployment information

**Deployment method**: Using the current [docker-compose.insecure.yml](https://github.com/SUSE/Portus/blob/master/examples/compose/docker-compose.insecure.yml)

**Configuration**:

```yml
version: "2"

services:
  portus:
    image: opensuse/portus:head
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      # SSL
      - PORTUS_CHECK_SSL_USAGE_ENABLED='false'

      # Since we have no nginx in insecure mode, portus have to
      # serve the static files
      - RAILS_SERVE_STATIC_FILES='true'
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro

  background:
    image: opensuse/portus:head
    depends_on:
      - portus
      - db
    environment:
      # Theoretically not needed, but cconfig's been buggy on this...
      - CCONFIG_PREFIX=PORTUS
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      - PORTUS_BACKGROUND=true
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro

  db:
    image: library/mariadb:10.0.23
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      - MYSQL_DATABASE=portus_production

      # Again, the password shouldn't be handled like this.
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - /var/lib/portus/mariadb:/var/lib/mysql

  registry:
    image: library/registry:2.6
    environment:
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: http://${MACHINE_FQDN}:3000/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: ${MACHINE_FQDN}:5000
      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /secrets/portus.crt

      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: http://${MACHINE_FQDN}:3000/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
      - /var/lib/portus/registry:/var/lib/registry
      - ./secrets:/secrets:ro
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
    ports:
      - 5000:5000
      - 5001:5001 # required to access debug service
    links:
- portus:portus
```

**Portus version**: latest docker image
