### ISSUE TITLE
background_1 restart when complete first setup (":"UNAUTHORIZED","message":"authentication required")

### ISSUE THREAD

**Issue by Nitrosito** [SUSE/Portus#1992]
### Description
When I complete the wizard to add a record the background container restarts, I leave the log:

```log
nginx_1       | 172.20.0.1 - portus [04/Oct/2018:14:35:49 +0000] "GET /v2/token?account=portus&scope=registry%3Acatalog%3A%2A&service=registry.xx.org HTTP/1.1" 200 665 "-" "Ruby"
registry_1    | time="2018-10-04T14:35:49Z" level=debug msg="authorizing request" go.version=go1.7.6 http.request.host="registry.x.org:5000" http.request.id=c07a4354-5bf0-42d1-839e-c1d969b45def http.request.method=GET http.request.remoteaddr="172.20.0.1:47972" http.request.uri="/v2/_catalog?n=100" http.request.useragent=Ruby instance.id=4ee8ae01-84ba-41ea-b9d9-aa3b312c992d version=v2.6.2 
registry_1    | time="2018-10-04T14:35:49Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.7.6 http.request.host="registry.xx.org:5000" http.request.id=c07a4354-5bf0-42d1-839e-c1d969b45def http.request.method=GET http.request.remoteaddr="172.20.0.1:47972" http.request.uri="/v2/_catalog?n=100" http.request.useragent=Ruby instance.id=4ee8ae01-84ba-41ea-b9d9-aa3b312c992d version=v2.6.2 
registry_1    | 172.20.0.1 - - [04/Oct/2018:14:35:49 +0000] "GET /v2/_catalog?n=100 HTTP/1.1" 401 145 "" "Ruby"
registryportus_background_1 exited with code 1
background_1  | [Mailer config] Host:     registry.xx.org
background_1  | [Mailer config] Protocol: https://
background_1  | [Database] Not ready yet. Waiting...
background_1  | [Database] Not ready yet. Waiting...
background_1  | [Initialization] Running: 'Registry events', 'Security scanning', 'Registry synchronization'
background_1  | [Mailer config] Host:     registry.xx.org
background_1  | [Mailer config] Protocol: https://
background_1  | [Initialization] Running: 'Registry events', 'Security scanning', 'Registry synchronization'
background_1  | /srv/Portus/lib/portus/registry_client.rb:182:in `get_page': Something went wrong while fetching the catalog Response: [401] - {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Class":"","Name":"catalog","Action":"*"}]}]} (Portus::RegistryClient::RegistryError)
background_1  | 	from /srv/Portus/lib/portus/registry_client.rb:160:in `paged_response'
background_1  | 	from /srv/Portus/lib/portus/registry_client.rb:107:in `catalog'
background_1  | 	from /srv/Portus/lib/portus/background/sync.rb:63:in `block in execute!'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `each'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `block in find_each'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:124:in `find_in_batches'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:50:in `find_each'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/querying.rb:9:in `find_each'
background_1  | 	from /srv/Portus/lib/portus/background/sync.rb:62:in `execute!'
background_1  | 	from /srv/Portus/bin/background.rb:56:in `block (2 levels) in <top (required)>'
background_1  | 	from /srv/Portus/bin/background.rb:54:in `each'
background_1  | 	from /srv/Portus/bin/background.rb:54:in `each_with_index'
background_1  | 	from /srv/Portus/bin/background.rb:54:in `block in <top (required)>'
background_1  | 	from /srv/Portus/bin/background.rb:53:in `loop'
background_1  | 	from /srv/Portus/bin/background.rb:53:in `<top (required)>'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `load'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `<top (required)>'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:90:in `runner'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
background_1  | 	from bin/rails:12:in `require'
background_1  | 	from bin/rails:12:in `<main>'
background_1  | RuntimeError: Something went wrong while invoking: /srv/Portus/vendor/bundle/ruby/2.5.0/bin/bundler.ruby2.5 exec rails r /srv/Portus/bin/background.rb
background_1  |   /srv/Portus/packaging/suse/portusctl/lib/runner.rb:12:in `exec'
background_1  |   /srv/Portus/packaging/suse/portusctl/lib/runner.rb:34:in `block in bundler_exec'
background_1  |   /srv/Portus/packaging/suse/portusctl/lib/runner.rb:30:in `chdir'
background_1  |   /srv/Portus/packaging/suse/portusctl/lib/runner.rb:30:in `bundler_exec'
background_1  |   /srv/Portus/packaging/suse/portusctl/lib/cli.rb:286:in `exec'
background_1  |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
background_1  |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
background_1  |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
background_1  |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
background_1  |   packaging/suse/portusctl/bin/portusctl:6:in `<top (required)>'
background_1  | bundler: failed to load command: packaging/suse/portusctl/bin/portusctl (packaging/suse/portusctl/bin/portusctl)
background_1  | [Mailer config] Host:     registry.xx.org
background_1  | [Mailer config] Protocol: https://
background_1  | [Initialization] Running: 'Registry events', 'Security scanning', 'Registry synchronization'
background_1  | /srv/Portus/lib/portus/registry_client.rb:182:in `get_page': Something went wrong while fetching the catalog Response: [401] - {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Class":"","Name":"catalog","Action":"*"}]}]} (Portus::RegistryClient::RegistryError)
background_1  | 	from /srv/Portus/lib/portus/registry_client.rb:160:in `paged_response'
background_1  | 	from /srv/Portus/lib/portus/registry_client.rb:107:in `catalog'
background_1  | 	from /srv/Portus/lib/portus/background/sync.rb:63:in `block in execute!'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `each'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `block in find_each'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:124:in `find_in_batches'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:50:in `find_each'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/querying.rb:9:in `find_each'
background_1  | 	from /srv/Portus/lib/portus/background/sync.rb:62:in `execute!'
background_1  | 	from /srv/Portus/bin/background.rb:56:in `block (2 levels) in <top (required)>'
background_1  | 	from /srv/Portus/bin/background.rb:54:in `each'
background_1  | 	from /srv/Portus/bin/background.rb:54:in `each_with_index'
background_1  | 	from /srv/Portus/bin/background.rb:54:in `block in <top (required)>'
background_1  | 	from /srv/Portus/bin/background.rb:53:in `loop'
background_1  | 	from /srv/Portus/bin/background.rb:53:in `<top (required)>'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `load'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `<top (required)>'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:90:in `runner'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
background_1  | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
background_1  | 	from bin/rails:12:in `require'
background_1  | 	from bin/rails:12:in `<main>'
background_1  | bundler: failed to load command: packaging/suse/portusctl/bin/portusctl (packaging/suse/portusctl/bin/portusctl)
background_1  | RuntimeError: Something went wrong while invoking: /srv/Portus/vendor/bundle/ruby/2.5.0/bin/bundler.ruby2.5 exec rails r /srv/Portus/bin/background.rb
background_1  |   /srv/Portus/packaging/suse/portusctl/lib/runner.rb:12:in `exec'
background_1  |   /srv/Portus/packaging/suse/portusctl/lib/runner.rb:34:in `block in bundler_exec'
background_1  |   /srv/Portus/packaging/suse/portusctl/lib/runner.rb:30:in `chdir'
background_1  |   /srv/Portus/packaging/suse/portusctl/lib/runner.rb:30:in `bundler_exec'
background_1  |   /srv/Portus/packaging/suse/portusctl/lib/cli.rb:286:in `exec'
background_1  |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
background_1  |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
background_1  |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
background_1  |   /srv/Portus/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
background_1  |   packaging/suse/portusctl/bin/portusctl:6:in `<top (required)>'
```

I think the error is relation with:
```
background_1  | /srv/Portus/lib/portus/registry_client.rb:182:in `get_page': Something went wrong while fetching the catalog Response: [401] - {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Class":"","Name":"catalog","Action":"*"}]}]} (Portus::RegistryClient::RegistryError)
```

**Configuration**:

- In a container, deploy with docker compose up --build:
  - Using the development `docker-compose.yml` 

```yml
version: "2"

services:
  portus:
    image: opensuse/portus:2.3.6
    restart: unless-stopped
    environment:
      - CCONFIG_PREFIX=PORTUS
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}
      - PORTUS_SECURITY_CLAIR_SERVER=http://clair:6060

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      # SSL
      - PORTUS_PUMA_TLS_KEY=/certificates/portus.key
      - PORTUS_PUMA_TLS_CERT=/certificates/portus.crt

      # NGinx is serving the assets instead of Puma. If you want to change this,
      # uncomment this line.
      #- RAILS_SERVE_STATIC_FILES='true'
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro
      - static:/srv/Portus/public

  background:
    image: opensuse/portus:2.3.6
    restart: unless-stopped
    depends_on:
      - portus
      - db
    environment:
      # Theoretically not needed, but cconfig's been buggy on this...
      - CCONFIG_PREFIX=PORTUS
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}
      - PORTUS_SECURITY_CLAIR_SERVER=http://clair:6060

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      - PORTUS_BACKGROUND=true
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro

  db:
    image: library/mariadb:10.0.23
    restart: unless-stopped
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      - MYSQL_DATABASE=portus_production

      # Again, the password shouldn't be handled like this.
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
     #- /var/lib/portus/mariadb:/var/lib/mysql
     - ./portus/mariadb:/var/lib/mysql

  registry:
    image: library/registry:2.6.2
    command: ["/bin/sh", "/etc/docker/registry/init"]
    restart: unless-stopped
    environment:
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: https://${MACHINE_FQDN}/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /secrets/portus.crt
      REGISTRY_HTTP_SECRET:xxesregistrysecret

      # SSL
      REGISTRY_HTTP_TLS_CERTIFICATE: /secrets/portus.crt
      REGISTRY_HTTP_TLS_KEY: /secrets/portus.key

      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://${MACHINE_FQDN}/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
      #- /var/lib/portus/registry:/var/lib/registry
      - ./registry/data/:/var/lib/registry
      - ./secrets:/secrets:ro
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
      - ./registry/init:/etc/docker/registry/init:ro
    ports:
      - 5000:5000
      - 5001:5001 # required to access debug service
    links:
      - portus:portus

  nginx:
    image: library/nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./secrets:/secrets:ro
      - static:/srv/Portus/public:ro
    ports:
      - 80:80
      - 443:443
    links:
      - registry:registry
      - portus:portus

  clair:
    image: quay.io/coreos/clair:v2.0.1
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "6060-6061:6060-6061"
    volumes:
      - /tmp:/tmp
      - ./clair/clair.yml:/clair.yml
    command: [-config, /clair.yml]

  postgres:
    image: library/postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: portus

volumes:
  static:
    driver: local

```

my Nginx.conf:
```

events {
  worker_connections 1024;
}

http {
  include       mime.types;
  default_type  application/octet-stream;
  charset       UTF-8;

  # Some basic config.
  server_tokens off;
  sendfile      on;
  tcp_nopush    on;
  tcp_nodelay   on;

  # On timeouts.
  keepalive_timeout     65;
  client_header_timeout 240;
  client_body_timeout   240;
  fastcgi_read_timeout  249;
  reset_timedout_connection on;

  ## Set a variable to help us decide if we need to add the
  ## 'Docker-Distribution-Api-Version' header.
  ## The registry always sets this header.
  ## In the case of nginx performing auth, the header will be unset
  ## since nginx is auth-ing before proxying.
  map $upstream_http_docker_distribution_api_version $docker_distribution_api_version {
	'' 'registry/2.0';
  }

  upstream portus {
    least_conn;
    server portus:3000 max_fails=3 fail_timeout=15s;
  }

  upstream registry {
    least_conn;
    server registry:5000 max_fails=3 fail_timeout=15s;
  }

  server {
    listen 443 ssl http2;
    #server_name 172.17.0.1;
    server_name registry.xx.org;
    root /srv/Portus/public;

    ##
    # SSL

    ssl on;

    # Certificates
    ssl_certificate /secrets/portus.crt;
    ssl_certificate_key /secrets/portus.key;

    # Enable session resumption to improve https performance
    #
    # http://vincent.bernat.im/en/blog/2011-ssl-session-reuse-rfc5077.html
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    # Enables server-side protection from BEAST attacks
    # http://blog.ivanristic.com/2013/09/is-beast-still-a-threat.html
    ssl_prefer_server_ciphers on;

    # Disable SSLv3 (enabled by default since nginx 0.8.19)
    # since it's less secure than TLS
    # http://en.wikipedia.org/wiki/Secure_Sockets_Layer#SSL_3.0
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

    # Ciphers chosen for forward secrecy and compatibility.
    #
    # http://blog.ivanristic.com/2013/08/configuring-apache-nginx-and-openssl-for-forward-secrecy.html
    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';

    ##
    # Docker-specific stuff.

    proxy_set_header Host $http_host;   # required for Docker client sake
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Scheme $scheme;

    # disable any limits to avoid HTTP 413 for large image uploads
    client_max_body_size 0;

    # required to avoid HTTP 411: see Issue #1486
    # (https://github.com/docker/docker/issues/1486)
    chunked_transfer_encoding on;

    ##
    # Custom headers.

    # Adding HSTS[1] (HTTP Strict Transport Security) to avoid SSL stripping[2].
    #
    # [1] https://developer.mozilla.org/en-US/docs/Security/HTTP_Strict_Transport_Security
    # [2] https://en.wikipedia.org/wiki/SSL_stripping#SSL_stripping
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";

    # Don't allow the browser to render the page inside a frame or iframe
    # and avoid Clickjacking. More in the following link:
    #
    # https://developer.mozilla.org/en-US/docs/HTTP/X-Frame-Options
    add_header X-Frame-Options DENY;

    # Disable content-type sniffing on some browsers.
    add_header X-Content-Type-Options nosniff;

    # This header enables the Cross-site scripting (XSS) filter built into
    # most recent web browsers. It's usually enabled by default anyway, so the
    # role of this header is to re-enable the filter for this particular
    # website if it was disabled by the user.
    add_header X-XSS-Protection "1; mode=block";

    # Add header for IE in compatibility mode.
    add_header X-UA-Compatible "IE=edge";

	# Redirect (most) requests to /v2/* to the Docker Registry
	location /v2/ {
	  # Do not allow connections from docker 1.5 and earlier
	  # docker pre-1.6.0 did not properly set the user agent on ping, catch "Go *" user agents
	  if ($http_user_agent ~ "^(docker\/1\.(3|4|5(?!\.[0-9]-dev))|Go ).*$" ) {
        return 404;
      }

      ## If $docker_distribution_api_version is empty, the header will not be added.
      ## See the map directive above where this variable is defined.
      add_header 'Docker-Distribution-Api-Version' $docker_distribution_api_version always;

      proxy_pass https://registry;
      proxy_set_header Host $http_host;   # required for docker client's sake
      proxy_set_header X-Real-IP $remote_addr; # pass on real client's IP
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_read_timeout 900;
      proxy_buffering on;
	}

	# Portus needs to handle /v2/token for authentication
	location = /v2/token {
      proxy_pass https://portus;
      proxy_set_header Host $http_host;   # required for docker client's sake
      proxy_set_header X-Real-IP $remote_addr; # pass on real client's IP
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_read_timeout 900;
      proxy_buffering on;
    }

	# Portus needs to handle /v2/webhooks/events for notifications
	location = /v2/webhooks/events {
      proxy_pass https://portus;
      proxy_set_header Host $http_host;   # required for docker client's sake
      proxy_set_header X-Real-IP $remote_addr; # pass on real client's IP
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_read_timeout 900;
      proxy_buffering on;
    }

    # Assets are mapped inside of /srv/Portus/public from a shared volume.
    location ~ ^/(assets)/ {
      access_log  off;
      gzip_static on;
      expires     max;
      add_header  Cache-Control public;
      add_header  Last-Modified "";
      add_header  ETag "";
      break;
    }

	# Portus handles everything else for the UI
	location / {
      try_files $uri/index.html $uri.html $uri @portus;
    }

    location @portus {
      proxy_pass https://portus;
      proxy_set_header Host $http_host;   # required for docker client's sake
      proxy_set_header X-Real-IP $remote_addr; # pass on real client's IP
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_read_timeout 900;
      proxy_buffering on;
    }
  }
} 
```

My registry config.yml
```
version: 0.1
loglevel: debug
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: :5000
  tls:
    certificate: /secrets/portus.crt
    key: /secrets/portus.key
auth:
  token:
    realm: https://registry.xx.org/v2/token
    service: registry.xx.org:5000
    issuer: sistemas.xx
    rootcertbundle: /secrets/portus.crt
notifications:
  endpoints:
    - name: portus
      url: https://registry.xx.org/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s
```

my .env:
```

MACHINE_FQDN=registry.xx.org
SECRET_KEY_BASE=a4ff3269c363b785f7417bbf39b952a2256718bd3818bce5c506b52e1943814dc78d87c71c33d2d472528c43b55cccf80879b42c3d20f808af77e7c30d852684
PORTUS_PASSWORD=12341234
DATABASE_PASSWORD=portus
```

**Portus version**:  2.3.5@35b9c801bf5275537a8bd8152d2f5769d6c24b09

**Comment by mssola** [comment]
> What does that section do? Add authentication in REGISTER?

What it does is to inform the registry that there is an authorization service which is located in `https://registry.xxx.org/v2/token`. 

> If I do not put it ... can everyone do PUSH? Or are permits handled by PORTUS?

You will have a docker registry without an authorization service in place. Thus, any action will be permitted.

I've taken a quick look at your config, and something smells fishy on your registry configuration:

```yml
auth:
  token:
    realm: https://registry.xxx.org/v2/token
    service: registry.xxx.org:5000
    issuer: sistemas.xxx    # <- NOTE: this usually is the same FQDN as the realm.
    rootcertbundle: /secrets/portus.crt
```

The issuer section of the registry specifies who issued the certificate used to authenticate with Portus. Also, note that the configuration you are passing is in clear conflict with the configuration from the `docker-compose.yml` file (see the `REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}` environment variable).
