### ISSUE TITLE
500 on "/" after updating from 2.3 -> 2.4

### ISSUE THREAD

**Issue by Strum355** [SUSE/Portus#1993]
### Description

Using docker-compose file, updated image tag from 2.3 to 2.4
Updated config-local.yml with new LDAP config layout
Ran `docker-compose up -d`
`portus` container logs:
```
Processing by Auth::SessionsController#new as HTML,
    28:     meta content="/favicon/browserconfig.xml" name="msapplication-config",
Started GET "/" for 86.42.32.156 at 2018-10-05 17:35:42 +0000,
  app/controllers/auth/sessions_controller.rb:16:in `new',
Completed 500 Internal Server Error in 82ms (Views: 80.3ms | ActiveRecord: 0.0ms),
  Rendered errors/_status_title.html.slim (7.0ms),
  Rendered errors/500.html.erb within layouts/errors (2.4ms),
  Parameters: {"status"=>"500"},
Processing by ErrorsController#show as HTML,
  app/views/layouts/authentication.html.slim:31:in `_app_views_layouts_authentication_html_slim___2644840005764363694_48009680',
    33:     = yield :js_header,
    34: ,
    32:     = javascript_include_tag(*webpack_asset_paths("unauthenticated"),  defer: true),
    31:     = javascript_include_tag(*webpack_asset_paths("vendors~application~unauthenticated"), defer: true),
    30: ,
    29:     meta content="#205683" name="theme-color",
ActionView::Template::Error (Can't find entry point 'vendors~application~unauthenticated' in webpack manifest):,
,
  app/middleware/catch_json_parse_errors.rb:11:in `call',
Completed 401 Unauthorized in 325ms (ActiveRecord: 2.4ms),
  Rendered devise/sessions/new.html.slim within layouts/authentication (198.1ms),
  User Load (1.2ms)  SELECT `users`.* FROM `users` WHERE (`users`.`username` != 'portus'),
  Rendered shared/_notifications.html.slim (58.1ms),
  Rendered shared/_notification.html.slim (32.1ms),
   (1.2ms)  SELECT COUNT(*) FROM `users` WHERE (`users`.`username` != 'portus')
```

### Steps to reproduce

See above

- **Expected behavior**: Presented with login page
- **Actual behavior**: Got the 500 page and the above log

### Deployment information

**Deployment method**: 
Using examples/compose/docker-compose.yml as a base
Had working configuration with 2.3

**Configuration**:
```yml
email:
  from: portus@example.com
  name: Portus
  reply_to: no-reply@example.com
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    domain: example.com
    ssl_tls: ''
    enable_starttls_auto: false
    openssl_verify_mode: none
    ca_path: ''
    ca_file: ''
    user_name: username@example.com
    password: "****"
    authentication: login
gravatar:
  enabled: true
delete:
  enabled: true
  contributors: false
  garbage_collector:
    enabled: false
    older_than: 30
    tag: ''
ldap:
  enabled: true
  hostname: ldap.<domain>.<tld>
  port: 390
  timeout: 5
  encryption:
    method: ''
    options:
      ca_file: ''
      ssl_version: ''
  base: <basedn>
  filter: ''
  uid: uid
  authentication:
    enabled: true
    bind_dn: <binddn>
    password: "****"
  guess_email:
    enabled: false
    attr: ''
oauth:
  local_login:
    enabled: true
  google_oauth2:
    enabled: false
    id: ''
    secret: ''
    domain: ''
    options:
      hd: ''
  open_id:
    enabled: false
    identifier: ''
    domain: ''
  github:
    enabled: false
    client_id: ''
    client_secret: ''
    organization: ''
    team: ''
    domain: ''
  gitlab:
    enabled: false
    application_id: ''
    secret: ''
    group: ''
    domain: ''
    server: ''
  bitbucket:
    enabled: false
    key: ''
    secret: ''
    domain: ''
    options:
      team: ''
first_user_admin:
  enabled: true
signup:
  enabled: false
check_ssl_usage:
  enabled: true
registry:
  jwt_expiration_time:
    value: 30
  catalog_page:
    value: 100
  timeout:
    value: 2
  read_timeout:
    value: 120
machine_fqdn:
  value: docker.<domain>.<tld>
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: true
  create_team:
    enabled: true
  manage_team:
    enabled: true
  create_namespace:
    enabled: true
  manage_namespace:
    enabled: true
  create_webhook:
    enabled: true
  manage_webhook:
    enabled: true
  push_images:
    policy: allow-teams
security:
  clair:
    server: ''
    health_port: 6061
    timeout: 900
  zypper:
    server: ''
  dummy:
    server: ''
anonymous_browsing:
  enabled: false
background:
  registry:
    enabled: true
  sync:
    enabled: true
    strategy: initial
pagination:
  limit: 10
  before_after: 2

Portus version: 2.4.0@2.4.0
```

**Comment by mssola** [comment]
@vitoravelino could you take a look at this? It looks javascript-related :wink:

**Comment by vitoravelino** [comment]
@Strum355 What's the content of `public/assets/webpack/` folder? What's the content of `manifest.json`?

**Comment by Strum355** [comment]
![image](https://user-images.githubusercontent.com/18282288/46802173-878e5880-cd54-11e8-95ca-268db27e1b22.png)
```json
{
  "errors": [
    
  ],
  "warnings": [
    
  ],
  "version": "2.2.1",
  "hash": "47dd9ab30388f7506997",
  "publicPath": "\/assets\/webpack\/",
  "assetsByChunkName": {
    "application": [
      "application-07d1c7069b652505eace.js",
      "application-07d1c7069b652505eace.js.map"
    ]
  },
  "assets": [
    {
      "name": "application-07d1c7069b652505eace.js",
      "size": 470667,
      "chunks": [
        0
      ],
      "chunkNames": [
        "application"
      ],
      "emitted": true
    },
    {
      "name": "application-07d1c7069b652505eace.js.map",
      "size": 2894436,
      "chunks": [
        0
      ],
      "chunkNames": [
        "application"
      ],
      "emitted": true
    },
    {
      "name": "application-07d1c7069b652505eace.js.gz",
      "size": 131197,
      "chunks": [
        
      ],
      "chunkNames": [
        
      ],
      "emitted": true
    },
    {
      "name": "application-07d1c7069b652505eace.js.map.gz",
      "size": 641646,
      "chunks": [
        
      ],
      "chunkNames": [
        
      ],
      "emitted": true
    },
    {
      "name": "manifest.json",
      "size": 0,
      "chunks": [
        
      ],
      "chunkNames": [
        
      ]
    }
  ],
  "entrypoints": {
    "application": {
      "chunks": [
        0
      ],
      "assets": [
        "application-07d1c7069b652505eace.js",
        "application-07d1c7069b652505eace.js.map"
      ]
    }
  },
  "children": [
    
  ]
}
```
Pretty printed json

**Comment by vitoravelino** [comment]
That's not was is expected for 2.4. I guess it's related to the same problem stated in #1902. Try `docker-compose down -v` before upgrading as mentioned on https://github.com/SUSE/Portus/issues/1902#issuecomment-408155138.

**Comment by Strum355** [comment]
LDAP settings (censored):

```yaml
ldap:
  enabled: true

  hostname: "<host>"
  port: <port>
  timeout: 5

  encryption:
    method: ""
    options:
      ca_file: ""
      ssl_version: ""

  base: "<base dn>"

  filter: ""

  uid: "uid"

  authentication:
    enabled: true
    bind_dn: "<bind dn>"
    password: "<pass>"
```

manifest.json:
```json
{
  "errors": [
    
  ],
  "warnings": [
    
  ],
  "version": "4.16.1",
  "hash": "5122079157dc0c25bbf8",
  "publicPath": "\/assets\/webpack\/",
  "outputPath": "\/home\/abuild\/rpmbuild\/BUILD\/Portus-v2.4\/public\/assets\/webpack",
  "assetsByChunkName": {
    "vendors~application~unauthenticated": [
      "vendors~application~unauthenticated-4cad68655ebceb1a5aa0.chunk.js",
      "vendors~application~unauthenticated-4cad68655ebceb1a5aa0.chunk.js.map"
    ],
    "application": [
      "application-dd2fe7d7318238832be4.js",
      "application-dd2fe7d7318238832be4.js.map"
    ],
    "unauthenticated": [
      "unauthenticated-a4484868868f95b5134b.js",
      "unauthenticated-a4484868868f95b5134b.js.map"
    ],
    "vendors~application": [
      "vendors~application-eb2091f277cc03fcc755.chunk.js",
      "vendors~application-eb2091f277cc03fcc755.chunk.js.map"
    ]
  },
  "assets": [
    {
      "name": "unauthenticated-a4484868868f95b5134b.js.gz",
      "size": 3272,
      "chunks": [
        
      ],
      "chunkNames": [
        
      ]
    },
    {
      "name": "vendors~application~unauthenticated-4cad68655ebceb1a5aa0.chunk.js",
      "size": 210878,
      "chunks": [
        0
      ],
      "chunkNames": [
        "vendors~application~unauthenticated"
      ],
      "emitted": true
    },
    {
      "name": "unauthenticated-a4484868868f95b5134b.js",
      "size": 9829,
      "chunks": [
        2
      ],
      "chunkNames": [
        "unauthenticated"
      ],
      "emitted": true
    },
    {
      "name": "vendors~application-eb2091f277cc03fcc755.chunk.js",
      "size": 109304,
      "chunks": [
        3
      ],
      "chunkNames": [
        "vendors~application"
      ],
      "emitted": true
    },
    {
      "name": "vendors~application~unauthenticated-4cad68655ebceb1a5aa0.chunk.js.map",
      "size": 1019956,
      "chunks": [
        0
      ],
      "chunkNames": [
        "vendors~application~unauthenticated"
      ],
      "emitted": true
    },
    {
      "name": "application-dd2fe7d7318238832be4.js.map",
      "size": 563036,
      "chunks": [
        1
      ],
      "chunkNames": [
        "application"
      ],
      "emitted": true
    },
    {
      "name": "unauthenticated-a4484868868f95b5134b.js.map",
      "size": 31797,
      "chunks": [
        2
      ],
      "chunkNames": [
        "unauthenticated"
      ],
      "emitted": true
    },
    {
      "name": "vendors~application-eb2091f277cc03fcc755.chunk.js.map",
      "size": 362704,
      "chunks": [
        3
      ],
      "chunkNames": [
        "vendors~application"
      ],
      "emitted": true
    },
    {
      "name": "manifest.json",
      "size": 0,
      "chunks": [
        
      ],
      "chunkNames": [
        
      ]
    },
    {
      "name": "application-dd2fe7d7318238832be4.js",
      "size": 176292,
      "chunks": [
        1
      ],
      "chunkNames": [
        "application"
      ],
      "emitted": true
    },
    {
      "name": "unauthenticated-a4484868868f95b5134b.js.map.gz",
      "size": 9590,
      "chunks": [
        
      ],
      "chunkNames": [
        
      ]
    },
    {
      "name": "manifest.json.gz",
      "size": 568,
      "chunks": [
        
      ],
      "chunkNames": [
        
      ]
    },
    {
      "name": "application-dd2fe7d7318238832be4.js.gz",
      "size": 32252,
      "chunks": [
        
      ],
      "chunkNames": [
        
      ]
    },
    {
      "name": "vendors~application-eb2091f277cc03fcc755.chunk.js.gz",
      "size": 30958,
      "chunks": [
        
      ],
      "chunkNames": [
        
      ]
    },
    {
      "name": "vendors~application~unauthenticated-4cad68655ebceb1a5aa0.chunk.js.gz",
      "size": 73279,
      "chunks": [
        
      ],
      "chunkNames": [
        
      ]
    },
    {
      "name": "application-dd2fe7d7318238832be4.js.map.gz",
      "size": 94060,
      "chunks": [
        
      ],
      "chunkNames": [
        
      ]
    },
    {
      "name": "vendors~application-eb2091f277cc03fcc755.chunk.js.map.gz",
      "size": 91655,
      "chunks": [
        
      ],
      "chunkNames": [
        
      ]
    },
    {
      "name": "vendors~application~unauthenticated-4cad68655ebceb1a5aa0.chunk.js.map.gz",
      "size": 294354,
      "chunks": [
        
      ],
      "chunkNames": [
        
      ]
    }
  ],
  "filteredAssets": 0,
  "entrypoints": {
    "application": {
      "chunks": [
        0,
        3,
        1
      ],
      "assets": [
        "vendors~application~unauthenticated-4cad68655ebceb1a5aa0.chunk.js",
        "vendors~application~unauthenticated-4cad68655ebceb1a5aa0.chunk.js.map",
        "vendors~application-eb2091f277cc03fcc755.chunk.js",
        "vendors~application-eb2091f277cc03fcc755.chunk.js.map",
        "application-dd2fe7d7318238832be4.js",
        "application-dd2fe7d7318238832be4.js.map"
      ],
      "children": {
        
      },
      "childAssets": {
        
      }
    },
    "unauthenticated": {
      "chunks": [
        0,
        2
      ],
      "assets": [
        "vendors~application~unauthenticated-4cad68655ebceb1a5aa0.chunk.js",
        "vendors~application~unauthenticated-4cad68655ebceb1a5aa0.chunk.js.map",
        "unauthenticated-a4484868868f95b5134b.js",
        "unauthenticated-a4484868868f95b5134b.js.map"
      ],
      "children": {
        
      },
      "childAssets": {
        
      }
    }
  },
  "namedChunkGroups": {
    "application": {
      "chunks": [
        0,
        3,
        1
      ],
      "assets": [
        "vendors~application~unauthenticated-4cad68655ebceb1a5aa0.chunk.js",
        "vendors~application~unauthenticated-4cad68655ebceb1a5aa0.chunk.js.map",
        "vendors~application-eb2091f277cc03fcc755.chunk.js",
        "vendors~application-eb2091f277cc03fcc755.chunk.js.map",
        "application-dd2fe7d7318238832be4.js",
        "application-dd2fe7d7318238832be4.js.map"
      ],
      "children": {
        
      },
      "childAssets": {
        
      }
    },
    "unauthenticated": {
      "chunks": [
        0,
        2
      ],
      "assets": [
        "vendors~application~unauthenticated-4cad68655ebceb1a5aa0.chunk.js",
        "vendors~application~unauthenticated-4cad68655ebceb1a5aa0.chunk.js.map",
        "unauthenticated-a4484868868f95b5134b.js",
        "unauthenticated-a4484868868f95b5134b.js.map"
      ],
      "children": {
        
      },
      "childAssets": {
        
      }
    }
  },
  "children": [
    
  ]
}
```
