### ISSUE TITLE
2.4 - Error 500 at /admin/registries/new

### ISSUE THREAD

**Issue by branzo** [SUSE/Portus#1996]
### /admin/registries/new
It seems that with a newly instanced stack (Docker compose), after creating the first admin account, a 500 error is thrown back at the user while being redirected at the registry creation step (https://regg.my-reg-hostname/admin/registries/new).

Docker image version:
```
REPOSITORY                  TAG                 IMAGE ID                                                                  CREATED             SIZE
opensuse/portus             2.4                 sha256:3b7629ab1e0bffc79460103e6eec3fbba7485ea72b440c6ee104123158f3ddd9   29 hours ago        245MB
```

### Steps to reproduce

1. Bring up the stack, let portus create the "portus" user
2. Open registry, create admin
3. 500 Error

- **Expected behavior**: registry configuration
- **Actual behavior**: error 500, have a look at the logs:

```
portus_1    | Adding the "portus" user
portus_1    |    (0.5ms)  BEGIN
portus_1    |   User Exists (2.2ms)  SELECT  1 AS one FROM `users` WHERE `users`.`email` = BINARY 'portus@portus.com' LIMIT 1
portus_1    |   User Exists (0.6ms)  SELECT  1 AS one FROM `users` WHERE `users`.`username` = BINARY 'portus' LIMIT 1
portus_1    |   Namespace Exists (0.9ms)  SELECT  1 AS one FROM `namespaces` WHERE `namespaces`.`name` = 'portus' LIMIT 1
portus_1    |   SQL (0.7ms)  INSERT INTO `users` (`username`, `encrypted_password`, `email`, `admin`, `created_at`, `updated_at`) VALUES ('portus', '$2a$10$L3.TSp3GXa0toOoqWY4KyuuQM992Tn.m57x/1SpjNIqo0PdI.s/dW', 'portus@portus.com', 1, '2018-10-10 13:00:48', '2018-10-10 13:00:48')                                                                            
portus_1    |    (0.5ms)  SELECT COUNT(*) FROM `registries`
portus_1    |    (0.4ms)  COMMIT
portus_1    | Database ready
portus_1    | [65] Puma starting in cluster mode...
portus_1    | [65] * Version 3.10.0 (ruby 2.5.0-p0), codename: Russell's Teapot
portus_1    | [65] * Min threads: 1, max threads: 4
portus_1    | [65] * Environment: production
portus_1    | [65] * Process workers: 6
portus_1    | [65] * Preloading application
portus_1    | [Mailer config] Host:     regg.studiostorti.com
portus_1    | [Mailer config] Protocol: https://
portus_1    |   User Exists (0.3ms)  SELECT  1 AS one FROM `users` WHERE `users`.`username` = 'portus' LIMIT 1
portus_1    |   User Load (0.8ms)  SELECT  `users`.* FROM `users` WHERE `users`.`username` = 'portus' LIMIT 1
portus_1    |    (0.6ms)  BEGIN
portus_1    |   SQL (16.9ms)  UPDATE `users` SET `encrypted_password` = '$2a$10$EUP3p/OI81ptrrWA3tNFEODuAlWfLMWobUN3xVvdD2q6xZnFvL9Bq', `updated_at` = '2018-10-10 13:01:09' WHERE `users`.`id` = 1
portus_1    |    (0.4ms)  COMMIT
portus_1    |   User Exists (0.8ms)  SELECT  1 AS one FROM `users` WHERE `users`.`username` = 'portus' LIMIT 1
portus_1    |    (0.3ms)  SELECT COUNT(*) FROM `registries`
[...]
portus_1    | [65] * Listening on ssl://0.0.0.0:3000?cert=/certificates/bundle.pem&key=/certificates/cert.key&verify_mode=none
portus_1    | [65] Use Ctrl-C to stop
portus_1    | [65] - Worker 0 (pid: 68) booted, phase: 0
portus_1    | [65] - Worker 1 (pid: 72) booted, phase: 0
portus_1    | [65] - Worker 2 (pid: 76) booted, phase: 0
portus_1    | [65] - Worker 3 (pid: 86) booted, phase: 0
portus_1    | [65] - Worker 4 (pid: 95) booted, phase: 0
portus_1    | [65] - Worker 5 (pid: 99) booted, phase: 0
[...]
portus_1    | Started POST "/users" for 172.20.0.7 at 2018-10-10 13:02:12 +0000                                                                                                                                                                                                                                                                                      
portus_1    | Processing by Auth::RegistrationsController#create as HTML                     
portus_1    |   Parameters: {"utf8"=>"✓", "authenticity_token"=>"VujQ7AbTNHf2PS4RUVoRfQ6uHHup0B8G53AccYxapgHVitkflFo9WvEKiBAxNAbwvuUa+Y+v22IrfibBlb6EeQ==", "user"=>{"username"=>"admin", "email"=>"test@test.tld", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "admin"=>"true"}}                                                               
portus_1    |    (0.4ms)  SELECT COUNT(*) FROM `users` WHERE (`users`.`username` != 'portus') AND `users`.`enabled` = 1 AND `users`.`admin` = 1                                                                                                                                                                                                                      
portus_1    |   CACHE (0.0ms)  SELECT COUNT(*) FROM `users` WHERE (`users`.`username` != 'portus') AND `users`.`enabled` = 1 AND `users`.`admin` = 1  [["username", "portus"], ["enabled", true], ["admin", true]]                                                                                                                                                   
portus_1    |    (0.4ms)  BEGIN                                                                                                                                                                                                                                                                                                                                      
portus_1    |   User Exists (0.8ms)  SELECT  1 AS one FROM `users` WHERE `users`.`email` = BINARY 'test@test.tld' LIMIT 1                                                                                                                                                                                                                                            
portus_1    |   User Exists (0.7ms)  SELECT  1 AS one FROM `users` WHERE `users`.`username` = BINARY 'admin' LIMIT 1                                                                                                                                                                                                                                                 
portus_1    |   Namespace Exists (0.7ms)  SELECT  1 AS one FROM `namespaces` WHERE `namespaces`.`name` = 'admin' LIMIT 1
portus_1    |   SQL (0.8ms)  INSERT INTO `users` (`username`, `encrypted_password`, `email`, `admin`, `created_at`, `updated_at`) VALUES ('admin', '$2a$10$IiH4ZE7VdBtzx7lcsxkFLuywZ9MwQc/DWP3RksKH/7SJtIwHe66oW', 'test@test.tld', 1, '2018-10-10 13:02:12', '2018-10-10 13:02:12')
portus_1    |    (0.8ms)  SELECT COUNT(*) FROM `registries`
portus_1    |    (0.6ms)  COMMIT
portus_1    |    (0.4ms)  BEGIN
portus_1    |   User Exists (0.8ms)  SELECT  1 AS one FROM `users` WHERE (`users`.`username` = BINARY 'admin' AND `users`.`id` != 2) LIMIT 1
portus_1    |   SQL (0.7ms)  UPDATE `users` SET `last_sign_in_at` = '2018-10-10 13:02:12', `current_sign_in_at` = '2018-10-10 13:02:12', `last_sign_in_ip` = '172.20.0.7', `current_sign_in_ip` = '172.20.0.7', `sign_in_count` = 1, `updated_at` = '2018-10-10 13:02:12' WHERE `users`.`id` = 2
portus_1    |    (0.6ms)  COMMIT
portus_1    | Redirected to https://regg.studiostorti.com/
portus_1    | Completed 302 Found in 347ms (ActiveRecord: 14.4ms)
[...]
portus_1    | Redirected to https://regg.studiostorti.com/admin/registries/new
portus_1    | Filter chain halted as :force_registry_config! rendered or redirected
portus_1    | Completed 302 Found in 13ms (ActiveRecord: 0.3ms)
[...]
portus_1    | Started GET "/admin/registries/new" for 172.20.0.7 at 2018-10-10 13:02:13 +0000                                                                                                                                                                                                                                                                         
portus_1    | Processing by Admin::RegistriesController#new as HTML
portus_1    |   User Load (4.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 2  ORDER BY `users`.`id` ASC LIMIT 1
portus_1    |    (0.4ms)  SELECT COUNT(*) FROM `registries`
portus_1    |   CACHE (0.0ms)  SELECT COUNT(*) FROM `registries`
portus_1    |   Rendered admin/registries/new.html.slim within layouts/application (27.9ms)
portus_1    |   Rendered shared/_config.html.slim (14.8ms)
portus_1    | Completed 401 Unauthorized in 191ms (ActiveRecord: 5.4ms)
portus_1    |
portus_1    | ActionView::Template::Error (undefined method `[]' for nil:NilClass):
portus_1    |     1: javascript:
portus_1    |     2:   window.API_URL = '//#{app_path}';
portus_1    |     3:   window.PAGINATION = {
portus_1    |     4:     limit: #{pagination_limit},
portus_1    |     5:     beforeAfter: #{pagination_before_after}
portus_1    |     6:   };
portus_1    |   app/helpers/application_helper.rb:60:in `pagination_limit'
portus_1    |   app/views/shared/_config.html.slim:4:in `_app_views_shared__config_html_slim__591396720873740933_39431440'
portus_1    |   app/views/layouts/application.html.slim:31:in `_app_views_layouts_application_html_slim___1282159714487203136_29924240'
portus_1    |   app/middleware/catch_json_parse_errors.rb:11:in `call'
portus_1    |
portus_1    |
portus_1    | Processing by ErrorsController#show as HTML
portus_1    |   Parameters: {"status"=>"500"}
portus_1    |   Rendered errors/500.html.erb within layouts/errors (1.6ms)
portus_1    |   Rendered errors/_status_title.html.slim (23.8ms)
portus_1    | Completed 500 Internal Server Error in 68ms (Views: 66.0ms | ActiveRecord: 0.0ms)
```

Providing logs of the moment when the issue has happened would also be
useful. If you are in production, you might want to set the `PORTUS_LOG_LEVEL`
to `debug` to get a more verbose log.

### Deployment information

**Deployment method**: updated images tags inside a 2.3 docker-compose.yaml and ran a new stack

**Configuration**:

```yml
Evaluated configuration:
---
email:
  from: portus@mytest-reg.domain.tld
  name: Portus
  reply_to: no-reply@domain.tld
  smtp:
    enabled: true
    address: my-mail-relay
    port: 25
    domain: portus
gravatar:
  enabled: true
delete:
  enabled: true
ldap:
  enabled: false
  hostname: ldap_hostname
  port: 389
  method: plain
  base: ''
  filter: ''
  uid: uid
  authentication:
    enabled: false
    bind_dn: ''
    password: "____"
  guess_email:
    enabled: false
    attr: ''
oauth:
  google_oauth2:
    enabled: false
    id: ''
    secret: ''
    domain: ''
    options:
      hd: ''
  open_id:
    enabled: false
    identifier: ''
    domain: ''
  github:
    enabled: false
    client_id: ''
    client_secret: ''
    organization: ''
    team: ''
    domain: ''
  gitlab:
    enabled: false
    application_id: ''
    secret: ''
    group: ''
    domain: ''
    server: ''
  bitbucket:
    enabled: false
    key: ''
    secret: ''
    domain: ''
    options:
      team: ''
first_user_admin:
  enabled: true
signup:
  enabled: true
check_ssl_usage:
  enabled: true
registry:
  jwt_expiration_time:
    value: 5
  catalog_page:
    value: 250
  timeout:
    value: 2
  read_timeout:
    value: 120
machine_fqdn:
  value: mytest-reg.domain.tld
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: true
  create_team:
    enabled: true
  manage_team:
    enabled: true
  create_namespace:
    enabled: true
  manage_namespace:
    enabled: true
security:
  clair:
    server: http://clair:6060
    health_port: 6061
  zypper:
    server: ''
  dummy:
    server: ''
anonymous_browsing:
  enabled: true

```

**Portus version**: 2.4.0@2.4.0
