### ISSUE TITLE
Not able to get "delete" button in Portus 2.5

### ISSUE THREAD

**Issue by ashniku** [SUSE/Portus#2000]
### Description

Check out the `CONTRIBUTING.md` file for some considerations before submitting a
new issue.

### Steps to reproduce

```yml
version: "3"

services:
  portus:
    image: opensuse/portus:head
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}
      - CCONFIG_PREFIX=PORTUS   # Added for Bug

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      # SSL
      - PORTUS_PUMA_TLS_KEY=/certificates/portus.key
      - PORTUS_PUMA_TLS_CERT=/certificates/portus.crt

      - PORTUS_DELETE_ENABLED=true   # Added for delete functionalitya
      - PORTUS_DELETE_CONTRIBUTORS=true
      - PORTUS_DELETE_GARBAGE_COLLECTOR_ENABLED=true

      # NGinx is serving the assets instead of Puma. If you want to change this,
      # uncomment this line.
      #- RAILS_SERVE_STATIC_FILES='true'
    ports:
      - 3000:3000
    volumes:
      - ./secrets:/certificates:ro
      - static:/srv/Portus/public
    hostname: xxxxxxx.com
    networks:
      - portusNetwork
```

Should get delete button  
- **Actual behavior**: Not getting delete button for tags

I can see env variables are set:

  docker exec -it compose_portus_1_855c26cc2007  portusctl exec rake portus:info

delete:
  enabled: true
  contributors: true
  garbage_collector:
    enabled: true
    older_than: 30
    tag: ''
 Note: I have logged in with the admin user,that is created during configuration...
