### ISSUE TITLE
How delete unused/old images

### ISSUE THREAD

**Issue by rgawron** [SUSE/Portus#2003]
Hi

I install Portus using docker-compose and I use version 2.4.0-dev
From GUI I can only remove tags but I can't remove image and clean disk. 
It is normal ? How can I remove old images ? 

In config.yml in registry directory I have this:

```yml
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
```

What is "delete" option ?
