### ISSUE TITLE
Namespaces tab shows duplicates for some user account (LDAP Auth)

### ISSUE THREAD

**Issue by 0rax** [SUSE/Portus#2007]
### Description

Some user seems to have multiple times the same namespace being shown to them under the `Namespaces` tab in the Portus UI. This can be replicated using the API where each namespaces are returned 5 or 6 times.

This issue does not affect anything else than the UI and Portus API but is a minor annoyance as the list is now shown 30+ namespaces instead of the only 8 created. When clicking on any of the namespace name, everything seems to work fine there.

### Steps to reproduce

1. Install Portus 2.4 on Docker with user auth set to LDAP with SimpleTLS
2. Login as the first user to create an admin account, then create the necessary teams and namespaces (namespaces are shown properly to this user)
4. Create a new accounts by connecting using user credentials from the LDAP server
5. New users connects to Portus and check the `Namespaces` tabs

- **Expected behavior**: The Namespaces tab should show each namespace once
- **Actual behavior**: Some users have duplicate namespace entries under the `Namespaces` tab (replicated while querying the API). See the attached screenshots.

##### `Namespaces` tab on bugged account
<details>
  <summary>Click to reveal</summary>

![portus-namespaces](https://user-images.githubusercontent.com/2822534/47026411-471c4980-d15d-11e8-91d6-a84036a3f1ba.png)

</details>

##### `/api/v1/namespaces` return on bugged account
<details>
  <summary>Click to reveal</summary>

![portus-api](https://user-images.githubusercontent.com/2822534/47026410-471c4980-d15d-11e8-940c-a631638a9320.png)

</details>

### Deployment information

**Deployment method**: Portus container from Docker hub (`opensuse/portus:2.4`) on Rancher 1.6.21 using MariaDB 10.0 as the backend database

**Configuration**:

```sh
portusctl exec rake portus:info
```

<details>
  <summary>Click to reveal command output</summary>

```yml
[Mailer config] Host:     portus.my.fqdn
[Mailer config] Protocol: https://
Evaluated configuration:
---
email:
  from: portus@example.com
  name: Portus
  reply_to: ''
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    domain: example.com
    ssl_tls: ''
    enable_starttls_auto: false
    openssl_verify_mode: none
    ca_path: ''
    ca_file: ''
    user_name: ''
    password: "****"
    authentication: login
gravatar:
  enabled: false
delete:
  enabled: true
  contributors: false
  garbage_collector:
    enabled: false
    older_than: 30
    tag: ''
ldap:
  enabled: true
  hostname: ldap.my.fqdn
  port: 636
  timeout: 5
  encryption:
    method: simple_tls
    options:
      ca_file: ''
      ssl_version: TLSv1_2
  base: ou=users,dc=my,dc=fdqn
  filter: ''
  uid: uid
  authentication:
    enabled: true
    bind_dn: cn=readonly,dc=my,dc=fdqn
    password: "****"
  guess_email:
    enabled: true
    attr: mail
oauth:
  local_login:
    enabled: true
  google_oauth2:
    enabled: false
    id: ''
    secret: ''
    domain: ''
    options:
      hd: ''
  open_id:
    enabled: false
    identifier: ''
    domain: ''
  github:
    enabled: false
    client_id: ''
    client_secret: ''
    organization: ''
    team: ''
    domain: ''
  gitlab:
    enabled: false
    application_id: ''
    secret: ''
    group: ''
    domain: ''
    server: ''
  bitbucket:
    enabled: false
    key: ''
    secret: ''
    domain: ''
    options:
      team: ''
first_user_admin:
  enabled: true
signup:
  enabled: false
check_ssl_usage:
  enabled: false
registry:
  jwt_expiration_time:
    value: 60
  catalog_page:
    value: 300
  timeout:
    value: 2
  read_timeout:
    value: 120
machine_fqdn:
  value: portus.my.fqdn
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: false
  create_team:
    enabled: true
  manage_team:
    enabled: false
  create_namespace:
    enabled: true
  manage_namespace:
    enabled: false
  create_webhook:
    enabled: true
  manage_webhook:
    enabled: true
  push_images:
    policy: allow-teams
security:
  clair:
    server: ''
    health_port: 6061
    timeout: 900
  zypper:
    server: ''
  dummy:
    server: ''
anonymous_browsing:
  enabled: false
background:
  registry:
    enabled: true
  sync:
    enabled: true
    strategy: initial
pagination:
  limit: 10
  before_after: 2
```

</details>
</br>

**Portus version**: 2.4.0@2.4.0

**Comment by Vesli** [comment]
Hey, this PR would be in handy on my side as well.
I didn't had time to put much thought on it but we face the same issue.

**Comment by ArcticSnowman** [comment]
Running v2.4 in Kube with LDAP auth and I certainly not seeing that..   what is your ldap.toml config?

**Comment by 0rax** [comment]
@ArcticSnowman I dont really understand what you are asking for, my current Portus configuration for LDAP auth is the following 
```
ldap:
  enabled: true
  hostname: ldap.my.fqdn
  port: 636
  timeout: 5
  encryption:
    method: simple_tls
  base: ou=users,dc=my,dc=fdqn
  filter: ''
  uid: uid
  authentication:
    enabled: true
    bind_dn: cn=readonly,dc=my,dc=fdqn
    password: "****"
  guess_email:
    enabled: true
    attr: mail
```

My `ou=users` LDAP sub-tree is setup with entries of `objectClass`: `posixAccount`, `shadowAccount` and `inetOrgPerson`.

Every user is found properly and everything works as expected, it just seems that the APU returns more than one entry per namespace for some of my users.

Just in case this has an importance, my Portus is configured to connect to a MariaDB 10.0 running on AWS RDS with the following settings updated from the defaults:
```
character_set_database: utf8
character_set_server: utf8
collaction_connection: utf8_unicode_ci
collaction_server: utf8_unicode_ci
```
