### ISSUE TITLE
Using docker-compose examples results in background process errors.

### ISSUE THREAD

**Issue by cmeisinger** [SUSE/Portus#2016]
### Description

Setting up a new instance of portus using 2.4 and the default docker-compose.yml (and clair-ssl) results in a setup where teh background process is unable to speak to the registry.

### Steps to reproduce

1.  git clone from the portus repo.
2.  Copy the example/compose/ directory to a working directory.
3.  Update .env file to use the FQDN of the machine.
4.  Update the docker-compose file to use 2.4 variants of portus in lieu of HEAD. (2.3 tried as well.)
5.  Copy letsencrypt certs into ./secrtes/
6.  Run a docker-compose up . 

-  The logs continuously spam the following....
```
registry_1    | time="2018-10-26T20:55:59Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.7.6 http.request.host="10.10.10.10:5000" http.request.id=fa001326-8290-49a5-8099-85d4832d1edd http.request.method=GET http.request.remoteaddr="10.10.10.10:45440" http.request.uri="/v2/_catalog?n=100" http.request.useragent=Ruby instance.id=42f9a36c-1757-4a9c-acc8-b0fbf435b679 version=v2.6.2 
registry_1    | 10.10.10.10 - - [26/Oct/2018:20:55:59 +0000] "GET /v2/_catalog?n=100 HTTP/1.1" 401 145 "" "Ruby"
background_1  | Net::OpenTimeout: connection timed out
background_1  | Exception: Net::OpenTimeout: connection timed out
```

(IP Address changed.  In actuality it's an EIP bound to an AWS instance.)

### Deployment information
Mentioned up above.  Docker-compose from ./examples/ 

**Configuration**:

```yml
Evaluated configuration:
---
email:
  from: portus@example.com
  name: Portus
  reply_to: ''
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    domain: example.com
    ssl_tls: ''
    enable_starttls_auto: false
    openssl_verify_mode: none
    ca_path: ''
    ca_file: ''
    user_name: ''
    password: "****"
    authentication: login
gravatar:
  enabled: true
delete:
  enabled: true
  contributors: false
  garbage_collector:
    enabled: false
    older_than: 30
    tag: ''
ldap:
  enabled: false
  hostname: ldap_hostname
  port: 389
  timeout: 5
  encryption:
    method: ''
    options:
      ca_file: ''
      ssl_version: TLSv1_2
  base: ''
  filter: ''
  uid: uid
  authentication:
    enabled: false
    bind_dn: ''
    password: "****"
  guess_email:
    enabled: false
    attr: ''
oauth:
  local_login:
    enabled: true
  google_oauth2:
    enabled: false
    id: ''
    secret: ''
    domain: ''
    options:
      hd: ''
  open_id:
    enabled: false
    identifier: ''
    domain: ''
  github:
    enabled: false
    client_id: ''
    client_secret: ''
    organization: ''
    team: ''
    domain: ''
  gitlab:
    enabled: false
    application_id: ''
    secret: ''
    group: ''
    domain: ''
    server: ''
  bitbucket:
    enabled: false
    key: ''
    secret: ''
    domain: ''
    options:
      team: ''
first_user_admin:
  enabled: true
signup:
  enabled: true
check_ssl_usage:
  enabled: true
registry:
  jwt_expiration_time:
    value: 15
  catalog_page:
    value: 100
  timeout:
    value: 2
  read_timeout:
    value: 120
machine_fqdn:
  value: hub.fqdn.com
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: true
  create_team:
    enabled: true
  manage_team:
    enabled: true
  create_namespace:
    enabled: true
  manage_namespace:
    enabled: true
  create_webhook:
    enabled: true
  manage_webhook:
    enabled: true
  push_images:
    policy: allow-teams
security:
  clair:
    server: ''
    health_port: 6061
    timeout: 900
  zypper:
    server: ''
  dummy:
    server: ''
anonymous_browsing:
  enabled: true
background:
  registry:
    enabled: true
  sync:
    enabled: true
    strategy: initial
pagination:
  limit: 10
  before_after: 2

Portus version: 2.4.0@2.4.0
```

**Portus version**: 2.4.0
