### ISSUE TITLE
Not all assets respect RAILS_RELATIVE_URL_ROOT

### ISSUE THREAD

**Issue by atheriel** [SUSE/Portus#2017]
### Description

This is mentioned in the more recent comments on #1608, but it should be a separate issue. When Portus is deployed with `RAILS_RELATIVE_URL_ROOT`, not all static assets will respect this relative root. In particular:

- All assets mentioned in the `.css` file, including the webfonts and the layout background image.
- All favicons mentioned in the `<head>` tag.

### Steps to reproduce

1. Deploy Portus to non-root location with a valid `RAILS_RELATIVE_URL_ROOT`, with or without Rails serving the static assets.
2. Open the application in a browser, particularly with dev tools open.
3. Observe that some assets return 404 (while others work just fine).

- **Expected behavior**: Assets are served correctly.
- **Actual behavior**: Specific assets will 404 because they are not adhering to the relative root.

I can provide more deployment/configuration details if necessary, but I doubt that they are useful in this case.

**Portus version:** 2.4.

**Comment by vitoravelino** [comment]
@atheriel could you give more details about the errors themselves and your deployment? Because I've tried to reproduce in the docker-compose file I use for dev and it works with rails serving the assets.

**Comment by vitoravelino** [comment]
Actually, the css, webfonts and images work fine but the favicons are indeed not found.

**Comment by atheriel** [comment]
Sure, I'm trying to get Portus deployed as a stack inside a swarm cluster. It looks like this:

```yaml
version: '3.1'

services:
  portus:
    image: opensuse/portus:latest
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=xxx.x.x.x
      - PORTUS_CHECK_SSL_USAGE_ENABLED=false
      - CCONFIG_PREFIX=PORTUS
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABSE=portus
      - PORTUS_DB_PASSWORD=portus
      - PORTUS_DB_POOL=5
      - PORTUS_SECRET_KEY_BASE_FILE=/run/secrets/key_base
      - PORTUS_PASSWORD_FILE=/run/secrets/user_password
      - PORTUS_KEY_PATH=/certificates/portus.key
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_RELATIVE_URL_ROOT=/portus/
    ports:
      - 3000:3000
    networks:
      - portus
    secrets:
      - user_password
      - key_base
    logging:
      options:
        max-size: "500k"

  background:
    image: opensuse/portus:latest
    environment:
      - PORTUS_BACKGROUND=true 
      - PORTUS_MACHINE_FQDN_VALUE=xxx.x.x.x
      - CCONFIG_PREFIX=PORTUS
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABSE=portus
      - PORTUS_DB_PASSWORD=portus
      - PORTUS_DB_POOL=5
      - PORTUS_SECRET_KEY_BASE_FILE=/run/secrets/key_base
      - PORTUS_PASSWORD_FILE=/run/secrets/user_password
      - PORTUS_KEY_PATH=/certificates/portus.key
    networks:
      - portus
    secrets:
      - user_password
      - key_base
    logging:
      options:
        max-size: "500k"

  db:
    image: library/mariadb:10.0.23
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      - MYSQL_DATABSE=portus
      - MYSQL_ROOT_PASSWORD=portus
    networks:
      - portus
    logging:
      options:
        max-size: "500k"

secrets:
  user_password:
    file: ./user_password.txt
  key_base:
    file: ./key_base.txt

networks:
  portus: {}
```
I also have nginx sitting between this cluster and the outside world, redicting `/portus/` to port 3000.
```nginx
location /portus/ {
    proxy_pass http://127.0.0.1:3000/portus/;
}
```
For the most part, this is working fine. But in devtools (and in nginx logs), plenty of asset calls are returning 404 because they are being retrieved from `/assets/` instead of `/portus/assets/` (in this case). So it is my suspicion that these assets are not respecting `RAILS_RELATIVE_URL_ROOT`.

By the way, two users describe identical patterns to what I have seen [here](https://github.com/SUSE/Portus/issues/1608#issuecomment-359754923) and [here](https://github.com/SUSE/Portus/issues/1608#issuecomment-369979335).
