### ISSUE TITLE
Portus user does not exists

### ISSUE THREAD

**Issue by gioppoluca** [SUSE/Portus#2032]
### Description
I installed the docker-container release of Portus and registry does not allow to login  and in the dashboard I have a message that states that "Portus" user does not exists

### Steps to reproduce

Configured the files and tryed to use the product, but not able to login on registry (getting no authorization"

### Deployment information

Centos 7 

docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:03 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:25:29 2018
  OS/Arch:          linux/amd64
  Experimental:     false

Portus image: 2.4
DB is an external postgres (no container)

**Configuration**:
docker exec -ti registry_portus_1 portusctl exec rake portus:info
[Mailer config] Host:     portus.test.lan
[Mailer config] Protocol: https://
  User Exists (0.6ms)  SELECT  1 AS one FROM "users" WHERE "users"."username" = $1 LIMIT 1  [["username", "portus"]]
  User Exists (0.5ms)  SELECT  1 AS one FROM "users" WHERE "users"."username" = $1 LIMIT 1  [["username", "portus"]]
Evaluated configuration:
---
email:
  from: portus@example.com
  name: Portus
  reply_to: ''
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    domain: example.com
    ssl_tls: ''
    enable_starttls_auto: false
    openssl_verify_mode: none
    ca_path: ''
    ca_file: ''
    user_name: ''
    password: "****"
    authentication: login
gravatar:
  enabled: true
delete:
  enabled: true
  contributors: false
  garbage_collector:
    enabled: false
    older_than: 30
    tag: ''
ldap:
  enabled: false
  hostname: ldap_hostname
  port: 389
  timeout: 5
  encryption:
    method: ''
    options:
      ca_file: ''
      ssl_version: TLSv1_2
  base: ''
  filter: ''
  uid: uid
  authentication:
    enabled: false
    bind_dn: ''
    password: "****"
  guess_email:
    enabled: false
    attr: ''
oauth:
  local_login:
    enabled: true
  google_oauth2:
    enabled: false
    id: ''
    secret: ''
    domain: ''
    options:
      hd: ''
  open_id:
    enabled: false
    identifier: ''
    domain: ''
  github:
    enabled: false
    client_id: ''
    client_secret: ''
    organization: ''
    team: ''
    domain: ''
  gitlab:
    enabled: false
    application_id: ''
    secret: ''
    group: ''
    domain: ''
    server: ''
  bitbucket:
    enabled: false
    key: ''
    secret: ''
    domain: ''
    options:
      team: ''
first_user_admin:
  enabled: true
signup:
  enabled: true
check_ssl_usage:
  enabled: "'false'"
registry:
  jwt_expiration_time:
    value: 15
  catalog_page:
    value: 100
  timeout:
    value: 2
  read_timeout:
    value: 120
machine_fqdn:
  value: registry.sdp.csi.it
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: true
  create_team:
    enabled: true
  manage_team:
    enabled: true
  create_namespace:
    enabled: true
  manage_namespace:
    enabled: true
  create_webhook:
    enabled: true
  manage_webhook:
    enabled: true
  push_images:
    policy: allow-teams
security:
  clair:
    server: ''
    health_port: 6061
    timeout: 900
  zypper:
    server: ''
  dummy:
    server: ''
anonymous_browsing:
  enabled: true
background:
  registry:
    enabled: true
  sync:
    enabled: true
    strategy: initial
pagination:
  limit: 10
  before_after: 2

Portus version: 2.4.0@762c9665bb11b8998dcda6891d7e220657b79086

```yml
docker-compose.yml 
version: "2"

services:
  portus:
    image: opensuse/portus:latest
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=registry.sdp.csi.it
      - PORTUS_LOG_LEVEL=debug
      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=prd-sdp-vdb03.sdp.csi.it
      - PORTUS_DB_DATABASE=SDPTOOLS
      - PORTUS_DB_PASSWORD=Fireka4go
      - PORTUS_DB_POOL=5
      - PORTUS_DB_ADAPTER=postgresql
      - PORTUS_DB_USERNAME=sdptool

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=portsdp
      - PORTUS_KEY_PATH=/certificates/sdp.csi.it.key
      - PORTUS_PASSWORD=portsdp1
      

      # SSL
      - PORTUS_CHECK_SSL_USAGE_ENABLED='false'

      # Since we have no nginx in insecure mode, portus have to
      # serve the static files
      - RAILS_SERVE_STATIC_FILES='true'
    ports:
      - 3000:3000
    volumes:
      - /root/secrets:/certificates:ro

  background:
    image: opensuse/portus:latest
    depends_on:
      - portus
    environment:
      # Theoretically not needed, but cconfig's been buggy on this...
      - CCONFIG_PREFIX=PORTUS
      - PORTUS_MACHINE_FQDN_VALUE=registry.sdp.csi.it

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=prd-sdp-vdb03.sdp.csi.it
      - PORTUS_DB_DATABASE=SDPTOOLS
      - PORTUS_DB_PASSWORD=Fireka4go
      - PORTUS_DB_POOL=5
      - PORTUS_DB_ADAPTER=postgresql
      - PORTUS_DB_USERNAME=sdptool 

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=portsdp
      - PORTUS_KEY_PATH=/certificates/sdp.csi.it.key
      - PORTUS_PASSWORD=portsdp1

      - PORTUS_BACKGROUND=true
    volumes:
      - /root/secrets:/certificates:ro


  registry:
    image: library/registry:2.6
    environment:
      REGISTRY_LOGLEVEL: debug

      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: http://registry.sdp.csi.it:3000/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: registry.sdp.csi.it:5000
      REGISTRY_AUTH_TOKEN_ISSUER: registry.sdp.csi.it
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /secrets/sdp.csi.it.cer
      
      # SSL
      REGISTRY_HTTP_TLS_CERTIFICATE: /secrets/sdp.csi.it.cer
      REGISTRY_HTTP_TLS_KEY: /secrets/sdp.csi.it.key
      
      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: http://registry.sdp.csi.it:3000/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
      - /registrypersistence:/var/lib/registry
      - /root/secrets:/secrets:ro
      - ./config.yml:/etc/docker/registry/config.yml:ro
    ports:
      - 5000:5000
      - 5001:5001 # required to access debug service
    links:
      - portus:portus

config.yml 
version: 0.1
log:
  fields:
    service: registry
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: 0.0.0.0:5000
  host: https://registry.sdp.csi.it:5000
  debug:
    addr: 0.0.0.0:5001
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3




```
