### ISSUE TITLE
Error deleting images / repos via portus-web

### ISSUE THREAD

**Issue by Kulturserver** [SUSE/Portus#2045]
### Description

We are getting an error when trying to delete an image or repo via portus-web. The GUI tells us that the deletion was successful, but actually the deleted item is still available on the server. The container portus_registry_1 sends the following error message:

time="2018-11-26T15:09:35Z" level=warning msg="error authorizing context:
authorization token required" go.version=go1.7.6
http.request.host="hub.culturebase.or
g:5000" http.request.id=6b0b309f-4dd7-409b-af9b-306ea0f778bb
http.request.method=DELETE http.request.remoteaddr="172.18.0.1:38713"
http.request.uri="/v2/php/php
5.6dev/manifests/sha256:e5450018745b1c027889676f41f6c7b348f2f6df6f5d9c87930ee46ed6e91cc9"
http.request.useragent=Ruby instance.id=a338712d-1d31-44cc-aefe-dc391d
c17b81 vars.name="php/php5.6dev"
vars.reference="sha256:e5450018745b1c027889676f41f6c7b348f2f6df6f5d9c87930ee46ed6e91cc9"
version=v2.6.2
172.18.0.1 - - [26/Nov/2018:15:09:35 +0000] "DELETE
/v2/php/php5.6dev/manifests/sha256:e5450018745b1c027889676f41f6c7b348f2f6df6f5d9c87930ee46ed6e91cc9
HTTP/1.1
" 401 153 "" "Ruby"
time="2018-11-26T15:09:35Z" level=info msg="response completed"
go.version=go1.7.6 http.request.host="hub.culturebase.org:5000"
http.request.id=d2f69619-c330-40
18-8b90-f884753a478a http.request.method=DELETE
http.request.remoteaddr="172.18.0.1:38718"
http.request.uri="/v2/php/php5.6dev/manifests/sha256:e5450018745b1c02
7889676f41f6c7b348f2f6df6f5d9c87930ee46ed6e91cc9" http.request.useragent=Ruby
http.response.duration=13.105854ms http.response.status=202
http.response.written=
0 instance.id=a338712d-1d31-44cc-aefe-dc391dc17b81 version=v2.6.2
172.18.0.1 - - [26/Nov/2018:15:09:35 +0000] "DELETE
/v2/php/php5.6dev/manifests/sha256:e5450018745b1c027889676f41f6c7b348f2f6df6f5d9c87930ee46ed6e91cc9
HTTP/1.1
" 202 0 "" "Ruby"

Also, after pushing an image, we are only able to see it in the portus-web GUI after restarting all containers via docker-compose down and docker-compose up.

### Steps to reproduce

1. Checking out portus git
2. Edited yaml (see below)
3. Installed local apache with proxy modules and the following vhosts:

<VirtualHost *:80>
  ServerName hub.culturebase.org
RewriteEngine on
ReWriteCond %{SERVER_PORT} !^443$
RewriteRule ^/(.*) https://%{HTTP_HOST}/$1 [NC,R,L]
</VirtualHost>
<VirtualHost *:443>
        ServerName hub.culturebase.org
        Header set Host "hub.culturebase.org"
        RequestHeader set X-Forwarded-Proto "https"
        ProxyRequests Off
        ProxyPreserveHost On
        SSLProxyEngine on
        SSLProxyCheckPeerName Off
        SSLProxyCheckPeerCN Off
        ProxyPass / https://localhost:444/
        ProxyPassReverse / https://localhost:444/
        Include include/ssl.conf
</VirtualHost>

### Deployment information

We use docker-compose.yaml with ssl (Secure) and the following containers:
- Portus
- Background
- MariaDB
- Registry
- Nginx

```yml
version: "2"

services:
  portus:
    image: opensuse/portus:latest
    restart: always
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=hub.culturebase.org
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=password
      - PORTUS_DB_POOL=5
      - PORTUS_SECRET_KEY_BASE=string
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=password
      - PORTUS_PUMA_TLS_KEY=/certificates/portus.key
      - PORTUS_PUMA_TLS_CERT=/certificates/portus.crt
      #- RAILS_SERVE_STATIC_FILES='true'
    ports:
      - 3000:3000
    links:
      - db
    volumes:
      - ./secrets:/certificates
      - static:/srv/Portus/public

  background:
    image: opensuse/portus:latest
    restart: always
    depends_on:
      - portus
      - db
    environment:
      - CCONFIG_PREFIX=PORTUS
      - PORTUS_MACHINE_FQDN_VALUE=hub.culturebase.org
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=password
      - PORTUS_DB_POOL=5
      - PORTUS_SECRET_KEY_BASE=string
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=password
      - PORTUS_BACKGROUND=true
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro

  db:
    image: library/mariadb:10.0.23
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    restart: always
    environment:
      - MYSQL_DATABASE=portus_production
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - /opt/portus/mariadb:/var/lib/mysql

  registry:
    image: library/registry:2.6
    restart: always
    command: ["/bin/sh", "/etc/docker/registry/init"]
    environment:
      REGISTRY_AUTH_TOKEN_REALM: https://hub.culturebase.org:3000/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: hub.culturebase.org:5000
      REGISTRY_AUTH_TOKEN_ISSUER: hub.culturebase.org
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /secrets/portus.crt
      REGISTRY_HTTP_TLS_CERTIFICATE: /secrets/portus.crt
      REGISTRY_HTTP_TLS_KEY: /secrets/portus.key
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://hub.culturebase.org:3000/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
      - /opt/portus/registry:/var/lib/registry
      - ./secrets:/secrets
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
      - ./registry/init:/etc/docker/registry/init:ro
    ports:
      - 5000:5000
      - 5001:5001 # required to access debug service
    links:
      - portus:portus

  nginx:
    image: library/nginx:alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./secrets:/secrets
      - static:/srv/Portus/public:ro
    ports:
      - 81:80
      - 444:443
    links:
      - registry:registry
      - portus:portus

volumes:
  static:
    driver: local

```

**Portus version**: 2.4.0
