### ISSUE TITLE
Performance issue after Portus upgrade from 2.2 to 2.4 

### ISSUE THREAD

**Issue by dimuskin** [SUSE/Portus#2059]
### Description

I was upgraded our Portus server from 2.2 to 2.4 (with vulnerability check enabled)
Everything was fine, before security scanner finish her works. 

To understand the size of the database, I cite the number of records in the tables.

namespaces: 181
repositories: 310
tags: 12K
scan_results: 1.2M !!!

Most GUI pages working slowly, but, for example, Repositories tab does not work at all.

### Steps to reproduce

1. Install portus
2. Load huge amount of records
3. Click to Repositories tab

- **Expected behavior**: I expected to see repositories list
- **Actual behavior**: But I got Timeout error after 10 min.

Also I tried to run main portus process in debug mode, it give me huge amount (several thousand) of SQL select logs. Started from that:

Started GET "/repositories" for 172.18.0.3 at 2018-12-13 13:17:15 +0000
Processing by RepositoriesController#index as HTML
  User Load (9.8ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 47  ORDER BY `users`.`id` ASC LIMIT 1
   (1.0ms)  SELECT COUNT(*) FROM `registries`
  Repository Load (2.1ms)  SELECT `repositories`.* FROM `repositories`
  Repository Load (1.4ms)  SELECT `repositories`.* FROM `repositories` INNER JOIN `namespaces` ON `namespaces`.`id` = `repositories`.`namespace_id` INNER JOIN `teams` ON `teams`.`id` = `namespaces`.`team_id` INNER JOIN `team_users` ON `team_users`.`team_id` = `teams`.`id` INNER JOIN `users` ON `users`.`id` = `team_users`.`user_id` WHERE (users.id = 47)
  Namespace Load (8.6ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`id` = 71 LIMIT 1
  Registry Load (0.7ms)  SELECT  `registries`.* FROM `registries` WHERE `registries`.`id` = 1 LIMIT 1
   (0.5ms)  SELECT COUNT(*) FROM `stars` WHERE `stars`.`repository_id` = 98
   (0.7ms)  SELECT COUNT(*) FROM `tags` WHERE `tags`.`repository_id` = 98
  Tag Load (4.0ms)  SELECT `tags`.* FROM `tags` WHERE `tags`.`repository_id` = 98
  Star Exists (0.8ms)  SELECT  1 AS one FROM `stars` WHERE `stars`.`repository_id` = 98 AND `stars`.`user_id` = 47 LIMIT 1
  Team Load (0.5ms)  SELECT  `teams`.* FROM `teams` WHERE `teams`.`id` = 68 LIMIT 1
  User Exists (0.9ms)  SELECT  1 AS one FROM `users` INNER JOIN `team_users` ON `users`.`id` = `team_users`.`user_id` WHERE `team_users`.`team_id` = 68 AND `team_users`.`role` = 2 AND `users`.`id` = 47 LIMIT 1
  CACHE (0.1ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`id` = 71 LIMIT 1  [["id", 71]]
  CACHE (0.0ms)  SELECT  `registries`.* FROM `registries` WHERE `registries`.`id` = 1 LIMIT 1  [["id", 1]]
   (0.8ms)  SELECT COUNT(*) FROM `stars` WHERE `stars`.`repository_id` = 147
   (0.6ms)  SELECT COUNT(*) FROM `tags` WHERE `tags`.`repository_id` = 147
  Tag Load (6.4ms)  SELECT `tags`.* FROM `tags` WHERE `tags`.`repository_id` = 147
  Star Exists (1.7ms)  SELECT  1 AS one FROM `stars` WHERE `stars`.`repository_id` = 147 AND `stars`.`user_id` = 47 LIMIT 1
  CACHE (0.1ms)  SELECT  `teams`.* FROM `teams` WHERE `teams`.`id` = 68 LIMIT 1  [["id", 68]]
  CACHE (0.0ms)  SELECT  1 AS one FROM `users` INNER JOIN `team_users` ON `users`.`id` = `team_users`.`user_id` WHERE `team_users`.`team_id` = 68 AND `team_users`.`role` = 2 AND `users`.`id` = 47 LIMIT 1  [["team_id", 68], ["role", 2], ["id", 47]]
  CACHE (0.0ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`id` = 71 LIMIT 1  [["id", 71]]

as far as I understand GUI, when opening this page, tries to load and display all data from the database, which greatly overloads the system.

Perhaps the algorithm contains an erroneous recursive query. 

My idea is try to delete all records from `scan_results` table and disable vulnerability check. Is it make sense?

### Deployment information

**Deployment method**: 
docker, based on instruction

**Configuration**:

```yml
email:
  from: "Docker-reg@XXXXX.com"
  name: "XXXXX Docker Registry"
  reply_to: "docker@XXXXX.com"
  smtp:
    enabled: true
    address: "xxxxx"
    port: 25,

machine_fqdn:
  value: "registry.XXXXX.com"

first_user_admin:
  enabled: true

delete:
  enabled: true
  contributors: false

display_name:
  enabled: true

signup:
  enabled: false

anonymous_browsing:
  enabled: false

background:
  registry:
    enabled: true

  sync:
    enabled: true
    strategy: on-start

```

**Portus version**:  2.4.0
