### ISSUE TITLE
Image v2.4 on Dockerhub bug

### ISSUE THREAD

**Issue by TechCatOther** [SUSE/Portus#2070]
### Description

Image on Dockerhub - opensuse/portus:2.4 broken with pagination. Image on dockerhub need to rebuild. After rebuilding from git - all ok. I found that app/views/shared/_config.html.slim old with "limit:" there.

### Steps to reproduce

1. docker pull  opensuse/portus:2.4
2. Start example compose
3. Select namespaces/userlist

- **Expected behavior**: I expected showing lists
- **Actual behavior**: List loaded, but don't show. 

### Deployment information

**Deployment method**: docker-compose

**Configuration**: 
```
pagination:
  # Number of entries to be listed per page
  per_page: 10
  # Number of pages to be showed before and after the current one
  # e,g.: Prev 1 2 [3] 4 5 Next
  before_after: 2
```

**Portus version**: 2.4.0@3591e04ba75caf913cee1e0a1c699b47ae9d0848
