### ISSUE TITLE
Unable to pull an image

### ISSUE THREAD

**Issue by zekker6** [SUSE/Portus#2075]
### Steps to reproduce

1. Push image where any layer size is more than 10MB
2. Try to pull an image
3. See images are pulled normally till download size goes to ~10MB
4. Download speed drops to ~0 (after 30 minutes wait 1MB of data was transferred)

- **Expected behavior**: Successfull pull
- **Actual behavior**: Pull stucks after about 8-10MB downloaded

Providing logs of the moment when the issue has happened would also be
useful. If you are in production, you might want to set the `PORTUS_LOG_LEVEL`
to `debug` to get a more verbose log.

### Description

Portus was deployed some time ago, but wasn't actual in use except for several push/pull tests.
Recently i've started migration to portus from local docker registry and noticed that there is no way to download heavy images, download just stucks after a while.

Some more details:
* After download restart(kill with ctrl+c) there will be normal speed for the firsl ~10MB, but download will be stopped again.
* At the beginning there was 2.3 version deployed, upgrade to 2.4 did not fix this issue.
* There is no connection issue cluster as restart works fine, as well as several other applications which are using same network(upload and download).
* Using different docker versions did not make any change. Tried 18.06 on windows with WSL(local machine), 17.06 centos 7 host(local server), 18.06 ubuntu 16.04 host(cloud server)
* Portus log contain `Unsupported mediaType 'application/octet-stream'` which was referenced here - #1565 

### Deployment information

**Deployment method**: 

Deployed via custom helm chart(based on the official one, added LE certificates support and custom mariadb deployment). 
Deployment contains:
* portus container
* registry container
* mariadb instance

```
NAME                                      READY   STATUS    RESTARTS   AGE
portus-mariadb-0                          1/1     Running   0          37d
portus-portus-69bd7596cb-jzc89            2/2     Running   0          15m
portus-portus-registry-7dd45db747-f7j74   1/1     Running   0          8m
```

Traffic is routed via ingress controller. Routes configuration is copied from the official nginx examples.
Registry and portus are hosted using one domain name `portus.__omitted__.com` and served over https with LE cert.

Portus routes:
```yaml
- host: {{ .Values.nginx.host | quote }}
      http:
        paths:
          - path: /v2/token
            backend:
              serviceName: {{ template "portus.fullname" . }}
              servicePort: {{ .Values.portus.service.port }}
          - path: /v2/webhooks/events
            backend: 
              serviceName: {{ template "portus.fullname" . }}
              servicePort: {{ .Values.portus.service.port }}
          - backend:
              serviceName: {{ template "portus.fullname" . }}
              servicePort: {{ .Values.portus.service.port }}
```

Registry routes:
```yaml
- host: {{ .Values.nginx.host | quote }}
      http:
        paths:
          - path: /v2/
            backend:
              serviceName: {{ template "registry.fullname" . }}
              servicePort: {{ .Values.registry.service.port }}
          - path: /v2/_catalog
            backend:
              serviceName: {{ template "registry.fullname" . }}
              servicePort: {{ .Values.registry.service.port }}
```

**Configuration**:

Portus
```yaml
portus-portus-69bd7596cb-jzc89:/ # portusctl exec rake portus:info
[Mailer config] Host:     portus-portus
[Mailer config] Protocol: https://
  User Exists (0.5ms)  SELECT  1 AS one FROM `users` WHERE `users`.`username` = 'portus' LIMIT 1
  User Load (0.7ms)  SELECT  `users`.* FROM `users` WHERE `users`.`username` = 'portus' LIMIT 1
   (0.6ms)  BEGIN
  SQL (0.8ms)  UPDATE `users` SET `encrypted_password` = '$2a$10$YH1DzukbKjbjLNRb843YBuj8wUojEHg3CcO9WjS.WkAH9yxJBBZ/y', `updated_at` = '2018-12-19 17:47:19' WHERE `users`.`id` = 4
   (10.8ms)  COMMIT
  User Exists (0.6ms)  SELECT  1 AS one FROM `users` WHERE `users`.`username` = 'portus' LIMIT 1
   (0.5ms)  SELECT COUNT(*) FROM `registries`
Evaluated configuration:
---
email:
  from: portus@example.com
  name: Portus
  reply_to: no-reply@example.com
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    domain: example.com
    ssl_tls: ''
    enable_starttls_auto: false
    openssl_verify_mode: none
    ca_path: ''
    ca_file: ''
    user_name: username@example.com
    password: "****"
    authentication: login
gravatar:
  enabled: true
delete:
  enabled: true
  contributors: false
  garbage_collector:
    enabled: false
    older_than: 30
    tag: ''
ldap:
  enabled: false
  hostname: ldap_hostname
  port: 389
  timeout: 5
  encryption:
    method: ''
    options:
      ca_file: ''
      ssl_version: TLSv1_2
  base: ''
  filter: ''
  uid: uid
  authentication:
    enabled: false
    bind_dn: ''
    password: "****"
  guess_email:
    enabled: false
    attr: ''
oauth:
  local_login:
    enabled: true
  google_oauth2:
    enabled: false
    id: ''
    secret: ''
    domain: ''
    options:
      hd: ''
  open_id:
    enabled: false
    identifier: ''
    domain: ''
  github:
    enabled: false
    client_id: ''
    client_secret: ''
    organization: ''
    team: ''
    domain: ''
  gitlab:
    enabled: true
    application_id: __omitted__
    secret: __omitted__
    group: ''
    domain: ''
    server: __omitted__
  bitbucket:
    enabled: false
    key: ''
    secret: ''
    domain: ''
    options:
      team: ''
first_user_admin:
  enabled: true
signup:
  enabled: false
check_ssl_usage:
  enabled: false
registry:
  jwt_expiration_time:
    value: 5
  catalog_page:
    value: 100
  timeout:
    value: 2
  read_timeout:
    value: 120
machine_fqdn:
  value: portus-portus
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: true
  create_team:
    enabled: true
  manage_team:
    enabled: true
  create_namespace:
    enabled: true
  manage_namespace:
    enabled: true
  create_webhook:
    enabled: true
  manage_webhook:
    enabled: true
  push_images:
    policy: allow-teams
security:
  clair:
    server: ''
    health_port: 6061
    timeout: 900
  zypper:
    server: ''
  dummy:
    server: ''
anonymous_browsing:
  enabled: false
background:
  registry:
    enabled: true
  sync:
    enabled: true
    strategy: initial
pagination:
  limit: 10
  per_page: 10
  before_after: 2

Portus version: 2.4.0@942f18113fa1d5672e0c189e3669f5552204fa5e
```

**Portus version**: 2.4.0@942f18113fa1d5672e0c189e3669f5552204fa5e

### Logs

CLI:
```
__omitted__: Pulling from __omitted__
4fe2ade4980c: Pull complete
00d3d3303f7c: Pull complete
66b4647144b5: Downloading [====================>                              ]   11.3MB/28.22MB // stuck
70111f842123: Download complete
6d407c5641e1: Download complete
43515b674927: Download complete
9421c2e8eb0d: Download complete
6fcb7f9ecba7: Download complete
02ab14e25f5f: Download complete
ac7d8f6b5175: Download complete
a24a1106dff7: Download complete
47ff38f0170c: Downloading [=======>                                           ]  20.08MB/137.5MB // stuck
fd5d44c811cd: Downloading [=====>                                             ]  13.21MB/130.1MB // stuck
caba3e4b8d51: Waiting
1101c3d0d982: Waiting
fb66d9106975: Waiting
eba6ab6a76d5: Waiting
94d66149940d: Waiting
1a94a57a20ee: Waiting
42dff489e53a: Waiting
77bad7c19de3: Waiting
bda10ce87a99: Waiting
4536abf06b5f: Waiting
0cc2009fe2f6: Waiting
c24efda1a930: Waiting
```

[Portus log](https://pastebin.com/n1JYBSzx)

[Portus background log](https://pastebin.com/UsscqgS6)

[Registry log](https://pastebin.com/uLKtM6Qe)
