### ISSUE TITLE
Warn message every second "error authorizing context: authorization token required"

### ISSUE THREAD

**Issue by Nitrosito** [SUSE/Portus#2077]
### Description

Hello, when it has been running portus during + - 12 / 24h these types of messages start to appear
```
xxx - time="2018-12-20T09:36:46Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.7.6 http.request.host="registry.xxx.org:5000" http.request.id=694b545b-f81b-44cd-97b7-83fbc1e42dc1 http.request.method=GET http.request.remoteaddr="192.168.80.1:54874" http.request.uri="/v2/" http.request.useragent=Ruby instance.id=04c5f958-6a6f-4c00-860f-3dbf71fdd48a version=v2.6.2
```
192.168.80.1 is the gateway of docker network

My docker-compose:
```
version: "2"

services:
  portus:
    image: opensuse/portus:2.4
    restart: unless-stopped
    environment:
      - CCONFIG_PREFIX=PORTUS
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}
      - PORTUS_SECURITY_CLAIR_SERVER=http://clair:6060
      - PORTUS_DISPLAY_NAME_ENABLED=true
      - PORTUS_DELETE_ENABLED=true
      - PORTUS_SIGNUP_ENABLED=false

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      # SSL
      - PORTUS_PUMA_TLS_KEY=/certificates/portus.key
      - PORTUS_PUMA_TLS_CERT=/certificates/portus.crt

      # NGinx is serving the assets instead of Puma. If you want to change this,
      # uncomment this line.
      - RAILS_SERVE_STATIC_FILES='true'
      - PORTUS_CHECK_SSL_USAGE_ENABLED=false
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro
      - static:/srv/Portus/public
    logging:
      driver: gelf
      options:
        gelf-address: udp://192.168.3.254:12201
        tag: "{{.Name}}swarm"


  background:
    image: opensuse/portus:2.4
    restart: unless-stopped
    depends_on:
      - portus
      - db
    environment:
      # Theoretically not needed, but cconfig's been buggy on this...
      - CCONFIG_PREFIX=PORTUS
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}
      - PORTUS_SECURITY_CLAIR_SERVER=http://clair:6060

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      - PORTUS_BACKGROUND=true
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro
    logging:
      driver: gelf
      options:
        gelf-address: udp://192.168.3.254:12201
        tag: "{{.Name}}swarm"

  db:
    image: library/mariadb:10.0.23
    restart: unless-stopped
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      - MYSQL_DATABASE=portus_production

      # Again, the password shouldn't be handled like this.
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
     #- /var/lib/portus/mariadb:/var/lib/mysql
     - ./portus/mariadb:/var/lib/mysql
    logging:
      driver: gelf
      options:
        gelf-address: udp://192.168.3.254:12201
        tag: "{{.Name}}swarm"

  registry:
    image: library/registry:2.6.2
    command: ["/bin/sh", "/etc/docker/registry/init"]
    restart: unless-stopped
    environment:
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: https://${MACHINE_FQDN}:50001/v2/token 
      REGISTRY_AUTH_TOKEN_SERVICE: ${MACHINE_FQDN} 
      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN} 
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /secrets/portus.crt 
      #REGISTRY_HTTP_SECRET: xxxesregistrysecret 

      # SSL
      REGISTRY_HTTP_TLS_CERTIFICATE: /secrets/portus.crt
      REGISTRY_HTTP_TLS_KEY: /secrets/portus.key

      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://${MACHINE_FQDN}:50001/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
      #- /var/lib/portus/registry:/var/lib/registry
      - ./registry/data/:/var/lib/registry
      - ./secrets:/secrets:ro
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
      - ./registry/init:/etc/docker/registry/init:ro
    ports:
      - 5000:5000
      - 5001:5001 # required to access debug service
    links:
      - portus:portus
    logging:
      driver: gelf
      options:
        gelf-address: udp://192.168.3.254:12201
        tag: "{{.Name}}swarm"

  nginx:
    image: library/nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./secrets:/secrets:ro
      - static:/srv/Portus/public:ro
    ports:
      - 50001:50001
    links:
      - registry:registry
      - portus:portus
    logging:
     driver: gelf
     options:
       gelf-address: udp://192.168.3.254:12201
       tag: "{{.Name}}swarm"
  clair:
    #image: quay.io/coreos/clair:v2.0.1
    image: quay.io/coreos/clair:v2.0.6
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "6060-6061:6060-6061"
    volumes:
      - /tmp:/tmp
      - ./clair/clair.yml:/clair.yml
    command: [-config, /clair.yml]
    logging:
      driver: gelf
      options:
        gelf-address: udp://192.168.3.254:12201
        tag: "{{.Name}}swarm"
 
  postgres:
    image: library/postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: portus
    logging:
      driver: gelf
      options:
        gelf-address: udp://192.168.3.254:12201
        tag: "{{.Name}}swarm"
volumes:
  static:
    driver: local

```

my registry config
``version: 0.1
loglevel: debug
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: :5000
  tls:
    certificate: /secrets/portus.crt
    key: /secrets/portus.key
notifications:
  endpoints:
    - name: portus
      url: https://registry.xxx.org:3000/v2/webhooks/events
      timeout: 500ms
      threshold: 5
backoff: 1s`

```
