### ISSUE TITLE
Portus 2.4.2 undefined method `public_file_server' for #<Rails::Application

### ISSUE THREAD

**Issue by pushou** [SUSE/Portus#2129]
### Description
I upgraded Portus to 2.4.2 from an existing 2.4.0 install and I've got this error now.
Seems to be relative to rails version

portus_1      | /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `public_file_server' for #<Rails::Application::Configuration:0x0000000004691820> (NoMethodError)
portus_1      | 	from /srv/Portus/config/environments/production.rb:27:in `block in <top (required)>'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/railtie.rb:210:in `instance_eval'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/railtie.rb:210:in `configure'
portus_1      | 	from /srv/Portus/config/environments/production.rb:3:in `<top (required)>'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `block in require'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:240:in `load_dependency'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `require'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/engine.rb:597:in `each'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/engine.rb:597:in `block in <class:Engine>'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/initializable.rb:30:in `instance_exec'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/initializable.rb:30:in `run'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/initializable.rb:55:in `block in run_initializers'
portus_1      | 	from /usr/lib64/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
portus_1      | 	from /usr/lib64/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
portus_1      | 	from /usr/lib64/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
portus_1      | 	from /usr/lib64/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
portus_1      | 	from /usr/lib64/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/initializable.rb:44:in `each'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/initializable.rb:44:in `tsort_each_child'
portus_1      | 	from /usr/lib64/ruby/2.5.0/tsort.rb:415:in `call'
portus_1      | 	from /usr/lib64/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
portus_1      | 	from /usr/lib64/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
portus_1      | 	from /usr/lib64/ruby/2.5.0/tsort.rb:347:in `each'
portus_1      | 	from /usr/lib64/ruby/2.5.0/tsort.rb:347:in `call'
portus_1      | 	from /usr/lib64/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
portus_1      | 	from /usr/lib64/ruby/2.5.0/tsort.rb:226:in `tsort_each'
portus_1      | 	from /usr/lib64/ruby/2.5.0/tsort.rb:205:in `tsort_each'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/initializable.rb:54:in `run_initializers'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/application.rb:352:in `initialize!'
portus_1      | 	from /srv/Portus/config/environment.rb:7:in `<top (required)>'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `block in require'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:240:in `load_dependency'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `require'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/application.rb:328:in `require_environment!'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/commands/runner.rb:52:in `<top (required)>'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/commands/commands_tasks.rb:123:in `require'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/commands/commands_tasks.rb:90:in `runner'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
portus_1      | 	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/commands.rb:17:in `<top (required)>'
portus_1      | 	from bin/rails:12:in `require'
portus_1      | 	from bin/rails:12:in `<main>'
portus_1      | exit status 1

### Steps to reproduce

Providing logs of the moment when the issue has happened would also be
useful. If you are in production, you might want to set the `PORTUS_LOG_LEVEL`
to `debug` to get a more verbose log.

### Deployment information

**Deployment method**: how have you deployed Portus? Are you using one of the
[examples](https://github.com/SUSE/Portus/tree/master/examples) as a base? If
possible, could you paste your configuration? (don't forget to strip passwords
or other sensitive data!)

**Configuration**:
95db20e8a44d:/ # portusctl exec rake portus:info        
rake aborted!
NoMethodError: undefined method `public_file_server' for #<Rails::Application::Configuration:0x0000000005a634c0>
Did you mean?  public_send
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/railtie/configuration.rb:95:in `method_missing'
/srv/Portus/config/environments/production.rb:27:in `block in <top (required)>'
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/railtie.rb:210:in `instance_eval'
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/railtie.rb:210:in `configure'
/srv/Portus/config/environments/production.rb:3:in `<top (required)>'
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `block in require'
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:240:in `load_dependency'
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `require'
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/engine.rb:597:in `each'
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/engine.rb:597:in `block in <class:Engine>'
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/initializable.rb:30:in `instance_exec'
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/initializable.rb:30:in `run'
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/initializable.rb:55:in `block in run_initializers'
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/initializable.rb:44:in `each'
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/initializable.rb:44:in `tsort_each_child'
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/initializable.rb:54:in `run_initializers'
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/application.rb:352:in `initialize!'
/srv/Portus/config/environment.rb:7:in `<top (required)>'
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `block in require'
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:240:in `load_dependency'
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `require'
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/application.rb:328:in `require_environment!'
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/srv/Portus/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => portus:info => environment
(See full trace by running task with --trace)
exit status 1

```yml
version: "2"

services:
  portus:
    image: opensuse/portus:2.4.2
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5


      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      # SSL
      - PORTUS_PUMA_TLS_KEY=/certificates/portus.key
      - PORTUS_PUMA_TLS_CERT=/certificates/portus.crt

      # NGinx is serving the assets instead of Puma. If you want to change this,
      # uncomment this line.
      - RAILS_SERVE_STATIC_FILES='false'
      - PORTUS_SECURITY_CLAIR_SERVER=http://clair:6060

    ports:
      - 3000:3000
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro
      - static:/srv/Portus/public
      - ./config:/srv/Portus/config
      - ./config/config-local.yml:/srv/Portus/config/config-local.yml
    networks:
        portus_net:
          ipv4_address: 192.168.20.2

```
```
root@registry:/opt/dockercompose/Portus# docker images |grep portus
opensuse/portus                                  2.4.2               5a10af2dfd99        About an hour ago   244MB
root@registry:/opt/dockercompose/Portus# 
```

thanks for your help
