### ISSUE TITLE
Using basic auth to connect to registry

### ISSUE THREAD

**Issue by boh717** [SUSE/Portus#2132]
### Description

Hi everyone,
I'm trying to make portus background process to connect to registry via basic authentication.
I've already check issue https://github.com/SUSE/Portus/issues/1393 without obtaining anything useful.

The recurrent error in background process is: `Exception: Cannot find bearer realm`.

Unfortunately, documentation isn't helpful.

Could you please point me into the right direction?

### Deployment information

```
registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
    REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    REGISTRY_STORAGE_DELETE_ENABLED: "True"
  volumes:
    - /opt/docker-registry:/var/lib/registry
    - <hidden>:/certs
    - <hidden>/auth:/auth
portus:
  image: opensuse/portus:latest
  ports:
    - 8081:3000
  links:
    - mariadb
  environment:
    PORTUS_MACHINE_FQDN_VALUE: <hidden>
    PORTUS_CHECK_SSL_USAGE_ENABLED: "True"
    RAILS_SERVE_STATIC_FILES: "True"
    CCONFIG_PREFIX: PORTUS
    PORTUS_SECRET_KEY_BASE: <hidden>
    PORTUS_KEY_PATH: /certs/domain.key
    PORTUS_PASSWORD: <hidden>
    PORTUS_DB_HOST: mariadb
    PORTUS_PUMA_TLS_KEY: /certs/domain.key
    PORTUS_PUMA_TLS_CERT: /certs/domain.crt
  volumes:
      - <hidden>:/certs

background:
    image: opensuse/portus:latest
    restart: always
    environment:
      CCONFIG_PREFIX: PORTUS
      PORTUS_MACHINE_FQDN_VALUE: <hidden>
      PORTUS_DB_HOST: mariadb
      PORTUS_DB_DATABASE: portus_production
      PORTUS_DB_POOL: 5
      PORTUS_SECRET_KEY_BASE: <hidden>
      PORTUS_KEY_PATH: /certs/domain.key
      PORTUS_PASSWORD: <hidden>
      PORTUS_BACKGROUND: "True"
    links:
      - mariadb
    volumes:
      - <hidden>:/certs:ro

mariadb:
    image: mariadb
    environment:
       MYSQL_ROOT_PASSWORD: <hidden>
    ports:
     - 3306:3306
    volumes:
      - <hidden>:/var/lib/mysql
```

**Portus version**: 2.4.1@ddc403833c8975a83aa93d01baa4bc10acd40c1b (taken from UI)
