### ISSUE TITLE
LDAP auth fails on 2nd login

### ISSUE THREAD

**Issue by cxcv** [SUSE/Portus#2136]
### Steps to reproduce

1. enable ldap auth
2. perform a successfull login
3. logout
4. login again

- **Expected behavior**: 2nd login should work
- **Actual behavior**: 2nd login fails with error "This user can only authenticate if LDAP is enabled"

Looking into [lib/portus/ldap/configuration.rb](https://github.com/SUSE/Portus/commit/d287a693a937c1c8fe5985876c918ccffe1d466f#diff-578fa3d57ff56cd6168492f38049947dR62), I see the LDAP provider checks:
```
elsif user&.encrypted_password == ""
```
which is empty for LDAP users.

I've verified this in the DB (select username,encrypted_password from users), the password is empty.

As this line was added recently, I guest it might have introduced a bug for the 2nd login
(@mssola  could you comment?)

### Deployment information

docker-compose.yml:
```
[...]
# LDAP support. If enabled, then only users of the specified LDAP server will
# be able to use Portus. Take a look at the documentation of LDAP support in our
# online docs: http://port.us.org/features/2_LDAP-support.html.
ldap:
  enabled: true

  # Hostname and port of your LDAP server.
  hostname: "ldap.dst-its.de"
  port: 389

  # The connection timeout to be used for all LDAP requests measured in seconds.
  timeout: 5

  # Encryption options
  encryption:
    # Available methods: "simple_tls" and "start_tls". If you leave this value
    # empty (default), then no encryption will be enforced.
    method: "start_tls"
    options:
      # The CA file to be accepted by the LDAP server. If none is provided, then
      # the default parameters from the host will be sent.
      ca_file: ""

      # Protocol version.
      ssl_version: "TLSv1_2"

  # The base where users are located (e.g. "ou=users,dc=example,dc=com").
  base: "OU=DST Users,OU=DST,DC=dst-its,DC=de"

  # The base where admin users are located.
  # (e.g. "ou=admin,dc=example,dc=com"). Use this base if you have a separate
  # route for admin users. Users logging in from this base will be considered
  # Portus administrators automatically.
  admin_base: ""
  #admin_base: "CN=dst-cima-admins,OU=Groups,OU=DST,DC=dst-its,DC=de"

  # The base where groups are located (e.g. "ou=groups,dc=example,dc=com").
  group_base: "OU=Groups,OU=DST,DC=dst-its,DC=de"

  # User filter (e.g. "mail=george*").
  filter: ""

  # The LDAP attribute where to search for username. The default is 'uid'.
  uid: "sAMAccountName"

  # LDAP credentials used to search for a user.
  authentication:
    enabled: true
    bind_dn: "CN=LDAP,OU=Service User,OU=DST,DC=dst-its,DC=de"
    password: "<secret>"

  # Automatically add team members from a matching LDAP group into each
  # team. Note that this will not delete nor update existing team members. Only
  # `groupOfNames` and `groupOfUniqueNames` are supported.
  group_sync:
    enabled: true

    # The role in which new team members will be added. Note that Portus
    # administrators will be added as team owners regardless of this setting.
    default_role: "viewer"

  # Portus needs an email for each user, but there's no standard way to get
  # that from LDAP servers. You can tell Portus how to get the email from users
  # registered in the LDAP server with this configurable value. There are three
  # possibilities:
  #
  #   - disabled: this is the default value. It means that Portus won't do a
  #     thing when registering LDAP users (users will be redirected to their
  #     profile page until they setup an email account).
  #   - enabled where "attr" is empty: for this you need "ldap.base" to have
  #     some value. In this case, the hostname will be guessed from the domain
  #     component of the provided base string. For example, for the dn:
  #     "ou=users,dc=example,dc=com", and a user name "user", the resulting
  #     email is "user@example.com".
  #   - enabled where "attr" is not empty: with this you specify the attribute
  #     inside a LDIF record where the email is set.
  #
  # If something goes wrong when trying to guess the email, then it just falls
  # back to the default behavior (empty email).
  guess_email:
    enabled: true
    attr: "mail"
[...]
```

**Configuration**:

```yml
[schema] Selected the schema for mysql
[Mailer config] Host:     registry.docker.cima.dst-its.de
[Mailer config] Protocol: https://
Evaluated configuration:
---
email:
  from: portus@example.com
  name: Portus
  reply_to: ''
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    domain: example.com
    ssl_tls: ''
    enable_starttls_auto: false
    openssl_verify_mode: none
    ca_path: ''
    ca_file: ''
    user_name: ''
    password: "****"
    authentication: login
gravatar:
  enabled: true
delete:
  enabled: true
  contributors: false
  garbage_collector:
    enabled: false
    older_than: 30
    keep_latest: 5
    tag: ''
ldap:
  enabled: true
  hostname: ldap.dst-its.de
  port: 389
  timeout: 5
  encryption:
    method: start_tls
    options:
      ca_file: ''
      ssl_version: TLSv1_2
  base: OU=DST Users,OU=DST,DC=dst-its,DC=de
  admin_base: ''
  group_base: OU=Groups,OU=DST,DC=dst-its,DC=de
  filter: ''
  uid: sAMAccountName
  authentication:
    enabled: true
    bind_dn: CN=LDAP,OU=Service User,OU=DST,DC=dst-its,DC=de
    password: "****"
  group_sync:
    enabled: true
    default_role: viewer
  guess_email:
    enabled: true
    attr: mail
oauth:
  local_login:
    enabled: true
  google_oauth2:
    enabled: false
    id: ''
    secret: ''
    domain: ''
    options:
      hd: ''
  open_id:
    enabled: false
    identifier: ''
    domain: ''
  github:
    enabled: false
    client_id: ''
    client_secret: ''
    organization: ''
    team: ''
    domain: ''
  gitlab:
    enabled: false
    application_id: ''
    secret: ''
    group: ''
    domain: ''
    server: ''
  bitbucket:
    enabled: false
    key: ''
    secret: ''
    domain: ''
    options:
      team: ''
first_user_admin:
  enabled: true
signup:
  enabled: true
check_ssl_usage:
  enabled: "'false'"
registry:
  jwt_expiration_time:
    value: 15
  catalog_page:
    value: 100
  timeout:
    value: 2
  read_timeout:
    value: 120
machine_fqdn:
  value: registry.docker.cima.dst-its.de
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: true
  create_team:
    enabled: true
  manage_team:
    enabled: true
  create_namespace:
    enabled: true
  manage_namespace:
    enabled: true
  create_webhook:
    enabled: true
  manage_webhook:
    enabled: true
  push_images:
    policy: allow-teams
security:
  clair:
    server: http://clair:6060
    health_port: 6061
    timeout: 900
  zypper:
    server: ''
  dummy:
    server: ''
anonymous_browsing:
  enabled: true
background:
  registry:
    enabled: true
  sync:
    enabled: true
    strategy: initial
pagination:
  per_page: 10
  before_after: 2

Portus version: 2.5.0-dev@b7f912d6e9dbcf2a74702526b946ea2ee35499e5
```
