### ISSUE TITLE
[2.4.2] Background process crash

### ISSUE THREAD

**Issue by opopops** [SUSE/Portus#2152]
### Description

Background process crash every 2 minutes with this error:

```
/srv/Portus/app/models/tag.rb:137:in `fetch_digest': undefined method `full_name' for nil:NilClass (NoMethodError)
	from /srv/Portus/app/models/tag.rb:65:in `delete_by_digest!'
	from /srv/Portus/app/services/tags/destroy_service.rb:11:in `execute'
	from /srv/Portus/lib/portus/background/garbage_collector.rb:35:in `block in execute!'
	from /srv/Portus/lib/portus/background/garbage_collector.rb:34:in `each'
	from /srv/Portus/lib/portus/background/garbage_collector.rb:34:in `execute!'
	from /srv/Portus/bin/background.rb:58:in `block (2 levels) in <top (required)>'
	from /srv/Portus/bin/background.rb:56:in `each'
	from /srv/Portus/bin/background.rb:56:in `each_with_index'
	from /srv/Portus/bin/background.rb:56:in `block in <top (required)>'
	from /srv/Portus/bin/background.rb:55:in `loop'
	from /srv/Portus/bin/background.rb:55:in `<top (required)>'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/commands/runner.rb:60:in `load'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/commands/runner.rb:60:in `<top (required)>'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/commands/commands_tasks.rb:123:in `require'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/commands/commands_tasks.rb:90:in `runner'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:12:in `require'
	from bin/rails:12:in `<main>'

```
### Deployment information

portus is deployed via docker, Versions I use:

portus: 2.4.2
registry: 2.7.1
mariadb: 10.3

**Configuration**:

You can get this information like this:

- In bare metal execute: `bundle exec rake portus:info`.
- In a container:
  - Using the development `docker-compose.yml` file: `docker exec -it <container-id> bundle exec rake portus:info`.
  - Using the [production image](https://hub.docker.com/r/opensuse/portus/): `docker exec -it <container-id> portusctl exec rake portus:info`.

```yml
docker exec background portusctl exec rake portus:info
Evaluated configuration:
---
email:
  from: portus@example.com
  name: Portus
  reply_to: ''
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    domain: example.com
    ssl_tls: ''
    enable_starttls_auto: false
    openssl_verify_mode: none
    ca_path: ''
    ca_file: ''
    user_name: ''
    password: "****"
    authentication: login
gravatar:
  enabled: true
delete:
  enabled: true
  contributors: true
  garbage_collector:
    enabled: true
    older_than: 15
    tag: "(^(feature|hotfix|review|release|support).*|^(\\\\w{8,})$)"
ldap:
  enabled: false
  hostname: ldap_hostname
  port: 389
  timeout: 5
  encryption:
    method: ''
    options:
      ca_file: ''
      ssl_version: TLSv1_2
  base: ''
  filter: ''
  uid: uid
  authentication:
    enabled: false
    bind_dn: ''
    password: "****"
  guess_email:
    enabled: false
    attr: ''
oauth:
  local_login:
    enabled: true
  google_oauth2:
    enabled: false
    id: ''
    secret: ''
    domain: ''
    options:
      hd: ''
  open_id:
    enabled: false
    identifier: ''
    domain: ''
  github:
    enabled: false
    client_id: ''
    client_secret: ''
    organization: ''
    team: ''
    domain: ''
  gitlab:
    enabled: false
    application_id: ''
    secret: ''
    group: ''
    domain: ''
    server: ''
  bitbucket:
    enabled: false
    key: ''
    secret: ''
    domain: ''
    options:
      team: ''
first_user_admin:
  enabled: true
signup:
  enabled: true
check_ssl_usage:
  enabled: true
registry:
  jwt_expiration_time:
    value: 15
  catalog_page:
    value: 100
  timeout:
    value: 2
  read_timeout:
    value: 120
machine_fqdn:
  value: registry.domain.red
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: true
  create_team:
    enabled: true
  manage_team:
    enabled: true
  create_namespace:
    enabled: true
  manage_namespace:
    enabled: true
  create_webhook:
    enabled: true
  manage_webhook:
    enabled: true
  push_images:
    policy: allow-teams
security:
  clair:
    server: ''
    health_port: 6061
    timeout: 900
  zypper:
    server: ''
  dummy:
    server: ''
anonymous_browsing:
  enabled: true
background:
  registry:
    enabled: true
  sync:
    enabled: true
    strategy: update-delete
pagination:
  limit: 10
  per_page: 10
  before_after: 2

Portus version: 2.4.2@c2950a41f7db0e8e6ab3de5464f67be79b4e8779
```
