### ISSUE TITLE
Bringing up Portus causes 'table exists' error

### ISSUE THREAD

**Issue by bertoost** [SUSE/Portus#2162]
### Description

I succeeded to created configuration for Kubernetes. Therefor when I apply the deployment (with a non-background portus, and a background-portus container). The Pod fails and some database errors occur after a couple of seconds.

```bash
Mysql2::Error: Table 'users' already exists
```

### Steps to reproduce

Hard for you to reproduce, but I just apply the deployment in Kubernetes, it looks wel for 2 seconds and then it starts to fail with above error.
I tried to cleanup the database, but the error happens again every time

### Deployment information

```yml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: portus
  namespace: registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: portus
        tier: registry
    spec:
      containers:
      - name: portus
        image: opensuse/portus:2.4.2
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        ports:
        - containerPort: 443
        envFrom:
        - configMapRef:
            name: portus-config
        env:
        # Database settings
        - name: PORTUS_DB_HOST
          valueFrom:
            secretKeyRef:
              name: portus-secrets
              key: db-host
        - name: PORTUS_DB_PORT
          valueFrom:
            secretKeyRef:
              name: portus-secrets
              key: db-port
        - name: PORTUS_DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: portus-secrets
              key: db-name
        - name: PORTUS_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: portus-secrets
              key: db-username
        - name: PORTUS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: portus-secrets
              key: db-password
        # Secrets settings
        - name: PORTUS_SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: portus-secrets
              key: keybase
        - name: PORTUS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: portus-secrets
              key: password
        volumeMounts:
          - name: secrets
            mountPath: /secrets
          - name: certificates
            mountPath: /certificates
      
      - name: portus-background
        image: opensuse/portus:2.4.2
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        envFrom:
        - configMapRef:
            name: portus-config
        env:
        - name: PORTUS_BACKGROUND
          value: 'true'
        # Database settings
        - name: PORTUS_DB_HOST
          valueFrom:
            secretKeyRef:
              name: portus-secrets
              key: db-host
        - name: PORTUS_DB_PORT
          valueFrom:
            secretKeyRef:
              name: portus-secrets
              key: db-port
        - name: PORTUS_DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: portus-secrets
              key: db-name
        - name: PORTUS_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: portus-secrets
              key: db-username
        - name: PORTUS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: portus-secrets
              key: db-password
        volumeMounts:
          - name: secrets
            mountPath: /secrets

      volumes:
      - name: secrets
        secret:
          secretName: portus-secrets
          items:
          - key: key
            path: portus.key
      
      - name: certificates
        secret:
          secretName: portus-secrets
          items:
          - key: cert
            path: portus.cert
```

**Configuration**:

Secrets setup

```yml
apiVersion: v1
kind: Secret
metadata:
  name: portus-secrets
  namespace: registry
type: Opaque
data:
  db-host: #not-here
  db-port: #not-here
  db-name: #not-here
  db-username: #not-here
  db-password: #not-here

  # openssl rand -hex 64
  keybase: #not-here
  password: #not-here

  # key & cert
  key: ''
  cert: ''
```

Configmap

```yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: portus-config
  namespace: registry
data:
  PORTUS_MACHINE_FQDN_VALUE: 'my-registry.domain.not-here'
  PORTUS_GRAVATAR_ENABLED: 'true'
  PORTUS_FIRST_USER_ADMIN_ENABLED: 'true'
  PORTUS_SIGNUP_ENABLED: 'false'
  PORTUS_ANONYMOUS_BROWSING_ENABLED: 'false'
  PORTUS_CHECK_SSL_USAGE_ENABLED: 'false'
  PORTUS_LOG_LEVEL: 'debug'
  RAILS_SERVE_STATIC_FILES: 'true'
  PORTUS_KEY_PATH: '/secrets/portus.key'
```

**Portus version**: 2.4.2
