### ISSUE TITLE
SMTP settings for Office365 returns authentication unsuccessful

### ISSUE THREAD

**Issue by inkychris** [SUSE/Portus#2184]
### Description
SMTP configuration always seems to fail when using the same rails settings that are successful in Gitlab. Office365 does seem to be a little more sensitive than, for example, Gmail: it fails to authenticate if the sender and account addresses are different. Note that Gitlab is deployed with  their official docker image (Ubuntu). All other features in Portus appear to work.

### Steps to reproduce

With the following in `portus/config.yml`:
```yaml
email:
  from: account@example.co.uk
  name: account@example.co.uk
  reply_to: account@example.co.uk
  smtp:
    enabled: true
    address: smtp.office365.com
    port: 587
    domain: example.co.uk
    user_name: account@example.co.uk
    password: <PASSWORD>
    authentication: login
    enable_starttls_auto: true
```

...and the following result from `rake portus:info`:
```yaml
email:
  from: account@example.co.uk
  name: account@example.co.uk
  reply_to: account@example.co.uk
  smtp:
    enabled: true
    address: smtp.office365.com
    port: 587
    domain: example.co.uk
    ssl_tls: ''
    enable_starttls_auto: true
    openssl_verify_mode: none
    ca_path: ''
    ca_file: ''
    user_name: account@example.co.uk
    password: "****"
    authentication: login
```
- **Expected behavior**: Receive email from `account@example.co.uk`
- **Actual behavior**:
```
portus_1      | Processing by PasswordsController#create as HTML
portus_1      |   Parameters: {"utf8"=>"✓", "authenticity_token"=>"abcd1234==", "user"=>{"email"=>"chris.wright@example.co.uk"}, "button"=>""}
portus_1      |   Rendered vendor/bundle/ruby/2.5.0/gems/devise-4.4.0/app/views/devise/mailer/reset_password_instructions.html.erb (0.5ms)
portus_1      |
portus_1      | Sent mail to chris.wright@example.co.uk (5698.0ms)
portus_1      | [Mailer] 535 5.7.3 Authentication unsuccessful [LO2P265CA0453.GBRP265.PROD.OUTLOOK.COM]
portus_1      | :
portus_1      | Redirected to https://docker.example.co.uk/users/password/new
portus_1      | Completed 302 Found in 5990ms (ActiveRecord: 2.3ms)
```

### Deployment information
**Deployment method**: Using modified docker-compose example with Clair.
**Portus version**: 2.4.3@5a616c0ef860567df5700708256f42505cdb9952
