### ISSUE TITLE
Dashboard UI Oh No! page 500 Error when change or deleted namespace or team

### ISSUE THREAD

**Issue by RjEcho217** [SUSE/Portus#2190]
### Description

I can access all other pages when I login with any user but the dashboard UI and it give no indication in the logs of an error only a 500 error

I believe this happened right after i deleted and created a new team. 

### Steps to reproduce

1. I ran the docker-compose.insecure.yml with some persistent data dir links

2. Then I made a new user(non admin)  the ncreated a team Admin owned and a namespace for the repos to go I then changed the Team name and then deleted a teamnamespace. Then created a Team for the new User to own  with 2 namespaces for repos. 

3. I attempted to login as the user and see the dashboard and check to see what repos were accessible and this page hit and the logs show a 500 internal error. 

- **Expected behavior**: To login and see the dashboard and not the Oh Oh! error page. 
- **Actual behavior**: 
Best part of the logs i can find considering i restarted thinking it was an error that could maybe reset. 
```
^[[32mportus_1      |^[[0m app/views/dashboard/index.html.slim:6:in `_app_views_dashboard_index_html_slim__1494383318374779852_40883080'
^[[32mportus_1      |^[[0m Processing by ErrorsController#show as HTML
^[[32mportus_1      |^[[0m   Parameters: {"status"=>"500"}
^[[32mportus_1      |^[[0m   Rendering errors/500.html.erb within layouts/errors
^[[32mportus_1      |^[[0m   Rendered errors/500.html.erb within layouts/errors (0.0ms)
^[[32mportus_1      |^[[0m   Rendered errors/_status_title.html.slim (0.0ms)
^[[32mportus_1      |^[[0m Completed 500 Internal Server Error in 1ms (Views: 1.1ms | ActiveRecord: 0.0ms)
^[[32mportus_1      |^[[0m Started GET "/repositories" for 10.63.11.116 at 2019-05-03 15:18:29 +0000
^[[32mportus_1      |^[[0m Processing by RepositoriesController#index as HTML
^[[32mportus_1      |^[[0m   Rendering repositories/index.html.slim within layouts/application
^[[32mportus_1      |^[[0m   Rendered repositories/index.html.slim within layouts/application (3.3ms)
^[[32mportus_1      |^[[0m   Rendered shared/_config.html.slim (2.8ms)
^[[32mportus_1      |^[[0m   Rendered shared/_header.html.slim (5.5ms)
^[[32mportus_1      |^[[0m   Rendered shared/_aside.html.slim (8.5ms)
^[[32mportus_1      |^[[0m   Rendered shared/_search.html.slim (3.1ms)
^[[32mportus_1      |^[[0m   Rendering shared/_notification.html.slim
^[[32mportus_1      |^[[0m   Rendered shared/_notification.html.slim (0.1ms)
^[[32mportus_1      |^[[0m   Rendering shared/_notification.html.slim
^[[32mportus_1      |^[[0m   Rendered shared/_notification.html.slim (0.0ms)
^[[32mportus_1      |^[[0m   Rendered shared/_notifications.html.slim (0.6ms)
^[[32mportus_1      |^[[0m Completed 200 OK in 59ms (Views: 50.7ms | ActiveRecord: 1.6ms)
^[[32mportus_1      |^[[0m Started GET "/repositories/team?page=1&sort_attr=name&sort_order=asc" for 10.63.11.116 at 2019-05-03 15:18:30 +0000
^[[32mportus_1      |^[[0m Processing by RepositoriesController#team_repositories as JSON
^[[32mportus_1      |^[[0m   Parameters: {"page"=>"1", "sort_attr"=>"name", "sort_order"=>"asc"}
^[[32mportus_1      |^[[0m Started GET "/repositories/other?page=1&sort_attr=name&sort_order=asc" for 10.63.11.116 at 2019-05-03 15:18:30 +0000
^[[32mportus_1      |^[[0m Processing by RepositoriesController#other_repositories as JSON
^[[32mportus_1      |^[[0m   Parameters: {"page"=>"1", "sort_attr"=>"name", "sort_order"=>"asc"}
^[[32mportus_1      |^[[0m Completed 200 OK in 22ms (Views: 7.9ms | ActiveRecord: 8.3ms)
^[[32mportus_1      |^[[0m Completed 200 OK in 27ms (Views: 8.7ms | ActiveRecord: 8.7ms)
^[[32mportus_1      |^[[0m Started GET "/" for 10.63.11.207 at 2019-05-03 16:28:10 +0000
^[[32mportus_1      |^[[0m Processing by DashboardController#index as HTML
^[[32mportus_1      |^[[0m Scoped order is ignored, it's forced to be batch order.
^[[32mportus_1      |^[[0m   Rendering dashboard/index.html.slim within layouts/application
^[[32mportus_1      |^[[0m   Rendered dashboard/partials/_portus_user_alert.html.slim (3.4ms)
^[[32mportus_1      |^[[0m   Rendered dashboard/partials/_stats.html.slim (8.4ms)
^[[32mportus_1      |^[[0m   Rendered public_activity/registry/_remove_team.html.slim (6.9ms)
^[[32mportus_1      |^[[0m   Rendered public_activity/team/_add_member.html.slim (6.5ms)
^[[32mportus_1      |^[[0m   Rendered public_activity/team/_change_team_name.html.slim (90.6ms)
^[[32mportus_1      |^[[0m   Rendered dashboard/partials/_recent_activities.html.slim (130.4ms)
^[[32mportus_1      |^[[0m   Rendered dashboard/index.html.slim within layouts/application (147.5ms)
^[[32mportus_1      |^[[0m Completed 500 Internal Server Error in 171ms (ActiveRecord: 11.4ms)
```

### Deployment information

**Deployment method**: Via docker-compose. the path was under the Portus dir (Portus/examples/compose) I made a copy of the docker-compose.insecure.yml with my alterations(provided below) 

**Configuration**: 

```[schema] Selected the schema for mysql
[Mailer config] Host:     portus.test.lan
[Mailer config] Protocol: https://
Evaluated configuration:
---
email:
  from: portus@example.com
  name: Portus
  reply_to: ''
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    domain: example.com
    ssl_tls: ''
    enable_starttls_auto: false
    openssl_verify_mode: none
    ca_path: ''
    ca_file: ''
    user_name: ''
    password: "****"
    authentication: login
gravatar:
  enabled: true
delete:
  enabled: true
  contributors: false
  garbage_collector:
    enabled: false
    older_than: 30
    keep_latest: 5
    tag: ''
ldap:
  enabled: false
  hostname: ldap_hostname
  port: 389
  timeout: 5
  encryption:
    method: ''
    options:
      ca_file: ''
      ssl_version: TLSv1_2
  base: ''
  admin_base: ''
  group_base: ''
  filter: ''
  uid: uid
  authentication:
    enabled: false
    bind_dn: ''
    password: "****"
  group_sync:
    enabled: true
    default_role: viewer
  guess_email:
    enabled: false
    attr: ''
oauth:
  local_login:
    enabled: true
  google_oauth2:
    enabled: false
    id: ''
    secret: ''
    domain: ''
    options:
      hd: ''
  open_id:
    enabled: false
    identifier: ''
    domain: ''
  github:
    enabled: false
    client_id: ''
    client_secret: ''
    organization: ''
    team: ''
    domain: ''
  gitlab:
    enabled: false
    application_id: ''
    secret: ''
    group: ''
    domain: ''
    server: ''
  bitbucket:
    enabled: false
    key: ''
    secret: ''
    domain: ''
    options:
      team: ''
first_user_admin:
  enabled: true
signup:
  enabled: true
check_ssl_usage:
  enabled: "'false'"
registry:
  jwt_expiration_time:
    value: 15
  catalog_page:
    value: 100
  timeout:
    value: 2
  read_timeout:
    value: 120
machine_fqdn:
  value: 10.63.5.187
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: true
  create_team:
    enabled: true
  manage_team:
    enabled: true
  create_namespace:
    enabled: true
  manage_namespace:
    enabled: true
  create_webhook:
    enabled: true
  manage_webhook:
    enabled: true
  push_images:
    policy: allow-teams
security:
  clair:
    server: ''
    health_port: 6061
    timeout: 900
  zypper:
    server: ''
  dummy:
    server: ''
anonymous_browsing:
  enabled: true
background:
  registry:
    enabled: true
  sync:
    enabled: true
    strategy: initial
pagination:
  per_page: 10
  before_after: 2

Portus version: 2.5.0-dev@30420987709df9e72b54de6590d3a2df1a2aff73
```

```yml
version: "2"

services:
  portus:
    image: opensuse/portus:head
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      # SSL
      - PORTUS_CHECK_SSL_USAGE_ENABLED='false'

      # Since we have no nginx in insecure mode, portus have to
      # serve the static files
      - RAILS_SERVE_STATIC_FILES='true'
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro

  background:
    image: opensuse/portus:head
    depends_on:
      - portus
      - db
    environment:
      # Theoretically not needed, but cconfig's been buggy on this...
      - CCONFIG_PREFIX=PORTUS
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      - PORTUS_BACKGROUND=true
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro

  db:
    image: library/mariadb:10.0.23
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      - MYSQL_DATABASE=portus_production

      # Again, the password shouldn't be handled like this.
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - /db_data:/var/lib/mysql

  registry:
    image: library/registry:2.6
    environment:
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: http://${MACHINE_FQDN}:3000/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: ${MACHINE_FQDN}:5000
      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /secrets/portus.crt

      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: http://${MACHINE_FQDN}:3000/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
#      - /var/lib/portus/registry:/var/lib/registry
      - /registry_data/images:/var/lib/registry
      - ./secrets:/secrets:ro
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
    ports:
      - 5000:5000
      - 5001:5001 # required to access debug service
    links:
      - portus:portus
  ```                                               

**Portus version**: Portus version: 2.5.0-dev@30420987709df9e72b54de6590d3a2df1a2aff73
