### ISSUE TITLE
OpenID authentication does not verify server certificate

### ISSUE THREAD

**Issue by zhangyoufu** [SUSE/Portus#2193]
### Description

```
I, [2019-05-08T02:23:16.999230 #63]  INFO -- omniauth: (open_id) Request phase initiated.
I, [2019-05-08T02:23:17.010585 #63]  INFO -- OpenID: WARNING: making https request to https://openid.example.com/ without verifying server certificate; no CA path was specified.
```

### Steps to reproduce

```
oauth:
  open_id:
    enabled: true
    identifier: https://openid.example.com
    domain: example.com
```

- **Expected behavior**: connection is secured by TLS, and no warning in portus log
- **Actual behavior**: the server certificate is not verified

### Deployment information

**Portus version**: 2.4.3@5a616c0ef860567df5700708256f42505cdb9952
