### ISSUE TITLE
Background_1 Errors --- Registry_1 TLS handshake error -- >.<

### ISSUE THREAD

**Issue by RjEcho217** [SUSE/Portus#2195]
Ive been trying at this for days PLEASE HELP!

Compose file running from the /Portus/examples/compose directory.

I'm at a complete loss 3 days now of trying to get this to work? Does this even work ive tried portus/head 
portus/2.4.3
portus/2.4

If I run this compose file docker-compose.3.yml the background_1 exits with exit 1, it cannot speak to the registry.... I cannot figure out why...
```
version: "2"

services:
  portus:
    image: opensuse/portus:2.4.3
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      # SSL
      - PORTUS_PUMA_TLS_KEY=/certificates/portus.key
      - PORTUS_PUMA_TLS_CERT=/certificates/portus.crt

      # NGinx is serving the assets instead of Puma. If you want to change this,
      # uncomment this line.
      - RAILS_SERVE_STATIC_FILES='true'
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db

    volumes:
      - ./secrets:/certificates:ro
      - static:/srv/Portus/public

  background:
    image: opensuse/portus:2.4.3
    depends_on:
      - portus
      - db
    environment:
      # Theoretically not needed, but cconfig's been buggy on this...
      - CCONFIG_PREFIX=PORTUS
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}


      - PORTUS_BACKGROUND=true
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro

  db:
    image: library/mariadb:10.0.23
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      - MYSQL_DATABASE=portus_production

      # Again, the password shouldn't be handled like this.
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - /db_data_test:/var/lib/mysql

  registry:
    image: library/registry:2.6
    command: ["/bin/sh", "/etc/docker/registry/init"]
    environment:
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: https://${MACHINE_FQDN}/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /secrets/portus.crt

      # SSL
      REGISTRY_HTTP_TLS_CERTIFICATE: /secrets/portus.crt
      REGISTRY_HTTP_TLS_KEY: /secrets/portus.key

      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://${MACHINE_FQDN}/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
      - /registry_data/images:/var/lib/registry
      - ./secrets:/secrets:ro
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
      - ./registry/init:/etc/docker/registry/init:ro
    ports:
      - 5000:5000
      - 5001:5001 # required to access debug service
    links:
      - portus:portus

  nginx:
    image: library/nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./secrets:/secrets:ro
      - static:/srv/Portus/public:ro
    ports:
      - 8080:80
      - 443:443
    links:
      - registry:registry
      - portus:portus

volumes:
  static:
    driver: local
```

This is the error from terminal for the background_1
I run this command as root          **docker-compose** -f docker-compose.3.yml up**
```
registry_1    | + cp /secrets/portus.crt /usr/local/share/ca-certificates
registry_1    | + update-ca-certificates
registry_1    | WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
registry_1    | + registry serve /etc/docker/registry/config.yml
registry_1    | time="2019-05-08T20:08:44Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.7.6 instance.id=52e2b562-1311-42c5-9618-49b806072ee2 version=v2.6.2-14-ga66a4c3
registry_1    | time="2019-05-08T20:08:44Z" level=info msg="configuring endpoint portus (https://leap15master.xxxx.net/v2/webhooks/events), timeout=2s, headers=map[]" go.version=go1.7.6 instance.id=52e2b562-1311-42c5-9618-49b806072ee2 version=v2.6.2-14-ga66a4c3
registry_1    | time="2019-05-08T20:08:44Z" level=info msg="redis not configured" go.version=go1.7.6 instance.id=52e2b562-1311-42c5-9618-49b806072ee2 version=v2.6.2-14-ga66a4c3
registry_1    | time="2019-05-08T20:08:44Z" level=info msg="Starting upload purge in 41m0s" go.version=go1.7.6 instance.id=52e2b562-1311-42c5-9618-49b806072ee2 version=v2.6.2-14-ga66a4c3
registry_1    | time="2019-05-08T20:08:44Z" level=info msg="debug server listening :5001"
registry_1    | time="2019-05-08T20:08:44Z" level=info msg="listening on [::]:5000, tls" go.version=go1.7.6 instance.id=52e2b562-1311-42c5-9618-49b806072ee2 version=v2.6.2-14-ga66a4c3
nginx_1       | 2019/05/08 20:08:45 [warn] 1#1: the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/nginx.conf:60
nginx_1       | nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/nginx.conf:60
db_1          | 190508 20:08:42 [Note] mysqld (mysqld 10.0.23-MariaDB-1~jessie) starting as process 1 ...
db_1          | 190508 20:08:42 [Note] InnoDB: Using mutexes to ref count buffer pool pages
db_1          | 190508 20:08:42 [Note] InnoDB: The InnoDB memory heap is disabled
db_1          | 190508 20:08:42 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1          | 190508 20:08:42 [Note] InnoDB: Memory barrier is not used
db_1          | 190508 20:08:42 [Note] InnoDB: Compressed tables use zlib 1.2.8
db_1          | 190508 20:08:42 [Note] InnoDB: Using Linux native AIO
db_1          | 190508 20:08:42 [Note] InnoDB: Using CPU crc32 instructions
db_1          | 190508 20:08:42 [Note] InnoDB: Initializing buffer pool, size = 256.0M
db_1          | 190508 20:08:42 [Note] InnoDB: Completed initialization of buffer pool
db_1          | 190508 20:08:42 [Note] InnoDB: Highest supported file format is Barracuda.
db_1          | 190508 20:08:42 [Note] InnoDB: The log sequence numbers 2323797 and 2323797 in ibdata files do not match the log sequence number 2325746 in the ib_logfiles!
db_1          | 190508 20:08:42 [Note] InnoDB: Database was not shutdown normally!
db_1          | 190508 20:08:42 [Note] InnoDB: Starting crash recovery.
db_1          | 190508 20:08:42 [Note] InnoDB: Reading tablespace information from the .ibd files...
db_1          | 190508 20:08:42 [Note] InnoDB: Restoring possible half-written data pages
db_1          | 190508 20:08:42 [Note] InnoDB: from the doublewrite buffer...
db_1          | 190508 20:08:43 [Note] InnoDB: 128 rollback segment(s) are active.
db_1          | 190508 20:08:43 [Note] InnoDB: Waiting for purge to start
db_1          | 190508 20:08:43 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.26-76.0 started; log sequence number 2325746
db_1          | 190508 20:08:43 [Note] Plugin 'FEEDBACK' is disabled.
db_1          | 190508 20:08:43 [Note] Server socket created on IP: '::'.
db_1          | 190508 20:08:43 [Warning] 'proxies_priv' entry '@% root@dcb99b222a8d' ignored in --skip-name-resolve mode.
db_1          | 190508 20:08:43 [Note] mysqld: ready for connections.
db_1          | Version: '10.0.23-MariaDB-1~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
background_1  | [Mailer config] Host:     leap15master.xxxxx.net
background_1  | [Mailer config] Protocol: https://
portus_1      | Database ready
portus_1      | [43] Puma starting in cluster mode...
portus_1      | [43] * Version 3.10.0 (ruby 2.5.0-p0), codename: Russell's Teapot
portus_1      | [43] * Min threads: 1, max threads: 4
portus_1      | [43] * Environment: production
portus_1      | [43] * Process workers: 4
portus_1      | [43] * Preloading application
background_1  | [Initialization] Running: 'Registry events', 'Registry synchronization'
portus_1      | [Mailer config] Host:     leap15master.xxxxx.net
portus_1      | [Mailer config] Protocol: https://
portus_1      | [43] * Listening on ssl://0.0.0.0:3000?cert=/certificates/portus.crt&key=/certificates/portus.key&verify_mode=none
portus_1      | [43] Use Ctrl-C to stop
portus_1      | [43] - Worker 0 (pid: 46) booted, phase: 0
portus_1      | [43] - Worker 1 (pid: 50) booted, phase: 0
portus_1      | [43] - Worker 2 (pid: 58) booted, phase: 0
portus_1      | [43] - Worker 3 (pid: 61) booted, phase: 0
background_1  | Net::OpenTimeout: connection timed out
background_1  | Exception: Net::OpenTimeout: connection timed out
registry_1    | time="2019-05-08T20:09:18Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.7.6 http.request.host="Leap15Master.xxxxx.net:5000" http.request.id=17deb4c3-9510-4130-90a0-2f040d1ecbf8 http.request.method=GET http.request.remoteaddr="192.168.0.1:60450" http.request.uri="/v2/_catalog?n=100" http.request.useragent=Ruby instance.id=52e2b562-1311-42c5-9618-49b806072ee2 version=v2.6.2-14-ga66a4c3
registry_1    | 192.168.0.1 - - [08/May/2019:20:09:18 +0000] "GET /v2/_catalog?n=100 HTTP/1.1" 401 145 "" "Ruby"
portus_1      | Started GET "/v2/token?account=portus&scope=registry%3Acatalog%3A%2A&service=leap15master.xxxxxx.net" for 192.168.0.6 at 2019-05-08 20:09:18 +0000
portus_1      | Processing by Api::V2::TokensController#show as JSON
portus_1      |   Parameters: {"account"=>"portus", "scope"=>"registry:catalog:*", "service"=>"leap15master.xxxxx.net"}
portus_1      | Completed 200 OK in 211ms (Views: 1.2ms | ActiveRecord: 61.0ms)
nginx_1       | 192.168.0.1 - portus [08/May/2019:20:09:20 +0000] "GET /v2/token?account=portus&scope=registry%3Acatalog%3A%2A&service=leap15master.xxxxxx.net HTTP/1.1" 200 662 "-" "Ruby"
registry_1    | time="2019-05-08T20:09:20Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.7.6 http.request.host="Leap15Master.xxxxxx.net:5000" http.request.id=c814522e-c833-4226-9812-130420f8495c http.request.method=GET http.request.remoteaddr="192.168.0.1:60462" http.request.uri="/v2/_catalog?n=100" http.request.useragent=Ruby instance.id=52e2b562-1311-42c5-9618-49b806072ee2 version=v2.6.2-14-ga66a4c3
registry_1    | 192.168.0.1 - - [08/May/2019:20:09:20 +0000] "GET /v2/_catalog?n=100 HTTP/1.1" 401 145 "" "Ruby"
 background_1  | /srv/Portus/lib/portus/registry_client.rb:182:in `get_page': Something went wrong while fetching the catalog Response: [401] - {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Class":"","Name":"catalog","Action":"*"}]}]} (Portus::RegistryClient::RegistryError)
background_1  |         from /srv/Portus/lib/portus/registry_client.rb:160:in `paged_response'
background_1  |         from /srv/Portus/lib/portus/registry_client.rb:107:in `catalog'
background_1  |         from /srv/Portus/lib/portus/background/sync.rb:63:in `block in execute!'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/relation/batches.rb:51:in `each'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/relation/batches.rb:51:in `block in find_each'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/relation/batches.rb:124:in `find_in_batches'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/relation/batches.rb:50:in `find_each'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/querying.rb:9:in `find_each'
background_1  |         from /srv/Portus/lib/portus/background/sync.rb:62:in `execute!'
background_1  |         from /srv/Portus/bin/background.rb:58:in `block (2 levels) in <top (required)>'
background_1  |         from /srv/Portus/bin/background.rb:56:in `each'
background_1  |         from /srv/Portus/bin/background.rb:56:in `each_with_index'
background_1  |         from /srv/Portus/bin/background.rb:56:in `block in <top (required)>'
background_1  |         from /srv/Portus/bin/background.rb:55:in `loop'
background_1  |         from /srv/Portus/bin/background.rb:55:in `<top (required)>'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/commands/runner.rb:60:in `load'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/commands/runner.rb:60:in `<top (required)>'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/commands/commands_tasks.rb:123:in `require'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/commands/commands_tasks.rb:90:in `runner'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
background_1  |         from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/commands.rb:17:in `<top (required)>'
background_1  |         from bin/rails:12:in `require'
background_1  |         from bin/rails:12:in `<main>'
background_1  | exit status 1
compose_background_1 exited with code 1

```
If I run just the default docker-compose.yml I get this!!!

```
db_1          | 190508 20:14:53 [Note] mysqld (mysqld 10.0.23-MariaDB-1~jessie) starting as process 1 ...
db_1          | 190508 20:14:53 [Note] InnoDB: Using mutexes to ref count buffer pool pages
db_1          | 190508 20:14:53 [Note] InnoDB: The InnoDB memory heap is disabled
db_1          | 190508 20:14:53 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1          | 190508 20:14:53 [Note] InnoDB: Memory barrier is not used
db_1          | 190508 20:14:53 [Note] InnoDB: Compressed tables use zlib 1.2.8
db_1          | 190508 20:14:53 [Note] InnoDB: Using Linux native AIO
db_1          | 190508 20:14:53 [Note] InnoDB: Using CPU crc32 instructions
db_1          | 190508 20:14:53 [Note] InnoDB: Initializing buffer pool, size = 256.0M
db_1          | 190508 20:14:53 [Note] InnoDB: Completed initialization of buffer pool
db_1          | 190508 20:14:53 [Note] InnoDB: Highest supported file format is Barracuda.
db_1          | 190508 20:14:54 [Note] InnoDB: 128 rollback segment(s) are active.
db_1          | 190508 20:14:54 [Note] InnoDB: Waiting for purge to start
db_1          | 190508 20:14:54 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.26-76.0 started; log sequence number 2283249
db_1          | 190508 20:14:54 [Note] Plugin 'FEEDBACK' is disabled.
db_1          | 190508 20:14:54 [Note] Server socket created on IP: '::'.
db_1          | 190508 20:14:54 [Warning] 'proxies_priv' entry '@% root@2bc4c764df6b' ignored in --skip-name-resolve mode.
db_1          | 190508 20:14:54 [Note] mysqld: ready for connections.
db_1          | Version: '10.0.23-MariaDB-1~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
registry_1    | + cp /secrets/portus.crt /usr/local/share/ca-certificates
registry_1    | + update-ca-certificates
registry_1    | WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
registry_1    | + registry serve /etc/docker/registry/config.yml
registry_1    | time="2019-05-08T20:14:55Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.7.6 instance.id=df86fc67-7f1a-48be-8aad-f73d0c5a1c81 version=v2.6.2-14-ga66a4c3
registry_1    | time="2019-05-08T20:14:55Z" level=info msg="configuring endpoint portus (https://leap15master.xxxxx.net/v2/webhooks/events), timeout=2s, headers=map[]" go.version=go1.7.6 instance.id=df86fc67-7f1a-48be-8aad-f73d0c5a1c81 version=v2.6.2-14-ga66a4c3
registry_1    | time="2019-05-08T20:14:55Z" level=info msg="redis not configured" go.version=go1.7.6 instance.id=df86fc67-7f1a-48be-8aad-f73d0c5a1c81 version=v2.6.2-14-ga66a4c3
registry_1    | time="2019-05-08T20:14:55Z" level=info msg="Starting upload purge in 8m0s" go.version=go1.7.6 instance.id=df86fc67-7f1a-48be-8aad-f73d0c5a1c81 version=v2.6.2-14-ga66a4c3
registry_1    | time="2019-05-08T20:14:55Z" level=info msg="debug server listening :5001"
nginx_1       | 2019/05/08 20:14:56 [warn] 1#1: the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/nginx.conf:60
registry_1    | time="2019-05-08T20:14:55Z" level=info msg="listening on [::]:5000, tls" go.version=go1.7.6 instance.id=df86fc67-7f1a-48be-8aad-f73d0c5a1c81 version=v2.6.2-14-ga66a4c3
nginx_1       | nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/nginx.conf:60
portus_1      | /usr/bin/bundle:23:in `load': cannot load such file -- /usr/lib64/ruby/gems/2.6.0/gems/bundler-1.16.4/exe/bundle (LoadError)
portus_1      |         from /usr/bin/bundle:23:in `<main>'
portus_1      | Database ready
background_1  | /usr/bin/bundle:23:in `load': cannot load such file -- /usr/lib64/ruby/gems/2.6.0/gems/bundler-1.16.4/exe/bundle (LoadError)
background_1  |         from /usr/bin/bundle:23:in `<main>'
background_1  | Database ready
portus_1      | [34] Puma starting in cluster mode...
portus_1      | [34] * Version 3.12.1 (ruby 2.6.3-p62), codename: Llamas in Pajamas
portus_1      | [34] * Min threads: 1, max threads: 4
portus_1      | [34] * Environment: production
portus_1      | [34] * Process workers: 4
portus_1      | [34] * Preloading application
portus_1      | [schema] Selected the schema for mysql
portus_1      | [Mailer config] Host:     leap15master.xxxxxx.net
portus_1      | [Mailer config] Protocol: https://
portus_1      | Creating scope :owner. Overwriting existing method TeamUser.owner.
portus_1      | Creating scope :contributor. Overwriting existing method TeamUser.contributor.
portus_1      | Creating scope :viewer. Overwriting existing method TeamUser.viewer.
portus_1      | [34] * Listening on ssl://0.0.0.0:3000?cert=/certificates/portus.crt&key=/certificates/portus.key&verify_mode=none
portus_1      | [34] ! WARNING: Detected 1 Thread(s) started in app boot:
portus_1      | [34] ! #<Thread:0x0000560b19c09408@/srv/Portus/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:299 sleep> - /srv/Portus/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:301:in `sleep'
portus_1      | [34] Use Ctrl-C to stop
portus_1      | [34] - Worker 0 (pid: 36) booted, phase: 0
portus_1      | [34] - Worker 1 (pid: 38) booted, phase: 0
portus_1      | [34] - Worker 3 (pid: 48) booted, phase: 0
portus_1      | [34] - Worker 2 (pid: 41) booted, phase: 0
background_1  | [schema] Selected the schema for mysql
background_1  | [Mailer config] Host:     leap15master.xxxxxx.net
background_1  | [Mailer config] Protocol: https://
background_1  | Creating scope :owner. Overwriting existing method TeamUser.owner.
background_1  | Creating scope :contributor. Overwriting existing method TeamUser.contributor.
background_1  | Creating scope :viewer. Overwriting existing method TeamUser.viewer.
background_1  | /usr/bin/bundle:23:in `load': cannot load such file -- /usr/lib64/ruby/gems/2.6.0/gems/bundler-1.16.4/exe/bundle (LoadError)
background_1  |         from /usr/bin/bundle:23:in `<main>'
registry_1    | 2019/05/08 20:15:10 http: TLS handshake error from 192.168.16.1:42454: tls: first record does not look like a TLS handshake


^^^^This last line just repeats over and over and the IP seems to be different each time. 
```
My registry config is not altered nor is the init script.

I commented out ssl on, in the nginx script as i was seeing the error but the error is persistent. 

I downloaded new images.

I remade the portus secret keys as well as adding my own ca.pem to my server. 

My client side wouldnt even access the registry because i using a self signed cert, even when i added it to my client side OS and to the docker /etc/docker/certs.d/*FDQNRegistry:5000/

Im about to just say screw it and we can use just a simple repo man, this should not be this difficult.... Not trying to be mean or anything but i really dont have anything else. Im at my wits end. 

**FYI** My Insecure portus works fine other than an issue with changing or deleting the namespace gives me a 500 error for the Dashboard.
