### ISSUE TITLE
OAuth2/OpendID connect documentation: How to add multiple client_ids from same domain?

### ISSUE THREAD

**Issue by raolivei** [SUSE/Portus#2207]
### Issue

How to specify more than one client_id + client_secret, for members in the same domain?

### Scenario

We want to be able to add multiple users from the same domain (OAuth2/OpenID Connect). In this particular case, I will be using google_oauth2.

### Steps to reproduce

In`config.yml` (or `config-local.yml` if you prefer) there is the following settings to enable google_oauth2 authentication: 

```yaml
google_oauth2:
    enabled: true
    id: "{{ google_client_id }}"
    secret: "{{ google_client_secret }}"
    domain: "{{ google_domain }}"
    options:
      # G Suite domain. If set, then only members of the domain can sign in/up.
      # If it's empty then any google users con sign in/up.
      hd: ""
```

After spinning up the containers, I can successfully login to Portus using my Google account.
Now I want the service to be available to my colleagues -- for that, I need to specify their client_id and client_secret in the file. But I don't see to find a way to add them.

The latest comment line from the above snippet says that any Google users could be able to sign in/up if a domain is not specified, but I get the following error if client_id/client_secret are not in the desired format:

```400. That’s an error.
Error: invalid_request
Missing required parameter: client_id
Providing logs of the moment when the issue has happened would also be
useful. If you are in production, you might want to set the `PORTUS_LOG_LEVEL`
to `debug` to get a more verbose log.
```

So that makes clear that we need client_id. I have tried to pass more cliend_ids as arguments to the file but that didn't work.

### Portus version
image: opensuse/portus:2.4
