### ISSUE TITLE
"Authorization fails" when deleting application token with admin API call

### ISSUE THREAD

**Issue by kurthaegeman** [SUSE/Portus#2210]
### Description

Using an admin token, I do a DELETE call on the Portus API trying to delete a user's token. The response is an "authorization failed".

### Steps to reproduce

1. As admin, create a user token.
```
POST {{PORTUS_URL}}/api/v1/users/671/application_tokens
Status 201 Created
{
    "id": 879,
    "application": "helloworld3",
    "plain_token": "DuC7HvuzxNHHzxx7MBRC"
}
```

2. List the user's tokens.
```
GET {{PORTUS_URL}}/api/v1/users/671/application_tokens
Status 200 OK
[
    {
        "id": 873,
        "application": "helloworld"
    },
    {
        "id": 876,
        "application": "helloworld2"
    },
    {
        "id": 879,
        "application": "helloworld3"
    }
]
```

3. Try to delete the newly created token.
```
DELETE {{PORTUS_URL}}/api/v1/users/application_tokens/879
Status 403 Forbidden
{
    "message": "Authorization fails"
}
```

- **Expected behavior**: I expected response status 204 No Content and the application token to have been deleted.
- **Actual behavior**: Deletion call fails.

It is possible for the admin to delete its own application tokens.

### Deployment information

**Deployment method**: Portus v2.4.3, running in a Docker container.

**Configuration**:

```yml
[Mailer config] Host:     registry.domain.com
[Mailer config] Protocol: https://
Evaluated configuration:
---
email:
  from: portus@domain.com
  name: Portus
  reply_to: marvin@domain.com
  smtp:
    enabled: true
    address: smtp.domain.com
    port: 30025
    domain: domain.com
    ssl_tls: ''
    enable_starttls_auto: false
    openssl_verify_mode: none
    ca_path: ''
    ca_file: ''
    user_name: ''
    password: "****"
    authentication: login
gravatar:
  enabled: true
delete:
  enabled: true
  contributors: false
  garbage_collector:
    enabled: false
    older_than: 30
    tag: ''
ldap:
  enabled: false
  hostname: ldap_hostname
  port: 389
  timeout: 5
  encryption:
    method: ''
    options:
      ca_file: ''
      ssl_version: TLSv1_2
  base: ''
  filter: ''
  uid: uid
  authentication:
    enabled: false
    bind_dn: ''
    password: "****"
  guess_email:
    enabled: false
    attr: ''
oauth:
  local_login:
    enabled: true
  google_oauth2:
    enabled: false
    id: ''
    secret: ''
    domain: ''
    options:
      hd: ''
  open_id:
    enabled: false
    identifier: ''
    domain: ''
  github:
    enabled: false
    client_id: ''
    client_secret: ''
    organization: ''
    team: ''
    domain: ''
  gitlab:
    enabled: false
    application_id: ''
    secret: ''
    group: ''
    domain: ''
    server: ''
  bitbucket:
    enabled: false
    key: ''
    secret: ''
    domain: ''
    options:
      team: ''
first_user_admin:
  enabled: true
signup:
  enabled: false
check_ssl_usage:
  enabled: true
registry:
  jwt_expiration_time:
    value: 5
  catalog_page:
    value: 100
  timeout:
    value: 2
  read_timeout:
    value: 120
machine_fqdn:
  value: registry.domain.com
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: true
  create_team:
    enabled: true
  manage_team:
    enabled: true
  create_namespace:
    enabled: true
  manage_namespace:
    enabled: true
  create_webhook:
    enabled: true
  manage_webhook:
    enabled: true
  push_images:
    policy: allow-teams
security:
  clair:
    server: ''
    health_port: 6061
    timeout: 900
  zypper:
    server: ''
  dummy:
    server: ''
anonymous_browsing:
  enabled: true
background:
  registry:
    enabled: true
  sync:
    enabled: true
    strategy: on-start
pagination:
  limit: 10
  per_page: 10
  before_after: 2

Portus version: 2.4.3@5a616c0ef860567df5700708256f42505cdb9952

```
