### ISSUE TITLE
OCI images in registry not displayed

### ISSUE THREAD

**Issue by bsx** [SUSE/Portus#2220]
### Description

If the registry contains images in OCI format, these are not displayed in Portus.

### Steps to reproduce

1. Connect Portus 2.4.x to your own docker registry version 2.7.x
2. Push image in OCI format to registry

- **Expected behavior**: Image should show up in Portus UI
- **Actual behavior**: Image cannot be found in Portus

Background sync job reports the following for all OCI images:
```
Code: 404
Reported by Registry:
{"code"=>"MANIFEST_UNKNOWN", "message"=>"OCI manifest found, but accept header does not support OCI manifests"}
```

### Deployment information

**Deployment method**: Portus deployed in k8s.

**Configuration**:

```yml
email:
  from: <redacted>
  name: <redacted>
  reply_to: <redacted>
  smtp:
    enabled: true
    address: email-smtp.eu-west-1.amazonaws.com
    port: 587
    domain: <redacted>
    ssl_tls: ''
    enable_starttls_auto: false
    openssl_verify_mode: none
    ca_path: ''
    ca_file: ''
    user_name: TBD
    password: "****"
    authentication: login
gravatar:
  enabled: false
delete:
  enabled: true
  contributors: false
  garbage_collector:
    enabled: false
    older_than: 30
    tag: ''
ldap:
  enabled: false
  hostname: ldap_hostname
  port: 389
  timeout: 5
  encryption:
    method: ''
    options:
      ca_file: ''
      ssl_version: TLSv1_2
  base: ''
  filter: ''
  uid: uid
  authentication:
    enabled: false
    bind_dn: ''
    password: "****"
  guess_email:
    enabled: false
    attr: ''
oauth:
  local_login:
    enabled: true
  google_oauth2:
    enabled: false
    id: ''
    secret: ''
    domain: ''
    options:
      hd: ''
  open_id:
    enabled: false
    identifier: ''
    domain: ''
  github:
    enabled: false
    client_id: ''
    client_secret: ''
    organization: ''
    team: ''
    domain: ''
  gitlab:
    enabled: false
    application_id: ''
    secret: ''
    group: ''
    domain: ''
    server: ''
  bitbucket:
    enabled: false
    key: ''
    secret: ''
    domain: ''
    options:
      team: ''
first_user_admin:
  enabled: true
signup:
  enabled: false
check_ssl_usage:
  enabled: false
registry:
  jwt_expiration_time:
    value: 15
  catalog_page:
    value: 100
  timeout:
    value: 2
  read_timeout:
    value: 120
machine_fqdn:
  value: <redacted>
display_name:
  enabled: false
user_permission:
  change_visibility:
    enabled: true
  create_team:
    enabled: true
  manage_team:
    enabled: true
  create_namespace:
    enabled: true
  manage_namespace:
    enabled: true
  create_webhook:
    enabled: true
  manage_webhook:
    enabled: true
  push_images:
    policy: allow-teams
security:
  clair:
    server: http://clair:6060
    health_port: 6061
    timeout: 900
  zypper:
    server: ''
  dummy:
    server: ''
anonymous_browsing:
  enabled: false
background:
  registry:
    enabled: true
  sync:
    enabled: true
    strategy: update
pagination:
  limit: 10
  per_page: 10
  before_after: 2
```

**Portus version**: 2.4.3@5a616c0ef860567df5700708256f42505cdb9952
