### ISSUE TITLE
Dashboard error after namespace deleted

### ISSUE THREAD

**Issue by Chilinot** [SUSE/Portus#2222]
### Description
I was cleaning out old namespaces left over after testing the application. Now i cant open the dashboard without it crashing. Everything else works fine though.

### Steps to reproduce

1. I removed a namespace that contained a repository and a tagged image.
2. Attempted to go to dashboard
3. Crash with the following output in the logs:
```
Started GET "/" for 10.0.0.218 at 2019-08-15 14:00:28 +0000
  User Load (0.7ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 3  ORDER BY `users`.`id` ASC LIMIT 1
Processing by DashboardController#index as HTML
   (0.4ms)  SELECT COUNT(*) FROM `registries`
  Team Load (0.3ms)  SELECT `teams`.* FROM `teams` INNER JOIN `team_users` ON `teams`.`id` = `team_users`.`team_id` WHERE `team_users`.`user_id` = 3
  Registry Load (0.3ms)  SELECT  `registries`.* FROM `registries`  ORDER BY `registries`.`id` ASC LIMIT 1
  PublicActivity::Activity Load (0.5ms)  SELECT  `activities`.* FROM `activities` INNER JOIN webhooks ON activities.trackable_id = webhooks.id INNER JOIN namespaces ON namespaces.id = webhooks.namespace_id INNER JOIN teams ON teams.id = namespaces.team_id INNER JOIN team_users ON teams.id = team_users.team_id WHERE (activities.trackable_type = 'Webhook' AND team_users.user_id = 3)  ORDER BY `activities`.`id` DESC LIMIT 20
   (0.3ms)  SELECT `team_users`.`team_id` FROM `team_users` WHERE `team_users`.`user_id` = 3
   (0.4ms)  SELECT `namespaces`.`id` FROM `namespaces` WHERE `namespaces`.`team_id` IN (1, 5, 7)
Scoped order and limit are ignored, it's forced to be batch order and batch size
  PublicActivity::Activity Load (0.3ms)  SELECT  DISTINCT `activities`.* FROM `activities` WHERE (activities.trackable_type = 'Webhook')  ORDER BY `activities`.`id` ASC LIMIT 1000
   (0.6ms)  SELECT COUNT(*) FROM `users` WHERE `users`.`username` = 'portus'
  Namespace Load (0.3ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`id` = 5 LIMIT 1
  Rendered dashboard/partials/_portus_user_alert.html.slim (3.0ms)
  CACHE (0.0ms)  SELECT COUNT(*) FROM `registries`
   (0.8ms)  SELECT COUNT(*) FROM `users` WHERE (`users`.`username` != 'portus') AND `users`.`enabled` = 1
   (0.3ms)  SELECT COUNT(*) FROM `teams` WHERE `teams`.`hidden` = 0
   (0.2ms)  SELECT COUNT(*) FROM `namespaces`
  Rendered dashboard/partials/_stats.html.slim (11.5ms)
  PublicActivity::Activity Load (0.7ms)  SELECT  DISTINCT `activities`.* FROM ( (SELECT `activities`.* FROM ( (SELECT `activities`.* FROM ( (SELECT `activities`.* FROM ( (SELECT `activities`.* FROM ( (SELECT  `activities`.* FROM `activities` WHERE (activities.trackable_type = 'Team' AND activities.trackable_id IN (1,5,7))  ORDER BY `activities`.`id` DESC LIMIT 20) UNION ALL (SELECT  `activities`.* FROM `activities` WHERE (activities.trackable_type = 'Registry' AND activities.trackable_id IN (1))  ORDER BY `activities`.`id` DESC LIMIT 20) ) activities) UNION ALL (SELECT  `activities`.* FROM `activities` INNER JOIN namespaces ON activities.trackable_id = namespaces.id WHERE (activities.trackable_type = 'Namespace' AND (namespaces.team_id IN (1,5,7) OR (activities.key = 'namespace.change_visibility' AND namespaces.visibility = 2)))  ORDER BY `activities`.`id` DESC LIMIT 20) ) activities) UNION ALL (SELECT  `activities`.* FROM `activities` INNER JOIN repositories ON activities.trackable_id = repositories.id INNER JOIN namespaces ON namespaces.id = repositories.namespace_id WHERE (activities.trackable_type = 'Repository' AND (namespaces.team_id IN (1,5,7) OR namespaces.visibility = 2))  ORDER BY `activities`.`id` DESC LIMIT 20) ) activities) UNION ALL (SELECT  `activities`.* FROM `activities` WHERE (activities.trackable_type = 'ApplicationToken' AND activities.owner_id = 3)  ORDER BY `activities`.`id` DESC LIMIT 20) ) activities) UNION ALL (SELECT `activities`.* FROM `activities` WHERE 1=0) ) activities  ORDER BY `activities`.`id` DESC LIMIT 20
  User Load (0.7ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 3 LIMIT 1
  Rendered public_activity/application_token/_destroy.html.slim (14.1ms)
  CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 3 LIMIT 1  [["id", 3]]
  Rendered public_activity/application_token/_create.html.slim (10.3ms)
  CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 3 LIMIT 1  [["id", 3]]
  Rendered public_activity/registry/_delete.html.slim (4.4ms)
  CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 3 LIMIT 1  [["id", 3]]
  Rendered public_activity/namespace/_delete.html.slim (4.5ms)
  CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 3 LIMIT 1  [["id", 3]]
  Registry Load (0.3ms)  SELECT  `registries`.* FROM `registries` WHERE `registries`.`id` = 1 LIMIT 1
  Namespace Load (0.4ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`id` = 9 LIMIT 1
  CACHE (0.0ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`id` = 9 LIMIT 1  [["id", 9]]
  Rendered public_activity/repository/_delete.html.slim (7.1ms)
  CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 3 LIMIT 1  [["id", 3]]
  Namespace Load (0.4ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`id` = 11 LIMIT 1
  Rendered public_activity/namespace/_change_visibility.html.slim (5.7ms)
  CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 3 LIMIT 1  [["id", 3]]
  Rendered public_activity/namespace/_delete.html.slim (0.7ms)
  CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 3 LIMIT 1  [["id", 3]]
  CACHE (0.0ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`id` = 5 LIMIT 1  [["id", 5]]
  CACHE (0.0ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`id` = 5 LIMIT 1  [["id", 5]]
  Rendered public_activity/repository/_delete.html.slim (1.4ms)
  User Load (0.6ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 5 LIMIT 1
  Repository Load (0.3ms)  SELECT  `repositories`.* FROM `repositories` WHERE `repositories`.`id` = 5 LIMIT 1
  CACHE (0.0ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`id` = 11 LIMIT 1  [["id", 11]]
  Tag Load (0.3ms)  SELECT  `tags`.* FROM `tags` WHERE `tags`.`id` = 11 LIMIT 1
  Rendered public_activity/repository/_push.html.slim (16.8ms)
  CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 5 LIMIT 1  [["id", 5]]
  CACHE (0.0ms)  SELECT  `repositories`.* FROM `repositories` WHERE `repositories`.`id` = 5 LIMIT 1  [["id", 5]]
  CACHE (0.0ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`id` = 11 LIMIT 1  [["id", 11]]
  Tag Load (0.4ms)  SELECT  `tags`.* FROM `tags` WHERE `tags`.`id` = 9 LIMIT 1
  Rendered public_activity/repository/_push.html.slim (2.6ms)
  CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 3 LIMIT 1  [["id", 3]]
  Namespace Load (0.3ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`id` = 1 LIMIT 1
  Rendered public_activity/namespace/_change_visibility.html.slim (1.5ms)
  CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 3 LIMIT 1  [["id", 3]]
  CACHE (0.0ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`id` = 11 LIMIT 1  [["id", 11]]
  Rendered public_activity/namespace/_change_visibility.html.slim (1.2ms)
  CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 3 LIMIT 1  [["id", 3]]
  Rendered public_activity/namespace/_change_visibility.html.slim (0.8ms)
  CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 5 LIMIT 1  [["id", 5]]
  CACHE (0.0ms)  SELECT  `repositories`.* FROM `repositories` WHERE `repositories`.`id` = 5 LIMIT 1  [["id", 5]]
  CACHE (0.0ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`id` = 11 LIMIT 1  [["id", 11]]
  Tag Load (0.4ms)  SELECT  `tags`.* FROM `tags` WHERE `tags`.`id` = 7 LIMIT 1
  Rendered public_activity/repository/_push.html.slim (2.4ms)
  CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 5 LIMIT 1  [["id", 5]]
  CACHE (0.0ms)  SELECT  `repositories`.* FROM `repositories` WHERE `repositories`.`id` = 5 LIMIT 1  [["id", 5]]
  CACHE (0.0ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`id` = 11 LIMIT 1  [["id", 11]]
  Tag Load (0.3ms)  SELECT  `tags`.* FROM `tags` WHERE `tags`.`id` = 5 LIMIT 1
  Rendered public_activity/repository/_push.html.slim (2.3ms)
  CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 3 LIMIT 1  [["id", 3]]
  Rendered public_activity/namespace/_change_visibility.html.slim (0.7ms)
  CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 3 LIMIT 1  [["id", 3]]
  CACHE (0.0ms)  SELECT  `registries`.* FROM `registries` WHERE `registries`.`id` = 1 LIMIT 1  [["id", 1]]
  PublicActivity::Activity Load (0.5ms)  SELECT DISTINCT `activities`.* FROM ( (SELECT `activities`.* FROM ( (SELECT `activities`.* FROM ( (SELECT `activities`.* FROM ( (SELECT `activities`.* FROM ( (SELECT  `activities`.* FROM `activities` WHERE (activities.trackable_type = 'Team' AND activities.trackable_id IN (1,5,7))  ORDER BY `activities`.`id` DESC LIMIT 20) UNION ALL (SELECT  `activities`.* FROM `activities` WHERE (activities.trackable_type = 'Registry' AND activities.trackable_id IN (1))  ORDER BY `activities`.`id` DESC LIMIT 20) ) activities) UNION ALL (SELECT  `activities`.* FROM `activities` INNER JOIN namespaces ON activities.trackable_id = namespaces.id WHERE (activities.trackable_type = 'Namespace' AND (namespaces.team_id IN (1,5,7) OR (activities.key = 'namespace.change_visibility' AND namespaces.visibility = 2)))  ORDER BY `activities`.`id` DESC LIMIT 20) ) activities) UNION ALL (SELECT  `activities`.* FROM `activities` INNER JOIN repositories ON activities.trackable_id = repositories.id INNER JOIN namespaces ON namespaces.id = repositories.namespace_id WHERE (activities.trackable_type = 'Repository' AND (namespaces.team_id IN (1,5,7) OR namespaces.visibility = 2))  ORDER BY `activities`.`id` DESC LIMIT 20) ) activities) UNION ALL (SELECT  `activities`.* FROM `activities` WHERE (activities.trackable_type = 'ApplicationToken' AND activities.owner_id = 3)  ORDER BY `activities`.`id` DESC LIMIT 20) ) activities) UNION ALL (SELECT `activities`.* FROM `activities` WHERE 1=0) ) activities
  Repository Load (0.3ms)  SELECT `repositories`.* FROM `repositories`
  PublicActivity::Activity Load (0.3ms)  SELECT  `activities`.* FROM `activities`  ORDER BY `activities`.`created_at` DESC LIMIT 20
  Repository Load (0.3ms)  SELECT `repositories`.* FROM `repositories` WHERE `repositories`.`namespace_id` = 5
  Star Load (0.2ms)  SELECT `stars`.* FROM `stars` WHERE `stars`.`user_id` = 3  ORDER BY updated_at desc
  Rendered public_activity/namespace/_change_namespace_description.html.slim (49.6ms)
  Rendered dashboard/partials/_recent_activities.html.slim (175.0ms)
  Rendered dashboard/index.html.slim within layouts/application (217.0ms)
Completed 401 Unauthorized in 296ms (ActiveRecord: 20.8ms)

ActionView::Template::Error (undefined method `registry_path' for #<#<Class:0x0000000004b79630>:0x0000000004bced60>
Did you mean?  repository_path):
    12:         - else
    13:           strong
    14:             = "#{activity_owner(activity)} edited the description of the namespace "
    15:         = link_to activity.trackable.name, activity.trackable
    16:       small
    17:         i.fa.fa-clock-o
    18:         = activity_time_tag activity.created_at
  app/views/public_activity/namespace/_change_namespace_description.html.slim:15:in `_app_views_public_activity_namespace__change_namespace_description_html_slim___106994446458002559_69954586442300'
  app/views/dashboard/partials/_recent_activities.html.slim:23:in `block in _app_views_dashboard_partials__recent_activities_html_slim__3468944930485379505_28863700'
  app/views/dashboard/partials/_recent_activities.html.slim:22:in `_app_views_dashboard_partials__recent_activities_html_slim__3468944930485379505_28863700'
  app/views/dashboard/index.html.slim:6:in `_app_views_dashboard_index_html_slim___1858305548689483363_39741080'
  app/middleware/catch_json_parse_errors.rb:11:in `call'


Processing by ErrorsController#show as HTML
  Parameters: {"status"=>"500"}
  Rendered errors/500.html.erb within layouts/errors (0.6ms)
  Rendered errors/_status_title.html.slim (1.7ms)
Completed 500 Internal Server Error in 15ms (Views: 14.9ms | ActiveRecord: 0.0ms)
```

### Deployment information

**Configuration**:
```yaml
version: '3.7'

services:
  portus:
    image: opensuse/portus:2.4.3
    environment:
      CCONFIG_PREFIX: PORTUS
      PORTUS_MACHINE_FQDN_VALUE: xxxx
      RAILS_SERVE_STATIC_FILES: "true"

      # Email
      PORTUS_EMAIL_FROM: 'xxxx'
      PORTUS_EMAIL_NAME: 'xxxxx'
      PORTUS_EMAIL_SMTP_ENABLED: 'true'
      PORTUS_EMAIL_SMTP_ADDRESS: 'xxxxx'
      PORTUS_EMAIL_SMTP_PORT: 'xxx'
      PORTUS_EMAIL_SMTP_SSL_TLS: 'xxx'
      PORTUS_EMAIL_SMTP_USER_NAME: 'xxxxxx'
      PORTUS_EMAIL_SMTP_PASSWORD_FILE: /run/secrets/portus_smtp-password
      PORTUS_EMAIL_SMTP_AUTHENTICATION: 'login'

      # Security
      PORTUS_SECRET_KEY_BASE_FILE: /run/secrets/portus_secret-key-base
      PORTUS_KEY_PATH: /run/secrets/portus_certificate-key
      PORTUS_PASSWORD_FILE: /run/secrets/portus_password

      # - Disable SSL, Traefik will handle it externaly
      PORTUS_CHECK_SSL_USAGE_ENABLE: "false"

      # Database
      PORTUS_DB_HOST: xxxx
      PORTUS_DB_PORT: xxx
      PORTUS_DB_DATABASE: xxxxx
      PORTUS_DB_USERNAME: xxxxx
      PORTUS_DB_PASSWORD_FILE: /run/secrets/portus_db-password
      PORTUS_DB_POOL: 5
    secrets:
      - portus_secret-key-base
      - portus_certificate-key
      - portus_password
      - portus_db-password
      - portus_smtp-password
    networks:
      - traefik-public
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.port=3000
        - traefik.tags=traefik-public
        - traefik.app.frontend.rule=Host:xxxxxx;PathPrefix:/
        - traefik.app.frontend.priority=10
        - traefik.api.frontend.rule=Host:xxxxxxx;PathPrefix:/v2/webhooks/events,/v2/token
        - traefik.api.frontend.priority=40
      placement:
        constraints:
          - node.role == worker

  # Runs tasks in the background, such as handle events etc
  background:
    image: opensuse/portus:2.4.3
    environment:
      PORTUS_BACKGROUND: "true"
      CCONFIG_PREFIX: PORTUS
      PORTUS_MACHINE_FQDN_VALUE: xxxxxx
      # Database
      PORTUS_DB_HOST: xxxxx
      PORTUS_DB_PORT: xxxxx
      PORTUS_DB_DATABASE: xxxxx
      PORTUS_DB_USERNAME: xxxxx
      PORTUS_DB_PASSWORD_FILE: /run/secrets/portus_db-password
      PORTUS_DB_POOL: 5
      # Security
      PORTUS_SECRET_KEY_BASE_FILE: /run/secrets/portus_secret-key-base
      PORTUS_KEY_PATH: /run/secrets/portus_certificate-key
      PORTUS_PASSWORD_FILE: /run/secrets/portus_password
    networks:
      - traefik-public
    secrets:
      - portus_secret-key-base
      - portus_certificate-key
      - portus_password
      - portus_db-password
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  registry:
    image: registry:2.6
    environment:
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: xxxxx
      REGISTRY_AUTH_TOKEN_SERVICE: xxxxxx
      REGISTRY_AUTH_TOKEN_ISSUER: xxxxx
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /run/secrets/portus_certificate

      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: http://portus:3000/v2/webhooks/events
          timeout: 500ms
          threshold: 5
          backoff: 1s
    secrets:
      - portus_certificate
    configs:
      - source: portus_registry
        target: /etc/docker/registry/config.yml
    volumes:
      - /nfs/docker/docker-registry/registry:/var/lib/registry
    networks:
      - traefik-public
    depends_on:
      - portus
      - background
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.port=5000
        - traefik.tags=traefik-public
        - traefik.frontend.rule=Host:xxxxxx;PathPrefix:/v2
        - traefik.frontend.priority=20
      placement:
        constraints:
          - node.role == worker
```
