### ISSUE TITLE
"Insufficient scope" when trying to upload image

### ISSUE THREAD

**Issue by Kulturserver** [SUSE/Portus#2239]
We are unable to upload an image in Version 2.5.0-dev@a1b9f2ebfeb84680a9dcd5629195e4c52815735c and get the message "error authorizing context: insufficient scope" - changing the registry according to the issues https://github.com/SUSE/Portus/issues/1736 or https://github.com/SUSE/Portus/issues/2216 did unfortunately not solve the problem. If anybody has another idea, help would be highly appreciated. Thanks!

> 172.19.0.6 - - [09/Oct/2019:08:24:25 +0000] "POST /v2/sa/php7.3-nginx/blobs/uploads/ HTTP/1.0" 401 232 "" "docker/19.03.0-beta2
go/go1.12.4 git-commit/c601560 kernel/4.19.0-5-amd64 os/linux arch/amd64
UpstreamClient(Docker-Client/19.03.0-beta2 \(linux\))"time="2019-10-09T08:24:25Z" level=warning msg="error authorizing context: insufficient scope" go.version=go1.7.6 http.request.host=hub.culturebase.org
http.request.id=55a0f7a2-5a7c-4fd9-88d4-6ad3242dbd68 http.request.method=POST
http.request.remoteaddr=87.123.130.120 http.request.uri="/v2/sa/php7.3-nginx/blobs/uploads/
" http.request.useragent="docker/19.03.0-beta2 go/go1.12.4 git-commit/c601560
kernel/4.19.0-5-amd64 os/linux arch/amd64
UpstreamClient(Docker-Client/19.03.0-beta2 \(linux\))" instance.id=128b2192-fd36-417eacb9-0cbb3d5ed356
vars.name="sa/php7.3-nginx" version=v2.6.2-14-ga66a4c3
172.19.0.6 - - [09/Oct/2019:08:24:25 +0000] "POST /v2/sa/php7.3-nginx/blobs/uploads/ HTTP/1.0" 401 232 "" "docker/19.03.0-beta2 go/go1.12.4 git-commit/c601560 kernel/4.19.0-5-amd64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.0-beta2 \(linux\))"

**Comment by Kulturserver** [comment]
Unfortunately, we didn't manage to solve this problem yet. It seems that the registry isn't able to contact the portus instance. It would be great, if anybody had a proposition how we could track this behaviour in detail. Thanks!

**Comment by Kulturserver** [comment]
Sorry to keep insisting, but we still aren't able to get beyond this error. Any help would be appreciated. Thanks!

**Comment by mssola** [comment]
It must be a configuration error somewhere. Are you using any of the provided examples, by any chance? Could you paste here the configuration that you are using (e.g. docker-compose.yml, etc.)? Be extra careful with getting fqdn's right and generating certificates properly.

**Comment by Kulturserver** [comment]
Thanks for your reply! As for the configuration, here is our docker-compose.yml:

`version: "2"

services:
  portus:
    image: opensuse/portus:head
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      # SSL
      - PORTUS_PUMA_TLS_KEY=/certificates/portus.key
      - PORTUS_PUMA_TLS_CERT=/certificates/portus.crt

      # NGinx is serving the assets instead of Puma. If you want to change this,
      # uncomment this line.
      #- RAILS_SERVE_STATIC_FILES='true'
    ports:
      - 3000:3000
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro
      - static:/srv/Portus/public

  background:
    image: opensuse/portus:head
    depends_on:
      - portus
      - db
    environment:
      # Theoretically not needed, but cconfig's been buggy on this...
      - CCONFIG_PREFIX=PORTUS
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      - PORTUS_BACKGROUND=true
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro

  db:
    image: library/mariadb:10.0.23
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      - MYSQL_DATABASE=portus_production

      # Again, the password shouldn't be handled like this.
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - /var/opt/docker/data/mariadb:/var/lib/mysql

  registry:
    image: library/registry:2.6
    command: ["/bin/sh", "/etc/docker/registry/init"]
    environment:
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: https://${MACHINE_FQDN}/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /secrets/portus.crt

      # SSL
      REGISTRY_HTTP_TLS_CERTIFICATE: /secrets/portus.crt
      REGISTRY_HTTP_TLS_KEY: /secrets/portus.key

      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://${MACHINE_FQDN}/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
      - /var/opt/docker/data/registry:/var/lib/registry
      - ./secrets:/secrets:ro
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
      - ./registry/init:/etc/docker/registry/init:ro
    ports:
      - 5000:5000
      - 5001:5001 # required to access debug service
    links:
      - portus:portus

  nginx:
    image: library/nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./secrets:/secrets:ro
      - static:/srv/Portus/public:ro
    ports:
      - 81:80
      - 444:443
    links:
      - registry:registry
      - portus:portus

volumes:
  static:
    driver: local
`

In the same directory, there is a .env-file with the following content:
`MACHINE_FQDN=images.culturebase.org

SECRET_KEY_BASE=jköjjkljoiuoiuzuizuizuizpuzpuoijoiuzzitzz

PORTUS_PASSWORD=password-for-portus

DATABASE_PASSWORD=dbpassword`

and those are further subdirectories:

- data: Directory to store the MariaDB-Content

- registry: configuration and Start-Script for Registry (config.yml and init).

- nginx: the nginx-Configuration-file nginx.conf

- secrets: a self-Generated and signed Certificate + Key (images.culturebase.org)

**Comment by mssola** [comment]
In principle this looks fine (unless I'm missing something). Usually these kinds of errors occur because of wrong certificates, for example (e.g. the FQDN of the certificate not being set to the one configured on the registry's or the portus' config, badly generated certificates, etc.). So, one tip I can give you is to generate different kinds of certificates with different FQDN values (or better yet, try out non-self signed certificates on a staging environment). Otherwise, and just to clear out silly mistakes, can you post the log of docker-compose when running with this configuration?

**Comment by Jean-Baptiste-Lasselle** [comment]
> culturebase.org

HI @Kulturserver , maybe this will help you : https://github.com/SUSE/Portus/issues/2264#issuecomment-565684494

**Comment by Jean-Baptiste-Lasselle** [comment]
> ```yaml
>       REGISTRY_NOTIFICATIONS_ENDPOINTS: >
>         - name: portus
>           url: https://${MACHINE_FQDN}/v2/webhooks/events
>           timeout: 2000ms
>           threshold: 5
>           backoff: 1s
> ```

@Kulturserver I think I found your mistake in your configuration, I made the exact same, but trickier, you will understand why : 
* First, what is wrong in your configuration, is one variable value, inside your `docker-compose.yml` file, applied to the `registry` service : the `REGISTRY_NOTIFICATIONS_ENDPOINTS` .
* You set `REGISTRY_NOTIFICATIONS_ENDPOINTS` to a value including `url: https://${MACHINE_FQDN}/v2/webhooks/events`,  but the value should be `url: https://${MACHINE_FQDN}:3000/v2/webhooks/events` instead. 
* Once you did the config change, just `docker-compose up -d --force-recreate` : this will bring everything backup, with no data loss (I tested it, including users and user permissions, application token etc...) 
*  I really hate those one-off starters like the one you started from like all of us : from the docuemntation. Here the problem is that `MACHINE_FQDN` is used here to reach the `portus` service, and somewhere else in the code to reach the `registry` serice, which makes it all a b***dy hell of a spaghetti dish. In our case, and as your logs inform you, `REGISTRY_NOTIFICATIONS_ENDPOINTS` ' s `url` is used by the docker `registry`, in conformity with their _docker auth_ spec, to send an HTTP request to (anyone you like, as you configure), in order to notify an event occured,like : 
*  the `docker push` of you `rocket.chat`  image has sucessfully completed
*  or this person just pulled that image from that namespace 
* and that's how `portus` updates its webpages, displaying list of repositories in a name space... 

see details in https://github.com/SUSE/Portus/issues/2264#issuecomment-565684494

Hope it helps, and the team did not die since October 30 ....

**Comment by Kulturserver** [comment]
Hi Jean-Baptiste, thanks a lot for your reply! Unfortunately, changing the registry notifications endpoints like you suggested didn't solve our problem yet, but we won't give up on this...

**Comment by Kulturserver** [comment]
@mssola : Here are the logs you requested, maybe they can shed a light on the problem...
[registry.log](https://github.com/SUSE/Portus/files/3967716/registry.log)
[portus.log](https://github.com/SUSE/Portus/files/3967717/portus.log)

**Comment by Jean-Baptiste-Lasselle** [comment]
> > culturebase.org
> 
> HI @Kulturserver , maybe this will help you : [#2264 (comment)](https://github.com/SUSE/Portus/issues/2264#issuecomment-565684494) . Did you have any progress with using `portus` ?

Hi @Kulturserver apleasure, I'm justy sharing the understanding andthrill I had those last7 days Ispent discovring portus. 
I'm happy and will be eager to share experience on operating production `portus` services, so I'll help you furher,  and i'm curious to know the bottom issue you experience : 
* so I looked up your logs : can you provide logs of the `background` container, in addition of those of  `portus` and `registry`
* what  I read in your `registry` logs : well you're trying todocker push an image, and in the terminal you just get with an error : your image is not pushed to the docker registry to start with,so don't even need to go further in portus 
* but i did go further,and indeed you can see in the registry's logs    : 
```bash
time="2019-12-16T10:23:31Z" level=info msg="configuring endpoint portus (https://images.culturebase.org:3000/v2/webhooks/events), timeout=2s, headers=map[]" go.version=go1.7.6 instance.id=8157cf56-498c-4a44-9ec7-701ea5a7d6f6 version=v2.6.2-14-ga66a4c3 
```

**Comment by Jean-Baptiste-Lasselle** [comment]
> @mssola : Here are the logs you requested, maybe they can shed a light on the problem...it would also be very helpful for us if there is a way to check and verify certificates?
> [registry.log](https://github.com/SUSE/Portus/files/3967716/registry.log)
> [portus.log](https://github.com/SUSE/Portus/files/3967717/portus.log)

TO checkyour certifcates, it's very simple : 

```bash
curl  https://images.culturebase.org:3000
# the port number is really important, unless you have a reverseproxy.
# the machine from where your execute that curl command should be the machine where you execute [docker push]
# curl will then tell you if there's any problem with the certificate, and if 
# succeeds, will tell you it completed OK with code `200` and display in
# stdout some HTML
```

**Comment by Jean-Baptiste-Lasselle** [comment]
@Kulturserver I found another problem in your configuration, un comment this line in your `docker-compose.yml` : 

```Yaml
    - RAILS_SERVE_STATIC_FILES='true'
```
I immediately saw that because your have an error on https://images.culturebase.org:3000/, well know from community, which is an error inthe webpage, coming from the frontend components : 

```bash
Error compiling CSS Assets
"SassC::SyntaxError: Error: File to import not found or unreadable: raleway."         on line 3 of 'app/assets/stylesheets/application.scss' >> @import "raleway";

"/srv/Portus/app/assets/stylesheets/application.scss:3"
 
```


I think your instance on `3000` port is a different (lab) instance, from your production env at port `80`, isn't it?

**Comment by Kulturserver** [comment]
Thanks a lot for your effort, @Jean-Baptiste-Lasselle ! We've checked the issues you reported, but are still running into trouble unfortunately.

- The SSL certificate is valid, curl shows the page without errors. (*  SSL certificate verify ok.)

- Regarding Issue #2264:
  - Different tags didn't bring any change / success
  - Even in the user's own namespace like https://images.culturebase.org/username/php7-nginx only "permission denied" appears.
- docker login images.culturebase.org (and images.culturebase.org:5000) works without errors
- The namespace has all necessary rights
- But still a push into the user's namespace doesn't work.

- our setup:

- images.culturebase.org: is the basic host, on which docker is running
  - nginx with port 443 and vhost images.culturebase.org - config:

>server {
>    listen 443 ssl;
>    listen [::]:443 ssl;
>    ssl_certificate /etc/nginx/ssl/STAR_culturebase_org.crt;
>    ssl_certificate_key /etc/nginx/ssl/STAR_culturebase_org.key;
>    server_name images.culturebase.org;
>    index index.php;
>    include include/php.conf;
>    access_log /var/log/nginx/images.culturebase.org-access.log;
>    error_log /var/log/nginx/images.culturebase.org-error.log;
>    location / {
>      proxy_pass https://localhost:444;
>      proxy_set_header Host $http_host;
>      proxy_set_header X-Real-IP $remote_addr;
>      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>      proxy_set_header X-Forwarded-Proto $scheme;
>   }
>}

- the docker nginx runs on port 444
- Docker-Portus on port 3000
- Docker-Registry on port 5000

- docker ps:
> CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                                      NAMES
> 
> db48ac2dfa7e        nginx:alpine           "nginx -g 'daemon of…"   18 minutes ago      Up 18 minutes       0.0.0.0:81->80/tcp, 0.0.0.0:444->443/tcp   docker_nginx_1
> 
> 549692e35aae        registry:2.6           "/entrypoint.sh /bin…"   18 minutes ago      Up 18 minutes       0.0.0.0:5000-5001->5000-5001/tcp           docker_registry_1
> 
> 014f5c2f174f        opensuse/portus:head   "/init"                  18 minutes ago      Up 18 minutes       0.0.0.0:3000->3000/tcp                     docker_portus_1
> 
> bf437b848b85        mariadb:10.0.23        "/docker-entrypoint.…"   18 minutes ago      Up 18 minutes       3306/tcp                                   docker_db_1
> 

As you can see, the docker_background container is missing here. I'm attaching another log as you with regarding stderr/stdout.

Thanks again!
[portus2.log](https://github.com/SUSE/Portus/files/3978775/portus2.log)

**Comment by Jean-Baptiste-Lasselle** [comment]
>     * namespace

hi @Kulturserver thank you so much for the provided details, I'll have a look at that tomorrow, and will return with further analysis asap.

**Comment by Kulturserver** [comment]
Thanks again! 

OK, the portus_Background_container process is not running. I found the
following error-messages by running docker logs docker_background_1:

/usr/bin/bundle:23:in `load': cannot load such file --
/usr/lib64/ruby/gems/2.6.0/gems/bundler-1.16.4/exe/bundle (LoadError)
    from /usr/bin/bundle:23:in `<main>'
   Database ready
[schema] Selected the schema for mysql
[Mailer config] Host:     images.culturebase.org
[Mailer config] Protocol: https://
Creating scope :owner. Overwriting existing method TeamUser.owner.
Creating scope :contributor. Overwriting existing method TeamUser.contributor.
Creating scope :viewer. Overwriting existing method TeamUser.viewer.
/usr/bin/bundle:23:in `load': cannot load such file --
/usr/lib64/ruby/gems/2.6.0/gems/bundler-1.16.4/exe/bundle (LoadError)
 from /usr/bin/bundle:23:in `<main>'
   /srv/Portus/lib/portus/registry_client.rb:197:in `get_page':
   Something went wrong while fetching the catalog Response: [401]

 - {"errors":[{"code":"UNAUTHORIZED"
 ,"message":"authentication required","detail":[{"Type":"registry","Class":"","Name":"catalog","Action":"*"}]}]}
 (Portus::RegistryClient::RegistryError)
 from /srv/Portus/lib/portus/registry_client.rb:174:in
 `paged_response'
 from /srv/Portus/lib/portus/registry_client.rb:121:in `catalog'
 from /srv/Portus/lib/portus/background/sync.rb:63:in `block in execute!'
 from /srv/Portus/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/relation/batches.rb:70:in
    `block (2 levels) in find_each'
 from /srv/Portus/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/relation/batches.rb:70:in `each'
 from /srv/Portus/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/relation/batches.rb:70:in `block in find_each'
 from
 /srv/Portus/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/relation/batches.rb:136:in `block in
  find_in_batches'
 from /srv/Portus/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/relation/batches.rb:238:in `block in
    in_batches'
 from /srv/Portus/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/relation/batches.rb:222:in `loop'
 from /srv/Portus/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/relation/batches.rb:222:in `in_batches'
 from /srv/Portus/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/relation/batches.rb:135:in `find_in_batches'
 from /srv/Portus/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/relation/batches.rb:69:in `find_each'
 from /srv/Portus/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/querying.rb:11:in `find_each'
 from /srv/Portus/lib/portus/background/sync.rb:62:in `execute!'
 from /srv/Portus/bin/background.rb:61:in `block (2 levels) in <top required)>'
 from /srv/Portus/bin/background.rb:58:in `each'
 from /srv/Portus/bin/background.rb:58:in `each_with_index'
 from /srv/Portus/bin/background.rb:58:in `block in top (required)>'
 from /srv/Portus/bin/background.rb:57:in `loop'
 from /srv/Portus/bin/background.rb:57:in `<top (required)>'
 from /srv/Portus/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/commands/runner/runner_command.rb:38:in `load'
 from /srv/Portus/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/commands/runner/runner_command.rb:38:in `perform'
 from /srv/Portus/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
 from /srv/Portus/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
 from /srv/Portus/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
 from /srv/Portus/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/command/base.rb:65:in `perform'
 from /srv/Portus/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/command.rb:46:in `invoke'
 from /srv/Portus/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<top (required)>'
 from bin/rails:12:in `require'
 from bin/rails:12:in `<main>'
[Initialization] Running: 'Registry events', Registry synchronization'

exit status 1

**Comment by Jean-Baptiste-Lasselle** [comment]
> docker_background_1

HI @Kulturserver (happy newyear), so, you see this in your background logs : 

```bash
Something went wrong while fetching the catalog Response: [401]

{"errors":[{"code":"UNAUTHORIZED"
,"message":"authentication required","detail":[{"Type":"registry","Class":"","Name":"catalog","Action":"*"}]}]}
(Portus::RegistryClient::RegistryError)
```

That means your `background` service is requesting access the `docker registry API`, more exactly the `catalog` endpoint, exactly this one : https://docs.docker.com/registry/spec/api/#listing-repositories

To do that, your `background` has to authenticate to `registry`, using both : 
* the `portus` token issuer service (set by `REGISTRY_AUTH_TOKEN_SERVICE` and `REGISTRY_AUTH_TOKEN_SERVICE` env. vars. in your `docker-compose.yml`), 
* and the token service of  `registry` (set by `REGISTRY_AUTH_TOKEN_ISSUER` env. var. in your `docker-compose.yml`).
 
###  What I propose your next

* _First test_ (reproduceability) : run this and confirm you don't have any change in the background service logs (exact same error) : 

```bash
docker-compose up -d --force-recreate background && docker-compose logs -f
```

* _Second test_ (network configuration) :  I also see today one mistake I think, in your `docker-compose.yml`.
  * first, add this line into your `.env` (create `.env` file if does not exists) : 

```bash
OCI_REGISTRY_SERVICE_FQDN=oci-registry.culturebase.devops
```  
  * in your in your `docker-compose.yml`, replace this  : 
```Yaml
  registry:
    image: library/registry:2.6
    command: ["/bin/sh", "/etc/docker/registry/init"]
    environment:
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: https://${MACHINE_FQDN}/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /secrets/portus.crt

      # SSL
      REGISTRY_HTTP_TLS_CERTIFICATE: /secrets/portus.crt
      REGISTRY_HTTP_TLS_KEY: /secrets/portus.key

      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://${MACHINE_FQDN}/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
``` 
  *  by this : 

```Yaml
  registry:
    image: library/registry:2.6
    command: ["/bin/sh", "/etc/docker/registry/init"]
    environment:
      # Authentication
      # REGISTRY_AUTH_TOKEN_REALM => should be a URI pointing at the portus service
      REGISTRY_AUTH_TOKEN_REALM: https://${MACHINE_FQDN}:3000/v2/token
      # REGISTRY_AUTH_TOKEN_SERVICE => should be a FQDN for the registry service
      REGISTRY_AUTH_TOKEN_SERVICE: ${OCI_REGISTRY_SERVICE_FQDN}
      # REGISTRY_AUTH_TOKEN_ISSUER => should be a FQDN for the portus service
      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /secrets/portus.crt

      # SSL
      REGISTRY_HTTP_TLS_CERTIFICATE: /secrets/portus.crt
      REGISTRY_HTTP_TLS_KEY: /secrets/portus.key

      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://${MACHINE_FQDN}:3000/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    # This network config for the registry docker-compose service, guarantees
    # that you can ping -c 4 ${OCI_REGISTRY_SERVICE_FQDN}  from within 
    # all containers.
    # That is because they share the implicit network defined in your config : the 
    # default host networking.On that network, the ${OCI_REGISTRY_SERVICE_FQDN}  host 
    # name will exists, and point to the registry container
    #
    networks:
      pipeline_portus:
        aliases:
         - ${OCI_REGISTRY_SERVICE_FQDN}

``` 
  * Finally, run this and return here with logs : 

```bash
# A./ reloading updated configuration for the registry config 
# don't do this one if you don't have backup for your 
# docker image storage, and portus pgsql database 

docker-compose up -d --force-recreate registry 
# instead just [docker-compose restart registry], should be enough to update your container's ENV VAR runtime values

# B./ recreate and launch the background service
docker-compose up -d --force-recreate background && docker-compose logs -f
```


Sorry for the delay in answer. Anyway, we now know you did have a problem with your background container, so this has to be solved, on the way to total success. 

No waiting for your additional logs :)

**Comment by Kulturserver** [comment]
Hi,

I execute the following command and get an error-message:
docker-compose up -d --force-recreate registry
ERROR: Service "registry" uses an undefined network "pipeline_portus"

our docker-compose.yml is actually this:


version: "2"

services:
  portus:
    image: opensuse/portus:head
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      # SSL
      - PORTUS_PUMA_TLS_KEY=/certificates/portus.key
      - PORTUS_PUMA_TLS_CERT=/certificates/portus.crt

      # NGinx is serving the assets instead of Puma. If you want to change this,
      # uncomment this line.
      - RAILS_SERVE_STATIC_FILES='true'
      - RAILS_SERVE_STATIC_ASSETS='true'
      - PORTUS_LOG_LEVEL=debug
    ports:
      - 3000:3000
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro
      - static:/srv/Portus/public

  background:
    image: opensuse/portus:head
    depends_on:
      - portus
      - db
    environment:
      # Theoretically not needed, but cconfig's been buggy on this...
      - CCONFIG_PREFIX=PORTUS
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}
      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      - PORTUS_BACKGROUND=true
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro

  db:
    image: library/mariadb:10.0.23
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      - MYSQL_DATABASE=portus_production
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - /var/opt/docker/data/mariadb:/var/lib/mysql

  registry:
    image: library/registry:2.6
    command: ["/bin/sh", "/etc/docker/registry/init"]
    environment:
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: https://${MACHINE_FQDN}:3000/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: ${OCI_REGISTRY_SERVICE_FQDN}
      #      REGISTRY_AUTH_TOKEN_SERVICE: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /secrets/portus.crt

      # SSL
      REGISTRY_HTTP_TLS_CERTIFICATE: /secrets/portus.crt
      REGISTRY_HTTP_TLS_KEY: /secrets/portus.key
      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://${MACHINE_FQDN}:3000/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    networks:
      pipeline_portus:
        aliases:
         - ${OCI_REGISTRY_SERVICE_FQDN}
    volumes:
      - /var/opt/docker/data/registry:/var/lib/registry
      - ./secrets:/secrets:ro
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
      - ./registry/init:/etc/docker/registry/init:ro
    ports:
      - 5000:5000
      - 5001:5001 # required to access debug service
    links:
      - portus:portus

  nginx:
    image: library/nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./secrets:/secrets:ro
      - static:/srv/Portus/public:ro
    ports:
      - 81:80
      - 444:443
    links:
      - registry:registry
      - portus:portus

volumes:
  static:
    driver: local

**Comment by Jean-Baptiste-Lasselle** [comment]
hi @Kulturserver ok, I am working on this new data tomorrow on.

One thing immediately, about : 

>
> Hi,
>
> I execute the following command and get an error-message:
>
> `docker-compose up -d --force-recreate registry`
> `ERROR: Service "registry" uses an undefined network "pipeline_portus"`
> 

* Edit your `docker-compose.yml` file,  and replace all occurences of the string  `pipeline_portus`, by the string `portus_net`, and re-run : 

```bash
docker-compose up -d --force-recreate registry
```

* What do you get now ?

**Comment by Jean-Baptiste-Lasselle** [comment]
@Kulturserver Also, there are steps you did not proceed with : 

proceed with the following test steps :  
* first, add this line into your `.env` (create `.env` file if does not exists) : 
```bash
OCI_REGISTRY_SERVICE_FQDN=oci-registry.culturebase.devops
```  
* In your `docker-compose.yml`,  add this to the end of file : 
```Yaml
# bridge networks will allow accessing the host network, from containers, and
# also expose net ports on host network
networks:
  portus_net:
    driver: bridge
```
* again in your `docker-compose.yml`, for every service except `registry`, add this : 
```Yaml
    networks:
       - portus_net
```
* Again in your in your `docker-compose.yml`, replace this  : 
```Yaml
  registry:
    image: library/registry:2.6
    command: ["/bin/sh", "/etc/docker/registry/init"]
    environment:
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: https://${MACHINE_FQDN}/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /secrets/portus.crt

      # SSL
      REGISTRY_HTTP_TLS_CERTIFICATE: /secrets/portus.crt
      REGISTRY_HTTP_TLS_KEY: /secrets/portus.key

      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://${MACHINE_FQDN}/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
``` 
*  by this : 
```Yaml
  registry:
    image: library/registry:2.6
    command: ["/bin/sh", "/etc/docker/registry/init"]
    environment:
      # Authentication
      # REGISTRY_AUTH_TOKEN_REALM => should be a URI pointing at the portus service
      REGISTRY_AUTH_TOKEN_REALM: https://${MACHINE_FQDN}:3000/v2/token
      # REGISTRY_AUTH_TOKEN_SERVICE => should be a FQDN for the registry service
      REGISTRY_AUTH_TOKEN_SERVICE: ${OCI_REGISTRY_SERVICE_FQDN}
      # REGISTRY_AUTH_TOKEN_ISSUER => should be a FQDN for the portus service
      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /secrets/portus.crt

      # SSL
      REGISTRY_HTTP_TLS_CERTIFICATE: /secrets/portus.crt
      REGISTRY_HTTP_TLS_KEY: /secrets/portus.key

      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://${MACHINE_FQDN}:3000/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    # This network config for the registry docker-compose service, guarantees
    # that you can ping -c 4 ${OCI_REGISTRY_SERVICE_FQDN}  from within 
    # all containers.
    # On the 'portus_net' network, the
    # ${OCI_REGISTRY_SERVICE_FQDN}  hostname will exist, and
    # point to the registry container
    #
    # your old config defined implicitly a network : the 
    # default host-bridged network. Now it's a dedicated, also
    # bridged network,named 'portus_net'
    #    
    networks:
      portus_net:
        aliases:
         - ${OCI_REGISTRY_SERVICE_FQDN}

```
