### ISSUE TITLE
Using JIB to push images works, but images don't show up in the UI

### ISSUE THREAD

**Issue by markusheiden** [SUSE/Portus#2243]
### Description

When I push via JIB (e.g. `mvn jib:build`) to our docker-ce registry, the image shows as successfully pushed to the registry. But Portus does not show it. If I try pulling it, I do get the correct image, which means the registry got the image. 

Pulling it via docker and pushing it via docker make it appear in Portus.

An analysis of a colleague showed that the events of the registry are in a slightly different order (sorry, but I don't know the details) when pushing with JIB instead of the docker client.

### Steps to reproduce

1. Build and push image with JIB.
2. Take a look in Portus.

- **Expected behavior**: Image is shown in Portus.
- **Actual behavior**: Image is not visible in Portus.

Sorry, but the other requested information is not available for me.

**Comment by Jean-Baptiste-Lasselle** [comment]
hi @markusheiden I encountered same  problem, and I'm pretty sure where your problem is : 
It's in the `backgound`

Indeed, as you will find in the `portus` awful documentation (I mean it, it's awful, awfully inconsistent yet) : 
> 
>  the background process is _required_ for a production setup.
>
Why _required_? I'll tell you why: because if it isn't there, well you will miss something.

I encountered the same problem : the Web UI would never show any images in the namespace listing page, though  I **did** sucesfully pushed several images to the `registry`.
What is really important to understand, is that : 
* the `background` container in the docker-compose.yml Im' sure you know about, receives the webhook HTTP request sent by the `docker registry` to send notifications about regsitry events , like _"Oh a [docker push] just completed successfully, you can display it in your web ui now"_ .
* without the `background`, I surely verified that I stil can sucessfully push new images to the `docker registry`, but the `Portus` WebUI Portus at https://portus.mycompany.io:3000/ won't ever display it...

What happened for em is that I messed up with the background container configuration, so it just stopped its execution at runtime, and therefore...byebye UI.
Se well I though then that I could definitely check that webhooks are important ONLY to the backgound, the `portus` container does not need to receive them (actually he already discards them, if I believe its logs in my current envronment), with the following experience : 
* I create a new env. variable `export PORTUS_BACKGROUND_SERVICE_FQDN=portus-backservice.pegasusio.io`
* Then I change the configuration of the notifications for the `private docker registry`, in the `docker-compose.yml`, so that it becomes : 

```yaml
      # REGISTRY_HTTP_TLS_KEY: /secrets/portus.key
      REGISTRY_HTTP_TLS_CERTIFICATE: /secrets/portus-oci-registry.crt
      REGISTRY_HTTP_TLS_KEY: /secrets/portus-oci-registry.key
      # Portus endpoint
      # So here https://${PORTUS_BACKGROUND_SERVICE_FQDN}/v2/webhooks/events  should point to portus background service
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://${PORTUS_BACKGROUND_SERVICE_FQDN}:3000/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
```
* Instead of : 

```yaml
      # REGISTRY_HTTP_TLS_KEY: /secrets/portus.key
      REGISTRY_HTTP_TLS_CERTIFICATE: /secrets/portus-oci-registry.crt
      REGISTRY_HTTP_TLS_KEY: /secrets/portus-oci-registry.key
      # Portus endpoint
      # So here https://${PORTUS_SERVICE_FQDN}/v2/webhooks/events  should point to portus
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://${PORTUS_SERVICE_FQDN}:3000/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
```

I'll do those tests tomorrow, n give u the answerif you ask.

All in all, I'm pretty sure here you just got rid of the background container, or misconfigured it.

Do you have any logs I can read? 

`docker-compose logs -f`

JB

**Comment by dleborgne** [comment]
We have the same problem here using Jib 2.0.0 and Portus 2.4.3. Everything works as expected with the Docker 19.03 client but when Jib sends the manifest PUT request, the Portus backgound container log contains a "Cannot find user" message, which is probably caused by the empty "actor" field in the JSON message received by the background Portus container.

**Push event by Docker client, with non-empty "actor" field**
```
Handling 'push' event:
{
  "id": "e4f8ba20-c7e1-4916-919c-a90803854ccc",
  "timestamp": "2020-02-04T11:00:56.708989056Z",
  "action": "push",
  "target": {
    "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
    "size": 1785,
    "digest": "sha256:49433a8241d5e44ca711191b978055f1d2ab5ccc862acf7c4d8d73c274342e91",
    "length": 1785,
    "repository": "testjib/hello-world",
    "url": "https://registry/v2/testjib/hello-world/manifests/sha256:49433a8241d5e44ca711191b978055f1d2ab5ccc862acf7c4d8d73c274342e91",
    "tag": "latest"
  },
  "request": {
    "id": "b1579a99-7f2b-454a-aeb3-f1bf611b320f",
    "addr": "10.255.0.2",
    "host": "registry",
    "method": "PUT",
    "useragent": "docker/19.03.4 go/go1.12.10 git-commit/9013bf5 kernel/4.9.184-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.4 \\(windows\\))"
  },
  "actor": {
    "name": "testjib"
  },
  "source": {
    "addr": "0564da668715:5000",
    "instanceID": "4396b935-e643-4384-8526-2e85839e5427"
  }
}
```

**Push event by Jib, with empty "actor" field**
```Handling 'push' event:
{
  "id": "412c19bc-fe91-4e81-a735-b2ac76f97bf8",
  "timestamp": "2020-02-04T10:46:20.116168774Z",
  "action": "push",
  "target": {
    "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
    "size": 1403,
    "digest": "sha256:7d13e143448e78c7f81c75aeda012513b7f898bfb5f8cc2a6541a13c5d831a16",
    "length": 1403,
    "repository": "testjib/hello-world",
    "url": "https://registry/v2/testjib/hello-world/manifests/sha256:7d13e143448e78c7f81c75aeda012513b7f898bfb5f8cc2a6541a13c5d831a16",
    "tag": "latest"
  },
  "request": {
    "id": "aba2e75f-68fd-4f69-ba85-8a11cd10f828",
    "addr": "10.255.0.2",
    "host": "registry",
    "method": "PUT",
    "useragent": "jib 2.0.0 jib-maven-plugin Google-HTTP-Java-Client/1.34.0 (gzip)"
  },
  "actor": {
  },
  "source": {
    "addr": "0564da668715:5000",
    "instanceID": "4396b935-e643-4384-8526-2e85839e5427"
  }
}
Cannot find user
```

**Comment by Jean-Baptiste-Lasselle** [comment]
hi @markusheiden @dleborgne , I today add a comment to update you with my last test results, which are :   
* in my `docker-compose.yml`, I have 3 different network names / FQDN for `portus`, `background`, and `registry` (also therefore, I now have 3 different SSL/TLS Certificates)
* with this setup Igive you infos about, Ihave a runing portus, I can docker push and new images are updated in the Portus Web UI
* My main result I wanna give you here, is that I made sure, that it is the `portus` service, which expects and must receive webhooks  from the `registry` service, which I configured like this : 

```Yaml
      # Portus endpoint
      # So here https://${PORTUS_SERVICE_FQDN}/v2/webhooks/events  should point to portus
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://${PORTUS_SERVICE_FQDN}:3000/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
```

Does it help ? Did you already solved the problem ?

The only thing to help, that cross my mind, is that I think very likely the problem is unrelated with the `maven` `jib` plugin
