### ISSUE TITLE
Error writing events with webhook

### ISSUE THREAD

**Issue by mitesh-devops** [SUSE/Portus#2297]
I am using wildcard ssl and using the .crt with a combination of CA bundle file + certificate. The SSL works correctly when I add in portus UI. The push is also working but the webhook call is somehow not working. the registry container has the following error. 

`registry_1    | time="2020-04-21T15:09:30Z" level=error msg="retryingsink: error writing events: httpSink{https://registry.domain.com/v2/webhooks/events}: error posting: Post https://registry.domain.com/v2/webhooks/events: x509: certificate is valid for *.kinsta.com, kinsta.com, not registry.domain.com, retrying"`

We have added appropriate entries with extra_hosts and it works on internal IP correctly but the above error somehow indicated that webhook is being called on a public network.

[compose.txt](https://github.com/SUSE/Portus/files/4510980/compose.txt)

I have tried the solution given on https://github.com/SUSE/Portus/issues/1496. Please advice.

**Comment by Jean-Baptiste-Lasselle** [comment]
ok : 

* this is ths `registry` container, trying to connect to `portus`, sending exactly https://registry.domain.com/v2/webhooks/events  (he confirms to registry "_Yes, I got your notification, thank you, you can stop resending the webhook_")
* Well, first : 
  * I personnally think this is a monster configuration you have here, 
  * because the only reason why the https://registry.domain.com/v2/webhooks/events  HTTP request ends up to `portus` instead of `registry` , is because of a very special configuration you have in your `nginx.conf`, which you found in Portus git repo. Do you agree it is weird to call https://registry.domain.com/v2/webhooks/events , while you actually want to connect to https://portus.domain.com/v2/webhooks/events ?
* Oh, and actually, ou don't want to connect your portus with https://portus.domain.com/v2/webhooks/events , but with https://portus.kinsta.com/v2/webhooks/events , don't you ?
* Yes you do, and TLS agrees with you, and so prevents you from connecting to https://registry.domain.com/ while the certificate is for `*.kinsta.com` 
* but your wildcard TLS Cert, is `*.kinsta.com`
* So, the fix is that : 
  * you don't bother about nginx 
  * you change your configuration, so that the hostname for your registry is no longer `registry.domain.com`, but `registry.kinsta.com`, and same thing for portus.kinsta.com. Other possibility is that they all have hostname `docker.kinsta.com`, but it's weird, .think of hub.docker.com and `docker.io/yourname/portus:2.4.3` .... (`ping -c 4 docker.io`). Use : `PORTUS_MACHINE_FQDN=portus.kinsta.com` on `portus` (must match `portus.crt` TLS cert CN Common Name), and docker config (you're devops)
  * then also don't forget : 
```Yaml
auth:
  token:
    realm: https://PORTUS_SERVICE_FQDN_JINJA2_VAR:3000/v2/token
    service: OCI_REGISTRY_SERVICE_FQDN_JINJA2_VAR
    issuer:  PORTUS_SERVICE_FQDN_JINJA2_VAR
    rootcertbundle: /secrets/portus.crt
notifications:
  endpoints:
    - name: portus
      url: https://PORTUS_SERVICE_FQDN_JINJA2_VAR:3000/v2/webhooks/events
      # https://docs.docker.com/registry/notifications/
      # headers:
        # Authorization: Bearer bs2M5RmbspjzLkh4GrXX
      timeout: 500ms
      threshold: 5
      backoff: 1s
  secret: SECRET_PORTUS_API_KEY_JINJA2_VAR
```
* And come back with ur results
