### ISSUE TITLE
How do I configure the SSL key and cert path

### ISSUE THREAD

**Issue by deitch** [SUSE/Portus#275]
The auth server must use an SSL key to sign the requests. The same crt is made available to the registry using `rootcertbundle`.

But how do I tell Portus container where to find the key and crt files? It doesn't appear to have a `config.yml` or env var that I can pass to the container telling it where to find it?

Similarly, how do I tell Portus to run on 443 over https instead of 80 over http, and of course tell it where to find the key and crt to use for the https connection?

**Comment by gtron** [comment]
Hi deitch,
you need to configure a webserver that handles the secure comunication.

I added this in my docker-compose.yml:
```
sweb:
  image: nginx
  hostname: secureweb
  links:
    - registry
  volumes:
    - .:/portus
    - nginx/conf.d:/etc/nginx/conf.d
  ports:
    - "443:443"
```
And this is the conf.d for nginx: 
```
server {
    listen 443;
    server_name YOURHOST;

    ssl_certificate           /portus/docker/registry/portus.crt;
    ssl_certificate_key       /portus/docker/registry/portus.key;
    client_max_body_size 0; # disable any limits to avoid HTTP 413 for large image uploads

    ssl on;
    ssl_session_cache  builtin:1000  shared:SSL:10m;
    ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
    ssl_prefer_server_ciphers on;
    ssl_verify_client off;

    access_log            /portus/nginx/access.log;
    error_log            /portus/nginx/access.log;

    location / {

      proxy_set_header        Host $host;
      proxy_set_header        X-Real-IP $remote_addr;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto $scheme;

      # Fix the “It appears that your reverse proxy set up is broken" error.
      proxy_pass          http://registry:5000;
      proxy_read_timeout  90;

      proxy_redirect      http://localhost:8080 https://portus.corp.wallapop.com;
    }
}
```

Hope this helps... 
G.

**Comment by deitch** [comment]
Hi @gtron, thanks for stepping in to help.

I have been messing with this for hours, trying to get a decent auth engine for a private registry to work.

That answers the second question, although I think I may have an alternate path by changing the `command` line for the `web` service and telling it to go SSL.

But how about the first? How do you get the Portus to know which key to use to sign the jwt requests?

**Comment by jordimassaguerpla** [comment]
for Portus:

https://github.com/SUSE/Portus/blob/master/config/secrets.yml

for registry look into /etc/registry/config.yml

Also if you use self signed certificates, you'll have to add the certificate to your system. In SUSE you can copy your .crt to /etc/pki/trust/anchors/ and then run update-ca-certificates.

**Comment by jordimassaguerpla** [comment]
you could use a similar approach as @gron suggested for apache keys also for the secrets.yml file and then configure both secrets and the registry to use the same key as apache. Just have in mind that the private key must be accessible for whichever user you run your server.

**Comment by deitch** [comment]
Ah, got it. OK, I now mounted that file separately (the Dockerfile copies the whole app into the image), and am able to configure it.

I would suggest making all of the values in there env variable configurable, so you can easily run it via a compose.yml

Here is my docker-compose.yml that solved all of the above:

````yml
web:
  image: portus_web
  ports:
    - "3000:3000"
  links:
    - db
  volumes:
    - /var/lib/registry/certs:/certs
    - /var/lib/registry/portus/secrets.yml:/portus/config/secrets.yml
  environment:
    PRIVATE_KEY_PATH: /certs/registry.key
  # the following gets it working over https without a proxy server
  command: thin start --ssl --ssl-key-file /certs/registry.key --ssl-cert-file /certs/registry.crt

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: portus
  volumes:
    - /var/lib/registry/mysql:/var/lib/mysql

registry:
  image: registry:2.0.1
  ports:
    - "443:5000"
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.crt
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.crt
    REGISTRY_HTTP_TLS_KEY: /certs/registry.key
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    REGISTRY_NOTIFICATIONS_ENDPOINTS_NAME: portus
    REGISTRY_NOTIFICATIONS_ENDPOINTS_URL: https://web:3000/v2/webhooks/events
    REGISTRY_NOTIFICATIONS_ENDPOINTS_TIMEOUT: 500ms
    REGISTRY_NOTIFICATIONS_ENDPOINTS_THRESHOLD: 5
    REGISTRY_NOTIFICATIONS_ENDPOINTS_BACKOFF: 1s
    REGISTRY_AUTH: token
    REGISTRY_AUTH_TOKEN_REALM: https://reg.local:3000/v2/token
    REGISTRY_AUTH_TOKEN_SERVICE: reg.local
    REGISTRY_AUTH_TOKEN_ISSUER: portus.reg.local
    REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certs/registry.crt
  volumes:
    - /var/lib/registry/registry:/var/lib/registry
    - /var/lib/registry/certs:/certs
````
