### ISSUE TITLE
LDAP authentication

### ISSUE THREAD

**Issue by mmilbrath** [SUSE/Portus#378]
I have a use-case in which our LDAP server requires authentication and would be beneficial if the LDAP module supported the 'auth' argument when instantiating LDAP.

**Comment by dohnto** [comment]
@mssola are you soon going to work on this issue or should I dig in?

**Comment by mssola** [comment]
@dohnto that would be awesome! Take into consideration the issue #420 too. Basically, I was going to take the same approach as Gitlab with their `bind_dn` and `password` keys.

**Comment by dohnto** [comment]
Hm, after pulling the last changes from master branch, I am unable to get my code for LDAP auth get to work. Not sure what went wrong.

@mssola, if creating a feature described above is easy for you (and not such a PITA as for me, because it is in Ruby :D) maybe you can develop this feature instead of me :(

**Comment by mssola** [comment]
Maybe it's a regression from our side ? :/ Anyways, if you can't get it to work, maybe you can push your changes in a a branch in a personal fork? This way I could point you what's failing :) Moreover, if that's not enough, I'd be able to continue your work if you share it with us. Any help is appreciated :)

**Comment by dohnto** [comment]
I have created a branch [feature/ldap-auth](https://github.com/dohnto/Portus/tree/feature/ldap-auth). Though I am not sure about the implementation itself.

**Comment by mssola** [comment]
@dohnto thanks! I'll take a look at it as soon as possible ;)

**Comment by depay** [comment]
@dohnto looking forward to ur PR :smiley:

**Comment by depay** [comment]
@dohnto looking forward to ur PR :smiley:

**Comment by mssola** [comment]
@dohnto I've tried your branch and it works for me :D I've setup an LDAP server based on https://github.com/osixia/docker-openldap, then I've created a user, and your code works for me. By not working what do you mean? That it doesn't work for you or that rubocop/tests are failing ?

With that setup I had to write the following `config-local.yml` file:

```yaml
ldap:
  enabled: true

  hostname: 172.17.0.65
  port: 389
  method: "plain"
  base: "dc=example,dc=org"
  uid: "uid"

  guess_email:
    enabled: true
    attr: "mail"

  authentication:
    enabled: true
    bind_dn: "cn=admin,dc=example,dc=org"
    password: "admin"
```

I've created my user by attaching to the container and executing:

```
root@e18cfef7112f:/# ldapadd -x -D "cn=admin,dc=example,dc=org" -w admin -h localhost <<HERE
dn: uid=mssola,dc=example,dc=org
uid: mssola
cn: mssola
sn: 3
objectClass: top
objectClass: posixAccount
objectClass: inetOrgPerson
loginShell: /bin/bash
homeDirectory: /home/mssola
uidNumber: 14583102
gidNumber: 14564100
mail: mssola@example.org
userPassword: 12341234
HERE
```

Just make sure that you've set the proper `uid`, `base`, etc. If the only thing that is failing for you are tests/rubocop (which they are :P), just submit the PR and I'll help you there ;)

**Comment by nicholas-prozesky** [comment]
+1. Also managed to get it to work for me. Nice work @dohnto 
As you say, @mssola, I had to change "gui" to "cn" for it to work against my server, but works a treat.

**Comment by dohnto** [comment]
Ok, after destroying and starting a brand new vagrant machines, everything work as expected. I know that rubocop is failing and the testsuite is not complete, but my ruby skills are limited. I will submit the PR and we can talk about it there.

**Comment by mssola** [comment]
Fixed by PR #447.

**Comment by dohnto** [comment]
Just to note for someone like me who did not know much about docker. When you use `docker login` on your registry, the docker will store your **password** in moreless **plain-text** (base64 in fact) - there is a warning message during login but I have never paid any attention to it. So if you use LDAP authentication, it is quite possible, that your passwords will leak.

For more info see issue docker/docker#10318.

**Comment by mssola** [comment]
@dohnto You're totally right, this is surely worth mentioning in the wiki. Thanks for the heads up.

**Comment by flavio** [comment]
I think we should add the possibility to create unique tokens like Google does.

As a user you can create an application specific password that can be revoked anytime you want. By doing that you would not have to store your precious credentials in plain format on your disk (base64 is plain format...).
Also that could be useful for deployment bots.

What do you think? If you like the idea we should file a dedicated issue

**Comment by mssola** [comment]
@flavio sure, sounds like a good plan.

**Comment by arjunm183** [comment]
I am using portus and i have configured LDAP to authenticate users and i have normal users as well in Portus. Eventhough i have LDAP enabled in my config-local.yml file the login page still doesnt comes to LDAP LOGIN button. 

Version of Portus : Portus-20151120162040-2.2.x86_64
LDAP SERVER : Active Directory

Kindly help with this issue. Reference of my config-local.yml 

ldap:
  enabled: true
  hostname: emea.corpdir.net
  port: 389
  method: "plain"
  base: "dc=my,dc=ad,dc=server"
  uid: "cn"
  guess_mail:
    enabled: true
    attr: ""
  authentication:
    enabled: true
    bind_dn: "cn=userid,ou=admins,ou=resources,ou=docker,dc=my,dc=ad,dc=server"
    password: "blahblah"
first_user_admin:
  enabled: true

check_ssl_usage:
  enabled: true

signup:
    enabled: true

machine_fqdn:
    value: "s117fdreg161.fr117.corpintra.net"


Note: When i use my ldap bind dn username and password it works perfectly fine. I am able to fetch users. No issue in my configuration.

Can someone help me with this or route me to a right channel where i can get help.

**Comment by santosh0705** [comment]
Hi @flavio ,
Using application specific token is an awesome idea. In my CI environment I'm using Docker in Docker to build Docker images but, I'm not able to figure out how to use tokens with Docker cli so I can push the images to my private Docker Distribution.
I also searched the Docker documentation but didn't find any related notes. Any input to this will be a great help.

TIA

**Comment by santosh0705** [comment]
@arjunm183 
I'm using FreeIPA for LDAP service and the below LDAP configuration works with Portus without any problem:

```
ldap:
  enabled: true
  hostname: "<IP address of FreeIPA host system>"
  port: 389
  method: "starttls"
  base: "cn=users,cn=accounts,dc=example,dc=com"
  filter: "(memberOf=cn=developers,cn=groups,cn=accounts,dc=example,dc=com)"
  uid: "uid"
  authentication:
    enabled: true
    bind_dn: "uid=portus,cn=sysaccounts,cn=etc,dc=locuz,dc=com"
    password: "<password of portus sysaccount>"
  guess_email:
    enabled: true
    attr: "mail"
```

I'm using filter so `developers` group only can access. Also created a `sysaccounts` `portus` in LDAP to give access.
