### ISSUE TITLE
Using Portus via Docker-compose in "production"

### ISSUE THREAD

**Issue by JonathonReinhart** [SUSE/Portus#498]
I know Docker Compose isn't really intended for production yet, but I see no technical reason why it shouldn't work.

I'm trying to integrate Portus into my `docker-compose.yml` for running a registry and Portus in an integrated manner, on Docker.  I'm using [`jwilder/nginx-proxy`](https://hub.docker.com/r/jwilder/nginx-proxy) to automatically configure an NGINX reverse proxy, since I dislike using port numbers in URLs. (That image works *very* well.)

I originally tried using a pre-built Portus image ( [`bydga/portus`](https://hub.docker.com/r/bydga/portus/)), but I was seeing errors like this, which made me believe it was configured for "development" mode only:

```
token from untrusted issuer: "portus.test.lan"
```

So now I'm trying to build Portus in my `docker-compose.yml`, like this:

```yml
web:
  build: portus/
  expose:
    - 3000
  links:
    - db
  environment:
    # This tells nginx-proxy which vhost to autoconfigure
    VIRTUAL_HOST: "portus.example.com"
    RAILS_ENV: "production"
    PORTUS_SECRET_KEY_BASE: "deadbeefdeadbeef...."
    PORTUS_MACHINE_FQDN: "portus.example.com"
    PORTUS_KEY_PATH: "/etc/somewhereunique/portus.example.com.key"
    PORTUS_PASSWORD: "not used as key is not encrypted"
  command: puma -b tcp://0.0.0.0:3000 -w 3
  volumes:
    - /srv/docker-reg/tls:/etc/somewhereunique:ro

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: portus
  volumes:
    - /srv/docker-reg/mysql:/var/lib/mysql
```

To set up the database, I've created this script, based upon your `compose-setup.sh`,
```bash
#!/bin/bash
# Taken from setup_database() function in
# https://github.com/SUSE/Portus/blob/ef1dae0/compose-setup.sh

printf "Portus: configuring database..."
docker-compose run --rm web rake db:create db:migrate db:seed
```

But when I run it, I get the following output:
```
$ ./setup-db.sh 
Portus: configuring database...Creating registrycompose_db_1...
Error running migration! Please review database configuration
rake aborted!
Mysql2::Error: Can't connect to MySQL server on 'db' (111)
```

This doesn't make sense, since the `db` service is created. It seems to be a race condition against the `db` start-up delay (and this is admittedly a [shortcoming of docker-compose](https://github.com/docker/compose/issues/374)). So I manually try again, but get this error:

```
$ docker-compose run --rm web rake db:create db:migrate db:seed
Error running migration! Please review database configuration
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: No database selected: SHOW TABLES LIKE 'schema_migrations'
```

At this point, I'm about stumped. Am I heading the right direction, or way off-base? I would be happy to contribute anything I create to use Portus in this way. Thanks.
