### ISSUE TITLE
production container deployement - unable to get notifications to work

### ISSUE THREAD

**Issue by clarktlaugh** [SUSE/Portus#576]
I think I have a production containers deployment (not using docker-compose) almost fully working (I just figured out why the periodic crono sync wasn't working), but there is one thing that still isn't.  I am not getting any notifications about changes in the registry.  The only time Portus shows anything new is when the periodic catalog syncs occur.

I am quite sure this is some kind of config error on my part, as it worked when I ran a non-production deployment last week.  I just don't see what I'm missing.

I did see this in the Distribution doc (https://docs.docker.com/registry/notifications/):

```
notifications:
    endpoints:
      - name: alistener
        url: https://mylistener.example.com/event
        headers:
          Authorization: [Bearer <your token, if needed>]
        timeout: 500ms
        threshold: 5
        backoff: 1s
```

When enabling SSL in Portus and the registry, would an authorization header be needed?  If so, how?  Or is this unimportant?

Here is what I have for the notification configuration (set as EVs when starting the registry container):

```
  -e REGISTRY_NOTIFICATIONS_ENDPOINTS_NAME=portus  \
  -e REGISTRY_NOTIFICATIONS_ENDPOINTS_URL=https://docker-auth.my-domain.org/v2/webhooks/events  \
  -e REGISTRY_NOTIFICATIONS_ENDPOINTS_TIMEOUT=500ms  \
  -e REGISTRY_NOTIFICATIONS_ENDPOINTS_THRESHOLD=5  \
  -e REGISTRY_NOTIFICATIONS_ENDPOINTS_BACKOFF=1s  \
```
