### ISSUE TITLE
panic: unable to configure authorization (token): unable to parse token auth root certificate: asn1: structure error

### ISSUE THREAD

**Issue by maneeshmp** [SUSE/Portus#630]
Platform: AWS
OS: Ubuntu 14.04
Portus Version: 2.0.0

config.yaml

```
version: 0.1
loglevel: debug
storage:
  s3:
    accesskey: WERWE@#@234
    secretkey: sdfsdf4323sdfadffea
    region: us-east-1
    bucket: dockerregistry
    encrypt: true
    secure: true
  delete:
    enabled: true
http:
  addr: :5000
  tls:
    certificate: /etc/ssl/certs/docker-registry.abc.com.crt
    key: /etc/ssl/private/docker-registry.abc.com.key
auth:
  token:
    realm: https://docker-registry.abc.com/v2/token
    service: docker-registry.abc.com:5000
    issuer: docker-registry.abc.com
    rootcertbundle: /etc/ssl/private/docker-registry.abc.com.key
notifications:
  endpoints:
    - name: cs-docker
      url: https://docker-registry.abc.com/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s
```

PS: I am trying to configure both portus and registry in the same host. DNS: docker-registry.abc.com
Certificate is created through openssl command and signed by verisign. 

docker logs 

```
panic: unable to configure authorization (token): unable to parse token auth root certificate: asn1: structure error: tags don't match (16 vs {class:0 tag:2 length:1 isCompound:false}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} tbsCertificate @2

goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp(0x7f181891c8f8, 0xc82034ff80, 0xc8200c7400, 0x7f181891c8f8)
        /go/src/github.com/docker/distribution/registry/handlers/app.go:236 +0x1fab
github.com/docker/distribution/registry.NewRegistry(0x7f181891c938, 0xc82034ff80, 0xc8200c7400, 0xc8200c7400, 0x0, 0x0)
        /go/src/github.com/docker/distribution/registry/registry.go:94 +0x2b0
github.com/docker/distribution/registry.glob.func1(0x134e2e0, 0xc820376e70, 0x1, 0x1)
        /go/src/github.com/docker/distribution/registry/registry.go:57 +0x2b3
github.com/spf13/cobra.(*Command).execute(0x134e2e0, 0xc82000a090, 0x1, 0x1, 0x0, 0x0)
        /go/src/github.com/docker/distribution/Godeps/_workspace/src/github.com/spf13/cobra/command.go:495 +0x6e3
github.com/spf13/cobra.(*Command).Execute(0x134e2e0, 0x0, 0x0)
        /go/src/github.com/docker/distribution/Godeps/_workspace/src/github.com/spf13/cobra/command.go:560 +0x180
main.main()
        /go/src/github.com/docker/distribution/cmd/registry/main.go:22 +0x23

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 18 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 23 [sleep]:
time.Sleep(0x8bb2c97000)
        /usr/local/go/src/runtime/time.go:59 +0xf9
github.com/docker/distribution/registry/handlers.startUploadPurger.func1(0x7f181891c9c8, 0xc820309d40, 0x7f18178daf00, 0xc820390b40, 0x7f18178dad48, 0xc8202ebcb0, 0x2260ff9290000, 0x1395b00, 0x4e94914f0000)
        /go/src/github.com/docker/distribution/registry/handlers/app.go:938 +0x1af
created by github.com/docker/distribution/registry/handlers.startUploadPurger
        /go/src/github.com/docker/distribution/registry/handlers/app.go:945 +0x885

goroutine 24 [runnable]:
github.com/docker/distribution/notifications.(*eventQueue).run(0xc820277db0)
        /go/src/github.com/docker/distribution/notifications/sinks.go:172
created by github.com/docker/distribution/notifications.newEventQueue
        /go/src/github.com/docker/distribution/notifications/sinks.go:131 +0x1cb

goroutine 25 [runnable]:
github.com/docker/distribution/notifications.(*Broadcaster).run(0xc820349ce0)
        /go/src/github.com/docker/distribution/notifications/sinks.go:78
created by github.com/docker/distribution/notifications.NewBroadcaster
        /go/src/github.com/docker/distribution/notifications/sinks.go:39 +0x100
root@docker-registry:~#
```
