### ISSUE TITLE
[help needed] no successful auth challenge

### ISSUE THREAD

**Issue by doctori** [SUSE/Portus#650]
Hi,  
I'm trying to setup portus with docker-compose,  I've setup an nginx in front of my registry that will handle SSL and portus is behind the corporate reverse proxy, (I've setup our reverse proxy to handle ssl for the docker registry but it doesn"t support the big POST requests generate by a 'docker push' command)  
so my docker-compose.yml looks like something like this :  
```yaml
web:
  extends:
    file: docker/compose-common.yml
    service: web
  volumes:
    - .:/portus
  links:
    - db
  environment:
    RAILS_ENV: production
    PORTUS_PRODUCTION_HOST: db
    PORTUS_PRODUCTION_USERNAME: xxx
    PORTUS_PRODUCTION_PASSWORD: xxxx
    PORTUS_PRODUCTION_DATABASE: xxxxx
    PORTUS_SECRET_KEY_BASE: xxxxx
    PORTUS_PASSWORD: xxxxx
    PORTUS_MACHINE_FQDN: registry-portus.corporate.com
    PORTUS_KEY_PATH: server.key

crono:
  image: portus_web
  command: /usr/bin/supervisord
  volumes:
    - .:/portus
  links:
    - db

db:
  image: library/mariadb
  environment:
    MYSQL_ROOT_PASSWORD: xxxx
    MYSQL_DATABASE: xxxx
nginx:
  image: "nginx:1.9"
  ports:
    - 443:443
  links:
    - registry:registry
  volumes:
    - /etc/docker/registry:/etc/nginx/conf.d

registry:
  extends:
    file: docker/compose-common.yml
    service: registry
  volumes:
    - /etc/docker/registry/ssl:/registry/ssl/
    - ./docker/registry:/registry
    - /var/lib/registry/data:/var/lib/registry
  entrypoint: /registry/entry.sh
  links:
    - web
  ports:
    - 5001:5001 # required to access debug service
  environment:
    http_proxy: 'http://proxy.corporate.grp:3128/'
    https_proxy: 'http://proxy.corporate.grp:3128/'

```
I've added a step in the main Dockerfile in order to add our root certificate, 
This is the registry configuration : 
```yaml
version: 0.1
loglevel: debug
storage:
  cache:
     layerinfo: inmemory
  filesystem:
     rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: 0.0.0.0:5000
  host: registry.corporate.grp
  debug:
    addr: 0.0.0.0:5001
auth:
  token:
    realm:  https://registry-portus.corporate.com/v2/token
    service: registry.corporate.grp
    issuer: registry-portus.corporate.com
    rootcertbundle: /registry/portus.crt
notifications:
  endpoints:
    - name: portus
      url: http://web:3000/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s
```

when I try to `docker login` I've got this exception :  
```
Error response from daemon: no successful auth challenge for https://registry.corporate.grp/v2/ - errors: [Get https://registry-portus.corporate.com/v2/token?account=user&service=registry.corporate.grp: x509: certificate signed by unknown authority]
```
I've made sure that the web (portus) and registry don't have certificate issues (a curl https://registry from portus or curl https://portus from registry works) the client doesn't have certificate issues at least when checking with curl (curl https://registry or portus doesn't not raise certificate issues)  
I've try with the --insecure-registry option on the docker client,  
On the registry side this is what the logs looks like :  
```  
time="2015-12-28T15:14:04Z" level=debug msg="authorizing request" http.request.host=itregistry.corporate.grp http.request.id=9df2923b-a5ea-4467-ad9e-c535797ecf89 http.request.method=GET http.request.remoteaddr=10.25.4.139 http.request.uri="/v2/" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.16.0-4-amd64 os/linux arch/amd64" instance.id=7b706ca7-1bef-45da-8725-0fc9335ec9d3 version=v2.1.1
time="2015-12-28T15:14:04Z" level=warning msg="error authorizing context: authorization token required" http.request.host=itregistry.corporate.grp http.request.id=9df2923b-a5ea-4467-ad9e-c535797ecf89 http.request.method=GET http.request.remoteaddr=10.25.4.139 http.request.uri="/v2/" http.request.useragent="docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.16.0-4-amd64 os/linux arch/amd64" instance.id=7b706ca7-1bef-45da-8725-0fc9335ec9d3 version=v2.1.1
172.17.0.6 - - [28/Dec/2015:15:14:04 +0000] "GET /v2/ HTTP/1.0" 401 114 "" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.16.0-4-amd64 os/linux arch/amd64"
time="2015-12-28T15:14:05Z" level=debug msg="filesystem.List(\"/\")" instance.id=7b706ca7-1bef-45da-8725-0fc9335ec9d3 trace.duration=75.242µs trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).List" trace.id=5f841c0b-f06e-4c75-ac8d-533ce8de030a trace.line=123 version=v2.1.1
```

I've made sure that the portus key match the rootcertbundle on the registry, what's driving me mad is that I don't know which process doesn't like the certificates and which one ?   
I'm using Portus v2, registry (Distribution) v2.1.1 and nginx 1.9

I'm really sorry to bother you with this, thank you for your time.

**Comment by thenewguy** [comment]
I've been able to make this work but I needed to build an image based off the passenger base image to support sub path hosting.

However, I can copy and paste some of the configs to help with the variables I've set for certificates (note my configs are templated by CI but I think they are easy enough to read):

docker-compose-base.yml.tmpl:
```
portus-base:
  build: {portus_build_dir}
  environment:
    COMPOSE: 1
    SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
    CATALOG_CRON: 60.seconds
    PORTUS_KEY_PATH: /tmp/key
    PORTUS_MACHINE_FQDN: docker.internal.example.com
    PORTUS_PRODUCTION_DATABASE: portus_production
    PORTUS_PASSWORD: notsosecret
    PORTUS_SECRET_KEY_BASE: insertyourshere
    RAILS_ENV: production
    RACK_ENV: production
    WSGI_ENV: production
    NODE_ENV: production
    PASSENGER_APP_ENV: production
  volumes:
   - /etc/ssl/certs/:/etc/ssl/certs/:ro
   - /path/to/your.cert:/tmp/cert-ro:ro
   - /path/to/your.key:/tmp/key-ro:ro
   - /opt/deploy/portus/set-volume-permissions.sh:/etc/my_init.d/set-volume-permissions.sh
```

docker-compose.yml.tmpl:
```
db:
  image: library/mariadb
  environment:
    MYSQL_ROOT_PASSWORD: portus
  volumes:
    - /data/db:/var/lib/mysql

portus-crono:
  extends:
    file: docker-compose-base.yml
    service: portus-base
  command: /sbin/my_init -- /usr/bin/supervisord -c /tmp/crono-supervisord.conf
  links:
   - db
   - registry
  volumes:
    - /opt/deploy/portus/crono-supervisord.conf:/tmp/crono-supervisord.conf:ro
    - /var/log/portus/crono:/tmp/log/
    - /var/log/portus/crono/container:/portus/log
    - /opt/deploy/portus/crono-supervisord.conf:/etc/service/nginx/down:ro
    - /opt/deploy/portus/config-local.yml:/portus/config/config-local.yml
portus-web:
  extends:
    file: docker-compose-base.yml
    service: portus-base
  links:
   - db
   - registry
  volumes:
   - /opt/deploy/portus/vhost.conf:/etc/nginx/sites-enabled/portus.conf:ro
   - /var/log/portus/web:/tmp/log/
   - /var/log/portus/web/container:/portus/log
   - /opt/deploy/portus/config-local.yml:/portus/config/config-local.yml
registry:
  image: registry:2.2.0
  expose:
   - "80"
  volumes:
   - /opt/deploy/registry/config.yml:/etc/docker/registry/config.yml:ro
   - /etc/ssl/certs/:/etc/ssl/certs/:ro
   - /path/to/your.cert:/tmp/cert:ro
   - /path/to/your.cert:/etc/docker/certs.d/docker.internal.example.com/ca.crt:ro
   - /data/registry:/tmp/registry/storage
web:
  image: nginx:1.9.1
  command: nginx -c /tmp/nginx.conf
  ports:
   - "443:443"
   - "80:80"
  volumes:
   - /opt/deploy/web/nginx.conf:/tmp/nginx.conf:ro
   - /path/to/your.cert:/tmp/cert:ro
   - /path/to/your.key:/tmp/key:ro
   - /var/log/nginx:/tmp/log/
  links:
   - registry
   - portus-web

```

**Comment by doctori** [comment]
Hi,  
Thank you for your awnser,  
the only big difference seems to be that you insert the cert of portus into /etc/docker/certs.d...  
I thought it was only used by the docker daemon, I'll try that, thanks.

**Comment by thenewguy** [comment]
@doctori I am not sure what you are asking.  The cert bundle is specific to your internal PKI.  Depending on the format that your certificates are in, you can extract it or either request it from the certificate authority.  They need to be formatted as x509.

You can verify the cert is being presented correctly with the following:
```
openssl s_client -connect docker.internal.example.com:443 -CApath /etc/ssl/certs | less
```

Also, make sure you configured the registry to use the correct endpoints:

config.yml
```
version: 0.1
log: 
    fields:
        service: registry
storage:
    cache:
        blobdescriptor: inmemory
    filesystem:
        rootdirectory: /tmp/registry/storage
    delete:
        enabled: true
http:
    addr: :80
    host: https://docker.internal.example.com

auth:
  token:
    realm: https://docker.internal.example.com/portus/v2/token
    service: docker.internal.example.com
    issuer: docker.internal.example.com
    rootcertbundle: /tmp/cert

notifications:
  endpoints:
    - name: portus
      url: https://docker.internal.example.com/portus/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s
```

But it sounds like you aren't installing the certificate bundle correctly for the registry to trust portus.  You should use the openssl command above to inspect https://registry.corporate.grp/v2/

Also, you want to verify with curl that https://registry.corporate.grp/v2/ is correct.  http://registry and http://docker shouldn't be used except by the nginx proxy.  All traffic needs to go through your nginx proxy for everything to work out correctly.

Also, the upload issues are due to the buffers and body size allowed.  `client_max_body_size 0;` should fix that particular problem.
