### ISSUE TITLE
no Synchronization between portus and registry

### ISSUE THREAD

**Issue by phupn1510** [SUSE/Portus#705]
Hi, I am be able to push/pull images to a namespace on portus but I still can not see any repository on that namespace. I checked registry notification webhook but I still dont know how to fix it.
My docker-compose.yml notification:
    REGISTRY_NOTIFICATIONS_ENDPOINT_NAME: portus
    REGISTRY_NOTIFICATIONS_ENDPOINT_URL: http://xx.xx.xx.xx:3000/v2/webhooks/events
    REGISTRY_NOTIFICATIONS_ENDPOINT_TIMEOUT: 500
    REGISTRY_NOTIFICATIONS_ENDPOINT_THRESHOLD: 5
    REGISTRY_NOTIFICATIONS_ENDPOINT_BACKOFF: 1

**Comment by mssola** [comment]
Assuming that your Portus endpoint URL is the proper one, there are some typos on the env. variables. The configuration is:

```yml
notifications:
  endpoints:
    - name: portus
      url: http://172.17.0.1:3000/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s
```

You are setting stuff with `REGISTRY_NOTIFICATIONS_ENDPOINT_NAME`, when it should be `REGISTRY_NOTIFICATIONS_ENDPOINTS_NAME`. Note that `endpoints` is in plural in the config ;)

Does this fix your problem ?
