### ISSUE TITLE
nginx port forwarding doesn't work

### ISSUE THREAD

**Issue by gokhandincer** [SUSE/Portus#724]
I tried to install portus with docker-compose everything ok.And I was able to login in registry with **registry.abc.com:5000** but I couldn't able to login in with **registry.abc.com**
Here is my config;

######docker-compose.yml ######
```
nginx:
  image: "nginx:1.9"
  ports:
    - 443:443
  links:
    - registry
    - web
  volumes:
    - ./nginx/:/etc/nginx/conf.d:ro

web:
  build: .
  command: puma -b tcp://0.0.0.0:3000 -w 3
  environment:
    - PORTUS_MACHINE_FQDN=registry.abc.com
    - PORTUS_DB_HOST=portus_db_1
  volumes:
    - .:/portus
  ports:
    - 3000:3000
  links:
    - db

crono:
  image: portus_web
  entrypoint: bin/crono
  environment:
    - PORTUS_MACHINE_FQDN=registry.abc.com
    - PORTUS_DB_HOST=portus_db_1
  volumes:
    - .:/portus
  links:
    - db
db:
  image: library/mariadb:10.0.23
  environment:
    MYSQL_ROOT_PASSWORD: portus

registry:
  image: library/registry:2.1.1
  ports:
  volumes:
    - /registry_data
    - ./compose/registry/server.crt:/etc/docker/registry/server.crt:ro
    - ./compose/registry/server.key:/etc/docker/registry/server.key:ro
    - ./compose/registry/config.yml:/etc/docker/registry/config.yml:ro
  ports:
    - 5000:5000
  links:
    - web
```

#####registry config.yml#####

```
version: 0.1
storage:
  filesystem:
    rootdirectory: /registry_data
  delete:
    enabled: true
http:
  addr: 0.0.0.0:5000
  tls:
    certificate: /etc/docker/registry/server.crt
    key: /etc/docker/registry/server.key
auth:
  token:
    realm: http://registry.abc.com:3000/v2/token
    service: registry.abc.com:5000
    issuer: registry.abc.com
    rootcertbundle: /etc/docker/registry/server.crt
notifications:
  endpoints:
    - name: portus
      url: http://registry.abc.com:3000/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s

```
#####nginx registry.conf####

```
server {
  listen 443;
  server_name registry.abc.com;

  # SSL
  ssl on;
  ssl_certificate /etc/nginx/conf.d/server.crt;
  ssl_certificate_key /etc/nginx/conf.d/server.key;
  client_max_body_size 0;
  chunked_transfer_encoding on;

  location /v2/ {
      if ($http_user_agent ~ "^(docker\/1\.(3|4|5(?!\.[0-9]-dev))|Go ).*$" ) {
      return 404;
    }

   
    proxy_pass                          http://registry.abc.com:5000;
    proxy_set_header  Host              $http_host;   # required for docker client's sake
    proxy_set_header  X-Real-IP         $remote_addr; # pass on real client's IP
    proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header  X-Forwarded-Proto $scheme;
    proxy_read_timeout                  900;
  }
}
```

Do you have any i
