### ISSUE TITLE
Mail Config Error

### ISSUE THREAD

**Issue by raghu999** [SUSE/Portus#785]
Hi, Really Appreciate your work,  I am trying to Integrate Portus And have started up Portus with `RAILS_ENV=staging` . When i am testing the forgot password i  am getting this error. 

```
Started POST "/users/password" for 10.25.249.242 at 2016-03-15 22:09:42 +0000
Processing by PasswordsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"N4cEF4O/Besp/sAQSVILsSb6GYB45D+NNCBylKh/zVz/O+dj4bVJkfznTyYY8uY2c0l2FB1BYE2SByEjuLHKzw==", "user"=>{"email"=>"raghu_challa@*******.com"}, "button"=>""}
  Rendered /usr/local/bundle/gems/devise-3.5.1/app/views/devise/mailer/reset_password_instructions.html.erb (0.4ms)

Sent mail to raghu_challa@*******.com (16.6ms)
Completed 500 Internal Server Error in 49ms (ActiveRecord: 13.1ms)

SocketError (getaddrinfo: Name or service not known):
  app/controllers/passwords_controller.rb:10:in `create'

```

**Comment by mssola** [comment]
Hi @raghu999. This means that for some reason Portus cannot send an email to the specified address. Could you paste the config of `email` in your `config/config.yml` ? (or `config/config-local.yml` if you have it). Test that you can effectively send emails with that configuration without using Portus (e.g. if `smtp` is not enabled, by just calling the `sendmail` command). While you are at it, it would also help if you provided the Portus version that you are using and which setup did you use (vagrant, docker-compose, your own).

**Comment by raghu999** [comment]
I cloned from master(latest) and ran the compose-setup with RAILS_ENV=staging and RACK_ENV=staging. Below is my Mail Config of config/config.yml. we tried with both SMTP true and false but no luck .   

# Settings for the Portus mailer.
email:
  from: "portus@registry-sps@domain.net"
  name: "Portus"
  reply_to: "no-reply@registry-sps@domain.net"

  # If enabled, then SMTP will be used. Otherwise 'sendmail' will be used
  # (defaults to: /usr/sbin/sendmail -i -t).
  smtp:
    enabled: true
    address: "messaging.mdp"
    port: 25,
    user_name: "cloud_app_notifications001"
    password: "***********"
    domain: "domain.com"


FYI Pulled from the commit:
commit a47db5e2670b6f8fc0cc57d05e21baa1b40690d3
Author: Miquel Sabaté <msabate@suse.com>
Date:   Tue Mar 8 17:22:30 2016 +0100

**Comment by raghu999** [comment]
Changing My Config gives me a different error 

```
#CONFIG OF PORTUS MAIL
# Settings for the Portus mailer.
email:
  from: "portus@registry-sps@domain.net"
  name: "Portus"
  reply_to: "no-reply@registry-sps@domain.net"

  # If enabled, then SMTP will be used. Otherwise 'sendmail' will be used
  # (defaults to: /usr/sbin/sendmail -i -t).
  smtp:
    enabled: true
    address: "messaging.mdp.domain.net"
    port: 25,
    user_name: "cloud_app_notifications001"
    password: "***********"
    domain: "domain.net"
```

```
#ERROR IN DEBUG Mode

Sent mail to raghu_challa@domain.com (39.2ms)
Date: Thu, 17 Mar 2016 03:44:02 +0000
From: Portus <no-reply@registry-sps.domain.net>
Reply-To: no-reply@domain.net
To: raghu_challa@domain.com
Message-ID: <56ea280236a4b_103fc18648f9045671d@72a8c3f4f2a2.mail>
Subject: Reset password instructions
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<p>Hello raghu_challa@domain.com!</p>
```

<p>Someone has requested a link to change your password. You can do this through the link below.</p>

<p><a href="http://domain.net/users/password/edit?reset_password_token=vixQQPvUQcYyxsuw5sYk">Change my password</a></p>

<p>If you didn't request this, please ignore this email.</p>
<p>Your password won't change until you access the link above and create a new one.</p>

Completed 500 Internal Server Error in 316ms (ActiveRecord: 11.6ms)

OpenSSL::SSL::SSLError (hostname "messaging.mdp.domain.net" does not match the server certificate):
  app/controllers/passwords_controller.rb:10:in `create'
