### ISSUE TITLE
SSL certificate verify failed despite being trusted

### ISSUE THREAD

**Issue by cpoole** [SUSE/Portus#804]
I am having a similar issue to https://github.com/SUSE/Portus/issues/719 and I havent found a solution. 
I have two ELB's in AWS:
- portusELB (entrust signed cert)
- registryELB (entrust signed cert)

each of these has one container bound to it. 

ssl terminates on the ELB's. 

From the registryELB to the registry container the communication is over http
From the portusELB to the portus container the communication is over https using a self signed key pair.

portus and the registry are only aware of the ELB's DNS address. 

When I boot up portus and the registry I can not connect the registry from the portus UI unless I click "skip check". I see an error "Reason: SSL_connect returned=1 errno=0 state=error: certificate verify failed"

I have added the cert chain for the registry certificate to the ca-certificates on the portus container. I can curl successfully from the portus container to the registry container without any ssl compaints. 

It should be noted, everything else works, I can use portus for authentication with docker login, I can push to namespaces in the registry, I even see the registry webhook POST to portus informing portus that there is a new repository portus should request information about. 

the domain.crt used for REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE is the same as the domain.crt for PUMA_SSL_KEY

My docker-compose

```
distribution:
  image: connorpoole/distribution:0.0.17
  environment:
    REGISTRY_AUTH_TOKEN_ISSUER: portus.redacted.com
    REGISTRY_AUTH_TOKEN_SERVICE: distribution.redacted.com
    REGISTRY_AUTH_TOKEN_REALM: https://portus.redacted.com/v2/token
    REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certs/domain.crt
    REGISTRY_STORAGE_S3_ACCESSKEY: <redacted>
    REGISTRY_STORAGE_S3_SECRETKEY: <redacted>
    REGISTRY_STORAGE_S3_REGION: us-west-2
    REGISTRY_STORAGE_S3_BUCKET: docker-distribution
    REGISTRY_HTTP_SECRET: asdfasdfasdgasdg
    ENDPOINT_URL: https://portus.redacted.com/v2/webhooks/events
  ports:
    - "5000:5000"
    - "5001:5001"
  restart: always
portus:
  image: connorpoole/portus:0.0.11
  environment:
    DB_ADAPTER: mysql2
    DB_ENCODING: utf8
    DB_HOST: portus-db.redacted.rds.amazonaws.com
    DB_PORT: 3306
    DB_USERNAME: redacted
    DB_PASSWORD: redactedPass
    DB_DATABASE: portusdb
    RACK_ENV: production
    RAILS_ENV: production
    PUMA_SSL_CRT: /certs/domain.crt
    PUMA_SSL_KEY: /certs/key.pem
    PUMA_PORT: 443
    PUMA_WORKERS: 4
    SECRETS_SECRET_KEY_BASE: someredactedsecret
    SECRETS_ENCRYPTION_PRIVATE_KEY_PATH: /certs/key.pem
    SECRETS_PORTUS_PASSWORD: someredactedpassword
    MACHINE_FQDN: portus.redacted.com
    LOG_LEVEL: debug
    SSL_CERT_FILE: /ect/ssl/certs/ca-certificates.crt
  command: puma -b tcp://0.0.0.0:3000 -w 3
  ports:
    - "80:80"
    - "443:443"
```

the error:
```
Could not fetch the tag for target {"mediaType"=>"application/vnd.docker.distribution.manifest.v2+json", "size"=>2788, "digest"=>"sha256:ad55f7ec3c21c675b6cda4c20ecfbb139ea4e98e78df203291bb1eabc2fc5dec", "length"=>2788, "repository"=>"se/distribution", "url"=>"https://distribution.redacted.com/v2/se/distribution/manifests/sha256:ad55f7ec3c21c675b6cda4c20ecfbb139ea4e98e78df203291bb1eabc2fc5dec"}
4/7/2016 5:31:09 AMReason: SSL_connect returned=1 errno=0 state=error: certificate verify failed
```
