### ISSUE TITLE
Can't see repositories in portus

### ISSUE THREAD

**Issue by Vad1mo** [SUSE/Portus#837]
I have setup **Portus**<--->**registry**<--->**LDAP** working together. I can push and pull to the registry as an ldap user. I can also login to Portus and registry as an ldap user. However when I enter Portus and don't see any images. Or in other words Portus does not show the images that definitely exist.  

I have setup notifications in docker registry like so

```
notifications:
  endpoints:
    - name: portus
      url: https://portus.corp.acme.com/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s
```

Also when looking in the logs I can't see anything exceptional.

except maybe this. Can this be related to my problem? 

```
I, [2016-04-23T11:31:53.975771 #60]  INFO -- : Perform CatalogJob
Exception: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol
I, [2016-04-23T11:31:53.985223 #60]  INFO -- : Finished CatalogJob in 0.01 seconds
```

**Comment by Vad1mo** [comment]
I changed now my registry configuration from 
```
notifications:
  endpoints:
    - name: portus
      url: https://portus.corp.acme.com/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s
```

to 

```
notifications:
  endpoints:
    - name: portus
      url: http://portus.corp.acme.com:3000/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s
```
And I don't get any CatalogJob  exceptions but Portus still **does not display my registry content**.
