### ISSUE TITLE
Issue with enabling TLS

### ISSUE THREAD

**Issue by ligc** [SUSE/Portus#859]
HI,

I am trying to enable TLS with Portus, here is the procedure I used:

-  Clone the Portus code

_git clone https://github.com/SUSE/Portus.git_

- Create self-signed TLS key and certificate

_openssl req -newkey rsa:4096 -nodes -sha256 -keyout ./compose/registry/registry.key -x509 -days 365 -out ./compose/registry/registry.crt_

- Modify configuration files with the TLS key and certificate

_cd Portus/_

Modify compose/docker-compose.yml.template to add the volumes for the registry.crt and registry.key

```
registry:
  image: library/registry:2.3.1
  volumes:
    - /registry_data
    - ./compose/registry/portus.crt:/etc/docker/registry/portus.crt:ro
    - ./compose/registry/config.yml:/etc/docker/registry/config.yml:ro
    - ./compose/registry/registry.crt:/etc/docker/registry/registry.crt:ro
    - ./compose/registry/registry.key:/etc/docker/registry/registry.key:ro
```

Modify ./compose/registry/config.yml.template to add the tls section, and use registry.crt as the rootcertbundle

```
http:
  addr: 0.0.0.0:5000
  debug:
    addr: 0.0.0.0:5001
  tls:
    certificate: /etc/docker/registry/registry.crt
    key: /etc/docker/registry/registry.key
auth:
  token:
    realm: http://EXTERNAL_IP:3000/v2/token
    service: EXTERNAL_IP:5000
    issuer: EXTERNAL_IP
    rootcertbundle: /etc/docker/registry/registry.crt
```

- Run compose-setup.sh

_./compose-setup.sh -e 10.4.19.4_

However, when I tried to create the admin user with TLS enabled, it complains **"SSL error while communicating with the registry, check the server logs for more details. You can skip this check by clicking on the "Skip remote checks" checkbox."**

Any suggestion on what additional configuration I need to do to enable TLS communication between the Portus and the registry? Thank you.
