### ISSUE TITLE
Add markdown support code multi line

### ISSUE THREAD

**Issue by cedvan** [SUSE/Portus#875]
Hi,

My portus is build with v2.0.3.
Markdown support actually don't work with multi-line code :

```
php:
  image: postgresql
  volumes:
    - /var/lib/postgresql
  ports:
    - 3306
```

give : 

`php: image: postgresql volumes: - /var/lib/postgresql ports: - 3306`
