### ISSUE TITLE
Portus delete loop. 

### ISSUE THREAD

**Issue by dforste** [SUSE/Portus#952]
If I delete a tag on the registry in portus and then push it back to the registry it doesn't show up in portus and it keeps trying to "delete" it from portus without deleting it from the registry. 
crono output: 
``` I, [2016-07-05T15:52:25.867013 #1]  INFO -- : Perform CatalogJob
 [catalog] Created the tag '2.4.1'.
 I, [2016-07-05T15:52:27.174444 #1]  INFO -- : Finished CatalogJob in 1.31 seconds```
portus feed: 
``` portus deleted admin / registry:2.4.1```


To reproduce: 
Push the tag to the registry. 
Delete the tag from portus. 
Push the tag to the registry. 

Tag will exist on registry and Portus will constantly try to delete it from the UI when crono imports it.

**Comment by mssola** [comment]
I can definitely reproduce this bug. Thanks for the tip!

**Comment by mssola** [comment]
@dforste I'm no longer able to reproduce this :confused:. This is my config:

```
Portus version: master@8a67b557717b
Portus has evaluated the following configuration:
---
email:
  from: portus@example.com
  name: Portus
  reply_to: no-reply@example.com
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    user_name: username@example.com
    password: "****"
    domain: example.com
gravatar:
  enabled: true
delete:
  enabled: true
ldap:
  enabled: false
  hostname: ldap.suse.de
  port: 389
  method: plain
  base: ou=accounts,dc=suse,dc=de
  filter: ''
  uid: uid
  authentication:
    enabled: false
    bind_dn: ''
    password: "****"
  guess_email:
    enabled: true
    attr: ''
first_user_admin:
  enabled: true
signup:
  enabled: true
check_ssl_usage:
  enabled: true
jwt_expiration_time:
  value: 5.minutes
machine_fqdn:
  value: registry.mssola.cat
display_name:
  enabled: true
```

I've tried pushing the official [registry image](https://hub.docker.com/_/registry/) and also [alpine](https://hub.docker.com/_/alpine/). I've tried with only one tag, with multiple tags, storing the images in different repos, etc. Could you provide more information ? (maybe updating to the latest commit from the `master` branch is worth considering, but as far as I can tell we haven't touched anything on this).
