### ISSUE TITLE
500 error on sign_in (TypeError)

### ISSUE THREAD

**Issue by cpoole** [SUSE/Portus#967]
just upgraded portus from commit 89da1fbf5463d4fe4a3a0227c20ada993945fee2 to HEAD (master branch). LDAP auth is still enabled but now when I attempt to log in I get the following error:

```
portus_2       | 2016-07-08T11:26:59.185861990Z Started POST "/users/sign_in" for 10.42.91.156 at 2016-07-08 11:26:59 +0000
portus_2       | 2016-07-08T11:26:59.188212742Z Processing by Auth::SessionsController#create as HTML
portus_2       | 2016-07-08T11:26:59.188632944Z   Parameters: {"utf8"=>"✓", "authenticity_token"=>"sS5o4tSAcDPNglKSAOg1BCeWeni7cmgOnhXeIw0QOopEUc+VGiNNBw1tVd2YJa2+suzeCn9AGeV4HkNU3zFhrQ==", "user"=>{"username"=>"connor.poole", "password"=>"[FILTERED]"}, "button"=>""}
portus_2       | 2016-07-08T11:26:59.203490406Z Completed 500 Internal Server Error in 15ms (ActiveRecord: 0.0ms)
portus_2       | 2016-07-08T11:26:59.205189737Z 
portus_2       | 2016-07-08T11:26:59.205205709Z TypeError (no implicit conversion of Array into String):
portus_2       | 2016-07-08T11:26:59.205213563Z   lib/portus/ldap.rb:125:in `search_options'
portus_2       | 2016-07-08T11:26:59.205218339Z   lib/portus/ldap.rb:114:in `bind_options'
portus_2       | 2016-07-08T11:26:59.205222789Z   lib/portus/ldap.rb:37:in `authenticate!'
portus_2       | 2016-07-08T11:26:59.205227461Z   app/controllers/application_controller.rb:59:in `force_update_profile!'
portus_2       | 2016-07-08T11:26:59.205232117Z 
```

definitely a major blocker since no-one can auth.

**Comment by cpoole** [comment]
just tried with a fresh database. I see the same issue

**Comment by cpoole** [comment]
just tried with a fresh database but LDAP turned off. now I'm in. So definitely something related to the parsing of the LDAP bind query. 

my env variables for ldap:
```
LDAP_ENABLED: false
    LDAP_HOSTNAME: "ldap.foxpass.com"
    LDAP_PORT: 636
    LDAP_METHOD: "simple_tls"
    LDAP_BASE: "dc=something,dc=com"
    LDAP_FILTER: ""
    LDAP_UID: "uid"
    LDAP_AUTHENTICATION_ENABLED: true
    LDAP_AUTHENTICATION_BIND_DN: "cn=portus,dc=daqri,dc=com"
    LDAP_AUTHENTICATION_PASSWORD: "supersecretpassword"
```

**Comment by mssola** [comment]
I cannot reproduce this :confused: Taking a look at the code, this should be the LDAP filter, but in your case it appears empty right ? This is my config (`rake portus:info`):

```yaml
Portus version: master@8a67b557717b
Portus has evaluated the following configuration:
---
email:
  from: portus@example.com
  name: Portus
  reply_to: no-reply@example.com
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    user_name: username@example.com
    password: "****"
    domain: example.com
gravatar:
  enabled: true
delete:
  enabled: true
ldap:
  enabled: true
  hostname: ldap.suse.de
  port: 389
  method: plain
  base: ou=accounts,dc=suse,dc=de
  filter: ''
  uid: uid
  authentication:
    enabled: false
    bind_dn: ''
    password: "****"
  guess_email:
    enabled: true
    attr: ''
first_user_admin:
  enabled: true
signup:
  enabled: true
check_ssl_usage:
  enabled: true
jwt_expiration_time:
  value: 5.minutes
machine_fqdn:
  value: registry.mssola.cat
display_name:
  enabled: true
```

**Comment by mssola** [comment]
Of course, all these env. variables are prefixed with `PORTUS_` right ?

**Comment by cpoole** [comment]
huh, this is very strange.

```
[Mailer config] Host:     portus.something.info
[Mailer config] Protocol: https://
  ActiveRecord::SchemaMigration Load (47.3ms)  SELECT `schema_migrations`.* FROM `schema_migrations`

Portus version: 8a67b55
Portus has evaluated the following configuration:
---
email:
  from: portus@example.com
  name: Portus
  reply_to: no-reply@example.com
  smtp:
    enabled: false
    address: smtp.example.com
    port: 587
    user_name: username@example.com
    password: "****"
    domain: example.com
gravatar:
  enabled: true
ldap:
  enabled: true
  hostname: ldap.foxpass.com
  port: 636
  method: simple_tls
  base: dc=something,dc=com
  filter:
  - 
  - 
  - 
  uid: uid
  authentication:
    enabled: true
    bind_dn: cn=portus,dc=something,dc=com
    password: "****"
  guess_email:
    enabled: true
    attr:
    - 
    - 
    - 
first_user_admin:
  enabled:
    ? FIRST_USER_ADMIN_ENABLED: 
    : - 
      - 
      - 
signup:
  enabled: true
check_ssl_usage:
  enabled: true
jwt_expiration_time:
  value:
  - 
  - 
  - 
machine_fqdn:
  value: portus.something.info
```

some of my values end up as arrays?? 

in my docker-compose file I run like so:
```
portus:
  image: connorpoole/portus:0.0.27
  environment:
    DB_ADAPTER: mysql2
    DB_ENCODING: utf8
    DB_HOST: dburl
    DB_PORT: 3306
    DB_USERNAME: dbuser
    DB_PASSWORD: dppassword
    DB_DATABASE: portusdb
    PORTUS_LDAP_ENABLED: true
    PORTUS_LDAP_HOSTNAME: "ldap.foxpass.com"
    PORTUS_LDAP_PORT: 636
    PORTUS_LDAP_METHOD: "simple_tls"
    PORTUS_LDAP_BASE: "dc=something,dc=com"
    PORTUS_LDAP_FILTER: ""
    PORTUS_LDAP_UID: "uid"
    PORTUS_LDAP_AUTHENTICATION_ENABLED: true
    PORTUS_LDAP_AUTHENTICATION_BIND_DN: "cn=portus,dc=something,dc=com"
    PORTUS_LDAP_AUTHENTICATION_PASSWORD: "somepassword"
    PORTUS_LDAP_GUESS_EMAIL_ENABLED: true
    PORTUS_LDAP_GUESS_EMAIL_ATTR: "mail"
    PORTUS_FIRST_USER_ADMIN_ENABLED: true
    PORTUS_JWT_EXPIRATION_TIME_VALUE: "120.minutes"
    PORTUS_MACHINE_FQDN_VALUE: portus.something.info
    PORTUS_DISPLAY_NAME_ENABLED: true
    PORTUS_DELETE_ENABLED: true
    RACK_ENV: production
    RAILS_ENV: production
    PUMA_SSL_CRT: /certs/domain.crt
    PUMA_SSL_KEY: /certs/key.pem
    PUMA_PORT: 80
    PUMA_WORKERS: 4
    SECRETS_SECRET_KEY_BASE: thisisasecret
    SECRETS_ENCRYPTION_PRIVATE_KEY_PATH: /certs/key.pem
    SECRETS_PORTUS_PASSWORD: password
    LOG_LEVEL: debug
    SSL_CERT_FILE: /ect/ssl/certs/ca-certificates.crt
  command: puma -b tcp://0.0.0.0:3000 -w 3
  labels:
    io.rancher.conatiner.pull_image: always
    traefik.enable: manual
    traefik.domain_prefix: portus
    traefik.domain: something.info
    traefik.backend_name: portus
    traefik.port: 80
```

this is running on alpine with the following specs:
```
/portus # ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux-musl]
/portus # rails --version
Rails 4.2.6
```

my init script takes care of substituting any env variables not prefixed with `PORTUS_`
